### ISSUE TITLE
Swagger UI shows wrong/default value "application/json" in "Accept" against curl command 

### ISSUE THREAD

**Issue by dpatra1** [swagger-api/swagger-ui#1451] opened 2015-07-07 14:37 UTC
Hi,

I am using springfox(swagger2) for my micro-service api documentation. I am seeing an issue in swagger-ui.html w.r.t the content displayed against "Curl" command.

No matter what i select from the "Response Content Type" drop down, by default in the curl command it shows "application/json".

There is nothing wrong with the response which i am getting but user should see the correct Accept value which he selected.

Can someone help me here ?

Thanks,
Deba

**Comment by webron** [comment] 2015-07-07 14:50
This is a duplicate of #1397. Hopefully it'll be fixed in the next release.

**Closed by webron** 2015-07-07 14:50 UTC
