### ISSUE TITLE
Show required OAuth scopes on each endpoint in swagger for .net core 

### ISSUE THREAD

**Issue by priyankasingh0692** [swagger-api/swagger-ui#7267] opened 2021-05-14 05:41 UTC
The API I am documenting has a lot of scopes available. However, a single endpoint usually only requires one scope. Currently I am able to show all scopes the API has.

It would be great to know which individual scopes are required per endpoint.

 [Authorize(Roles = "read_account, gread_account")]
[Get]api/values

 [Authorize(Roles = "write_account, gwrite_account")]
[Post]api/values

**Comment by hkosova** [comment] 2021-05-14 07:15
Duplicate of #5062.

**Closed by hkosova** 2021-05-14 07:15 UTC
