### ISSUE TITLE
Logout followed by login keep

### ISSUE THREAD

**Issue by bordigoni** [swagger-api/swagger-ui#4196] opened 2018-02-06 09:02 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.9.1
| How did you install Swagger-UI? |  Maven
| Which browser & version?        | Chrome 63
| Which operating system?         | masOS 10.13.2

```yaml
openapi: 3.0.0
info:
  title: Demo API
  description: First test
  termsOfService: 'http://demo.io/terms-of-service/'
  contact:
    name: Demo Support
    email: support@demo.io
  version: 1.0.0
servers:
  - url: '{server}/v1'
    variables:
      server:
        default: https://api.demo.io
        description: the API endpoint

paths:
  /session:
    put:
      summary: Returns a new authentication token
      tags:
        - session
      security:
        - basicAuth: []
      responses:
        '201':
          description: A session object
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      user_id:
                        type: string
                        format: uuid
                        readOnly: true
                        example: 110e8400-e29b-11d4-a716-446655440000
                  - $ref: '#/components/schemas/Session'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Session:
      required:
        - token
      properties:
        token:
          type: string
          readOnly: true
          example: >-
            eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE
        
    Error:
      required:
        - message
      properties:
        message:
          description: a human readable message explaining the error
          type: string
        reason:
          description: a functionnal key about the error
          type: string
  responses:
    Unauthorized:
      description: Not authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
```

### Expected Behavior
* Open the authorization popup
* Enter Basic auth credentials
* Click Authorize
* Keep the popup open
* Logout
* Enter *other/corrected* Basic auth credentials
* Click Authorize
* Changes should be applied

### Current Behavior
* ...
* Enter **other/corrected** Basic auth credentials
* Click Authorize
* Displayed credentials are the former, when a call to `/session` is made using tryout, the first credentials are indeed used 

If I want that to work I have to close the popup first

### Possible Solution
 It should not be needed to close the popup to make the above scenario working

### Context
 Users could mess up their login or password, then realize they did, logout and correct.

**Comment by heldersepu** [comment] 2018-02-12 15:49
That is strange I just tested this on one of my WebAPI and it seems to work fine:
http://nhc-noaa.azurewebsites.net/swagger/ui/index?filter=Videos
Will try with your swagger spec now...

**Comment by heldersepu** [comment] 2018-02-12 15:59
Sorry but yours worked fine too:
http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/4196_swagger.yaml
At lease looking at the Curl it shows the correct credentials that I entered last...

**Comment by pho-enix** [comment] 2018-03-29 07:06
Hi @heldersepu I can reproduce the very same bug. It happens with our own setup (swagger-ui-dist 3.13.0) and in your test setup too (http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/4196_swagger.yaml).

Tested setups:
Win10 + Firefox 52
Ubuntu + Firefox 59
Ubuntu + Chrome 65

I only checked the basic auth part.

**Comment by heldersepu** [comment] 2018-03-29 12:55
@pho-enix can you provide steps to reproduce, here is what I did
- Open the authorization popup
- Enter Basic auth credentials (username: qwert)
- Click Authorize
- Keep the popup open
- Logout
- Enter other Basic auth credentials (username: aaaaa)
- Click Authorize
- Click Close
- Execute the PUT request
- The Curl shows something like:
`curl -X PUT ... -H "Authorization: Basic YWFhYWE6YWFhYWE="`
- Decode the auth it should be the last one used (aaaaa)

**Comment by pho-enix** [comment] 2018-03-29 13:03
* Open the authorization popup
* Enter Basic auth credentials (username: qwert)
* Click Authorize
* Click Close
* Open the authorization popup
* The Basic auth credentials show the correct username (qwert)
* Click Logout
* The Basic auth credentials are empty
* Enter Basic auth credentials (username: aaaaa)
* Click Authorize
* ** The Basic auth credentials show the incorrect username (qwert)**

If you close and open the pop-up, there is still the old (qwert) username.

Workaround:
Logout, Close, Open popup (it's empty then), Enter new username, Authorize

**Comment by heldersepu** [comment] 2018-03-29 13:14
Thanks @pho-enix  yes now I can reproduce with those steps

Closing the popup between usernames was the part that was not included in the original report.
bordigoni wrote (Keep the popup open)

**Comment by heldersepu** [comment] 2018-03-30 22:44
My mind is blown!

I put a debugger on where we set the username:
https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/oas3/components/http-auth.jsx#L62

And bamm some how there is a different result
![image](https://user-images.githubusercontent.com/545474/38156119-b01632ea-3449-11e8-985e-40a585091a50.png)

@webron, @shockey Have you guys seen anything like that before

**Comment by pho-enix** [comment] 2018-04-09 07:58
Great to see, that things are getting forward.

**Comment by heldersepu** [comment] 2018-04-09 13:42
Of course @pho-enix There is no other way than forward!

**Closed** 2018-04-20 23:08 UTC

**Comment by pho-enix** [comment] 2018-04-23 07:45
Thanks for the fix. I pulled the lastest release and stuff works as intended :)
