### ISSUE TITLE
Validation for "format": "date-time"

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3683] opened 2017-09-19 15:35 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature 
| Which Swagger/OpenAPI version?  | Latest 
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | Swagger-Net
| Which browser & version?        | Chrome
| Which operating system?         | Win 7

### Demonstration API definition
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Attribute#/Attribute/Attribute_GetAttribData

### Expected Behavior
Integer and Numbers have validation in place if we enter an invalid number and hit [Execute] the field will turn red and shake letting the user know there is a problem.
The same should be done for ```"format": "date-time"```

### Current Behavior
user is able to [Execute] with invalid data in a date-time field

**Comment by webron** [comment] 2017-09-19 16:35
Closing as duplicate of #993.

**Closed by webron** 2017-09-19 16:35 UTC
