### ISSUE TITLE
Missing options: apisSorter, docExpansion

### ISSUE THREAD

**Issue by nash4ever** [swagger-api/swagger-ui#3037] opened 2017-05-05 13:28 UTC
swagger-ui version: 3.x
`apisSorter` and `docExpansion` options are not supported.
I see that these features are second-tier priority, but what does it mean, when will you add these options to the swagger ui?
I only need these 2 basic options to be able to use the new version of swagger ui.
Is there any workaround? 

Thanks for your help.

**Comment by webron** [comment] 2017-05-05 21:29
It means that support for those would come after we add support for version 3.0 of the spec. Unfortunately, we don't have the capacity to work on everything at once. Should anyone submit a PR to add the functionality, we'll review and merge if proper.

**Comment by zak905** [comment] 2017-05-07 17:19
It would be nice to have some programmatic workaround in the meanwhile.

**Comment by zak905** [comment] 2017-05-08 08:26
This can toggle all the expand/collapse : $(".expand-operation").trigger("click");
but how to capture the swagger loading event

**Comment by zak905** [comment] 2017-05-08 09:06
this is the best solution I found so far: 

```
 function checkSwaggerLoaded() {
        var elem = document.getElementById("swagger-ui");
        if (elem.childElementCount > 0 && document.querySelector("#swagger-ui .info .title").innerText != "Loading...") {
            $(".expand-operation").trigger("click");
        } else {
         console.log("timeout");
            setTimeout(checkSwaggerLoaded, 200);
        }
        return;
    }
```

**Comment by webron** [comment] 2017-05-30 22:58
Duplicate of #2990 and #2799.

**Closed by webron** 2017-05-30 22:58 UTC
