### ISSUE TITLE
Service test requests not working with host-less specification

### ISSUE THREAD

**Issue by NelsonTC** [swagger-api/swagger-ui#2797] opened 2017-03-27 16:57 UTC
Hello.

I am using swagger-ui 3.0.3 and I intentionally did not define the host on my swagger specification, since I don't want to make the code environment-dependent.
I deployed my application with that specification and noticed the host-less configuration at the top of the page, where I find my base path without the host.

Nonetheless, I hoped the testing mechanism on swagger-ui would be cunning enough to use the current page host as the root for the request, if no host is defined in the specification.
When I actually tried, it got my hopes high, when I noticed the "curl" window pop showing the command with the proper URL. Something like:
`curl -X METHOD http://current_host:current_port/Base/path/Service/path ...`

Unfortunately, the actual HTTP request is targeted to `http://Base/path/Service/path` and therefore the tests won't work. Chrome Developer Tools console shows a `net::ERR_NAME_NOT_RESOLVED` error at `swagger-ui-bundle.js:65`.

Do you think it would be possible to use the current/swagger-ui host or at least the specification's url host on these host-less scenarios?

Kind regards,
Nélson.

**Comment by ddelay** [comment] 2017-03-27 19:00
I just opened a similar issue (Issue #2801).  My issue may be a duplicate of this one, but I'll let the experts decide.

**Comment by webron** [comment] 2017-03-27 22:17
Duplicate of #2760.

**Closed by webron** 2017-03-27 22:17 UTC
