### ISSUE TITLE
Support of "x-examples" for "body" type parameters (like sagger-ui v2.x.x)

### ISSUE THREAD

**Issue by Clem69B** [swagger-api/swagger-ui#7116] opened 2021-03-24 13:58 UTC
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
swagger: '2.0'
[...]
    post:
      tags:
        - _(deprecated) Triggers and Actions - V0 (use Triggers and Actions - V1 instead
      summary: Create an ActionPolicy
      description: 'The field `id` must not be provided, it will be automatically generated by the service as an UUID.<br><br>Usage of this API will be reported in your access log under ''routing'' category.<br><br>Restricted to API keys with at least one of the following roles : DATA_PROCESSING_W.'
      operationId: createUsingPOST_1
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: actionPolicy
          description: ActionPolicy to add
          required: true
          schema:
            $ref: '#/definitions/ActionPolicyV0'
          x-examples:
            default: |-
              {
                  "name": "name-aea80c1d-5777-4e20-822c-5e6871f428e5",
                  "enabled": true,
                  "triggers": {
                      "eventRuleIds": ["64e97cd3-9f49-43d9-84cf-7c4a806e3189"]
                  },
                  "actions": {
                      "emails": [{
                      "to": ["notification@toto.com"],
                      "cc": ["cc@foo.com"],
                      "cci": ["cci@bar.com"],
                      "subjectTemplate": "State change for {{stateKey}}",
                      "contentTemplate": "{{stateKey}} change from state {{previousState}} to state {{newState}} at {{timestamp}}"
                      }],
                      "sms": [{
                          "destinationPhoneNumbers": ["+33601234567"],
                          "contentTemplate": "{{stateKey}} new state {{newState}} at {{timestamp}}"
                      }]
                  }
              }
      responses:
        '200':
          description: ActionPolicy created
          schema:
            $ref: '#/definitions/ActionPolicyV0'
      security:
        - X-API-KEY:
            - global
      deprecated: true
[...]
 ```

### Is your feature request related to a problem?
We have recently moved from swagger-ui 2.X.X to swagger-ui 3.X.X
In swagger-ui 2.x.x, "x-examples" are interpreted : 
![image](https://user-images.githubusercontent.com/1653158/112320810-a9bf8b00-8caf-11eb-897b-8b15891f2a68.png)

In swagger-ui 3.x.x, "x-examples" are ignored : 
![image](https://user-images.githubusercontent.com/1653158/112320946-c8be1d00-8caf-11eb-96b4-c39152a62a16.png)

### Describe the solution you'd like
The same behaviour as swagger-ui 2.X.X would be perfect

### Describe alternatives you've considered
We know that "x-examples" is a vendor extension, and not a part of the swagger V2 specification. In fact, nothing seems to exist for body request examples. 
The migration to OpenAPI v3 will be a good answer, but requires much more work on our side (annotation migration, springfox to springdoc migration, etc.).

Thankyou for any response

**Comment by hkosova** [comment] 2021-03-24 14:27
Duplicate of #3233.

**Closed by hkosova** 2021-03-24 14:27 UTC
