### ISSUE TITLE
Operation deep link is incorrect (not bookmarkable)

### ISSUE THREAD

**Issue by danielFesenmeyer** [swagger-api/swagger-ui#4743] opened 2018-07-19 08:12 UTC
I found the following inconsistency regarding deep links.

### Q&A (please complete the following information)
 - OS: on request
 - Browser: Chrome, Firefox
 - Version: on request
 - Swagger-UI version: https://petstore.swagger.io
 - Swagger/OpenAPI version: https://petstore.swagger.io

### Content & configuration
https://petstore.swagger.io

### Describe the bug you're encountering
The operation deep link is incorrect. E.g. for POST pet it is: https://petstore.swagger.io/#/**operations/**pet/addPet, but should be https://petstore.swagger.io/#/pet/addPet

### To reproduce...

1. https://petstore.swagger.io
2. Click on the "pet" resource
3. Click on the "/pet" operation
4. The operation is opened, the browser url changes to https://petstore.swagger.io/#/pet/addPet
5. Open this url in a new brower tab
6. The deep link works: operation POST "/pet" is opened
7. Go back to 2, Get the URL of the "/pet" operation
8. The (incorrect) URL is https://petstore.swagger.io/#/**operations/**pet/addPet
9.  Open this url in a new brower tab
10. The deep does not work:  operation POST "/pet" won't be opened

### Expected behavior
I expect that getting the link URL from an operation gives me a correct deeplink, e.g.  https://petstore.swagger.io/#/pet/addPet

**Comment by TheMarex** [comment] 2018-09-24 19:43
Is this still a problem? I was not able to reproduce this.

**Comment by danielFesenmeyer** [comment] 2018-10-01 09:50
I also cannot reproduce it any more. It seems to have been fixed in the meantime.

**Comment by shockey** [comment] 2018-10-09 19:43
I'd hazard a guess that https://github.com/swagger-api/swagger-ui/pull/4832 fixed this.

In any event - closing this as resolved. Thanks @danielFesenmeyer & @TheMarex for the efforts here!

**Closed by shockey** 2018-10-09 19:43 UTC
Labels: cat: user experience, type: bug
