### ISSUE TITLE
Include esprima in manifest to support installation via skypack

### ISSUE THREAD

**Issue by olimart** [swagger-api/swagger-ui#7054] opened 2021-03-09 05:50 UTC
### Content & configuration

 Swagger-UI configuration options:

```js
import swaggerUi from 'https://cdn.skypack.dev/swagger-ui';
```
returns:

 ```js
* The package "swagger-ui" depends on "esprima" as a dependency,
 * but did not list any dependency version info in its package manifest.
 * Without this information, the CDN is unable to properly resolve this import.
 *
 * How to fix:
 *   - Let the "swagger-ui" package author know that "esprima" needs to be included in their package.json manifest.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

throw new Error("[Package Error] \"esprima\" no dependency version info found. (Imported by \"swagger-ui\").");
export default null;
 ```

### Is your feature request related to a problem?

It would be great to support (in-browser) installation via skypack
(or provide full example how to load in-browser without require)

### Describe the solution you'd like
Simpler in-browser installation.

### Describe alternatives you've considered
Server installation whicj makes the upgrade a bit more tedious to maintain.

**Comment by tim-lai** [comment] 2021-06-10 22:41
related/duplicate of #7110

**Comment by char0n** [comment] 2021-08-11 09:07
[SwaggerUI@3.52.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.52.0) no longer ships with esprima. You should no longer have issues skypack.

**Closed by char0n** 2021-08-11 09:07 UTC
Labels: cat: packaging
