### ISSUE TITLE
External schema resolve depth

### ISSUE THREAD

**Issue by havsar** [swagger-api/swagger-ui#2709] opened 2017-03-07 17:32 UTC
### Swagger files:

**swagger-base.json**
```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "API"
    },
    "schemes": [
        "http"
    ],
    "paths": {
        "/api/test/endpoint": {
            "post": {
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "swagger-external.json"
                        }
                    }
                }
            }
        }
    }
}
```

**swagger-external.json**
```
{
    "additionalProperties": false,
    "definitions": {
        "IConnection": {
            "additionalProperties": false,
            "properties": {
                "offerResponse": {
                    "$ref": "#/definitions/IOfferResponse"
                }
            },
            "type": "object"
        },
        "ILeg": {
            "additionalProperties": false,
            "properties": {
                "connection": {
                    "$ref": "#/definitions/IConnection"
                }
            },
            "type": "object"
        },
        "IOfferResponse": {
            "additionalProperties": false,
            "properties": {
                "offer": {
                    "$ref": "#/definitions/IOfferDetail"
                }
            },
            "type": "object"
        },
        "IOfferDetail": {
            "additionalProperties": false,
            "properties": {
                "reservation": {
                    "$ref": "#/definitions/IReservation"
                }
            },
            "type": "object"
        },
        "IReservation": {
            "additionalProperties": false,
            "properties": {
                "reservationScope": {
                    "$ref": "#/definitions/IReservationScope"
                }
            },
            "type": "object"
        },
        "IReservationScope": {
            "additionalProperties": false,
            "properties": {
                "compartment": {
                    "$ref": "#/definitions/ICompartment"
                }
            },
            "type": "object"
        },
        "ICompartment": {
            "additionalProperties": false,
            "properties": {
                "test": {
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "legs": {
            "$ref": "#/definitions/ILeg"
        }
    },
    "type": "object"
}
```

Swagger-ui doesn't resolve ICompartment definition properly.
Someone has a similiar issue? Is this configurable?

**Comment by webron** [comment] 2017-03-07 17:35
The files you shared are cut off so it's hard to tell.
Your swagger-external.json looks like an invalid Schema Object making it an invalid spec in the first place.

**Comment by HimmetAvsar** [comment] 2017-03-08 09:23
Updated the cut off json files for reproduction.

**Comment by webron** [comment] 2017-03-08 16:14
So your swagger-external.json is a full JSON Schema which is not supported by the spec. You can't have `definitions` in it, for example. You'd need to fix that before expecting it to render.

**Comment by havsar** [comment] 2017-03-09 11:31
I moved all the definitions to a single file now it seems to work. Are there any plans to support definitions in external files in future releases?

**Comment by webron** [comment] 2017-03-09 17:53
It's supported today.

**Comment by vortechs2000** [comment] 2017-03-16 21:56
@webron but it doesn't appear to work if you have a $ref inside your externally $ref'd file.  In that case, all i see in swagger-ui is the URI for the external ref.  IOW, multiple layers of external $ref don't work.

Should they?

**Comment by webron** [comment] 2017-03-16 22:33
It should work, yes. Keep in mind we're releasing a major new version soon, which might change everything. I'd suggest waiting a few days, checking with the new version, and if there's an issue with it there, we can figure it out together.

**Comment by vortechs2000** [comment] 2017-03-17 01:38
@webron sounds good - thanks

**Comment by webron** [comment] 2017-06-10 04:38
Closing as should work well in the new UI. Please add a comment or file a new ticket if you still encounter a problem.

**Closed by webron** 2017-06-10 04:38 UTC
