### ISSUE TITLE
Possibility to change default Parameter & Response content type to application/json

### ISSUE THREAD

**Issue by wojciech-soltys** [swagger-api/swagger-ui#5347] opened 2019-05-13 13:03 UTC
### Content & configuration
https://github.com/springfox/springfox/issues/2562 - more detailed description of issue

### Describe the solution you'd like 
I would like to have possibility to change default Parameter & Response content type to application/json or any other than application/xml.

**Comment by hkosova** [comment] 2019-08-23 17:00
Duplicate of #5132.

**Closed by hkosova** 2019-08-23 17:00 UTC
