### ISSUE TITLE
Javascript error while executing file upload request

### ISSUE THREAD

**Issue by billybraga** [swagger-api/swagger-ui#7907] opened 2022-03-12 03:53 UTC
### Q&A
 - OS: Windows
 - Browser: chrome
 - Version: 99
 - Method of installation: repro on editor.swagger.io and locally using npm+vuejs+webpack
 - Swagger-UI version: 4.6.2 and 4.6.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
https://editor.swagger.io

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Upload bug in swagger ui
  version: 1.0.0
servers:
- url: http://example.com
paths:
  /InsertFile:
    post:
      requestBody:
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: success
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
```

### Describe the bug you're encountering
```
TypeError: (0 , zt.isPlainObject) is not a function
    at Object.nn [as execute] (swagger-ui-es-bundle-core.js:1:165216)
    at swagger-ui-es-bundle-core.js:1:111063
    at swagger-ui-es-bundle-core.js:1:198302
    at redux.js:546:12
    at swagger-ui-es-bundle-core.js:1:127167
    at Object.r (swagger-ui-es-bundle-core.js:1:410340)
    at Object.executeRequest (swagger-ui-es-bundle-core.js:1:414734)
    at swagger-ui-es-bundle-core.js:1:111836
    at swagger-ui-es-bundle-core.js:1:198302
    at redux.js:546:12
```

### To reproduce...

1. Try it out
2. Choose file
3. Click execute

### Expected behavior
Request is sent

### Screenshots
![chrome_jVeTO0oJkB](https://user-images.githubusercontent.com/426739/158002668-492f21a4-38be-443e-811e-31d9017e5fce.png)

**Comment by pilotofbalance** [comment] 2022-03-16 12:38
Im getting similar one **TypeError: Ut.isPlainObject is not a function** , any updates?

**Comment by SpaseESG** [comment] 2022-03-20 17:45
+1 here.

**Comment by youasl** [comment] 2022-03-21 09:03
I have the same issue, for almost 3 weeks now. I also posted it on the community support forum. I noticed this issue is only with POST method. GET works.

**Comment by umamahesh134** [comment] 2022-03-22 08:47
I have the same issue just using the petstore example and executing the POST for a pet, I did not change any values, just executed the request as is.
Steps to reproduce:

open https://editor.swagger.io/ in your browser (I am using firefox, but other browsers had the same issue)
open the POST pet accordion
click on "Try it out"
click on "execute"
when you open the browser console, you can see the error message:

swagger-ui-es-bundle-core.js:1 TypeError: (0 , zt.isPlainObject) is not a function
    at Object.nn [as execute] (swagger-ui-es-bundle-core.js:1:165216)
    at swagger-ui-es-bundle-core.js:1:111063
    at Object.dispatch (swagger-ui-es-bundle-core.js:1:198302)
    at dispatch (<anonymous>:3665:80)
    at redux.js:546:12
    at swagger-ui-es-bundle-core.js:1:127167
    at Object.r (swagger-ui-es-bundle-core.js:1:410340)
    at Object.executeRequest (swagger-ui-es-bundle-core.js:1:414734)
    at swagger-ui-es-bundle-core.js:1:111836
    at Object.dispatch (swagger-ui-es-bundle-core.js:1:198302)

**Comment by char0n** [comment] 2022-03-23 13:35
Hello everybody,

After further analysis, it looks like this errors happens when SwaggerUI is build as part of SwaggerEditor. SwaggerUI build fragments are built using webpack@5, SwaggerEditor build fragments are built using webpack@4. It seems that if we build SwaggerUI as part of SwaggerEditor using current webpack configs this error and others are present. 

Investigating further for finding possible remediation for this issue.

**Comment by char0n** [comment] 2022-03-24 11:16
Create https://github.com/swagger-api/swagger-ui/pull/7937 to expose true `ESM` build which work with SwaggerEditor webpack@4 bunding. Tested that SwaggerEditor works correctly and eliminates the problem reported in this issue.

**Comment by char0n** [comment] 2022-03-24 13:13
Released as https://github.com/swagger-api/swagger-editor/releases/tag/v4.2.1 and successfully deployed to https://editor.swagger.io/

**Closed by char0n** 2022-03-24 13:13 UTC
Labels: type: bug, version: 4.x
