### ISSUE TITLE
Use server descriptions in servers.jsx component's pull-down menu

### ISSUE THREAD

**Issue by derekm** [swagger-api/swagger-ui#4908] opened 2018-09-28 17:38 UTC
The "Server" pull-down menu only shows URL values.

It might not be obvious to less technical users which URL is for what, so the pull-down menu should incorporate the description if it is provided.

**Comment by hkosova** [comment] 2018-10-01 11:13
Thanks for the report! This is already tracked in #4802.

**Comment by shockey** [comment] 2018-10-01 18:45
Closing as a duplicate of #4802 👍

**Closed by shockey** 2018-10-01 18:45 UTC
