### ISSUE TITLE
Downloading corrupted file format .xlsx. Bug to Swagger-UI 3.x.x

### ISSUE THREAD

**Issue by DanilaShapkin** [swagger-api/swagger-ui#5615] opened 2019-09-20 14:00 UTC
Backend responses with the file : 

![Снимок экрана от 2019-09-20 16-26-28](https://user-images.githubusercontent.com/43188845/65330731-f1012300-dbc3-11e9-97c9-4ef97a5d3c5d.png)

Clicking on **Download File** 
downloads  broken file with name- **-stream_phones-priority_blob_http___localhost_4200_5b1266aa-d837-45e6-bb56-cb633090af6d**

Configuratuin Swagger-UI-Bundle:
![Снимок экрана от 2019-09-20 16-50-22](https://user-images.githubusercontent.com/43188845/65332256-fad85580-dbc6-11e9-8744-d0705d76d945.png)

**Comment by webron** [comment] 2019-09-23 08:13
Are you able to provide a way to test and reproduce this? Otherwise we won't be able to do much with this report.

**Comment by shockey** [comment] 2019-09-28 05:06
Closing due to lack of actionable information — @DanilaShapkin, feel free to reply here when/if you're in a position to provide a way for us to reproduce this, and we'll reopen.

**Closed by shockey** 2019-09-28 05:06 UTC
