### ISSUE TITLE
link from descriptions to other operations

### ISSUE THREAD

**Issue by ralphvanetten** [swagger-api/swagger-ui#1107] opened 2015-04-01 10:13 UTC
It would be nice if you can link to other operations from the description.

For example, if you add the description using markdown somewhere with:

    To delete use the [DELETE /pet/{petId}](#!/pet/deletePet) operation.

It is rendered correctly but when you click on the link, the url in the url bar of the browser is updated but the documentation does not scroll to the correct location.

**Comment by webron** [comment] 2015-04-01 12:29
We've had a discussion on it in the google group, but it feels like the solution should come from the spec itself. There's an open issue - https://github.com/swagger-api/swagger-spec/issues/239.

**Comment by ralphvanetten** [comment] 2015-04-01 12:39
Ah, yes, that would also be a nice solution but it would be sufficient if clicking on an anchor link just works in swagger. Currently it only scrolls to the correct operation when the page is opened the first time.
So if somehow the same code is executed when clicking on an anchor link it would work.

**Comment by webron** [comment] 2015-04-01 12:41
Right, but the problem is that the anchor is generated and its logic can change, and since we don't officially have our own MD extensions (which would be defined in the spec), it would be difficult to implement (or rather maintain).

**Comment by ralphvanetten** [comment] 2015-04-01 12:46
Yes, you are right. If the generated anchors change a lot it will be difficult to maintain...

**Comment by fehguy** [comment] 2015-12-07 20:46
I'm going to close this out as there is a mechanism for doing so with external docs in the 2.0 spec.

**Closed by fehguy** 2015-12-07 20:46 UTC
Labels: Feature

**Comment by ksimka** [comment] 2017-03-29 17:04
@fehguy Can you please give an example of how can this be done (inline local links)?
