### ISSUE TITLE
Accept Headers not reflected in swagger UI for status code other than 200. 

### ISSUE THREAD

**Issue by mma5997** [swagger-api/swagger-ui#6988] opened 2021-02-23 05:35 UTC
If we follow the OAS3 spec for Response [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#responses-object) we can see that each response status code can have multiple media types and each media type, in turn, has a schema particular to it.

UseCase : For example oas3 example below, we can see 200 has a binary stream response but 400 has 3 media-types:application/json, application/xml, text/plain.

```
openapi: 3.0.0
info:
  version: "1.0"
  title: Resource
  description: Resource service
paths:
  /resource:
    get:
      summary: getResource
      description: getResource
      operationId: get-resource
      responses:
        "200":
          description: a binary document to be returned
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error400Element"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error400Element"
            text/plain:
              schema:
                $ref: "#/components/schemas/Error400Element"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Element"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error500Element"
            text/plain:
              schema:
                $ref: "#/components/schemas/Error500Element"
servers:
  - url: http://localhost:8088/
components:
  schemas:
    Error400Element:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        number:
          type: integer
    Error500Element:
      type: object
      properties:
        number:
          type: integer
        flag:
          type: boolean
```

When I try it out from editor.swagger.io it only populates the accept header with the media type selected at the drop-down of 200 response status code.
          
 What if the SwaggerUI client receives an Internal Server Error?
 So should the accept headers be populated as the union of all possible media types that can be possibly sent in response from 
the Server end?

**Comment by hkosova** [comment] 2021-02-25 11:39
Duplicate of #5649.
See also [this comment](https://github.com/swagger-api/swagger-ui/issues/5649#issuecomment-543355710) for an explanation.

**Closed by hkosova** 2021-02-25 11:39 UTC
