### ISSUE TITLE
[OpenAPI 3.1] Example value is not generated for nested objects that are referenced via allOf

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#9941] opened 2024-05-15 13:07 UTC
### Q&A (please complete the following information)
 - OS: macOS 13.6.7
 - Browser: Chrome latest
 - Method of installation: standalone Swagger UI (5.17.9), also https://editor-next.swagger.io (UI v. 5.17.3)
 - Swagger-UI version: 5.17.9, 5.17.3
 - Swagger/OpenAPI version: OpenAPI 3.1 only

Ref https://github.com/swagger-api/swagger-js/issues/3520

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.1.0
info:
  title: Example generation test
  version: 1.0.0
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'

components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          allOf:
            - $ref: '#/components/schemas/Bar'
    
    Bar:
      type: object
      properties:
        a:
          type: integer
          example: 123
        b:
          type: string
          example: hello
```

### Describe the bug you're encountering
The issue may (or may not) be related to #8374.

On the "Example Value" tab, the `bar` value appears empty object `"bar": {}` instead of an actual object generated from its schema `"bar": {"a": 123, "b": "hello"}`. This happens for properties that reference their schema using `allOf`+`$ref` instead of just `$ref`.

The property schema on the "Schema" tab appears correctly though, and shows all fields defined in the referenced schema.

The issue exists for OpenAPI 3.1 definitions and does NOT exist for OpenAPI 3.0 and 2.0.

### To reproduce...

1. Go to https://editor-next.swagger.io
2. Paste the definition provided above.
3. Expand the `GET /foo` operation and examine the "Example Value".

**Actual result:**
```json
{
  "bar": {}
}
```

**Expected result:**
```json
{
  "bar": {
    "a": 123,
    "b": "hello"
  }
}
```

4. Replace `openapi: 3.1.0` with `openapi: 3.0.0`.
5. Example "Example Value" again.

=> Now the example value is correct and includes the nested fields.

### Screenshots
<img width="842" src="https://github.com/swagger-api/swagger-ui/assets/8576823/db1bc585-a654-4bf0-895d-415f87546a96">

<img width="820" src="https://github.com/swagger-api/swagger-ui/assets/8576823/8d077050-eefc-47fd-a1b8-9e618a2a4e17">

### Additional context or thoughts
Looks like the correctness of the Example Value depends on whether the user expands the operation or schema first? If I first fully expand the schema under "Schemas" at the bottom, then the Example Value inside the operation is generated correctly.

![weird](https://github.com/swagger-api/swagger-ui/assets/8576823/13599060-a72d-41af-ac17-3fdb1288cba6)

**Comment by char0n** [comment] 2024-05-16 07:11
Hi @hkosova,

Nice to see you here again ;]

We're looking into the issue. Thanks for the report.

**Comment by glowcloud** [comment] 2024-05-16 07:40
I can confirm this is a regression in Swagger Client. 

This works properly in Swagger UI version 5.15.2 and stops working in 5.16.0. We updated the Swagger Client version from 3.26.8 to 3.27.0 and there were changes to dereferencing: https://github.com/swagger-api/swagger-js/pull/3472, so it looks like the regression was caused by that.

**Comment by char0n** [comment] 2024-05-16 07:43
@glowcloud can you constructor minimal reproducibe fixture with expected result and current result?

**Comment by glowcloud** [comment] 2024-05-16 08:01
Looks like it can be reproduced without the reference inside of `allOf`:
```yaml
openapi: 3.1.0
info:
  title: Example generation test
  version: 1.0.0
paths:
  /foo:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          allOf:
            - type: object
              properties:
                a:
                  type: integer
```

Here's the schema inside of response with the `allOf` keyword:
<img width="298" alt="Screenshot 2024-05-16 at 09 59 28" src="https://github.com/swagger-api/swagger-ui/assets/44094416/cf125ef8-7b82-4dbb-a1d8-2a5838d4aa87">
and under schemas:
<img width="221" alt="Screenshot 2024-05-16 at 09 59 45" src="https://github.com/swagger-api/swagger-ui/assets/44094416/a973642f-8390-4e8a-9ee4-fe1d527570a1">

**Comment by char0n** [comment] 2024-05-17 10:10
Associated upstream swagger-js issue has been created in https://github.com/swagger-api/swagger-js/issues/3520

**Comment by dominikforal** [comment] 2024-05-17 10:17
We're encountering the same issue with our documentation. This is a high priority matter as a significant portion of our documentation is affected.

**Comment by char0n** [comment] 2024-05-21 06:49
We already have an upstream regression remediation in https://github.com/swagger-api/swagger-js/pull/3521

ETA in SwaggerUI during today.

**Comment by char0n** [comment] 2024-05-21 10:06
Upstream fix released in [swagger-client@3.28.1](https://github.com/swagger-api/swagger-js/releases/tag/v3.28.1)

**Comment by char0n** [comment] 2024-05-21 10:12
Address for SwaggerUI in https://github.com/swagger-api/swagger-ui/pull/9950

**Closed** 2024-05-21 13:04 UTC
Labels: type: regression, version: 5.x

**Comment by hkosova** [comment] 2024-05-21 14:41
Thanks for the quick fix @char0n, @glowcloud!
