### ISSUE TITLE
non-required Boolean value is always selected

### ISSUE THREAD

**Issue by morficus** [swagger-api/swagger-ui#1191] opened 2015-04-21 21:04 UTC
When defining a `parameter` of type `boolean` and `required: false`, the generated select-box in Swagger-UI only provides a "true" or "false" option forcing a value to be selected.
The expected behavior was that there would be a 3rd option with a blank value (because this is a non-required field)

YAML file:
```
swagger: "2.0"

info:
  description: Just to demonstrate a bug with non-requiered boolean values
  title: Bug Demonstration
  version: 0.0.0

paths:
  # This is a path endpoint. Change it.
  /projects:
    # This is a HTTP operation
    get:
      summary: List all projects
      description: Get a list of `Porject` objects.
      parameters:
        - name: isActive
          in: query
          description: filter active vs non-active projects
          required: false
          type: boolean
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'

definitions:
  Project:
    properties:
      id:
        type: string
        description: Unique project identifyer
      name:
        type: string
        description: Project name
      isActive:
        type: boolean
        description: Is this an active project?
```

Viewer:
![screen_shot_2015-04-21_at_4_58_15_pm](https://cloud.githubusercontent.com/assets/718799/7262468/d066c2ae-e847-11e4-8400-7fd09c99f9f8.png)

**Comment by FJavierGil** [comment] 2015-04-23 18:39
Also, I think it would be better that the value assigned to the selected options was 1 or 0, not the string 'true' or 'false'

**Comment by webron** [comment] 2015-04-24 10:47
@FJavierGil - true/false is probably more understandable than 1/0, especially to non-developers, so we'll probably keep it as-is. Thank you for the suggestion though.

**Comment by FJavierGil** [comment] 2015-04-24 11:16
I refer to "value" attribute, not the visible text.

**Comment by webron** [comment] 2015-04-24 11:17
That's not possible. The specification refers to boolean value as being true/false.

**Comment by FJavierGil** [comment] 2015-04-24 11:19
Ok, Thank you.

**Comment by webron** [comment] 2015-04-24 11:20
If there's a field that you require to have the value of 1/0, I'd suggest setting it as an integer with an enum limiting to those values.

**Comment by firefoxNX** [comment] 2015-04-29 14:34
Another variation to this defect -

```
parameters:
        - name: optBooleanDefaultFalse
          in: query
          type: boolean
          required: false
          default: false
          description: Optional parameter. Default is false
```

The optBooleanDefaultFalse dropdown shows up with value true.

**Comment by webron** [comment] 2015-04-29 14:36
That's not really a variation of this bug, it's a different one.

**Comment by ponelat** [comment] 2015-04-29 14:48
if you make false a string.."false", it'll have the behavior you expect. But I would like to see it behave the same, given a boolean.
I'll what I can dig up...

**Comment by ponelat** [comment] 2015-04-30 08:26
The fix is in, and will eventually be in a release.
For now, if you'd like to see the default value of a boolean you can set the default to a string of that boolean. The fix will support both.

```json
default: "false" // this will work now and in the fix
....
default: false // this will work in the fix
```

**Comment by morficus** [comment] 2015-04-30 19:14
awesome! :+1:

**Comment by trobrock** [comment] 2015-05-01 01:05
Is there a timeline or workaround for the optional value bug? I have a boolean that is optional and the default case is neither true or false.

**Comment by ponelat** [comment] 2015-05-01 06:04
That is by design, if the boolean is optional then we don't want to force either a true or false. In other words it would not send the parameter in the request. See the top comment that started this issue.

However, for clarification here is a comparison of what happens in the develop_2.0 branch (our dev branch)
And what happens in the fix...

From or dev branch...
![in_develop_2 0](https://cloud.githubusercontent.com/assets/8438485/7427293/79f8ecce-efd8-11e4-985b-e2269fb9b0e0.png)

------
From the fix
![bleeding_edge](https://cloud.githubusercontent.com/assets/8438485/7427296/872c0e76-efd8-11e4-9b02-62580a76bc53.png)

**Comment by trobrock** [comment] 2015-05-01 15:24
What you described as an optional boolean with no default value should not get sent is exactly what I'm looking for, but is not what I'm seeing in swagger-ui master. I also am not see the not required, no default case in the test cases you provided. Am I missing something somewhere?

**Comment by ponelat** [comment] 2015-05-01 15:30
Try with swagger-ui/develop_2.0 branch. It should look like the first screenshot.

**Comment by fehguy** [comment] 2015-05-08 21:30
looks like this is fixed now.

**Closed by fehguy** 2015-05-08 21:30 UTC
Labels: Bug, P1

**Comment by morficus** [comment] 2015-05-08 21:44
:tada: :confetti_ball:

**Comment by webron** [comment] 2015-05-10 16:56
@FJavierGil - going over the README, I just noticed the `booleanValues` property in the https://github.com/swagger-api/swagger-ui#parameters. It's not exactly what you want, but it may suit your needs.

**Comment by FJavierGil** [comment] 2015-05-11 14:00
Great. Thank you very much!
