### ISSUE TITLE
Rendered html body viewer for text/html response body.

### ISSUE THREAD

**Issue by eunmin** [swagger-api/swagger-ui#1962] opened 2016-02-11 06:41 UTC
If the response body is text/html is, whether to show rendered html body in response body section?
Like this:
<img width="952" alt="2016-02-11 3 28 55" src="https://cloud.githubusercontent.com/assets/1837478/12970721/c6ba6a90-d0d5-11e5-9cf3-33628be59855.png">

**Comment by webron** [comment] 2016-02-11 22:10
Duplicate of #1748.

**Closed by webron** 2016-02-11 22:10 UTC
