### ISSUE TITLE
No error in UI when required file param is not provided

### ISSUE THREAD

**Issue by anujbhatia** [swagger-api/swagger-ui#2460] opened 2016-10-24 06:54 UTC
- swagger-ui version - v2.2.6
- a swagger file reproducing the issue -

``` json
{
  "swagger" : "2.0",
  "basePath" : "/api/l10n",
  "paths" : {
    "/v1.0/tasks/{project}/assets" : {
      "post" : {
        "tags" : [ "tasks" ],
        "summary" : "Add assets to Task",
        "description" : "Add assets to the task.",
        "operationId" : "addAssets",
        "consumes" : [ "multipart/form-data" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "project",
          "in" : "path",
          "description" : "Project Name.",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "file1",
          "in" : "formData",
          "required" : true,
          "type" : "file"
        } ]
      }
    }
  }
}
```

If I click 'Try It out!' without selecting a file to upload. I see no error in the Swagger UI. In the browser console I see:

```
Navigated to http://localhost:8080/
swagger-ui.js:4081 missing required params: file1
swagger-ui.js:4081 missing required params: file1
swagger-ui.js:4081 missing required params: file1
swagger-ui.js:7684 Uncaught TypeError: Cannot read property 'Content-Type' of undefined
```

**Comment by turkeylurkey** [comment] 2017-01-04 15:49
The fix has been merged. Please verify on a build after Jan. 4.

**Closed** 2017-01-05 00:56 UTC

**Comment by PrasanthJayaraman** [comment] 2019-09-09 12:02
The issue is still open in latest version. Even after i made required false.

![image](https://user-images.githubusercontent.com/15866057/64528773-ef636f80-d326-11e9-8d04-b3e39f0f3374.png)

My swagger code:

logger:
  x-swagger-router-controller: logger.controller.v1
  x-permission-type : none
  post:
    operationId: LoggerRequestHandler
    tags:
      - custom handlers
    responses:
      200:
        description: Request performed successfully
        schema:
           $ref: '#/definitions/logger'
      404:
        description: Api not found
        schema:
           $ref: '#/definitions/baseApiError'
      403:
        description: Forbidden
        schema:
           $ref: '#/definitions/baseApiError'
    parameters:
      - $ref: '#/parameters/authorization'
      - in: body
        description: Widget object (in `JSON` notation) to be added
        name: dashboardId
        required: false
        schema:
          $ref: '#/definitions/logger'

**Comment by webron** [comment] 2019-09-09 14:32
@PrasanthJayaraman Please file a new ticket following the issue template.
