### ISSUE TITLE
Hyperlink to specific documentation?

### ISSUE THREAD

**Issue by l8nite** [swagger-api/swagger-ui#573] opened 2014-09-16 08:46 UTC
Is there a way to link to a shared installation of swagger from a couple of different applications and have the API page for each app load automatically (or at least pre-fill the input box) ?

I.e., I want to have something like
```html
<a href="http://myswagger/?url=http://localhost/myapp/swagger_docs">View Documentation</a>
```

**Comment by fehguy** [comment] 2015-01-28 21:44
This will be in the `external docs` field in swagger-spec 2.0

**Comment by mohsen1** [comment] 2015-03-06 19:26
#1000 will fix this.

**Comment by mohsen1** [comment] 2015-03-18 22:15
Duplicate of https://github.com/swagger-api/swagger-ui/issues/608

**Closed by mohsen1** 2015-03-18 22:15 UTC
