### ISSUE TITLE
Cyclic references stopped working with version 3.10.0

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-ui#4214] opened 2018-02-12 13:32 UTC
The following two APIs reference each other:
* https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi3.json
* https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/Products.openapi3.json

Supplier in PeopleService references Product in ProductService, and vice versa:
![image](https://user-images.githubusercontent.com/951576/36098947-25079638-1001-11e8-9a8b-48253a74a123.png)

And Product in ProductService references Supplier in PeopleService:
![image](https://user-images.githubusercontent.com/951576/36098981-417d15d6-1001-11e8-8ae2-04f3efd3a1ee.png)

This worked fine with Swagger UI 3.9.x

Swagger UI 3.10.0 fails with Resolver errors and `Maximum call stack size exceeded`.

Links using public Swagger UI:
* http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi3.json
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/Products.openapi3.json

**Comment by heldersepu** [comment] 2018-02-12 13:45
Confirmed that it was working on UI 3.9:
http://offleaseonly.azurewebsites.net/swagger/ui/index?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi3.json

**Comment by heldersepu** [comment] 2018-02-12 13:47
The error `Could not resolve pointer` is thrown here:
https://github.com/swagger-api/swagger-js/blob/master/src/specmap/lib/refs.js#L273
I was the last one to touch that file, but I do not see how my change would create this regression...

**Comment by heldersepu** [comment] 2018-02-12 14:53
I was doing some troubleshooting and consolidated all the files:
- odata-definitions.json
- People.openapi3.json
- Products.openapi3.json

into one:
http://heldersepu.github.io/hs-scripts/swagger/4214_swagger.json

That works fine with the latest UI:
http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/4214_swagger.json

So the problem is NOT 100% on Cyclic references like the title indicates...
Looks like the problem is with full path references such as:
```js
 "$ref": "https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/odata-definitions.json#/definitions/Edm.GeographyPoint"
```
```js
  "$ref": "https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi3.json#/components/schemas/PeopleService.Supplier"
```

**Comment by heldersepu** [comment] 2018-02-12 15:31
One interesting observation... 
on the old version (3.9.1) if I hit the button [Explore] it shows the `Could not resolve pointer` error

**Comment by ralfhandl** [comment] 2018-02-12 15:58
Interesting: [Explore] behaves this way only with the People service, it works as expected with the Products service:
http://offleaseonly.azurewebsites.net/swagger/ui/index?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/Products.openapi3.json

**Comment by ralfhandl** [comment] 2018-02-12 15:58
And thanks for the super-fast investigation!

**Comment by heldersepu** [comment] 2018-02-12 16:10
I felt really bad that this all could be my fault! 
I was the last changing that file, and my change is related to $ref, but the fact that it works with the consolidated version is a relief, the bug must be somewhere else.

This is a very very strange case, I personally never used swagger with multiple files and reference like that, honestly don't see quite clear why you need it... 
Maybe for organizational purposes? if you are manually updating those swagger.json files, but you should have tools that generate them and each file should be self contain with all the refs it needs.

**Comment by ralfhandl** [comment] 2018-02-14 05:33
The REST APIs we publish use [OData](http://www.odata.org), and each OData service contains a `$metadata` resource with a machine-readable description of its resource model and operations in OData's service definition language. 

These OData service definitions are then automatically translated into OpenAPI descriptions, preserving as much information as possible. The tool takes one OData `$metadata` file and produces one corresponding OpenAPI file, no manual steps involved.

This approach worked fine with Swagger UI 2.x and up to Swagger UI 3.9.3.

**Comment by heldersepu** [comment] 2018-02-14 13:55
I don't know what to say! 
> This approach worked fine with Swagger UI 2.x and up to Swagger UI 3.9.3.

That does not help one bit, my suggestion is a workaround not a fix for what we know is broken

**Comment by ralfhandl** [comment] 2018-02-14 15:41
@heldersepu The easiest workaround is generating x-ref members instead of $ref members in case of cross-document references. This would make the OpenAPI documents self-contained, but has two drawbacks:
* We lie to OpenAPI clients by pretending not to know what the target schema of the cross-service reference is, so they have to expect anything
* We still get resolver errors for non-trivial services due to document-internal references similar to https://github.com/swagger-api/swagger-ui/issues/3366

**Comment by heldersepu** [comment] 2018-02-14 15:45
If we are looking for "The easiest workaround" just stick with the older version until there is a fix for this

**Comment by shockey** [comment] 2018-02-16 06:37
Jumping in here! 

This smells like a regression. @heldersepu, I don't see how your changes would have caused this right off the bat, but it looks as if that was the only change to Swagger-Client that shipped with UI 3.10.0.

I don't have any bandwidth for this before the end of the week (shipping some exciting stuff tomorrow though, keep a look out!) but I'll look at this early next week.

That said... if either of you crack the code before I can get to it, I wouldn't complain :wink:

**Comment by ralfhandl** [comment] 2018-02-16 13:37
See https://github.com/swagger-api/swagger-ui/issues/3366#issuecomment-366096404: cycle detection seems to work if you start within the cycle, and fail if you start outside of the cycle but then reach a cycle.

**Comment by heldersepu** [comment] 2018-02-16 14:30
I think that this issue is not related to 3366 in any way...
And to be honest the root cause of this issue does not seem about Cyclic references.

Here we are getting a: `Could not resolve reference because of: Could not resolve pointer`
That other is showing: `Cannot read property '...' of undefined`

**Comment by heldersepu** [comment] 2018-02-26 13:59
@ralfhandl && @shockey 
I do not see the errors on the latest:
- [petstore.swagger.io/?url=.../People.openapi3.json](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi3.json)
- [petstore.swagger.io/?url=.../Products.openapi3.json](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/Products.openapi3.json)

Magically fixed?

**Comment by heldersepu** [comment] 2018-02-26 14:36
One observation... 
there seems to still be an error, but it only shows after we start expanding stuff:
> Resolver error at paths./Products.get.responses.200.content.application /json.schema.properties.value.items.properties.Supplier.anyOf.0.$ref
Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: './People.openapi3.json' basePath: 'undefined'

But if is already expanded it does not show any errors:
[petstore.swagger.io/?url=.../People.openapi3.json&defaultModelsExpandDepth=5&docExpansion=full](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi3.json&defaultModelsExpandDepth=5&docExpansion=full)

**Comment by heldersepu** [comment] 2018-02-26 15:00
Comparing Specs:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#server-object-example

`basePath` was a Fixed field on 2.0 does not look that way on 3.0.1

**Comment by ralfhandl** [comment] 2018-02-26 16:04
Don't know about magic, but Swagger UI 3.11.0 certainly fixes this problem of Swagger UI 3.10.0.

Thanks a lot!

**Comment by heldersepu** [comment] 2018-02-26 16:06
I think you should keep it open, There still an error here...

**Comment by ralfhandl** [comment] 2018-02-26 16:13
You're right. The problem is there with both the OpenAPI 3.0.0 version of the example and the corresponding Swagger 2.0 version:

http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi.json#/Suppliers/get_Suppliers

Expanding the PATCH and DELETE operations with rather trivial request/response bodies works fine, expanding POST or GET operations with complex request/response bodies produces the `basePath` error.

The Swagger 2.0 variant of the example does define a `basePath`, so the error message seems to be misleading.

**Comment by shockey** [comment] 2018-02-28 00:50
I believe the lingering issue here is the same as #4258.

**Comment by shockey** [comment] 2018-03-01 19:43
Fixed! Thanks for the report @ralfhandl, sorry for the trouble.

You can preview a build that contains the fix here: http://spooky-jellyfish.surge.sh/?url=https://gist.githubusercontent.com/shockey/bbfafa9a57a37d80348a558b2124e314/raw/2d03c5feb0b039d332519582b5e2e0b97365cf61/api1.yaml

**Closed by shockey** 2018-03-01 19:43 UTC
Labels: P1, Regression

**Comment by ralfhandl** [comment] 2018-03-02 14:33
Cool, thanks! It works nicely with my example:

http://spooky-jellyfish.surge.sh/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi.json#/Suppliers/get_Suppliers

**Comment by ralfhandl** [comment] 2018-03-02 14:38
Well, one little snag remains: sometimes clicking on GET /Suppliers results in an endlessly spinning wheel. Clicking GET /Suppliers again to "collapse" it and then click a third time to "open" it again usually works.

![image](https://user-images.githubusercontent.com/951576/36903867-3c06f464-1e2f-11e8-953e-244dbc71cc3b.png)

**Comment by shockey** [comment] 2018-03-02 23:56
@ralfhandl hmm, weird - have you been able to figure out what's triggering the problem, or is it seemingly random?

**Comment by shockey** [comment] 2018-03-03 00:27
I think I found the problem 😄 @ralfhandl the patch I made will be released tonight!

**Comment by ralfhandl** [comment] 2018-03-05 09:00
Well, it is getting even weirder now. If I open Swagger UI with a fragment that expands GET /Suppliers, everything loads and looks good:
* http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi.json#/Suppliers/get_Suppliers

If I open Swagger UI without a fragment and then click on GET /Suppliers, I get resolver errors:
* http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/People.openapi.json

I also get resolver errors with both of the above URLs if I open GET Suppliers({ID}) for the first time. Closing it and expanding it again makes the resolver errors go away. 

This only affects the two GET operations for Suppliers, not the GET operations for People or PersonDetails.
