### ISSUE TITLE
Headers aren't displayed for responses

### ISSUE THREAD

**Issue by szymonp-kainos** [swagger-api/swagger-ui#1362] opened 2015-06-11 12:15 UTC
Tested on master 1f73415d0899d1fad41988e4858dbe21a624f186
On http://editor.swagger.io/#/ headers are displayed correctly.

Test response message
```json
   "201": {
      "description": "Object was correctly created",
      "headers": {
        "ETag": {
          "description": "versionId",
          "type": "string"
        },
        "Last-Modified": {
          "description": "date of last update",
          "type": "string"
        }
      }
    }
```

**Comment by webron** [comment] 2015-06-11 13:05
This is a duplicate of #1117.

**Closed by webron** 2015-06-11 13:05 UTC
