### ISSUE TITLE
Docker page: Lot's of deadlinks

### ISSUE THREAD

**Issue by ffmit** [swagger-api/swagger-ui#7115] opened 2021-03-24 09:20 UTC
Hello,

surely this one is not related to Swagger-ui itself, but it affects usage of the same.

The [Docker hub page](https://hub.docker.com/r/swaggerapi/swagger-ui) has lots of deadlinks,
starting from "Installation" ending at "Contributing", all are leading to the same error page.

Please see attached.

![grafik](https://user-images.githubusercontent.com/18364436/112284599-b29d6600-8c89-11eb-8810-722b7681ed0f.png)

![grafik](https://user-images.githubusercontent.com/18364436/112285151-496a2280-8c8a-11eb-988e-6d362d00ffce.png)

**Comment by hkosova** [comment] 2021-03-24 13:09
Duplicate of #6233.

**Closed by hkosova** 2021-03-24 13:09 UTC
