### ISSUE TITLE
Parameters in path scope not read

### ISSUE THREAD

**Issue by vpranckaitis** [swagger-api/swagger-ui#1118] opened 2015-04-03 07:59 UTC
swagger-ui doesn't read the path scope parameters (only method scope parameters).

Given spec:
```
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "example"
    },
    "paths": {
        "/eshop/{param1}/{param2}": {
			"parameters": [
				{
					"$ref": "#/parameters/param1"
				}
			],
            "post": {
                "description": "description",
				"parameters": [
                    {
                        "$ref": "#/parameters/param2"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "parameters": {
        "param1": {
            "name": "param1",
            "in": "path",
            "description": "param1",
            "required": true,
            "type": "number"
        },
        "param2": {
            "name": "param2",
            "in": "path",
            "description": "param2",
            "required": true,
            "type": "number"
        }
    }
}
```

The result:
![swagger](https://cloud.githubusercontent.com/assets/9212555/6979670/b8ccef94-d9ef-11e4-9d57-ce32e65729f3.PNG)

Swagger-editor displays parameters correctly:
![editor](https://cloud.githubusercontent.com/assets/9212555/6979716/60a94e9c-d9f0-11e4-9152-3161b799459c.PNG)

**Comment by fehguy** [comment] 2015-04-14 16:54
This should be supported in develop_2.0 now.  Please try again?

**Comment by pjmolina** [comment] 2015-06-15 17:14
Tested in `develop_2.0` with this sample swagger: https://gist.githubusercontent.com/pjmolina/39c7d7c415cc8b4acb85/raw/2a8dbb5c695e1beefa5fcf9ea532502f38132218/routeParameters.json

Unfortunately, the issue is still happening:
 - Parameters defined at operation level are shown. 
 - Parameters defined at path level are not shown.

**Comment by webron** [comment] 2015-06-15 17:16
Confirmed.

**Comment by pjmolina** [comment] 2015-06-17 11:22
Another repro sample. https://gist.githubusercontent.com/pjmolina/2c10cf5b06d20dbc6438/raw/c5c74734354fbc5e995bb8070346ed06f496aa45/joni.json

Swagger doc is valid accordingy to validator: http://online.swagger.io/validator/debug?url=https://gist.githubusercontent.com/pjmolina/2c10cf5b06d20dbc6438/raw/c5c74734354fbc5e995bb8070346ed06f496aa45/joni.json

In this case:
- Parameters defined inline at operation level are shown.
- Referencing params not shown (operation level and path level).

**Comment by webron** [comment] 2015-06-17 14:05
This probably depends on https://github.com/swagger-api/swagger-js/issues/491.

**Comment by glen-84** [comment] 2015-07-21 14:36
:+1:

**Comment by zallek** [comment] 2015-10-05 14:45
:+1:

**Comment by fehguy** [comment] 2015-10-05 18:28
ok got it. This is something that needs to be addressed here:

https://github.com/swagger-api/swagger-js/blob/master/lib/resolver.js

I'll open a ticket in that repo and reference this one

**Comment by fehguy** [comment] 2015-12-07 20:47
This has been resolved in swagger-js.

**Closed by fehguy** 2015-12-07 20:47 UTC
Labels: Bug, P1
