### ISSUE TITLE
when using allOf, Swagger UI will not show model definition

### ISSUE THREAD

**Issue by denghongcai** [swagger-api/swagger-ui#1572] opened 2015-08-28 04:11 UTC
```
UserQuestion: {
    allOf: [{
        $ref: "#/definitions/UserQuestionBasic"
    },
    {
        definition: "UserQuestionAddition",
        required: ["user_pet_id"],
        properties: {
            user_pet_id: {
                type: "string"
            }
        }
    }]
},
```

Schema is shown
![Imgur](http://i.imgur.com/YFwX7db.png)

But model definition is not shown
![Imgur](http://i.imgur.com/rMe3hC9.png)

Is this a bug or a feature ?

Swagger UI version is 2.1.1

**Comment by devigned** [comment] 2015-09-01 15:22
Duplicate of #723

**Comment by denghongcai** [comment] 2015-09-01 16:00
#723 is about model schema

**Comment by fehguy** [comment] 2015-09-05 07:19
This seems fixed in swagger-ui 2.1.2.  I've tested your sample and I see the correct model description.  note that you have an invalid field in your example:

```
definition: "UserQuestionAddition"
```

The property `definition` is not part of the [swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md).

Please reopen if you still see issues.

**Closed by fehguy** 2015-09-05 07:19 UTC

**Comment by denghongcai** [comment] 2015-09-09 04:17
I upgrade  swagger but no changes :cry:

**Comment by fehguy** [comment] 2015-09-09 05:11
Please share your whole swagger spec and I'll try it again.

**Comment by denghongcai** [comment] 2015-09-09 05:32
```
/user/question: {
  post: {
  tags: [
    "USER"
  ],
  summary: "创建一个问题",
  parameters: [
  {
    name: "body",
    in: "body",
    description: "问题内容",
    schema: {
      $ref: "#/definitions/UserQuestion"
    }
  }],
  responses: {
    201: {
    description: "问题已成功创建",
    schema: {
      $ref: "#/definitions/UserQuestionResponse"
    }}
  }
  }
}
``

```
UserQuestion: {
    allOf: [{
        $ref: "#/definitions/UserQuestionBasic"
    },
    {
        required: ["user_pet_id"],
        properties: {
            user_pet_id: {
                type: "string"
            }
        }
    }]
}
```
UserQuestionBasic: {
   required: [
  "syptom"
  ],
  properties: {
    symptom: {
      description: "",
      type: "string"
    }
  }
}
```

```

**Comment by mar612** [comment] 2015-09-09 16:02
1. There is a mistake in your UserQuestionBasic.  You've misspelled the parameter "symptom" under "required".
2. Where's the definition for UserQuestionResponse?

**Comment by denghongcai** [comment] 2015-09-11 02:39
```
"UserQuestionResponse": {
    "allOf": [{
        "$ref": "#/definitions/UserQuestionBasic"
    },
    {
        "properties": {
            "pet": {},
            "id": {
                "type": "integer"
            },
            "user_id": {
                "type": "string"
            }
        }
    }]
}
```

Still not work

**Comment by mar612** [comment] 2015-09-14 20:20
I don't have an issue with getting your definitions to load in Swagger UI.
Here is the swagger.json I used to test:

{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "denghongcai Swagger API"
  },
  "tags": [
    {
      "name": "USER"
    }
  ],
  "paths": {
    "\/user\/question": {
      "post": {
        "tags": [
          "USER"
        ],
        "summary": "创建一个问题",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "问题内容",
            "schema": {
              "$ref": "#\/definitions\/UserQuestion"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "问题已成功创建",
            "schema": {
              "$ref": "#\/definitions\/UserQuestionResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "UserQuestionBasic": {
      "type": "object",
      "required": [
        "symptom"
      ],
      "properties": {
        "symptom": {
          "type": "string",
          "description": ""
        }
      }
    },
    "UserQuestion": {
      "allOf": [{
        "$ref": "#/definitions/UserQuestionBasic"
      },
      {
        "required": [
          "user_pet_id"
        ],
        "properties": {
          "user_pet_id": {
            "type": "string"
          }
        }
      }]
    },
    "UserQuestionResponse": {
      "allOf": [{
        "$ref": "#/definitions/UserQuestionBasic"
      },
      {
        "properties": {
          "pet": {},
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "string"
          }
        }
      }]
    }
  }
}

**Comment by webron** [comment] 2015-09-21 15:58
@mar612 - thanks for looking into it.

**Comment by NicolasCayet** [comment] 2016-01-07 15:40
Hello,
I'm facing the same issue with a schema as BODY parameter containing a "allOf" attribute.

Does anyone have solved this error ?

I am using Swagger UI v2.1.1. The result is shown in this screenshot:
![capture d ecran 2016-01-07 a 16 33 03](https://cloud.githubusercontent.com/assets/7132562/12174372/7272890c-b55c-11e5-9749-2b913d55a0e6.png)


Below is the definition of one operation having trouble (other operations with the same structure as body parameter have the same problem), it has been submitted to editor.swagger.io and validated :
```
"\/users\/account\/facebook": {
			"post": {
				"operationId": "postAccountFacebookUsersFacebook",
				"summary": "Create an account from a Facebook session.",
				"description": " All datas about new user additionally passed into body parameters will override datas from Facebook session, and therefore, they will be validated before creation.",
				"parameters": [{
					"name": "fields",
					"in": "query",
					"required": false,
					"description": "Field names of the returned object that will be sent in response. If no value for this parameter, send all object properties. For sub-object fields, use colon (:) as separator",
					"type": "string",
					"default": "[]"
				}, {
					"name": "REQUEST_BODY",
					"in": "body",
					"description": "The payload that's appended to the HTTP request",
					"schema": {
						"allOf": [{
							"$ref": "#\/definitions\/Model_User_Standard_Input"
						}, {
							"type": "object",
							"properties": {
								"fb_access_token": {
									"description": "Access token requested from Facebook session",
									"type": "string"
								}
							}
						}]
					}
				}],
				"security": [{
					"anonymous_auth": ["default"]
				}],
				"responses": {
					"200": {
						"description": "The new user created",
						"schema": {
							"$ref": "#\/definitions\/Model_User_Standard_Output"
						}
					}
				}
			}
		},
```

The definition for Model_User_Standard_Input is (it is already used in other operations and is well displayed):
```
"Model_User_Standard_Input": {
		"type": "object",
		"description": "Abstract provisioning class defining common functions \/ attributes for provisioning authenticating with login and password (encrypted)<br\/><br\/>Provisioning extending this class does not allow recover account\/password by default (it must implement Model_User_IRecoverAccount first)",
		"properties": {
			"login": {
				"description": "Unique identifier for user, defined by himself in order to log in to API. Required if no email address has been provided",
				"type": "string",
				"maxLength": 255,
				"minLength": 1
			},
			"password": {
				"description": "Password for user, not hashed (but not store in persistent)",
				"type": "string",
				"minLength": 1
			},
			"email": {
				"description": "Email address",
				"type": "string",
				"maxLength": 255
			},
			"authorization_level": {
				"description": "Authorization level for the user",
				"type": "integer",
				"minimum": 0
			},
			"default_lang": {
				"description": "Default language for this user",
				"type": "string"
			},
			"edit_authorized_lang": {
				"description": "List of languages available for user when editing elements in API.",
				"type": "array",
				"items": {
					"type": "string"
				}
			},
			"gender": {
				"description": "User's gender. Valued by 1 for male or 2 for female",
				"type": "integer"
			},
			"firstname": {
				"description": "Firstname",
				"type": "string",
				"maxLength": 255
			},
			"lastname": {
				"description": "Lastname",
				"type": "string",
				"maxLength": 255
			},
			"country_code": {
				"description": "User's country's code from. ISO 3166-2 (Alpha-2 code)",
				"type": "string"
			},
			"phone": {
				"description": "Phone number with E.164 format. Leading `+` sign followed by country code are required",
				"type": "string",
				"maxLength": 20
			},
			"address": {
				"description": "Adress (number \/ street)",
				"type": "string",
				"maxLength": 255
			},
			"zipcode": {
				"description": "Zip code",
				"type": "string",
				"maxLength": 11
			},
			"city": {
				"description": "City name",
				"type": "string",
				"maxLength": 255
			}
		}
	}
```

**Comment by webron** [comment] 2016-01-07 15:42
Try updating to the latest version.

**Comment by NicolasCayet** [comment] 2016-01-07 15:50
Are you talking about the v2.1.4 which have a main issue with popup ?

![capture d ecran 2016-01-07 a 16 49 31](https://cloud.githubusercontent.com/assets/7132562/12174749/b2dd2694-b55e-11e5-923e-6d61481b12ff.png)

**Comment by webron** [comment] 2016-01-07 15:53
Is the first issue you raised resolved with it?

**Comment by NicolasCayet** [comment] 2016-01-07 16:02
I did not mention it sorry, but yes, the first issue is resolved with this version. So for now, I'll wait for a more stable version...
