### ISSUE TITLE
OAS 3.0 | Swagger-UI | Required input parameters not getting validated

### ISSUE THREAD

**Issue by zaheena** [swagger-api/swagger-ui#3747] opened 2017-10-11 15:16 UTC
I downloaded the `Swagger-UI 3.X` code from https://github.com/swagger-api/swagger-ui as of 10/11/2017.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Open Api 3.0
| Which Swagger-UI version?       | swagger-ui, 3.x
| How did you install Swagger-UI? | Dowloaded zip, extracted the /dist folder and added my yaml file to it.
| Which browser & version?        | Chrome Version 61.0.3163.91
| Which operating system?         | macOS Sierrra

### Demonstration API definition

```yaml
openapi: "3.0.0"

info:
  version: 1.0.0
  title: Example API
  description: A sample API using OpenApi 3.0
  contact:
    name: ABC
    email: test@test.com

servers:
  - url: http://localhost:8080
    description: Local instance of API

paths:
  /examples/{id}:
    get:
      tags: [examples]
      description: Test path
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: test
        in: query
        description: test query
        required: false
        schema:
          type: string
          example: test
      responses:
        '200':
          description: test response
          content:
            application/json:
              schema:
                type: string
                example: success
```

Extracted the `dist` folder from swagger-UI and added the following`swaggerEx.yaml` file to it:

In the `index.html` folder I made the following change:
```
  // Build a system
  const ui = SwaggerUIBundle({
    url: "swaggerEx.yaml",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

```

### Expected Behavior
As in swagger 2.0, I expected that the required parameters would be validated such as:

<img width="724" alt="screen shot 2017-10-11 at 10 11 34 am" src="https://user-images.githubusercontent.com/6210587/31449489-ad753896-ae6c-11e7-8f1b-e4ca9d3d1ee5.png">

### Current Behavior
With the new UI I see that the `required` parameter validation does not occur and the call keeps `loading` but never gets executed. Here is a screen shot with that behavior:
<img width="1426" alt="screen shot 2017-10-11 at 10 14 15 am" src="https://user-images.githubusercontent.com/6210587/31449612-fdb01b64-ae6c-11e7-9266-54f47ce0177d.png">

### Context
We are trying to document our API using Swagger. Right now the documentation part works but if we want to provide user with the ability to try out the API we cannot do that because of this issue.

Thank you.

**Comment by webron** [comment] 2017-10-11 15:41
@owenconti can you take a look?

**Comment by shockey** [comment] 2017-10-11 20:55
It'd be great to have this fixed before Friday's release.

**Comment by owenconti** [comment] 2017-10-11 21:03
Looking into it now.

**Comment by zaheena** [comment] 2017-10-25 22:50
Thank you for the fix!

**Comment by bronekrab** [comment] 2018-01-18 23:20
Hi, @owenconti , @webron , @shockey !
Topic starter's example still not working on https://editor.swagger.io.  `Id` path parameter is not highlighted in red. This is normal?

**Comment by shockey** [comment] 2018-01-18 23:26
@bronekrab, the issue is a little different: the required warning isn't showing, but the execute state isn't running away either.

that being said, i see it too - i'll reopen this.

**Comment by shockey** [comment] 2018-01-26 04:15
This will be fixed (again) in tomorrow night's release.

Thanks for the heads up on the regression, @bronekrab!

**Closed** 2018-01-26 04:14 UTC
Labels: 3.x, Bug, P2

**Comment by KyleGalvin** [comment] 2018-09-09 17:33
I am having a nearly identical issue. 

The only difference is I am using a swagger 2.0 document against swagger-ui 3.18.3
![swaggeruierror](https://user-images.githubusercontent.com/1386124/45267109-328cb900-b41b-11e8-905f-706798b8125c.png)

checking the network tab, the request is never made.

**Comment by KyleGalvin** [comment] 2018-09-09 17:40
After more troubleshooting, I took off the 'required' field to attempt to bypass validation. I enter a value for 'id' and I get 'undefined' in the url path:
![swaggeruierror](https://user-images.githubusercontent.com/1386124/45267194-b72c0700-b41c-11e8-9f0a-80e615b0aea6.png)

**Comment by francisco-lopez** [comment] 2019-06-06 18:15
Hi!! They have a solution? I 'am having the same problem

**Comment by nirmalgoswami** [comment] 2020-03-07 04:04
Same issue in openapi 3.0

**Comment by karvapallo** [comment] 2020-10-15 22:09
Still seeing this issue using OpenAPI 3.0

**Comment by fabpico** [comment] 2023-01-13 14:19
Is still happening. With GUI of https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#unpkg (swagger-ui-dist@4.5.0).

Console error:

```
system.js:490
Error: Required parameter id is not provided
    at index.js:233:13
    at Array.forEach (<anonymous>)
    at Object.Dn [as buildRequest] (index.js:200:22)
    at actions.js:452:24
    at utils.js:177:16
    at redux.js:546:12
    at wrap-actions.js:33:10
    at Object.r (system.js:175:26)
    at Object.executeRequest (system.js:487:14)
    at actions.js:499:22
```

Definition:
```
    /**
     * @OA\Get(
     *      path="/api/rest/article/{id}",
     *      tags={"REST"},
     *      @OA\Parameter(name="id", in="path", required=true),
     *      @OA\Response(
     *          response=200,
     *          description="Success",
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(
     *                  type="array",
     *                  @OA\Items(
     *                      @OA\Property(property="title", type="string"),
     *                      @OA\Property(property="description", type="string"),
     *                      @OA\Property(property="date", type="date"),
     *                      @OA\Property(property="authors", type="array",
     *                          @OA\Items(
     *                              @OA\Property(property="firstName", type="string"),
     *                              @OA\Property(property="lastName", type="string"),
     *                          )
     *                      ),
     *                  )
     *              )
     *          )
     *      )
     * )
     */
```
