### ISSUE TITLE
Can you display a lot of documents at the same time

### ISSUE THREAD

**Issue by xiaonizi-github** [swagger-api/swagger-ui#3630] opened 2017-09-01 08:04 UTC
sorry,t have ever ask this question,but i don not understand,so i ask again,Can this tool show only one document? I want to show a variety of different documents，it is ok?
for example,i have two files,one is the swagger.json,the second is swagger2.json,i want to display all in swagger-ui,how i should do?
and i start the swagger-ui by docker,the command is :docker run -d -p 8084:8080 -e "SWAGGER_JSON=xxx" -v /foo:/foo swagger-ui.

my swagger.json like this:
{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.",
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "localhost:8888",
  "basePath": "/clpssh",
  "tags": [
    {
      "name": "register",
      "description": "",
      "externalDocs": {
        "description": "",
        "url": "http://localhost:8888"
      }
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/register/addUser.do": {
      "post": {
        "tags": [
          "register"
        ],
        "summary": "Create user",
        "description": "This can only be done by the logged in user.",
        "operationId": "createUser",
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "formData",
            "name": "username",
            "description": "Created user object",
            "required": true,
            "type": "string"
          },
          {
            "in": "formData",
            "name": "password",
            "description": "Created user object",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": "#/definitions/ApiResponse"
          },
          "default": {
            "description": "successful operation"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "petstore_auth": {
      "type": "oauth2",
      "authorizationUrl": "http://petstore.swagger.io/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "write:pets": "modify pets in your account",
        "read:pets": "read your pets"
      }
    },
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}

the other file is the same.

**Comment by xiaonizi-github** [comment] 2017-09-01 08:09
@shockey @hkosova

**Comment by heldersepu** [comment] 2017-09-02 16:54
@xiaonizi-github 
As far as I know there is no way to display multiple swagger documents **at the same time**, you will have to combine them ahead of time, a script to do that should not be very difficult.

But Swagger-UI can show them in a nice drop-down ...
That way the user can pick one and see the documentation for their selection.
![image](https://user-images.githubusercontent.com/545474/29997267-d6918c2e-8fdc-11e7-9587-aa7d8c7a3efb.png)
That is done using the urls parameter:
https://github.com/swagger-api/swagger-ui#parameters

I hope that helps you...

**Comment by xiaonizi-github** [comment] 2017-09-04 01:48
@heldersepu thank you,i have a try.

**Comment by heldersepu** [comment] 2017-09-04 02:46
Since this is not a Bug or a Feature request... You should probably close this issue, if you have other questions post them on StackOverflow with the swagger tag, I'm sure there you will get a faster response.
https://stackoverflow.com/questions/tagged/swagger

**Comment by xiaonizi-github** [comment] 2017-09-04 09:13
@heldersepu  hello，i have search questions about swagger-ui # paramaters (urls),that do can display multiple files,but i want to display myself  *.jsons and by docker command,can you tell me what i should do ?

**Comment by heldersepu** [comment] 2017-09-04 13:58
Sorry, I don't know anything about docker, you should ask that on StackOverflow

**Comment by shockey** [comment] 2017-09-25 22:18
Closing due to inactivity.

**Closed by shockey** 2017-09-25 22:18 UTC
