### ISSUE TITLE
$refs failed to resolve with such error: "Could not resolve reference: Failed to execute 'delete' on 'Headers': Headers are immutable"

### ISSUE THREAD

**Issue by PatchRanger** [swagger-api/swagger-ui#8532] opened 2023-03-30 11:32 UTC
OS: Ubuntu 22.04.1
Browser: Chromium-based
Version 108.0.0.0
Method of installation: via docker image swaggerapi/swagger-ui
Swagger-UI version: v5.0.0-alpha.4
Swagger/OpenAPI version: 3.1.0

The installation is the same as in https://github.com/swagger-api/swagger-ui/issues/8525#issuecomment-1487891160.

After I successfully applied the workaround about absolute paths for `$ref`, I see in the browser console that requests for schemas began to go to the correct host - and even return with a 200 response.
But I found another problem: `$ref` inside uploaded documents refuse to load, I see a lot of red error messages with the following text:
```
Resolver error at $ref
Could not resolve reference: Failed to execute 'delete' on 'Headers': Headers are immutable
```
I see nor errors in the browser console neither non-ok requests in its Network tab.

In addition, when I click on the dropdown arrow next to each operation, the operation dropdown does not drop out - just the dropdown arrow changes to "open" and that's it. I believe this is related: apparently due to the fact that `$ref` has not loaded, there is nothing to show in the operation dropdown.

Perhaps the reason for this is the same as in the previous issue: incorrect resolution of relative paths. I hope that after fixing that problem, this problem will also go away. But perhaps this is not related, I do not have enough SwaggerUI context to judge with complete confidence - therefore, I am creating this issue in order to inform the development team about the difficulties that arise.

**Comment by PatchRanger** [comment] 2023-03-30 11:33
![Снимок экрана от 2023-03-30 18-12-09](https://user-images.githubusercontent.com/3889569/228823227-fe4f1b56-19e2-4d72-ba40-9501adb72364.png)

**Comment by char0n** [comment] 2023-03-30 14:30
#8525 was resolved in https://github.com/swagger-api/swagger-ui/pull/8533 and is unrelated to this issue.

**Comment by char0n** [comment] 2023-03-30 14:49
The issue is in again in swagger-client on this [line](https://github.com/swagger-api/swagger-js/blob/ae0e7e8fc67b535926ef7522c028f923c911bb86/src/resolver/apidom/reference/resolve/resolvers/http-swagger-client/index.js#L38).

**Comment by char0n** [comment] 2023-03-30 15:17
[Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) are immutable and thus we cannot remove headers from it. This works in `node-fetch` but doesn't work in browsers. 

To fix this, we have to clone the response in order to mutate it.

More info in https://developer.mozilla.org/en-US/docs/Web/API/Headers

**Comment by char0n** [comment] 2023-03-30 15:59
Addressed in https://github.com/swagger-api/swagger-js/commit/1df6b38a669fa68b78d98f8b19668e7cc344ec08

**Comment by char0n** [comment] 2023-03-31 07:16
Addressed for swagger-ui@5 in https://github.com/swagger-api/swagger-ui/pull/8536

**Comment by char0n** [comment] 2023-03-31 07:20
> @char0n Wow, I am impressed, blazingly fast debug & fix, thank you! I am going to check whether it fixes this issue (I am prettty sure it should).

Release will be comming in an half an hour. Please keep the issues related to OpenAPI 3.1.0 comming. OpenAPI 3.1.0 support in swagger-ui@5 is current priority and I appreciate any early feedback that you provide.

**Comment by char0n** [comment] 2023-03-31 07:53
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.5

**Closed by char0n** 2023-03-31 07:53 UTC
Labels: type: bug, version: 5.x
