### ISSUE TITLE
Maximum Values are rounded in swagger UI renderer

### ISSUE THREAD

**Issue by manojpandey89** [swagger-api/swagger-ui#7001] opened 2021-02-25 11:50 UTC
Hi 

Bigger maximum values for integer parameter like 9223372036854775807 are rounded off in renderer to 9223372036854776000. 

This changes the actual maximum value to wrong value. 

PFA the screenshot of the same.

Kindly look into this and fix. 

Thanks, 
Manoj

![image](https://user-images.githubusercontent.com/15842303/109149303-6267dc80-778d-11eb-90eb-f2acbac10b2d.png)

**Comment by hkosova** [comment] 2021-02-25 12:44
Duplicate of #2030

**Closed by hkosova** 2021-02-25 12:44 UTC
