### ISSUE TITLE
Model attribute and its properties not visible in Swagger 3 UI

### ISSUE THREAD

**Issue by codewanderer16** [swagger-api/swagger-ui#3642] opened 2017-09-08 21:30 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.1.7, 3.0.14
| How did you install Swagger-UI? | from the download zip
| Which browser & version?        | several
| Which operating system?         | Windows 10

### Demonstration API definition

[example swagger.json file](https://gist.github.com/codewanderer16/1ba4327eb54dcb97ec63f5ba40580f8d)

### Current Behavior

In the Patch Request model, expand Operations. The information for "value" is not visible.
(Occurs in the PATCH endpoint and the Models section.)

In the PATCH endpoint, the example value does not even list "value."

### Expected Behavior

Full content should be displayed.

**Comment by webron** [comment] 2017-09-11 09:16
The example doesn't list "value" because it doesn't have a type, so producing an example for it would be tricky. We could provide an example of an object/string/integer/array but no matter what we'll choose, someone will end up unhappy about it.

**Comment by hkosova** [comment] 2017-09-11 09:16
This might be related to #3545.

**Comment by hkosova** [comment] 2017-09-11 09:18
@webron the issue is also that the Model renderer does not render the property description.
![image](https://user-images.githubusercontent.com/8576823/30267432-3e13098a-96eb-11e7-87a3-50ff12ea9135.png)

**Comment by hkosova** [comment] 2017-09-11 09:21
@codewanderer16, is `value` suppposed to have no explicit `type`? No `type` means it can be any type - string, number, object, etc.

If it's supposed to be a key/value map (dictionary) then it should be `type: object` with `additionalProperties`. https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by webron** [comment] 2017-09-11 09:25
@hkosova yeah, I was just talking about the example value. I'm aware the `description` is not rendered which is why I didn't just close the ticket.

**Comment by codewanderer16** [comment] 2017-09-11 16:49
@hkosova yes, `value` can be any type.

For the example model, any example I choose will, of course, have a specific type. But will it be visible when `value` itself has no type? Not displaying it seems like a problem.

**Comment by codewanderer16** [comment] 2017-09-11 16:54
In Swagger 2.0, the description does render:
![image](https://user-images.githubusercontent.com/31778191/30286591-5bb04aae-96df-11e7-9db9-1ac8df041a87.png)

And `value` is visible in the example:
![image](https://user-images.githubusercontent.com/31778191/30286639-81aca2a2-96df-11e7-96f3-c2372bfac033.png)

**Comment by webron** [comment] 2017-09-11 21:26
Yes, but it's rendered *wrong*. There's no real right way of rendering it, not sure what would be the right solution here. The best suggestion right now is for you to provide an example yourself and that would be rendered.

**Comment by webron** [comment] 2018-07-05 19:13
Closing as this renders correctly now.

**Closed by webron** 2018-07-05 19:13 UTC
Labels: P2, type: bug, version: 3.x
