### ISSUE TITLE
Non-ascii character in src/core/components/parameter-row.jsx

### ISSUE THREAD

**Issue by briankrug** [swagger-api/swagger-ui#3104] opened 2017-05-18 16:54 UTC
The src/core/components/parameter-row.jsx file contains a non-ascii character at line 83 in the word parameter__type (The second a is actually a cyrillic lower case a - unicode point 430).

**Comment by shockey** [comment] 2017-05-18 22:30
Line 97 does indeed have a non-ASCII character, and has had one since the init commit: https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/parameter-row.jsx#L97

![image](https://cloud.githubusercontent.com/assets/680248/26225926/6cf9b2fc-3bde-11e7-9a81-3cc596210432.png)

Confirmed via [this script](http://www.babelstone.co.uk/Unicode/whatisit.html).

@briankrug, could you submit a PR that fixes this? 😄

**Comment by shockey** [comment] 2018-03-01 21:02
Fixed in https://github.com/swagger-api/swagger-ui/pull/3350.

Thanks for the report, @briankrug!

**Closed by shockey** 2018-03-01 21:02 UTC
Labels: P3, Ready, version: 3.x
