### ISSUE TITLE
subTypes not displayed in model

### ISSUE THREAD

**Issue by rpofuk** [swagger-api/swagger-ui#1526] opened 2015-08-10 11:52 UTC
Hi!

I have service and model definition:
SERVICE: 

```
"path" : "/process/start",
    "operations" : [ {
      "method" : "POST",
      "nickname" : "startProcess",
      "type" : "void",
      "parameters" : [ {
        "type" : "array",
        "items" : {
          "$ref" : "ProcessTaskDTO"
        },
        "paramType" : "body",
        "name" : "tasks",
        "required" : true
      }, {
        "type" : "string",
        "paramType" : "query",
        "name" : "token"
      } ],
      "consumes" : [ "application/json" ],
      "produces" : [ "application/json" ]
    } ]
```

MODEL: 

```
"ProcessTaskDTO" : {
      "id" : "ProcessTaskDTO",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        }
      }, 
      "subTypes" : ["ProcessTaskDTO1", "ProcessTaskDTO2"],
      "discriminator": "type"
    },
    "ProcessTaskDTO1" : {
      "id" : "ProcessTaskDTO1",
      "properties" : {
        "name1" : {
          "type" : "string"
        }
      }
    },
    "ProcessTaskDTO2" : {
      "id" : "ProcessTaskDTO2",
      "properties" : {
        "name2" : {
          "type" : "string"
        }
      }
    },
```

But model is not displayed in UI: 

![image](https://cloud.githubusercontent.com/assets/2906197/9170797/5b39c244-3f66-11e5-9045-bbb23383db16.png)

Found issue https://github.com/swagger-api/swagger-ui/issues/300 that's closed and it's related to response class. Is request model still an issue?

**Comment by webron** [comment] 2015-08-10 22:19
You're using an old version of the Swagger specification and some the conversion to 2.0 may not work properly. You can try the [v2.0.24](https://github.com/swagger-api/swagger-ui/tree/v2.0.24) tag which may have better results, but IIRC, there was never really support for sub types in older versions.

**Comment by pofuk** [comment] 2015-08-11 07:28
I'm compiled latest version from master. 
Is the problem in specification file (json file i supply to swagger) or the swaggerui version?

**Comment by pofuk** [comment] 2015-08-11 11:27
I converted my code to new spec version but still getting model withouth inherited entitys:

```
"ProcessTaskDTO": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "discriminator": "type",
      "required": [
        "type"
      ]
    },
    "ProcessFreeElementTask": {
      "allOf": [
        {
          "$ref": "#/definitions/ProcessTaskDTO"
        },
        {
          "properties": {
            "elementName": {
              "type": "string"
            }
          }
        }
      ]
    },
    "ProcessReferecedElementTaskDTO": {
      "allOf": [
        {
          "$ref": "#/definitions/ProcessTaskDTO"
        },
        {
          "properties": {
            "referecedElementId": {
              "type": "string"
            }
          }
        }
      ]
    },
```

![image](https://cloud.githubusercontent.com/assets/2906197/9196541/a91e0f80-402c-11e5-863b-d1b4d27b5179.png)

**Comment by webron** [comment] 2015-08-11 16:17
The support for `allOf` is currently incomplete. If you search the repository, you'll find the relevant issues.

**Comment by devigned** [comment] 2015-09-01 15:21
Duplicate of #723

**Comment by fehguy** [comment] 2015-09-05 07:29
@pofuk what you're seeing actually is what I would expect.  Since you're missing a bit of information I'm making one assumption.

In your input, you're using the `ProcessTaskDTO` as the input.  In your 2.0 spec version, there are only 3 fields, all of which you're seeing in the UI.  Likewise for the output, I'm guessing that's the output model that you have.

If you changed the input model to, say `ProcessReferecedElementTaskDTO` you would have the additional field `referecedElementId`. 

That said, what are you expecting?  Or did I get it wrong regarding the input type?

**Comment by mgttlinger** [comment] 2015-09-08 06:52
As I understand the spec if you specify a discriminator your types get treated as a polymorphic hierarchy and therefore the subtypes `ProcessFreeElementTask` and `ProcessReferecedElementTaskDTO` should be possible values and therefore shown. 

This is already implemented in the `develop_2.0` branch of swagger-js but not included in the current build of swagger-ui as it uses the `master` branch of swagger-js.

**Comment by AlbertoLeon** [comment] 2015-12-04 12:02
I need it subTypes and allowOf in my swagger-editor
Any plans to release it?

**Comment by mgttlinger** [comment] 2015-12-04 12:43
@AlbertoLeon It seems as though the feature was lost (or intentionally left out) when switching the branching model because it was implemented in the dev-branch but does not seem to have been merged to the master branch. I asked about this on the google group but unfortunately got no answer.

**Comment by ikitommi** [comment] 2016-03-09 14:23
Hi. Any news on this? Haven't seen any working examples of use of discriminator with the swagger-ui.

**Comment by DerManoMann** [comment] 2016-05-23 03:54
:+1: 
I'd also be interested to see an update on this - I've spend a fair number of hours trying to figure out how to get the UI to do this and there are lots of contradictionary information out there.

**Comment by greggvarona** [comment] 2016-05-31 10:19
Was anyone able to test `develop_2.0` as @mgttlinger has stated?

**Comment by mgttlinger** [comment] 2016-05-31 10:24
@geggvarona I use a custom built version of that branch when it was still around. The implementation displayed the type of the superclass as the merged properties of the subclasses (all optional)

**Comment by dklotz** [comment] 2016-07-27 14:33
@webron @fehguy any plans for this? It would be nice if for polymorphic input parameters, the ui could give some indication of "If you set the discriminator property to 'TYPE_A', you can use the additional fields 'X' and 'Y' and if you set it to 'TYPE_B' you can use the additional field 'Z'".

**Comment by fehguy** [comment] 2016-07-29 14:43
`allOf` is certainly supported.  Given that this issue is over a year old, and covers many topics, I suggest opening a new one to cover anything that is in the spec but not supported by swagger-ui.

`subTypes` is not a supported construct in the spec, but `allOf` is, as is `discriminator`.

**Comment by zhimoda** [comment] 2016-10-05 13:39
In my project I tried version 2.2.5 of swagger-ui. As I see it this issue is still present and relevant. If you reference a super type that uses the `discriminator`, swagger ui will not tell the viewer anything about the possible sub types. Without consulting the the swagger document itself the viewer sees an incomplete documentation. The choices in a project then are: not use `discriminator` or not not use swagger ui. If the feature was present in a branch that merged into master, what happened to it? Maybe the feature can be included without much work if it wasn't removed on purpose. I could try to look for it myself. I'm not the most qualified person to do so though. I will when I find the spare time. Anybody more qualified looking for a potential quick win?

**Comment by tanguyantoine** [comment] 2016-10-20 07:19
Same for me. Subtypes or not shown.

**Comment by chriswebster** [comment] 2016-11-07 22:30
I see the same issue with swagger-ui 2.2.6, I only see the definitions from the $ref in allOf

**Comment by VIIgit** [comment] 2016-11-15 23:48
Are there any plan's timeline to support this feature also in swagger ui?

**Comment by adeshf** [comment] 2016-12-16 15:47
@zhimoda do you have an example of a project that doesn't use a discriminator that renders properly with the swagger-ui?  I'm having trouble getting subtypes working without discriminators in the swagger-ui as well.

**Comment by agiannone** [comment] 2016-12-23 17:41
+1 polymorphism is fairly important to show otherwise it's effectively incomplete documentation

**Comment by QuasiSoDo** [comment] 2017-01-27 13:53
currently facing the same issue

**Comment by ab-taktik** [comment] 2017-03-02 09:00
currently facing the same issue

**Comment by mthippeswamy** [comment] 2017-03-20 15:25
The issue is still exist in the newer version 3.0.2

**Comment by dlowndes** [comment] 2017-05-16 01:34
I cannot create accurate API documentation without this feature!

**Comment by humblevladimirthegreat** [comment] 2017-05-19 14:28
I am attempting to use the discriminator and allOf features for polymorphism. The response model does not show the subtypes, and in the models you can see the subtypes but they all have the same name as the supertype (and doesn't display the description I've set for the the subtype so the user has no way of knowing which subtype it is). You can see this happen with the [example from the spec](http://swagger.io/specification/#models-with-polymorphism-support-91)  and in this issue https://github.com/swagger-api/swagger-ui/issues/2438

As others have stated, this is a very important issue that I hope gets resolved. It still exists as of the docker-pulled version from yesterday, May 18th (presumably 3.0.10). NOTE: Trying it in SwaggerHug does display the names of the subtype correctly, however the description in each subtype still doesn't show (even if there is no description defined in the supertype), and no mention of subtypes in responses.

**Comment by webron** [comment] 2017-05-19 19:06
To set everyone's expectations - we're currently not actively working on resolving this one. We're focused on adding support for the next version of the spec where additional JSON Schema constructs are added (anyOf, oneOf, not). We're hoping to resolve such rendering issues in that cycle, however, it won't be simple.

**Comment by zainkhalid** [comment] 2017-06-20 13:24
Hi folks,

I'm running into the same issue, and am thinking of implementing a fix for my needs. Based on the last comment on this thread, I understand you all aren't prioritizing fixing this currently, but would you be able to review and merge a PR if I submit one? If so, do you have any suggestions on the best approach to implement a fix?

I'm not too familiar with the codebase, but my current thinking is something along the lines of:

1. Use the `$$ref` and `discriminator` fields to detect subtypes.
2. In the `ParameterRow` and `Response` components, detect when a model has subtypes, and:
a. Create a `ModelExample`component for each subtype
b. Create a tab for each of the `ModelExample` instances. The UI will have a tab for each subtype, with additional tabs under those to view the model and example value (similar to how they currently work) for the selected subtype.

The one thing I'm not sure of how to handle is that, from what I understand of the code, it seems like parameters are currently assumed to have a single `schema` and a single`value` (and/or `value_xml`). For a polymorphic parameter, I believe this won't work because I want to display the model/schema and example value for each subtype. Is the right way to handle this to convert these fields into collections? If so, where is the right place to make that change and populate these fields for each subtype?

**Comment by webron** [comment] 2017-06-20 21:42
@zainkhalid yeah, adding support to it is not going to be easy (yet not impossible). It might be easier to do with OAS3 support.

@shockey might be able to give you some pointers.

**Comment by zainkhalid** [comment] 2017-06-21 03:35
> @zainkhalid yeah, adding support to it is not going to be easy (yet not impossible). It might be easier to do with OAS3 support.

Yup, that makes sense, but I've got a short timeframe + pre-existing codebases to contend with, which is why I'm trying to see if I can get it to work with the 2.0 spec.

> @shockey might be able to give you some pointers.

That would be great!

**Comment by raderio** [comment] 2017-08-01 12:39
Some news about when it will be implemented?

**Comment by zybreak** [comment] 2021-09-03 07:33
Its been 6 years, kids born when this issue was first raised are soon old enough to fix it themselves.

**Comment by webron** [comment] 2021-09-03 18:17
So said kids would be able to fix it themselves but you can't? :wink:

**Comment by zybreak** [comment] 2021-09-04 10:21
> So said kids would be able to fix it themselves but you can't? 😉

I think there’s more truth to that than I want to recognise

**Comment by ponelat** [comment] 2021-09-16 14:01
I'm no six-year old :D, but I can consolidate this issue with #2438. Closing in favour of that one.
Pull requests are still welcome!

**Closed by ponelat** 2021-09-16 14:01 UTC
Labels: type: feature, P2, version: 3.x
