### ISSUE TITLE
swagger crashes browser

### ISSUE THREAD

**Issue by ErliSoares** [swagger-api/swagger-ui#3911] opened 2017-11-15 18:31 UTC
I do not understand the reason the json file does not work, it has been validated with an error in the valuer, and it is not CORS problem, the browser simply hangs and the memory consumption of the browser goes to more than giga byte, the json file is only 131kb, not I was able to detect the problem, do you have any idea what it might be?
Sorry for English
[swagger_.zip](https://github.com/swagger-api/swagger-ui/files/1475864/swagger_.zip)

**Comment by heldersepu** [comment] 2017-11-28 19:30
I started breaking down the swagger.json into a smaller version:
http://nhc-noaa.azurewebsites.net/swagger/ui/index?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=Api
That one is less than 40K
The problem is that the JS takes to long and the browsers start raising warnings, on my version the browser takes approx 10secs, but after everything renders if we go expand/collapse the models it takes a while to respond

**Comment by heldersepu** [comment] 2017-11-28 19:37
Perhaps this issue should be merged into #1919

**Comment by shockey** [comment] 2017-11-28 23:56
@heldersepu, indeed.

Closing as a duplicate of #1919.

@ErliSoares, thanks for providing your Swagger definition - we'll use it to test against as we address performance issues :smile:

**Closed by shockey** 2017-11-28 23:56 UTC
Labels: Support
