### ISSUE TITLE
Wrong rendering of response examples

### ISSUE THREAD

**Issue by marshfire** [swagger-api/swagger-ui#2569] opened 2016-12-19 12:18 UTC
When I define response examples in the swagger editor I have to add application/json: before the response as specified.  However when the examples are rendered in swagger-ui I get the result with "application/json" as part of the resulting object. This seems to be wrong.

![screenshot from 2016-12-19 13-15-09](https://cloud.githubusercontent.com/assets/681471/21312625/806a93b8-c5ed-11e6-98c1-f907d431b04e.png)

swagger-ui version: master

```yaml
swagger: '2.0'

/external/disruptions:
    get:
      description: |
        Gets all possible predefined disruptions for a service the tracker might report.
      responses:
        200:
          description: Successful response
          schema:
            title: Disruptions
            type: array
            items:
              $ref: '#/definitions/disruption'
          examples:
            application/json:
            - id: '0123'
              name:
                en: 'Traffic accident'
                de: 'Verkehrsunfall'
            - id: '110'
              name:
                en: 'Medical emergency'
                de: 'Medizinischer Notfall'
definitions:
  disruption:
    type: object
    properties:
      id:
        type: string
        description: Identifier for a disruption. This will be used to inform about delays caused by disruptions.
      name:
        $ref: '#/definitions/localizedText'
    required: [id, name]
  localizedText:
    type: object
    description: A hashmap with language code as a key and the text as a value.
    properties:
      en:
        type: string
        description: English text must always be provided.
    required: [en]
    additionalProperties:
      type: string
```

**Comment by stevendearborn** [comment] 2016-12-22 22:10
Since this is in YAML, I would try to indent each item one more to the right.
My example attached is not an array and it does not render the media type.
<img width="959" alt="screen shot 2016-12-22 at 5 08 36 pm" src="https://cloud.githubusercontent.com/assets/6518685/21442074/970beb16-c869-11e6-8723-dca57fa95c94.png">

**Comment by hkosova** [comment] 2016-12-30 09:06
Looks like this is a duplicate of #1946.

**Comment by webron** [comment] 2017-06-10 03:59
This should be fixed in the new UI.

**Closed by webron** 2017-06-10 03:59 UTC
