### ISSUE TITLE
externalDocs property not rendered in swagger-ui?

### ISSUE THREAD

**Issue by mikeliucc** [swagger-api/swagger-ui#683] opened 2014-10-24 03:25 UTC
Hi,

I have learned of a schema object - externalDoc - here (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#externalDocumentationObject). However, the generated HTML, either via swagger2-editor or swagger-ui, does not seem to give any consideration towards this object.

Am I missing something? This schema object being considered for any specific use?

I'd like to ask for this property to be rendered in swagger-ui so that we can provide a more complete documentation to our service implementation team and our clients.

Thanks, Mike

**Comment by tshah010** [comment] 2015-02-03 21:52
Is this implemented now and available in new release? Thanks.

**Comment by webron** [comment] 2015-02-03 21:56
@tshah010 - not yet. This issue is marked for M2 which is the next release cycle.

**Comment by tshah010** [comment] 2015-02-05 22:59
Thanks @webron , when is the next release cycle?

**Comment by webron** [comment] 2015-02-05 23:09
About 3-4 weeks. Keep in mind this feature is slated to M2 but could be delayed. Obviously, PRs are always appreciated :)

**Comment by mohsen1** [comment] 2015-03-10 04:50
Related : #1000

**Comment by mohsen1** [comment] 2015-03-18 21:08
Duplicate of https://github.com/swagger-api/swagger-ui/issues/608

**Closed by mohsen1** 2015-03-18 21:08 UTC
Labels: Feature

**Comment by stevendearborn** [comment] 2015-04-24 18:30
There is definitely a lot of interest in ExternalDocs at the API/file, resource and method levels. I would like to see the JSON Schema place these in the three levels or more if anyone can think of a case for them.  I am looking to refer to static HTML pages for example API conventions, but a more general facility to link to other non-swagger documentation that become a part of swagger-ui once its generated makes sense.

**Comment by webron** [comment] 2015-04-26 10:23
@stevendearborn - there's a "bug" in the current spec documentation (and as a result in the JSON Schema of the spec) that doesn't expose the `externalDocs` in all the locations it should. I hope to fix it soon and have it affect the tooling as well.

**Comment by tshah010** [comment] 2016-03-16 21:03
externalDocs is rendered only if it is placed in root document object. But it doesn't work in Operation object and Schema object. When would that feature be implemented?

**Comment by dklotz** [comment] 2016-07-27 12:02
@tshah010 I think that's probably what #1614 is about?

**Comment by obfischer** [comment] 2017-02-02 17:06
@dklotz & @tshah010: I also think that swagger-api/swagger-ui#1641 addresses the same issue.

**Comment by melghazali** [comment] 2020-01-06 08:29
is there a C# example on how to add externalDocs?
