### ISSUE TITLE
date/date-time model properties rendered as string in model/schema (v2.1.0-M2)

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-ui#1183] opened 2015-04-18 10:37 UTC
hi,

after updating 2.1.8-M1 to 2.1.0-M2, date/date-time properties are rendered as type "string" in the model schema view with a default value of "string".

previously, with 2.1.8-M1, they were rendered as type "date-time" with a default value of the current timestamp in iso format.

my model property definition did not change (`{"type":"string","format":"date-time"}`).

was the behavior changed intentionally? presetting the value with a valid iso date(-time) string was the better approach imho. or am i maybe missing something else that has changed and i need to adapt to?

thanks, zyro

**Comment by ponelat** [comment] 2015-04-23 09:46
hi @zyro23,

It seems there was a bug, but it's working in with our latest source, so you should see the expected behavior in the next release or so. 

Note: latest source being ...
https://github.com/swagger-api/swagger-ui/commit/6f1b9b639477e090f0661df27e80456fb9376ce3
Built with swagger-client at....
https://github.com/swagger-api/swagger-js/commit/83023ca311d516f8556e57e581dddcbfc6342252

**Comment by webron** [comment] 2015-05-04 17:01
@zyro23 - can you retest as mentioned by @ponelat?

**Comment by zyro23** [comment] 2015-05-04 20:21
hmm... no luck :(

this is supposed to be fixed/working with https://github.com/swagger-api/swagger-ui/commit/6f1b9b639477e090f0661df27e80456fb9376ce3 right? i used the dist/swagger-ui.js from that revision (which is still the current develop_2.0 HEAD as of writing this..).

looking at the code, maybe the issue is that https://github.com/swagger-api/swagger-js/blob/master/lib/types/model.js#L347 checks for `type === 'date-time'` but as stated, my spec json contains `{"type":"string","format":"date-time"}`?

thanks, zyro

**Comment by ponelat** [comment] 2015-05-05 08:33
@zyro23, perhaps I wasn't clear enough...
The fix is in swagger-js, that's why I mentioned both SHAs.
Have a look at building from the bleeding edge....
https://github.com/swagger-api/swagger-ui/pull/1220#issuecomment-97736915

PS: I checked again, and the fix is there :)

**Comment by zyro23** [comment] 2015-05-05 19:58
fix confirmed working.

just made first contact with node/npm/gulp ;) went smooth with the provided pr comment. thx guys!

**Comment by webron** [comment] 2015-05-06 10:59
Thanks for the update, closing for now. Please reopen if needed.

**Closed by webron** 2015-05-06 10:59 UTC
Labels: Waiting for feedback

**Comment by grouchal** [comment] 2016-04-19 11:44
This seems to be happening in the current version  - is this tested for the in the current tests?

**Comment by ZandorZ** [comment] 2016-06-28 12:57
+1
