### ISSUE TITLE
Swagger UI opens link in new page

### ISSUE THREAD

**Issue by dvarrazzo** [swagger-api/swagger-ui#7326] opened 2021-05-28 17:01 UTC
The problem comes with the pages generated by FastAPI: advices about how to customise it are welcome.

 - Swagger-UI version: probably 3.49.0 (whatever currently served by https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js)

All links, including intra-page ones, are rendered with `target="_blank"`. This is a major usability issue and make documentation very hard to use.

**Comment by hkosova** [comment] 2021-05-28 20:10
Duplicate of #3473.

**Closed by hkosova** 2021-05-28 20:10 UTC

**Comment by dvarrazzo** [comment] 2021-05-28 20:39
Uhm... I am somewhat confident that a few months ago this wasn't happening. Any chance of that or I'm wrong?

**Comment by hkosova** [comment] 2021-05-28 21:06
It's not a recent change, it's been a few years.

Here are some related developer comments from https://github.com/swagger-api/swagger-ui/pull/3498#issuecomment-319253129:

> As for external links - we used to open them in the same tab, but due to (very) popular demand, implemented the opening in a new tab. It makes sense - if you navigate away from the documentation every time, it can break the flow.

> [...] #3473 is talking about something a bit different - _local_ links should not open in new tabs - that is, other anchors in the same instance of swagger-ui, should just jump to those anchors. However, I'm not sure our markdown parser generates those anchors in the first place, making this a harder problem to solve.

So external links having `target="_blank"` is by design, and the issue with internal anchor links is tracked in #3473.
