### ISSUE TITLE
Render primitive types in "Response Class"

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#1186] opened 2015-04-20 12:39 UTC
Swagger-UI currently assumes all responseType's are objects, instead of delegating to swagger-js.
As a result, when the response type is a primitive (a rare occasion?) swagger-ui doesn't render it... :frowning:  See screenshot...
Top is primitive and bottom is a schema model

![screenshot from 2015-04-20 14 31 40](https://cloud.githubusercontent.com/assets/8438485/7230092/f8b877e4-e76a-11e4-8af8-cb20a101992d.png)

**Comment by raaga123** [comment] 2015-09-18 21:01
Is there any word on a fix for this? All our methods return HttpResponseMessage (which also defaults to Object) in which various types may be enclosed, including primitives. The new "Status 20x" addition to the "Response Class" header makes the item more prominent, so the problem is hard to miss:

![image](https://cloud.githubusercontent.com/assets/7062600/9970966/500d7db2-5e1e-11e5-8b7b-0754178cc157.png)

**Comment by Catscratch** [comment] 2015-12-09 15:23
Same issue here. Vote for bugfix. :-)

**Comment by lmprice** [comment] 2016-01-29 16:46
It looks like this didn't make it into milestone v2.1.3. I'd really like to see this in the next milestone.

**Comment by bodnia** [comment] 2016-02-03 17:44
@raaga123 could you please provide an example schema to reproduce https://github.com/swagger-api/swagger-ui/issues/1186#issuecomment-141568105?

**Closed** 2016-02-22 17:46 UTC
Labels: Bug, P1
