### ISSUE TITLE
allOf is not supported

### ISSUE THREAD

**Issue by themihai** [swagger-api/swagger-ui#1017] opened 2015-03-10 00:43 UTC
allOf attribute is not supported by the UI.
![screenshot 2015-03-10 00 42 09](https://cloud.githubusercontent.com/assets/1800192/6567382/72e7e31a-c6be-11e4-8953-d7873d87282b.png)

 Example:
```

{
  "example.io/account/account.serviceAccountReq": {
    "allOf": [
      {
        "required": [
          "serviceAccount"
        ],
        "properties": {
          "serviceAccount": {
            "type": "string",
            "description": "\n The name of the service account"
          }
        }
      },
      {
        "$ref": "#/definitions/example.io/account.PolicyRaw"
      }
    ]
  },
  "example.io/account.PolicyRaw": {
    "properties": {
      "authCIDR": {
        "type": "string",
        "description": "\n Space separated"
      },
      "scopes": {
        "type": "string",
        "description": "\n Space separated scopes"
      }
    }
  }
}```

**Comment by mohsen1** [comment] 2015-03-10 00:57
Duplicate of #723

**Closed by mohsen1** 2015-03-10 00:57 UTC
