### ISSUE TITLE
failure conditions not resolving definied models

### ISSUE THREAD

**Issue by paul42** [swagger-api/swagger-ui#3115] opened 2017-05-21 21:33 UTC
- swagger-ui version: 753134ec49e4d6082adce2fac1228e2b12dc5e0c
- a swagger file reproducing the issue: https://gist.github.com/paul42/28269dd8d7cc5317be0e11bd59a18a33

Post with screen shots: http://imgur.com/a/26pKB

I have a model for errors, but swagger-ui doesn't appear to show it when a 404 is returned. I get a 404 in the chrome console when clicking the try it out button & execute. successful 200's return the correct response.

I've tried setting produces/consumes to application/json

Thanks for your consideration!

**Comment by xquery-guy** [comment] 2017-05-22 22:30
I have noticed this too. Going back to v3.0.7 I know that it would show the response xml or json but in this v3.0.11, the response on the non 200 response isn't getting displayed. Is there any fix for this?

**Comment by webron** [comment] 2017-05-23 22:56
This is a duplicate of #3041.

**Closed by webron** 2017-05-23 22:56 UTC
