### ISSUE TITLE
Swagger UI does not support encoding and headers for multipart bodies

### ISSUE THREAD

**Issue by aosavitski** [swagger-api/swagger-ui#5638] opened 2019-09-30 08:53 UTC
According to [specification](https://swagger.io/docs/specification/describing-request-body/multipart-requests/) it is possible to set content-type and custom headers to each part of multipart request. But currently swaggerUI ignore "encoding" and "headers" for multipart bodies.

Having this in swagger.yaml:
```
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                json-part:
                  type: object
                  properties:
                    some-items:
                      type: array
                      items:
                        type: object
                        properties:
                          someId:
                            type: string
                          anotherId:
                            type: string
            encoding:
              json-part:
                contentType: application/json
```

Expected result in request:
```
------WebKitFormBoundaryArshJH8u3O9BShd6
Content-Disposition: form-data; name="json-part"
Content-type: application/json

{
  "some-items": [
    {
      "someId": "string",
      "anotherId": "string"
    }
  ]
}
------WebKitFormBoundaryArshJH8u3O9BShd6--
```
Actual result:
```
------WebKitFormBoundaryArshJH8u3O9BShd6
Content-Disposition: form-data; name="json-part"

{
  "some-items": [
    {
      "someId": "string",
      "anotherId": "string"
    }
  ]
}
------WebKitFormBoundaryArshJH8u3O9BShd6--
```

**Comment by hkosova** [comment] 2019-09-30 08:59
Duplicate of #5356.

**Closed by hkosova** 2019-09-30 08:59 UTC
