### ISSUE TITLE
Swagger-ui json incorrect for embedded objects

### ISSUE THREAD

**Issue by ssoffline** [swagger-api/swagger-ui#3257] opened 2017-06-19 15:01 UTC
swagger-ui version - 3.0.10
Spec 2.0

In case of embedded objects, the Model is correct though the schema json used for firing calls does not match

Model

`DummyRequest{
requestId:	string 
minLength: 0
maxLength: 30
entity:	Entity{
entityName:	EntityName{firstName, lastName}
citizenshipCountry:	string 
phoneNumbers:	[type]

}`

Example value

`{
  "requestId": "string",
  "entity": {
    "entityName": {}
  },
}
`

Note that EntityName inside Entity is also an object, example value crashes in such a config and everything after that fails.

**Comment by webron** [comment] 2017-06-19 19:18
The issue is really unclear. Please provide a spec that reproduces the issue, describe what you see and what you *expect* to see in detail, so we can proceed.

**Comment by ssoffline** [comment] 2017-06-19 20:20
on swagger UI we have two parts in request when we try out a service

One is Example Value
`{ "requestId": "string", "entity": { "entityName": {} }, }`

other part is model where we see a browsable version of the same like

`DummyRequest{
requestId:	string
entity:	Entity{
entityName:	EntityName{firstName, lastName}
citizenshipCountry:	
phoneNumbers:	
}`

So in such case when we have multiple level of objects embedded

`DummyRequest->Entity->EntityName (firstName, LastName)`

It breaks at level three of objects

Actual result 

`{ "requestId": "string", "entity": { "entityName": {} }, }`

Expected Result

`{ "requestId": "string", "entity": { "entityName": {"firstname" : "string", "lastName" : "string"} }, }`

We are using interface based objects via org.immutables, can this be an issue?

petstore has examples till level 2

```
{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

```

**Comment by webron** [comment] 2017-06-19 20:53
It's really hard to tell. Can you share your API definition file so we can look into it?

**Comment by ssoffline** [comment] 2017-06-19 21:09
Here is the sample

`public class Request{
    public Entity entity;
}`

```
@Value.Immutable
@Gson.TypeAdapters
@JsonSerialize(as = ImmutableEntity.class)
@JsonDeserialize(as = ImmutableEntity.class)
public interface Entity{
    EntityName entityName();

    String citizenshipCountry();

    List<PhoneNumber> phoneNumbers();

}

```
```
@Value.Immutable
@Gson.TypeAdapters
@JsonSerialize(as = ImmutableEntityName .class)
@JsonDeserialize(as = ImmutableEntityName.class)
public interface EntityName {
    String firstName();

    String lastName();

}

```

```
@Value.Immutable
@Gson.TypeAdapters
@JsonSerialize(as = ImmutablePhoneNumber.class)
@JsonDeserialize(as = ImmutablePhoneNumber.class)
public interface PhoneNumber {
    PhoneNumberType type();

    String number();
}
```

and so on.

the json on UI is below, far from correct

`{ "requestId": "string", "entity": { "entityName": {} }, }
`

**Comment by webron** [comment] 2017-06-19 21:16
That's your code. I need the file that's being loaded into the UI.

**Comment by ssoffline** [comment] 2017-06-20 14:22
Can't share complete one, this is a snippet I am referring to.

```
{
  "swagger": "2.0",
  "tags": [
    {
      "name": "test tag"
    }
  ],
  "paths": {
    "/checkEntity": {
      "post": {
        "tags": [
          "test tag"
        ],
        "description": "",
        "operationId": "handle_1",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": false,
            "schema": {
              "$ref": "#/definitions/EntityRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/CustomResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "EntityRequest": {
      "type": "object",
      "properties": {
        "person": {
          "$ref": "#/definitions/Entity"
        },
      }
    },
    "CustomResponse": {
      "type": "object",
      "properties": {
        "responseResultCode": {
          "type": "string",
          "enum": [
            "SUCCESS",
            "FAILURE"
          ]
        }
      }
    },
    "Entity": {
      "type": "object",
      "properties": {
        "entityName": {
          "readOnly": true,
          "$ref": "#/definitions/EntityName"
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date",
          "readOnly": true
        },
        "citizenshipCountry": {
          "type": "string",
          "readOnly": true
        },
        "phoneNumbers": {
          "type": "array",
          "readOnly": true,
          "items": {
            "$ref": "#/definitions/PhoneNumber"
          }
        },
      }
    },
    "EntityName": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string",
          "readOnly": true
        },
        "lastName": {
          "type": "string",
          "readOnly": true
        },
      }
    },
    "PhoneNumber": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "readOnly": true,
          "enum": [
            "MOBILE"
          ]
        },
        "number": {
          "type": "string",
          "readOnly": true
        }
      }
    }
  }
}
```

**Comment by webron** [comment] 2017-06-20 17:46
Thanks for sharing that, I understand the issue better now. The generated example doesn't go deep enough, where it should be. This is a bug with the current implementation.

**Comment by ssoffline** [comment] 2017-06-21 01:53
By when should we expect a fix?

**Comment by webron** [comment] 2017-06-21 02:57
It's not going to be a high priority at the moment, due to time constraints. We'd be happy to review PRs that fix it though.

**Comment by ssoffline** [comment] 2017-06-21 02:59
Thanks, appreciate the help, I am more of a back-end developer, will wait for the fix,

**Comment by ssoffline** [comment] 2017-07-06 20:08
any luck here?

**Comment by ssoffline** [comment] 2017-07-27 20:32
Should not this be P1. How can swagger ui be used on industrial level with this issue?

**Comment by webron** [comment] 2017-07-28 02:50
I'm not really seeing others commenting on the issue expressing it's a blocker for them.

**Comment by ssoffline** [comment] 2017-08-02 18:21
That is surprising we have downgraded to older version 2.8.8, that solves this issue.

**Comment by webron** [comment] 2017-08-02 21:31
Happy to hear, though there's no version 2.8.8.

**Comment by ssoffline** [comment] 2017-08-03 13:09
2.2.8

**Comment by heldersepu** [comment] 2017-12-09 18:27
@ssoffline 
I was doing some research and it seem that removing the readOnly tags makes a big impact...

Modified:
http://nhc-noaa.azurewebsites.net/swagger/ui/index?url=http://nhc-noaa.azurewebsites.net/3257_v2.json&filter=test#/test tag

Original:
http://nhc-noaa.azurewebsites.net/swagger/ui/index?url=http://nhc-noaa.azurewebsites.net/3257.json&filter=test#/test tag

**Comment by heldersepu** [comment] 2017-12-09 18:59
From the Specs:
https://swagger.io/specification/


readOnly | boolean | Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.
-- | -- | --

**...but SHOULD NOT be sent as part of the request...**
I think that closes this issue

**Comment by webron** [comment] 2018-07-05 17:00
Thanks @heldersepu, you are correct. Closing.

**Closed by webron** 2018-07-05 17:00 UTC
Labels: P2, type: bug, version: 3.x
