### ISSUE TITLE
Docker run command just hangs

### ISSUE THREAD

**Issue by toymachiner62** [swagger-api/swagger-ui#2386] opened 2016-09-06 16:40 UTC
I'm trying to run swagger-ui via docker.

I followed the commands you have listed and it builds fine, but when I run it and hit http://localhost in my browser it's just page not found.

``` sh
git:(dab8c4a) $ docker build -t swagger-ui-builder --no-cache .  
Sending build context to Docker daemon  5.11 MB
Step 0 : FROM alpine:3.3
 ---> 0dcd4549ae28
Step 1 : MAINTAINER Roman Tarnavski
 ---> Running in 749aeab436a4
 ---> 90621a0f86b0
Removing intermediate container 749aeab436a4
Step 2 : RUN apk add --update nginx
 ---> Running in 72ee8e4e4e35
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/3) Installing nginx-initscripts (1.8.0-r0)
Executing nginx-initscripts-1.8.0-r0.pre-install
(2/3) Installing pcre (8.38-r1)
(3/3) Installing nginx (1.8.1-r1)
Executing busybox-1.24.2-r0.trigger
OK: 6 MiB in 14 packages
 ---> fc2573f1ff0f
Removing intermediate container 72ee8e4e4e35
Step 3 : COPY nginx.conf /etc/nginx/
 ---> e1441c15df08
Removing intermediate container 5ce9db700de3
Step 4 : ADD ./dist/ /usr/share/nginx/html
 ---> 6b49792258c5
Removing intermediate container 0b374cf6e598
Step 5 : EXPOSE 8080
 ---> Running in 825c8577462b
 ---> 019c01d88cf5
Removing intermediate container 825c8577462b
Step 6 : CMD nginx -g 'daemon off;'
 ---> Running in 7f13390d7bab
 ---> d9228fa2752d
Removing intermediate container 7f13390d7bab
Successfully built d9228fa2752d
git:(dab8c4a) $ docker run -p 80:8080 swagger-ui-builder        
```

Then I run this command and it just sits (Which i'm assuming is expected (not much docker experience here))

``` sh
git:(dab8c4a) $ docker run -p 80:8080 swagger-ui-builder   
```

I have tag v2.2.3 of swagger-ui checked out.

**Comment by heinrichj** [comment] 2016-09-08 17:53
Hi toymachiner62,

I wouldn't expect to open up the swagger instance you just started in a docker container to run under localhost. When we run a local docker container we need to connect against the docker-machine.
I would suggest you check the ip of your docker-machine and try to make your call against it's ip.
`$ docker-machine ls`

Hope this helps.

**Comment by stevendearborn** [comment] 2016-09-20 17:52
It would be nice if both the swagger-editor and swagger-ui Docker images would run consistently. I have the same problem with swagger-ui, but swagger-editor works fine.  I am using OS X with the latest Docker distribution.

**Comment by leckylao** [comment] 2017-04-16 11:28
Damn, it’s been half year I still have the same issue. Seems issue with nginx as open localhost there’s no server. But I am not sure how to check the nginx log in the container, the docker logs shows empty.

**Comment by leckylao** [comment] 2017-04-19 04:40
As @ghost mentioned that it does need to access UI through the docker-machine IP address with port. I guess to close the issue is update the instruction that instead of going localhost, it should use docker-machine-ip

> Build from Docker

Please run the following to build the Swagger UI from Docker.

docker build -t swagger-ui-builder .
docker run -p 127.0.0.1:8080:8080 swagger-ui-builder
This will start the Swagger UI on your local port 8080, specifically at http://localhost:8080

**Comment by webron** [comment] 2017-06-10 03:40
This should no longer be an issue with the new UI.

**Closed by webron** 2017-06-10 03:40 UTC
