### ISSUE TITLE
3.25.1 - 3.25.3 swagger-ui-react docExpansion=list throws a TypeError

### ISSUE THREAD

**Issue by edward-s** [swagger-api/swagger-ui#5982] opened 2020-05-01 01:17 UTC
Using `"swagger-ui-react": "3.25.1"`

If I specify `docExpansion=list`, 
```
 <SwaggerUI docExpansion="list" url={specUrl}  />
```
It will throw the following error

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at value (swagger-ui.js:8)
    at swagger-ui.js:1
```

Without `docExpansion`, it works
```
 <SwaggerUI url={specUrl}  />
```

With `"swagger-ui-react": "3.25.0"`, `docExpansion` works
```
 <SwaggerUI docExpansion="list" url={specUrl}  />
```

**Comment by eddiemora74** [comment] 2020-05-01 22:03
downgrading worked for me as well.

**Comment by hantaowang** [comment] 2020-05-01 23:10
I'm also having this issue, but downgrading does not work for me. I'm on the stable version of nodejs and npm. This just starting happening very recently too. My error is a little different:

```
TypeError: undefined is not an object (evaluating 's.indexOf')
    value — 1.chunk.js:232387
    configureFinalMapState — 1.chunk.js:217466
    updateStatePropsIfNeeded — 1.chunk.js:217515
    render — 1.chunk.js:217659
    ...
```

and also

```
The above error occurred in the <Connect(r)> component:
    in Connect(r) (created by t)
    in div (created by Lt)
    in Lt (created by t)
    in t (created by t)
    in div (created by t)
    ...
```

**Comment by enroly-mike** [comment] 2020-05-05 10:48
+1

**Comment by Kazanz** [comment] 2020-05-07 19:44
We have same issue as well.

**Comment by bwright1558** [comment] 2020-05-11 16:45
This is still an issue with swagger-ui-react 3.25.2.
In fact, swagger-ui is totally unusable. Regardless of the value of `docExpansion`, the component crashes hard when I attempt to expand anything. If I set it to `full`, it crashes before it even loads. If I don't set `docExpansion` at all, the component still crashes when I attempt to expand anything.

Solution for now is to revert to 3.25.0.

**Comment by noosxe** [comment] 2020-05-14 01:16
+1
using 3.25.0 works perfectly!

**Comment by edward-s** [comment] 2020-05-19 07:11
still broken in `3.25.3`.

I know this is open-source effort, but a breaking bug that makes the library unusable in react unfixed for close to 3 weeks?

**Comment by webron** [comment] 2020-05-19 14:50
@edward-s yes, you'd expect that within 3 weeks someone would contribute and fix it...

**Comment by Doctor-DC** [comment] 2020-05-20 03:17
This is still an issue with swagger-ui-react 3.25.0;  last week 3.25.0  works perfactly, but now i have same  issue:  Cannot read property 'indexOf' of undefined

**Comment by Doctor-DC** [comment] 2020-05-20 04:02
> This is still an issue with swagger-ui-react 3.25.0; last week 3.25.0 works perfactly, but now i have same issue: Cannot read property 'indexOf' of undefined

![image](https://user-images.githubusercontent.com/40282923/82403534-a6f17980-9a91-11ea-8096-cc0dad4aa74c.png)
I have to add url, then it work!

**Comment by jameswrightrg** [comment] 2020-05-22 09:13
Still broken in `3.25.4`.

**Comment by webron** [comment] 2020-05-22 15:48
There's no need to keep repeating that the issue is not resolved with every release. When it's resolved, this ticket will be closed.

**Comment by bwright1558** [comment] 2020-05-22 17:12
Found the problem. The latest change to swagger-ui-react added support for the `supportedSubmitMethods` prop. But if you don't set this value, then it gets passed to swagger-ui as null, which obviously doesn't have an `indexOf` property. I'm working on a fix and will have a PR for this shortly.

**Comment by lordkada** [comment] 2020-05-28 07:25
In the meanwhile, I have just added the `supportedSubmitMethods` property (e.g. set to supportedSubmitMethods={["get", "put", "post", "delete"]}) and it works (version 3.25.4).

**Closed** 2020-06-03 19:40 UTC

**Comment by tim-lai** [comment] 2020-06-11 22:00
As of the [latest release](https://github.com/swagger-api/swagger-ui/releases/tag/v3.26.1), `docExpansion` is now working properly for me with `list`, `full`, `none`
