### ISSUE TITLE
POST formData not working

### ISSUE THREAD

**Issue by clickslide** [swagger-api/swagger-ui#838] opened 2015-01-20 21:06 UTC
I'm trying to send a simple string as a POST parameter in swagger 2.0. However, I cannot seem to get it to work.

````
    post:
      summary: POST simple parameter
      description: Test
      consumes:
        - application/x-www-form-urlencoded
      parameters:
         -  name: _method
            in: formData
            type: string
            required: true
            description: testing
````

When I view a log of the $_POST details in my PHP server, the array is empty. It should contain the "_method" parameter. 

Please note that this was found as a bug in the swagger-editor here: https://github.com/swagger-api/swagger-editor/issues/299

I have found the same problem in the swagger-ui. Perhaps I'm missing something?

**Comment by webron** [comment] 2015-01-20 21:14
Confirmed. Looks like a regression.

**Comment by harikt** [comment] 2015-01-23 07:05
Subscribing for I have also been testing the same.

**Comment by mattoshry** [comment] 2015-01-24 07:36
Ran into this as well and wondered if the problem is here:
https://github.com/swagger-api/swagger-ui/blob/master/lib/swagger-client.js#L852
Perhaps the loop on 858 should populate formParams if param.in === 'formData'?

      if (param.in === 'body') {
        body = args[param.name];
      } else if (param.in === 'formData') {
        formParams[param.name] = args[param.name];
      }

**Comment by webron** [comment] 2015-01-24 09:47
@mattoshry - doesn't seem like it, considering the section following it - https://github.com/swagger-api/swagger-ui/blob/master/lib/swagger-client.js#L864-L877.

**Comment by webron** [comment] 2015-01-24 09:54
Ah, now I see what you mean. Looking back, the method was split into two, so the formParams indeed doesn't get populated.

**Comment by retrospectacus** [comment] 2015-01-27 21:34
This patch f9af6110334681cf570b2c03127d46bb4b6f6984 fixed my issue. Now swagger-ui correctly sends formData parameters with POST request in "Try it out" function.

**Comment by fehguy** [comment] 2015-01-30 07:07
this was fixed in develop_2.0

**Closed by fehguy** 2015-01-30 07:07 UTC
Labels: Bug

**Comment by tsamples** [comment] 2016-06-15 21:06
Is this now in the current version Version 2.10.1, I still seem to be experiencing this issue as is stated.

**Comment by webron** [comment] 2016-06-16 02:05
@tsamples - you may be confusing this project with swagger-editor.

**Comment by tsamples** [comment] 2016-06-16 02:39
Thanks,  You are correct it is a documented issue on the swagger editor
project.

https://github.com/swagger-api/swagger-editor/issues/599
