### ISSUE TITLE
200 OK response doesnt show up properly

### ISSUE THREAD

**Issue by ndhar-1** [swagger-api/swagger-ui#1505] opened 2015-07-31 20:05 UTC
If you have ‘response’ attribute in @ApiOperation, it doesn’t show on Swagger UI in 'Response Class' section in the beginning of API definition. 
Only if you specify ‘response’ attribute in @ApiResponse for 200 OK, it will show up. In this case the 200 OK response message doesn’t show up on UI.

So you can either have a response message of 200 OK
![image](https://cloud.githubusercontent.com/assets/10857276/9016281/0c5e6ebc-378d-11e5-9210-c52af0b0db85.png)

or the response class for the API.

![image](https://cloud.githubusercontent.com/assets/10857276/9016315/6917ea20-378d-11e5-8556-cf79f61f6f7e.png)
I need to see both.

**Comment by webron** [comment] 2015-07-31 20:08
Which version of swagger-core do you use?

**Comment by ndhar-1** [comment] 2015-07-31 20:15
swagger-annotations
1.5.1-M2

**Comment by webron** [comment] 2015-07-31 20:20
Can you share your swagger.json for both cases?

**Comment by ndhar-1** [comment] 2015-07-31 20:45
I am sorry, cannot share the entire JSON. But here are snippets:

Case 1:
@ApiOperation(value = "Update by id", httpMethod = "PUT", response = HelloSource.class)
 @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK")

 "responses" : {
          "200" : {
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          }

Case 2:  
@ApiResponse(code = 200, message = "OK", response = HelloSource.class)

"responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/HelloSource"
            }
          },
          "401" : {
            "description" : "Unauthorized"
          },

In brief, having 'response' attribute in @ApiOperation shows no response model on the UI.

**Comment by webron** [comment] 2015-07-31 21:05
Wait, so you just don't see the response model in the table of responses but you do see it at the top response above the operation?

**Comment by ndhar-1** [comment] 2015-07-31 21:09
well, if I use 
@ApiResponse(code = 200, message = "OK", response = HelloSource.class)

I see the response at the top level, but then response message 200 goes away from table of responses completely. There is no mention of it there at all.

**Comment by webron** [comment] 2015-07-31 21:14
Right then, this is a duplicate of #1297.

**Closed by webron** 2015-07-31 21:14 UTC

**Comment by ndhar-1** [comment] 2015-07-31 21:20
That issue for not showing model for 'secondary responses', which is other responses except 200 OK. I think that is different issue.

Also is this issue taken care of ? - "Having 'response' attribute in @ApiOperation shows no response model on the UI."

I am wondering if its issue with UI or Swagger Core ?

**Comment by webron** [comment] 2015-07-31 21:23
It's the same issue, doesn't matter if it's primary or secondary. Models are not displayed in the table as they have before.

It's not fixed it. There's a pending PR, not merged yet.

**Comment by raulra08** [comment] 2016-03-19 15:25
Hi, I am facing the same issue commented here, could you refer me to the solution? Is there something I should take into account when annotating my code with swagger-anotations?

**Comment by fehguy** [comment] 2016-03-19 15:46
Most likely this is in swagger-core, but to be sure, please post your swagger definition here.  As said before, we have test cases working--if it's not working for you, it needs investigation, and that's the only way to be sure.

**Comment by raulra08** [comment] 2016-03-21 15:33
I'll post an example of how it seems not to be working for me.

1. My Java code with annotations.
As you can see I am annotating 2 times the response model, first at the Operation level, secondly in the Responses.
With this combination, as you can see in the picture below, the response gets documented on the top of this method under "Response Class" and at the same time it doesn't get listed down in the "Response Messages".
- I have come to think this might be as is by design. You might be able to help to clarify if I am correct with this assumption.

Now, If I do not have the property _response_ set in _ApiResponse_ then the Model will not show up on the "Response Class" section (top of the method docs)

`@ApiOperation(nickname = "getAccount", value = "Get account",
      response = Account.class, httpMethod = "GET")
  @ApiResponses({
      @ApiResponse(code = 200, message = "Account", response = Account.class),
      @ApiResponse(code = 404, message = "Account with specified ID not found.")})`


2. Here's my swagger generated docs;
`"/accounts/{id}" : {
      "get" : {
        "tags" : [ "accounts" ],
        "summary" : "Get account",
        "description" : "",
        "operationId" : "getAccount",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "fields",
          "in" : "query",
          "required" : false,
          "type" : "string",
          "default" : "all"
        } ],
        "responses" : {
          "200" : {
            "description" : "Account",
            "schema" : {
              "$ref" : "#/definitions/Account"
            }
          },
          "404" : {
            "description" : "Account with specified ID not found."
          }
        }
      }
    }`

3. Here's an image to how my method looks like
<img width="968" alt="accountsapi" src="https://cloud.githubusercontent.com/assets/1486377/13923439/8853fe26-ef78-11e5-9559-f9d4c01ccd85.png">

Thanks a lot for your help.

**Comment by shobull** [comment] 2016-06-03 14:03
I'm seeing the same situation as @raulra08 's screenshot. Is it correct to see 200 response on top and the rest of responses in the "Response Messages" block?

**Comment by webron** [comment] 2016-06-03 14:59
@shobull - yes, that's the current design.

**Comment by raulra08** [comment] 2016-06-12 18:26
Right, Thank you @webron

**Comment by subhransu-das** [comment] 2020-03-02 06:58
Hi ,
@ApiResponse(code=200,message="fetch list of Service/Config Resources",response = testing.class,responseContainer = "List",
					examples=@Example(
					value = @ExampleProperty(mediaType = MediaType.APPLICATION_JSON_VALUE,
					value = "{testingId: 1234, testingName = Testing Name}"
							)
					)
			), 
			
			
but getting response example as 

[
    {
        "testingId": string,
        "testingName": string
    }
]

any suggestion
