### ISSUE TITLE
The example from json file cannot displayed correctly after upgarde Swagger-UI to 3.24.3

### ISSUE THREAD

**Issue by wangjiong04** [swagger-api/swagger-ui#5829] opened 2020-02-08 07:16 UTC
### Q&A (please complete the following information)
 - OS: windows
 - Browser: chrome
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 3.24.3
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
In our yaml file, we use a json file located the same level as the example:
RegisterConsumerAccountRequest:
        description: Consumer registration request payload.
        content:
            application/json:
                schema:
                   $ref: '#/components/schemas/RegisterConsumerAccountRequest'
                example:
                  $ref: 'create-customer-example.json'
```
Before upgraded, our Swagger-UI is 3.22.1, all the display are correct
<img src="https://user-images.githubusercontent.com/44149679/74081269-1e257380-4a88-11ea-8c85-be675204ab0a.jpg" width="800" />

After we upgraded to 3.24.3, the examples are disappeared but we didn't change any other thing
![i2](https://user-images.githubusercontent.com/44149679/74081271-27aedb80-4a88-11ea-8260-9dacb64b4a94.jpg)

**Comment by hkosova** [comment] 2020-02-09 19:12
The current behavior is actually correct because the `example` keyword does not support `$ref`. To reference an external example of request/response body you must use `examples.<name>.externalValue`:

```yaml
RegisterConsumerAccountRequest:
        description: Consumer registration request payload.
        content:
            application/json:
                schema:
                   $ref: '#/components/schemas/RegisterConsumerAccountRequest'
                examples:
                  Create customer example:
                    externalValue: 'create-customer-example.json'
```

However, `externalValue` examples are currently not supported in Swagger UI; this is tracked in #5433. As a workaround you can use inline examples instead of external examples.

**Comment by wangjiong04** [comment] 2020-02-10 00:51
Thank you! 
Will the examples.<name>.externalValue support the local file reference when the issue get fixed?

**Comment by hkosova** [comment] 2020-02-10 08:05
I think so.

**Comment by kirkoman** [comment] 2020-08-11 03:10
@wangjiong04 Does it work if you merge the example in as the schema-level "example" instead of using the media-type-level "example"?  I am using such a workaround, with the difference that I am referencing components, not files (so I'm not sure if it will work for you).  E.g.,
```yaml
RegisterConsumerAccountRequest:
        description: Consumer registration request payload.
        content:
            application/json:
                schema:
                     allOf:
                         - $ref: '#/components/schemas/RegisterConsumerAccountRequest'
                         - example:
                             $ref: 'create-customer-example.json'
```

**Comment by hkosova** [comment] 2020-08-11 06:48
@kirkoman
```yaml
- example:
    $ref: 'create-customer-example.json'
```
won't work because `example` does not support `$ref`.

This particular scenario - pointing to an external JSON data example - is defined using `examples.<name>.externalValue`, as shown in my [previous comment](https://github.com/swagger-api/swagger-ui/issues/5829#issuecomment-583881582).

**Comment by hkosova** [comment] 2020-08-11 06:50
Closing in favor of #5433.
Please follow #5433 for updates on `externalValue` support.

**Closed by hkosova** 2020-08-11 06:50 UTC
Labels: type: support

**Comment by kirkoman** [comment] 2020-08-28 05:10
@hkosova While I agree that `example` does not support `$ref` (nor should it according to the spec), `allOf` does support it.  But `allOf` is not supported in the media object, only in the schema object.  So my suggestion was to use the `schema.example` but to merge it with the referenced schema using `allOf`.  I know this works (at least for component references) because I'm using it extensively to accomplish nested example references.  My doubt was about whether it would work for referencing a json file (but I think it will).

It is possible this behavior is a bug, but the schema seems ambiguous.  Do you think I should open a separate issue about it?  OTOH since I'm actively using it, I don't really want it to be fixed. 😬 

I just confirmed again with this example (3.24.3), let me know if I am missing something:
```yaml
components:
  examples:
    SomeBasicType:
      value:
        is_it_some_text: Yes it is!
  schemas:
    SomeBasicType:
      type: object
      properties:
        is_it_some_text:
          type: string

/some/route:
  post:
    requestBody:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/SomeBasicType'
              - example:
                  $ref: '#/components/examples/SomeBasicType/value'
```
![example-references-working](https://user-images.githubusercontent.com/1413323/91523517-f0403900-e8ca-11ea-89f9-1a7be8b5fc0c.png)
