### ISSUE TITLE
Swagger-ui 3.17.1 deepLinking not working correctly

### ISSUE THREAD

**Issue by CaptainAgilek** [swagger-api/swagger-ui#4817] opened 2018-08-17 10:30 UTC
### Q&A (please complete the following information)
 - OS: [w10]
 - Browser: [chrome]
 - Version: [68.0.3440.106 ]
 - Method of installation: [maven]
 - Springfox Swagger-ui 2.9.2 uses **Swagger-UI version:  3.17.1**

In this version deepLinking doesn't work as expected.
It scrolls you to controllers which is alright, but it **doesn't scroll you to operation**.

This will scroll and open the controller.
http://localhost:8080/api/swagger-ui.html#/email-controller
But this will just load main page and that is all.
http://localhost:8080/api/swagger-ui.html#/email-controller/getFullEmailListUsingGET

I need it to work for operations also so I am using version 2.8.0 of Springfox Swagger-ui and there it works also for operations.
Springfox swagger-ui  2.8.0 uses **3.9.1 version of Swagger-ui** where it works correctly.

**Comment by shockey** [comment] 2018-08-17 22:39
Bug confirmed 😄

**Comment by CaptainAgilek** [comment] 2018-08-23 07:09
Yes it works.

**Comment by ErlendSB** [comment] 2018-08-24 07:32
I can confirm the same experience with 3.17.1 (via Swashbuckle 3.0). 
The scroll/expand to operation works as expected if I set docExpansion to 'list', but I'd like to have all operations collapsed when I first hit the page (docExpansion=none).

**Comment by CaptainAgilek** [comment] 2018-08-24 08:14
I tried setting docExpansion to 'list' and then the scroll/expand really worked as @ErlendSB said.

**Comment by shockey** [comment] 2018-08-25 02:55
@CaptainAgilek @ErlendSB, as much as we'd like to, we can't do much about Swashbuckle being on a non-current version of Swagger UI 😓 

I'm going to close this out for now - if either of you experience any issues in the latest version (which is always available at https://petstore.swagger.io/), bump this thread and I'll take another look.

Thanks!

**Comment by ErlendSB** [comment] 2018-08-25 09:41
The issue is still there in the latest version (of swagger-ui).
https://petstore.swagger.io/?docExpansion=none#/pet/addPet
You'd expect to have the addPet operation expanded when following this link, but in my case all are collapsed.
It seems like docExpansion=none is prioritized over deepLinking

**Comment by CaptainAgilek** [comment] 2018-08-27 09:26
Right, I didn't notice. So this bug remains even in the latest version...

**Comment by shockey** [comment] 2018-08-27 17:56
Confirmed - thanks @ErlendSB!

**Closed** 2018-08-28 05:58 UTC
Labels: P1, cat: deep linking, type: bug

**Comment by shockey** [comment] 2018-08-28 06:01
Ok, this is fixed in conjunction with `docExpansion: none` now 😄 

Thanks for following up, @ErlendSB!

**Comment by user20161119** [comment] 2019-02-26 09:32
not work for me either.
http://dev.wx.yqfoodec.com/swagger-ui.html#/%E5%95%86%E5%93%81/goodDetailUsingPOST

**Comment by shockey** [comment] 2019-02-26 22:20
@user20161119 you need to upgrade to a newer version of Swagger UI 🆙

**Comment by user20161119** [comment] 2019-02-27 01:33
> @user20161119 you need to upgrade to a newer version of Swagger UI 🆙

thanks,i use spring-fox based config in my spring mvc project,how to upgrade Swagger UI?
here is my maven dependency config
```
 <!-- swagger -->
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>2.9.2</version>
			</dependency> 
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.9.2</version>
			</dependency>
```

**Comment by shockey** [comment] 2019-02-27 02:34
I'm not sure - you'd have to ask that kind of question to the Springfox maintainers.

**Comment by CaptainAgilek** [comment] 2019-02-27 06:19
@user20161119 I was dealing with same problem and I have explained solution in my post. There is no newer version of springfox , so you can't use newer swagger version via springfox, but you can use springfox version 2.8.0 where is older swagger without this bug, in other words, it works correctly in this version.

**Comment by user20161119** [comment] 2019-02-27 08:33
@CaptainAgilek thanks,but i tried 2.8.0,not work neither. and i cofigured deeplink
···
 @Bean
    UiConfiguration uiConfig() {
        return UiConfigurationBuilder.builder().deepLinking(true).docExpansion(DocExpansion.NONE).build();
    }
```

**Comment by brian-hay** [comment] 2019-03-14 08:09
Not working for me either. Latest Swagger UI 3.21.0

**Comment by shockey** [comment] 2019-04-10 00:04
I'm going to lock this thread now - if anyone is still having problems I encourage you to open a new issue and follow our provided templates!
