### ISSUE TITLE
swagger-ui does not render when body type is boolean

### ISSUE THREAD

**Issue by javierestevez** [swagger-api/swagger-ui#2041] opened 2016-03-18 12:55 UTC
Hello,

I have an issue with one of my APIs that I am documenting with swagger. The API has a method annotated as an HTTP PUT and with a boolean parameter as the body request. When I try to load it into swagger-ui, the UI displays the message:

Finished Loading Resource Information. Rendering Swagger UI...

but no endpoint is loaded. The JS console displays the following error:

`index.js:24Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
(anonymous function) @ index.js:24
Handlebars.templates.param_list.Handlebars.template.main @ client.js:477
e @ handlebars-2.0.0.js:27
SwaggerUi.Views.ParameterView.Backbone.View.extend.render @ index.js:24
SwaggerUi.Views.OperationView.Backbone.View.extend.addParameter @ index.js:24
SwaggerUi.Views.OperationView.Backbone.View.extend.render @ index.js:24
SwaggerUi.Views.ResourceView.Backbone.View.extend.addOperation @ index.js:24
SwaggerUi.Views.ResourceView.Backbone.View.extend.render @ index.js:24
SwaggerUi.Views.MainView.Backbone.View.extend.addResource @ index.js:24
SwaggerUi.Views.MainView.Backbone.View.extend.render @ index.js:24
window.SwaggerUi.Backbone.Router.extend.render @ index.js:24
options.success @ index.js:24
SwaggerClient.buildFromSpec @ resolver.js:568
Resolver.finish @ spec-converter.js:179
Resolver.resolve @ spec-converter.js:88
obj.on.response @ resolver.js:325
responseInterceptor @ schema-markup.js:59
obj.on.response @ schema-markup.js:63
(anonymous function) @ schema-markup.js:285
Request.callback @ index.js:24
(anonymous function) @ index.js:24
Emitter.emit @ index.js:24xhr.onreadystatechange @ index.js:24`

You may find a simplified version of the swagger.json file attached. I did my best trying to see if the file complied with the spec, which I think it does.

[swagger.zip](https://github.com/swagger-api/swagger-ui/files/179638/swagger.zip)

I am using swagger-ui version 2.1.4.

**Comment by webron** [comment] 2016-03-18 17:06
Duplicate of #2004.

**Closed by webron** 2016-03-18 17:06 UTC

**Comment by xiaolongyuan** [comment] 2016-04-01 01:26
+1
