### ISSUE TITLE
How to default the opblock-tag-section to collapsed?

### ISSUE THREAD

**Issue by liuya05** [swagger-api/swagger-ui#2994] opened 2017-04-27 17:36 UTC
I am trying to migrate from version 2.1.5 to version 3.0.7.

With the old version, we set docExpansion: "none".  It seems this parameter is no longer supported in the new version.  When we open the page, it seems default to "list".  What can I do to make it displays the same as before?

I was able to manually make changes in swagger-ui-bundle.js file so that it defaults to collapsed.  But I would rather find a more elegant way to handle this issue.  Thanks.

**Comment by webron** [comment] 2017-04-28 21:44
It's just not implemented yet.

**Comment by 1Map** [comment] 2017-05-09 12:05
Also part of collapsing Models section. See: https://github.com/swagger-api/swagger-ui/issues/2834

**Comment by 1Map** [comment] 2017-05-09 12:30
<h4 class="opblock-tag"><span>auth</span><small>1map API - Authorization</small><button class="expand-operation" title="Expand operation"><svg class="arrow" width="20" height="20"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#large-arrow"></use></svg></button></h4>

**Comment by webron** [comment] 2017-05-30 22:56
Duplicate of #2799.

**Closed by webron** 2017-05-30 22:56 UTC
Labels: 3.x, Feature, P2
