### ISSUE TITLE
Authorization header not added due to scheme not being all lower-case

### ISSUE THREAD

**Issue by AroglDarthu** [swagger-api/swagger-ui#5935] opened 2020-03-26 16:36 UTC
We are using `Swashbuckle.AspNetCore` (v5.2.0).

Passing the scheme as it has been defined by http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml, has the effect that the authorization header is not added to the request. So, setting the scheme to *Bearer* does not work, whereas *bearer* does.

Please note: the UI for setting the bearer token is correctly displayed in both cases.

Upon making request, the curl command shows that the authorization header is not added for *Bearer* but it is when using *bearer*. Same goes when using *Basic* versus *basic*, etc.

See also https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1598

**Comment by AroglDarthu** [comment] 2020-03-26 16:44
Perhaps related to #5715

**Comment by hkosova** [comment] 2020-03-26 17:28
Can you post your OpenAPI definition that would demonstrate the issue?

**Comment by hkosova** [comment] 2020-04-10 16:18
Closing due to lack of requested information. If you could provide a full OpenAPI definition or a minimal example that reproduces the issue, we can reopen this.

**Closed by hkosova** 2020-04-10 16:18 UTC
