### ISSUE TITLE
Parameter content type other than application/json not displayed

### ISSUE THREAD

**Issue by jonnyry** [swagger-api/swagger-ui#4261] opened 2018-02-27 08:33 UTC
Swagger UI does not display a parameter content type other than application/json when the consumes element is set to something else (see YAML below).

This can be recreated by pasting the YAML in the newer Swagger online editor.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug 
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.11.0
| How did you install Swagger-UI? | Download from Git, used pre-build dist folder
| Which browser & version?    | Any
| Which OS? | Any

### Demonstration API definition

```yaml
swagger: '2.0'
info:
  title: Test
  version: '1.0'
host: 'server.com'
basePath: /fhir
schemes:
  - http
paths:
  /Patient/$getrecordsection:
    post:
      tags:
        - Get record section
      summary: Retrieve a care record section
      consumes:
        - application/json+fhir
        - application/xml+fhir
      produces:
        - application/json+fhir
        - application/xml+fhir
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/GetRecordSection'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
definitions:
  GetRecordSection:
    type: object
    properties:
      resourceType:
        type: string
        default: "Parameters"
      parameter:
        type: string
    example:
      resourceType: "Parameters"
      parameter: 
        - name: "patientIdentifier"
          valueIdentifier: 
            system: "http://fhir.provider.net/Id/patient-identifier"
            value: "9999999999"
        - name: "recordSection"
          valueCodeableConcept: 
            coding:
              - system: "http://fhir.provider.net/ValueSet/record-section"
                code: "ALL"
    xml:
      name: Parameters
```

### Expected Behavior
The parameter content type drop down should display the values listed in the consumes element.

### Current Behavior
The parameter content type drop down displays only application/json.

See https://stackoverflow.com/questions/48997911/swagger-ui-3-x-setting-custom-content-type-for-body-parameter

**Comment by hkosova** [comment] 2018-02-27 10:37
Looks like a duplicate of #4257.

**Comment by webron** [comment] 2018-02-27 16:56
Yup, closing as duplicate. Thanks for the report though.

**Closed by webron** 2018-02-27 16:56 UTC
