### ISSUE TITLE
Parameter of type "file" causing exception

### ISSUE THREAD

**Issue by atomgomba** [swagger-api/swagger-ui#662] opened 2014-10-16 14:21 UTC
Parameters of type `file` are causing an exception in the current swagger-ui (6b448c1fae) at line 537 in swagger-client.js. If parameter type is `file` then `getType()` function returns `undefined` and `innerType.toString()` will throw an exception. I had to add to the `if` statement in `getType()` this code `else if (type == "file") { return type; }` in order to get my API doc displayed.

Here is the API definition JSON:
http://pastebin.com/AC8cB8C1
Please note the `swagger` field is an integer because of an other issue with swagger-js (https://github.com/wordnik/swagger-js/issues/142).

**Comment by fehguy** [comment] 2015-01-06 05:18
Hi, I was missing a commit, my apologies.  I've pushed the file change here:

https://github.com/swagger-api/swagger-ui/commit/a5c1b637b5120a818e659bc448b02b6260d83d02

Just pull the source and run from the `dist` folder, no need to rebuild.

Can you please retry?  It's successfully submitting for me.

**Comment by micha-nerdlichter** [comment] 2015-01-06 14:41
Now the submit passes, but in the request header the Content-Type is set to application/json (shouldn't this change to multipart/form-data automatically?)

If I set the consumes parameter to ['multipart/form-data'] manually, the Content-Type is correct but the boundary is missing, which results in an invalid POST: http://prntscr.com/5p629g
The upload data is messed up and the file is just one blob in the $_POST-variable in php.

**Comment by webron** [comment] 2015-01-06 14:49
With regards to the content-type, you *have* to set it to 'multipart/form-data' when using "file" type. The spec is explicit about it.

If the boundary is missing, that's indeed a bug.

**Comment by fehguy** [comment] 2015-01-06 14:53
using the spec from @atomgomba I get both the content-type and boundary correctly set:

![image](https://cloud.githubusercontent.com/assets/249413/5630233/ab8159b0-9570-11e4-81ac-88b605888b44.png)

**Comment by micha-nerdlichter** [comment] 2015-01-06 15:10
@webron you're right, but I thought
````JS
      if (type && type.toLowerCase() === 'file') {
          if (!contentTypeModel.consumes) {
            contentTypeModel.consumes = 'multipart/form-data';
          }
        } 
````
would do that for me. But reading it a second time I realized it would only work if no "consumes" is set at all.

@fehguy regarding to http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2 the Content-Type should contain the boundary parameter:
````
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryK7wXVH1G13deSTiQ
````

When I upload a file to my API-endpoint using a REST-client, everything works fine and the parameter is set correctly.

**Comment by micha-nerdlichter** [comment] 2015-01-06 15:30
I think the problem is, as soon as you set the Content-Type header manually, the boundary is missing. According to http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax/5976031#5976031 the contentType option must be set to false to force jQuery to build the Content-Type header on it's own, including the correct boundary.

**Comment by fehguy** [comment] 2015-01-06 15:36
Thanks.  I'll look at this in a few

**Comment by fehguy** [comment] 2015-01-07 01:45
ok tested and pushed.  Please reopen if you see any other issues and thanks for the patience on this.

**Comment by micha-nerdlichter** [comment] 2015-01-07 10:37
Thanks for the fix. File upload works fine, but now normal POST with application/x-www-form-urlencoded is broken (e.g. users/sign_up/ doesn't pass any POST-parameters).

**Comment by webron** [comment] 2015-01-07 16:28
Confirmed.

**Comment by webron** [comment] 2015-01-07 19:01
To be exact, confirmed for 2.0 specs. 1.2 works fine.

**Comment by fehguy** [comment] 2015-01-31 22:00
this has been fixed in the develop_2.0 branch

**Closed by fehguy** 2015-01-31 22:00 UTC
Labels: Bug
