### ISSUE TITLE
Adding multiple plugins with wrapComponents on the same core component seems broken

### ISSUE THREAD

**Issue by DayS** [swagger-api/swagger-ui#7232] opened 2021-05-01 20:49 UTC
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 90.0.4430.93
 - Method of installation: npm
 - Swagger-UI version: [e.g. 3.47.1]
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition is not relevant for this issue bug here is a sample:
```yaml
openapi: "3.0.1"
paths:
  /my-endpoint:
    get:
      operationId: getMyAwesomeEndpoint
      responses:
        "200":
          description: "Successful operation"
```

Swagger-UI configuration options:
```js
import SwaggerUI from 'swagger-ui'
SwaggerUI({
  spec: spec,
  deepLinking: true,
  dom_id: '#swagger',
  plugins: [
    {
      wrapComponents: {
        info: (Original, { React, getComponents }) => (props) => {
          return React.createElement("div", null, [
            React.createElement("h3", {key: 1}, "Hello world! I am above the Info component"),
            React.createElement(Original, Object.assign({key: 2}, props)),
          ])
        }
      }
    },
    {
      wrapComponents: {
        info: (Original, { React, getConfig }) => (props) => {
          return React.createElement("div", null, [
            React.createElement(Original, Object.assign({key: 2}, props)),
            React.createElement("h4", {key: 1}, "Hello world! I am below the Info component") ,
          ])
        }
      }
    }
  ]
});
```

### Describe the bug you're encountering

When multiple plugins are configured with `wrapComponents` entry on the same core component (`info` for example), only the last one is applied.
I was expected all of them to be applied in a chain pattern. They should end up being embedded according to where the `Original` component is applied.
So, in this example I should see both my titles before and after the info content.

### Fix

I pinpointed the issue on [system.js](https://github.com/swagger-api/swagger-ui/blob/38c6e127bf/src/core/system.js#L325) where plugins are combined.
As `systemExtend()` is called with an empty object for `dest`, we can't [retrieve the existing components](https://github.com/swagger-api/swagger-ui/blob/38c6e127bf/src/core/system.js#L366).

I was able to fix this issue by replacing `.reduce(systemExtend, {})` with `.reduce(systemExtend, toolbox.getComponents())` on [system.js](https://github.com/swagger-api/swagger-ui/blob/38c6e127bf/src/core/system.js#L325)

WDYT ?

**Comment by mathis-m** [comment] 2021-05-01 21:01
@tim-lai as already reported for wrapSelectors in #7157 we should think of a general refactor of the system.js where the wrapping is done in appropriate way.

**Comment by DayS** [comment] 2021-05-01 21:35
I agree :)

In the meantime, can we expect a small fix on this point and the one in the related issue or is this out of scope for now ?

**Comment by tim-lai** [comment] 2021-05-18 22:14
@DayS I added some comments to your PR #7236. Pending some tweaks, this specific issue can get fixed. I do agree that it is safer to add a config option to change the current default behavior.

@mathis-m fyi, I did a quick experiment with both this issue and #7157. The PR associated with this ticket does not address the `wrapSelectors` referenced in #7157

**Comment by char0n** [comment] 2024-05-07 08:35
Hi everybody,

The expected behavior described in this issue has always been intended. It shouldn't matter if whether the plugins have been registered via `presets` or passed by the `plugin` option. Having said that, this is just a bug in the original behavior, and the expected  behavior (called chaining in this issue) should the default one. Wrapping actions and selectors already works like that.

In https://github.com/swagger-api/swagger-ui/pull/7236, the remediation was provided, but unfortunately  it also contains hidden bug, where the original components objects is being extended by the combined plugins because of this line:

```js
 const dest = pluginOptions.pluginLoadType === "chain" ? toolbox.getComponents() : {}
```

---

Action: we're gonna revert https://github.com/swagger-api/swagger-ui/commit/516e666f1c4c118fbf60456869a01f892eef8b0c  and replace it with non-configurable solution. We're going  to fix the mutation bug introduced by the line above.

**Comment by char0n** [comment] 2024-05-07 09:54
Addressed in https://github.com/swagger-api/swagger-ui/pull/9919

**Closed by char0n** 2024-05-07 09:54 UTC
Labels: type: enhancement, version: 5.x
