### ISSUE TITLE
File download via content-disposition header corrupts file

### ISSUE THREAD

**Issue by lmprice** [swagger-api/swagger-ui#1605] opened 2015-09-16 15:08 UTC
lnowak (https://github.com/swagger-api/swagger-ui/pull/1238) noted an issue where a file download triggered via the Content-Disposition header will result in a link to download the file, but the file will be corrupt. I am also seeing this issue in my environment. 

The response headers:
{
  "Cache-Control": "no-cache, no-store",
  "Content-Disposition": "attachment; filename=\"example.zip\"",
  "Transfer-Encoding": "chunked",
  "Content-Type": "application/octet-stream"
}

This is the download URL that it displays in the UI. If I download via this link, I get a corrupt file. If I use the link directly from the browser, I get a valid download.
blob:http%3A//localhost%3A8090/9222e8a1-8628-476f-9341-372d68729d58

**Comment by Thijs5** [comment] 2015-11-25 13:57
+1

**Comment by paul3291** [comment] 2015-12-06 22:17
+1

**Comment by ralfstuckert** [comment] 2015-12-07 14:43
+1

**Comment by gabs247** [comment] 2015-12-13 23:51
+1

**Comment by vivex** [comment] 2016-01-04 11:30
+1
If i try to download file via browser then it works, but with swagger download link, it gives me currupt file.

**Comment by mcnaggets** [comment] 2016-02-18 09:52
+1

**Comment by chandresh-gurbani** [comment] 2016-02-23 17:32
+1

**Comment by timbaer** [comment] 2016-02-29 10:05
+1

**Comment by kvnhck** [comment] 2016-03-18 10:11
+1

**Comment by julioarmandof** [comment] 2016-04-11 14:04
+1

**Comment by ivarref** [comment] 2016-04-26 09:49
+1

**Comment by ivarref** [comment] 2016-04-26 14:00
The problem is that there is (as far as I know) no support for XHR responseType='arraybuffer'. See e.g. https://github.com/swagger-api/swagger-js/issues/123 for information about arraybuffer.

The other (potential) problem is that the served file download content is actually being trimmed.

@vivex @lmprice I don't think this is possible to work around without changing the original swagger code.

**Comment by rumperto** [comment] 2016-06-13 13:17
+1

**Comment by dkreutzer** [comment] 2016-06-15 12:34
+1

**Comment by alex-konkov** [comment] 2016-07-18 07:49
+1

**Comment by arthurdm** [comment] 2016-07-18 14:23
+1

**Comment by IsmaGitHub** [comment] 2016-07-21 11:39
+1

**Comment by anadoba** [comment] 2016-08-12 11:15
+1

**Comment by fehguy** [comment] 2016-09-15 18:32
Please give https://github.com/swagger-api/swagger-ui/pull/2404 a shot and post back.  I'll merge after feedback

**Comment by fehguy** [comment] 2016-09-16 17:02
Fixed by https://github.com/swagger-api/swagger-ui/commit/656808b20cffcca4f6daff1741c4685d70be5757

**Comment by gkozyryatskyy** [comment] 2016-10-23 16:16
Is this already fixed? 
For me it still corrupts file and doubles its size.

**Comment by fehguy** [comment] 2016-10-23 19:05
Yes, that's why the issue was closed.  Please open a new issue if you think it's not fixed, and share some details.

**Comment by ivarref** [comment] 2016-10-25 18:44
Also corrupt file here.

**Comment by Afterlife88** [comment] 2016-10-27 14:58
Still same issue, double the size and corrupt the file

**Comment by fehguy** [comment] 2016-10-28 04:14
Hmm

**Comment by Jcomper** [comment] 2016-11-03 10:28
The same for me. Example in HEX, 
Response body:
`AE CE 1C E9 6F`
After download file, file contains:
`EF BF BD EF BF BD 1C EF BF BD 6F`

This piece of code:
` var binaryData = [];
          binaryData.push(content);
          href = window.URL.createObjectURL(new Blob(binaryData, {type: type}));`

works incorrectly and I can reproduce it in simple solution.

**Comment by rwg0** [comment] 2016-11-10 09:03
Data point:

Using 2.2.6 I get correct behaviour for a GET request that returns a binary attachment, but corruption for a POST request that returns the same binary attachment.

**Comment by Jcomper** [comment] 2016-11-10 09:46
I'm using 2.2.6 and have a problem with GET requests as well

**Comment by ibenschop** [comment] 2016-11-14 20:25
+1

**Comment by anhaupt75** [comment] 2016-11-17 08:58
+1

**Comment by fehguy** [comment] 2016-11-23 23:02
That's a lot of +1's!  Sorry this took so long, but it will be addressed by #2427

**Comment by fehguy** [comment] 2016-11-24 00:50
Fixed by https://github.com/swagger-api/swagger-ui/commit/49a1169878b50ccb4d237dedf22ac472b4c2b5d6

**Comment by Jcomper** [comment] 2016-11-28 15:51
For me, it doesn't seem to be fixed.

Code in https://github.com/swagger-api/swagger-ui/blob/v2.2.8/src/main/javascript/view/OperationView.js
lines 707-709 still brakes the attached files:

```
var binaryData = [];
binaryData.push(content);
href = window.URL.createObjectURL(new Blob(binaryData, {type: type}));
```

My response header:
```
{
  "date": "Mon, 28 Nov 2016 15:41:09 GMT",
  "server": "Microsoft-IIS/10.0",
  "x-aspnet-version": "4.0.30319",
  "x-powered-by": "ASP.NET",
  "content-type": "image/png",
  "status": "200",
  "cache-control": "private",
  "content-disposition": "attachment; filename=boty1px.png"
}
```
Even if I change code to:

```
var arrayBuffer = new ArrayBuffer(content.length);
var uint8Array = new Uint8Array(arrayBuffer);
for (var i = 0; i < content.length; i++) {
uint8Array[i] = content.charCodeAt(i);
}
href = window.URL.createObjectURL(new Blob([uint8Array], {type: type}));

```
file is still broken, usually the difference in one byte (checked on small files)

**Comment by fehguy** [comment] 2016-11-28 16:20
Please share your request headers. I'm guessing you are not asking for a binary file type?

**Comment by Ben305** [comment] 2016-11-28 22:17
Still having problems with 2.2.8:

<pre>
Connection:keep-alive
Content-Disposition:attachment; filename=File.zip
Content-Length:1116714
Content-Type:application/zip
Date:Mon, 28 Nov 2016 22:13:50 GMT
Server:nginx/1.6.2
X-Powered-By:Sails <sailsjs.org>
</pre>

The downloaded file has a size of 2 MB, while downloading the file with curl results in a (valid) file with a size for 1,2 MB

**Comment by fehguy** [comment] 2016-11-28 22:35
Looks like the check to see if the file is binary (which uses blob) doesn't include `zip`:

```js
SuperagentHttpClient.prototype. binaryRequest = function (accept) {
  if(!accept) {
    return false;
  }
  return (/^image/i).test(accept)
    || (/^application\/pdf/).test(accept)
    || (/^application\/octet-stream/).test(accept);
};
```

Can you please try with a raw PDF or image?  And open an issue in swagger-js about the `application/zip`?

**Comment by Ben305** [comment] 2016-11-28 22:42
I've fixed it by replacing `application/zip` with `application/octet-stream`

**Comment by joelittlejohn** [comment] 2016-11-28 23:01
@fehguy Do you think there might be a better way to detect a binary file? There's a wide variety of mime types that are binary (including user-defined types) so I don't think a list like this will work.

Maybe it should be possible to configure the types to treat as binary?

**Comment by fehguy** [comment] 2016-11-28 23:37
Yea, this technique isn't great.  I believe the issue is that when we use binary, we lose the ability to read some response headers via xhr.  Thus the binary is more "opt-in" than "opt-out".  If anyone has a better technique, I'm all for it.

**Comment by Jcomper** [comment] 2016-11-29 08:09
@fehguy 
If you are asking for accept parameter, then yes it is application/json:
```
:authority:api.sss.com
:method:GET
:path:/rest/v1/zmeigor4/projects/0/documents/35073755?alt=media
:scheme:https
accept:application/json
accept-encoding:gzip, deflate, sdch, br
accept-language:en-GB,en-US;q=0.8,en;q=0.6,ru;q=0.4,uk;q=0.2
authorization:Bearer 6drhAdDWblbablalbal
```
My endpoint can return json object or file of any time depending on input parameter.

**Comment by pratapbhaskar** [comment] 2017-01-06 09:05
+1

**Comment by joshhundsrucker-avalara** [comment] 2017-02-15 20:32
+1

**Comment by webron** [comment] 2017-03-20 22:45
Please try with 3.0. Keeping the ticket open for feedback.

**Comment by rockeshub** [comment] 2017-03-29 10:53
I am using the latest swagger UI . i am not getting the response body  for content-type like application/pdf and application/csv .
The response has 200 status and also response body contains raw data

My response headers contains :
Access-Control-Allow-Credentials:true
Access-Control-Allow-Methods:GET, POST, OPTIONS
Access-Control-Allow-Origin:http://localhost:3000
Connection:keep-alive
Content-Disposition:attachment; filename="Rakesh_www.webdemo.com_TEST_1495417604_2016-09-21_.csv"
Content-Encoding:gzip
Content-Type:application/octet-stream
Date:Wed, 29 Mar 2017 10:38:54 GMT
Server:nginx/1.4.6 (Ubuntu)
Set-Cookie:csessionid=373d14ff968ad6e57163e01d6915db4323932; Path=/; HttpOnly
Transfer-Encoding:chunked
X-FRAME-OPTIONS:SAMEORIGIN

**Comment by buunguyen** [comment] 2017-04-04 21:50
@rockeshub have you tried returning the correct content-type for the CSV or PDF instead of using application/octet-stream?

**Comment by rockeshub** [comment] 2017-04-10 10:51
@buunguyen  i haven't tried with other content-type, but if i call the same API using postman its working fine i am able to download the file. Also according to response-body.jsx i should get " Unknown response type" if my type is not proper.

**Comment by precizeman** [comment] 2017-05-08 09:12
For 2.2.10 file download works fine for GET queries. If I'm doing a POST query with FORM parameter type=file and trying to download file in Response (Produces: application/octet-stream, Responses.Schema.Type=file) the result file still corrupts. If I remove parameter with type=file from POST query, all works fine.
For 3.x file download doesn't work at all.

**Comment by webron** [comment] 2017-05-08 19:42
@precizeman do you have a public API to share to see the file download issue?

**Comment by precizeman** [comment] 2017-05-12 14:40
I will send link in next week (Monday-Tuesday), at this time I’m developing app.

**Comment by naimulhaider** [comment] 2017-05-17 22:32
+1

**Comment by alexk307** [comment] 2017-05-31 19:04
👍

**Comment by alexk307** [comment] 2017-05-31 19:04
+1

**Comment by jstrength** [comment] 2017-06-01 16:53
+1

**Comment by ajimenezvirtuallylive** [comment] 2017-06-06 15:52
+1

**Comment by webron** [comment] 2017-06-09 20:37
For everyone who +1'ed, it would be great to get live examples for us to see the issue in action. That would be a great step to get it fixed.

**Comment by rwg0** [comment] 2017-06-12 09:37
I don't know if this will be helpful, but I have created a test service here

http://testswaggerpostdownload.azurewebsites.net/swagger/ui/index#/Echo

This just echos back the uploaded file as the result of the POST request, allowing you to specify the response content-type too (defaulting to application/octet-stream).

This site is running Swashbuckle 5.4.0 - which is a .NET package for including swagger in a web project. Swashbuckle 5.4.0 seems to be using swagger-ui 2.2.0 (https://github.com/domaindrivendev/Swashbuckle/tree/v5.4.0).

The error for me is that if you pick any binary format file to test with then the file is corrupted after downloading the response body using swagger-ui. 

I realise that swagger-ui 2.2.0 is out of date, but if I use newer versions of Swashbuckle which use swagger-ui 2.2.4 I get this error in the browser when pressing the 'try it out' button.

```
swagger-ui-min-js:14 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at showStatus (swagger-ui-min-js:14)
    at showCompleteStatus (swagger-ui-min-js:14)
    at response (swagger-ui-min-js:9)
    at p (swagger-ui-min-js:7)
    at Object.t.on.response (swagger-ui-min-js:7)
    at Object.e.complete (swagger-ui-min-js:7)
    at k (jquery-1-8-0-min-js:2)
    at Object.fireWith (jquery-1-8-0-min-js:2)
    at y (jquery-1-8-0-min-js:2)
    at XMLHttpRequest.d (jquery-1-8-0-min-js:2)
```

I hope that this is helpful.

**Comment by mikesheen** [comment] 2017-06-20 04:41
I also get a '-' character at the start and end of my file name, as well as the file being bloated and corrupted.  Even the test service @rwg0 provided does the same.

**Comment by codingupastorm** [comment] 2017-06-21 06:02
+1 also having issue with corrupt file and hyphens on start and end of file name.

**Comment by pg26** [comment] 2017-06-28 15:48
+1 also having issue with corrupt file

**Comment by sudeshgutta** [comment] 2017-07-04 04:59
+1

**Comment by pwen090** [comment] 2017-07-04 05:51
+1 binary file being doubled and corrupted. Using Swashbuckle.AspNetCore 1.0.0.

**Comment by stickyhands** [comment] 2017-07-15 16:09
Just spent 2 days searching why my download where corrupted.
+1

**Comment by thestonehead** [comment] 2017-07-19 13:17
+1

I suspect it's a UTF-8 vs ANSI problem.

**Comment by mikesheen** [comment] 2017-07-20 10:49
@thestonehead Good call. I'll test out setting different charset parameters in the header to see if one particular charset resolves this.

**Comment by Sufod** [comment] 2017-08-02 17:28
+1 binary file being ~doubled and corrupted

**Comment by justajavaboy** [comment] 2017-08-04 23:36
+1

**Comment by zmellal** [comment] 2017-08-08 11:35
I have the same issue with pdf files

**Comment by KrishnaPuppala** [comment] 2017-08-17 16:57
+1

**Comment by shockey** [comment] 2017-08-17 17:53
Folks who are adding +1s: what version of Swagger-UI are you experiencing this with?

**Comment by Andrulez** [comment] 2017-08-21 14:26
+1
<version>2.7.0</version>
zip file doubled and corrupted.

**Comment by zmellal** [comment] 2017-08-21 14:34
How can I check the version ? My swagger interface is generated by flask-restplus plugin

**Comment by justajavaboy** [comment] 2017-08-21 21:38
v2.2.0
pdf files are doubled and corrupted

**Comment by webron** [comment] 2017-08-21 22:57
Hi everyone - for everyone's convenience we just added a documentation file to help you detect which version of Swagger-UI you're using. You can find it [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/version-detection.md).

Please note that unless you depend on swagger-ui directly as a stand alone package from npm (the one that's supplied from us), you are getting swagger-ui packaged by different providers (especially in other languages like java, php, python and so on) - and they don't always follow our versioning scheme. For example - there's no swagger-ui 2.7.0.

Remember, we need the version to be able to analyze the problems better, and without accurate information, we won't be able to assist.

**Comment by mikesheen** [comment] 2017-08-26 02:45
@webron - thanks for that - v2.2.10 here - this is what is bundled with ServiceStack at the moment.

**Comment by amelki** [comment] 2017-08-29 15:55
And I guess "2.7.0" was the latest version of Springfox, which embeds Swagger UI 2.2.10.
I have the exact same issues on my side: 
- corrupt file
- size ~doubled
- hyphens on start and end of file name, when a Content-Disposition header is provided

**Comment by zmellal** [comment] 2017-08-29 16:07
swagger UI version v2.2.6 from flask-Restplus 
pdf file corrupted

**Comment by javier-vasquez-mojix** [comment] 2017-08-30 19:50
+1

**Comment by nfrik** [comment] 2017-09-08 15:47
I have the same problem with Swagger v2.2.6 on flask-Restplus. You can partially solve it with the following trick:
https://stackoverflow.com/questions/26971491/how-do-i-link-to-images-not-in-static-folder-in-flask

**Comment by webron** [comment] 2017-09-11 09:29
Thanks everyone who provided their versions. It is unlikely that we'll issue any fixes to the 2.X branch of the code due to technical reasons.

While I understand a lot of you use the UI as provided as part of the libraries, at least for testing purposes, you should be able to test the latest version easily, even without installing it as part of your app, just running it locally. Can you give it a try and report back?

**Comment by eryi** [comment] 2017-11-08 11:49
@webron Unfortunately, the latest version doesn't support file download yet #3149

**Comment by heldersepu** [comment] 2017-11-12 13:41
@eryi - The latest version seems to be working fine, I do get a download link:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Image/Image_Put

I think this issue can be closed

**Comment by pg26** [comment] 2017-11-12 19:08
Which version are you using?

**Comment by heldersepu** [comment] 2017-11-12 19:34
@pg26 I'm always using the latest, as of this note: 
```
{"swaggerUi":
  {
  "version":"3.4.4",
  "gitRevision":"gfadc522f",
  "gitDirty":true,
  "buildTimestamp":"Sat, 11 Nov 2017 07:20:24 GMT",
  "machine":"banjo"
  }
}
```
Here are instructions to check the version:
https://github.com/swagger-api/swagger-ui/blob/master/docs/version-detection.md

**Comment by SeletskySergey** [comment] 2017-11-29 11:06
+1 swagger 1.1.0 for aspnetcore returns corrupted double-sized files

**Comment by heldersepu** [comment] 2017-11-29 13:42
@SeletskySergey  what is: 
>swagger 1.1.0 for aspnetcore 

perhaps you mean [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)?
Check the version of swagger-ui see if they are using the latest

**Comment by HerrDerb** [comment] 2018-02-12 08:09
+1
Just lost a half of a day because of this issue still not solved...

**Comment by heldersepu** [comment] 2018-02-12 16:27
@HerrDerb Sorry to hear, can you provide some more details?
What version of the UI are you using?

**Comment by HerrDerb** [comment] 2018-02-13 14:22
I'm currently on
```
	<dependency>
	    <groupId>io.springfox</groupId>
	    <artifactId>springfox-swagger2</artifactId>
	    <version>2.7.0</version>
	</dependency>
	<dependency>
	    <groupId>io.springfox</groupId>
	    <artifactId>springfox-swagger-ui</artifactId>
	    <version>2.7.0</version>
	</dependency>
```

**Comment by heldersepu** [comment] 2018-02-13 14:29
@HerrDerb  that version number is very strange ...
Last on record for the 2.x branch was: [v2.2.10](https://github.com/swagger-api/swagger-ui/releases/tag/v2.2.10) 

Compare with the [PetStore](http://petstore.swagger.io/) sample see if your looks like that that is the latest (3.x) and it is quite different from the previous one.

I think you should contact springfox see if they point you on the right direction.

**Comment by shockey** [comment] 2018-02-13 23:38
As @webron mentioned upthread:

> Thanks everyone who provided their versions. It is unlikely that we'll issue any fixes to the 2.X branch of the code due to technical reasons.
>  
> While I understand a lot of you use the UI as provided as part of the libraries, at least for testing purposes, you should be able to test the latest version easily, even without installing it as part of your app, just running it locally. Can you give it a try and report back?

#3149 is closed now, so you all should be able to test 3.x 😄

**Comment by CT100** [comment] 2018-02-20 14:57
+1 binary file being doubled and corrupted. Using Swashbuckle.AspNetCore 1.2.0.

**Comment by estianross** [comment] 2018-02-27 13:30
+1. Corrupts xlxs files. Using django-rest-swagger 2.1.2.

**Comment by heldersepu** [comment] 2018-02-27 13:33
@estianross Can you provide a link to your API?

**Comment by estianross** [comment] 2018-02-27 13:40
Unfortunately not as this is still in testing currently. Testing through drf browsable api and curl does not corrupt the file though, only by hitting the endpoint through swagger does it get corrupted.

**Comment by heldersepu** [comment] 2018-02-27 13:42
@estianross What can you share that would help us troubleshoot?

**Comment by estianross** [comment] 2018-02-27 13:59
Only a description of the issue in hopes and steps you can take to hopefully replicate it.
Firstly post to a view derived from drf's GenericAPIView
Second generate a workbook using openpyxl (wb = openpyxl.Workbook())
Next populate with a single example row (wb.active.append(row))
Finally:
```
filename = 'test.xlsx'
response = HttpResponse(content_type='application/vnd.ms-excel;charset=UTF-8', content=save_virtual_workbook(wb))
response['Content-Disposition'] = 'attachment; filename=%s' % filename
return response
```

Hopefully that's something to help, like I said above it's not a critical issue for me as it only shows up while testing through swagger, not while using the endpoint directly

**Comment by heldersepu** [comment] 2018-02-27 14:01
@estianross If your Swagger-UI looks like what they have on the image here:
https://marcgibbons.com/django-rest-swagger/#quick-start

They are using an old version (2.x), that version is no longer supported and has not receive any attention in while, see if you can get them to upgrade to the latest.

**Comment by estianross** [comment] 2018-02-27 14:06
Thanks for the assistance :D will do

**Comment by heldersepu** [comment] 2018-02-27 14:45
@estianross looking at the activity of the project:
https://github.com/marcgibbons/django-rest-swagger/pulse/monthly
>There hasn’t been any commit activity on marcgibbons/django-rest-swagger in the last month.

That is not a good sign ... See if there are any alternatives out there

**Comment by vikas1456** [comment] 2018-03-01 07:46
@SeletskySergey 
You need to update version of Swashbuckle.AspNetCore.SwaggerUI to 2.1.0 . No need to change any other version. it will work fine

**Comment by shockey** [comment] 2018-03-01 23:21
Can anyone confirm that this is still an issue with the latest 3.x version?

**Comment by HerrDerb** [comment] 2018-03-02 06:46
I can confirm that with 
```
<groupId>io.springfox</groupId>
<artifactId>springfox-swagger-ui</artifactId>
<version>2.8.0</version>
```
the problem is solved. I don't have an 3.x.x. around.

**Comment by shockey** [comment] 2018-03-13 20:30
@HerrDerb, thanks for the info!

---

I'm going to close this out - we've been courting reports for this being a problem in 3.x since last August, and haven't gotten any.

As a reminder, Swagger-UI 2.x is no longer under development, so we won't be addressing problems with any versions before 3.0.0.

Thanks to everyone for providing information!

**Closed by shockey** 2018-03-13 20:30 UTC

**Comment by utkarsh-sharma-31** [comment] 2018-04-10 07:12
@SeletskySergey How do we update the Swashbuckle.AspNetCore.SwaggerUI in Django Rest Swagger?

**Comment by asalih** [comment] 2019-03-28 18:49
If you still using Swashbuckle and swagger.ui 2.2.10 like me. This workaround worked for me;

`
(function () {
        var currentXhr;
        var currentXhrFn;
        var currentXhrArgs;

        var origOpen = XMLHttpRequest.prototype.open;
        XMLHttpRequest.prototype.open = function () {

          var bypass = false;

          for (var i = 0; i < arguments.length; i++) {
            if (arguments[i] === "bpfpdf") {
              bypass = true;
              break;
            }
          }

          if (!bypass) {
            currentXhr = this;
            currentXhrFn = this.onreadystatechange;
            currentXhrArgs = arguments;

            this.onreadystatechange = function () { }

            this.addEventListener('load', function () {
              if (this.getAllResponseHeaders().indexOf("content-type: application/pdf") > -1) {
                var newRequest = new XMLHttpRequest();
                newRequest.responseType = "arraybuffer";

                newRequest.addEventListener("readystatechange", function () {
                  if (this.readyState === 4) {
                    Object.defineProperty(currentXhr, "response", { writable: true });
                    Object.defineProperty(currentXhr, "responseText", { writable: true });

                    currentXhr.response = this.response;
                    currentXhr.responseText = null;

                    currentXhrFn.apply(newRequest);
                  }
                });

                newRequest.open(currentXhrArgs[0], currentXhrArgs[1], currentXhrArgs[2], "bpfpdf");

                newRequest.setRequestHeader("Authorization",
                  "Basic " +
                  btoa(swaggerUi.api.clientAuthorizations.authz.basicAuth.username + ":" + swaggerUi.api.clientAuthorizations.authz.basicAuth.password));

                newRequest.send(null);

              } else {
                if (currentXhrFn != null) {
                  currentXhrFn.apply(this);
                }
              }
            });
          }

          var params = Array.prototype.slice.call(arguments);

          if (bypass) {
            params.pop();
          }

          origOpen.apply(this, params);
        };
      })();
`
