### ISSUE TITLE
Map in request body not rendered

### ISSUE THREAD

**Issue by tsz662** [swagger-api/swagger-ui#1352] opened 2015-06-09 11:21 UTC
I believe the following schema valid but is not rendered in Swagger UI.
Or am I missing something?
(Forgive me if this is a duplicate of an existing issue.)

````javascript
    "/users" : {
      "put" : {
        "summary" : "Locks or removes multiple user accounts in batch.",
        "description" : "Request body carries a map of which key is a user ID and value is boolean; if the value is true, locks the user account. If the value is false, deletes the user account.",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "userlist",
          "in" : "body",
          "required" : true,
          "schema" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "boolean"
            }
          }
        } ],
````

**Comment by webron** [comment] 2015-06-09 13:36
This is a duplicate of #558. I've modified the issue's title now so it's easier to detect.

**Closed by webron** 2015-06-09 13:36 UTC
