### ISSUE TITLE
How to default operations to being closed?

### ISSUE THREAD

**Issue by gwynjudd** [swagger-api/swagger-ui#3144] opened 2017-05-28 22:43 UTC
When reporting an issue, please provide the following details:
- swagger-ui version
3.x
- a swagger file reproducing the issue
http://petstore.swagger.io/v2/swagger.json

I'd like to host swagger-ui but make it so that the operations are closed to start off, instead of open.

e.g., like this:

![image](https://cloud.githubusercontent.com/assets/314188/26532673/8f415f7e-445b-11e7-9647-4855b96ce9bb.png)

Not like this:

![image](https://cloud.githubusercontent.com/assets/314188/26532675/98c204b8-445b-11e7-917f-fc34e19e22cc.png)

**Comment by drjonnicholson** [comment] 2017-05-30 10:30
Also interested in this. Appears that the `docExpansion` config setting isn't supported anymore?

**Comment by webron** [comment] 2017-05-30 22:57
Duplicate of #2799 (will add a comment there re what to expect).

**Closed by webron** 2017-05-30 22:57 UTC
