### ISSUE TITLE
Error response does not show any details

### ISSUE THREAD

**Issue by jiyonghong** [swagger-api/swagger-ui#3050] opened 2017-05-08 08:01 UTC
I'm currently working with swagger@v2.0 and swagger-ui@v3.0.8 and having some issue on error response.

On 2xx responses, there are no problems. But when I receive 4xx responses, no details appear in the swagger response but there are actual response shown in the developer tools. I would like to know how to make swagger display this information in the detail section.

Please see the screenshot below.

![Screenshot](http://i.imgur.com/NDB0IA8.png)

**Comment by webron** [comment] 2017-05-08 19:39
Duplicate of #3041.

**Closed by webron** 2017-05-08 19:39 UTC
