### ISSUE TITLE
DockerHub Links for installation and configuration are dead

### ISSUE THREAD

**Issue by Sebi2020** [swagger-api/swagger-ui#7837] opened 2022-02-12 14:45 UTC
The links under the Documentation heading on https://hub.docker.com/r/swaggerapi/swagger-ui are dead.
For example https://hub.docker.com/r/swaggerapi/docs/usage/installation.md  returns 404.

**Comment by hkosova** [comment] 2022-02-13 15:41
Duplicate of #6233.

**Closed by hkosova** 2022-02-13 15:41 UTC
