### ISSUE TITLE
Using "content" in "parameters" doesn't work

### ISSUE THREAD

**Issue by piotrzarzycki21** [swagger-api/swagger-ui#4937] opened 2018-10-11 09:33 UTC
### Q&A (please complete the following information)
 - OS: Windows 10 64bit
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)
 - Method of installation: dist
 - Swagger-UI version: 3.19.3
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```
"/myapi/mymethod": {
      "post": {
        "summary": "My Method.",
        "operationId": "myapimymethod",
        "tags": [
          "common"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "params",
            "required": "true",
            "description": "Additional data for document",
            "content": {
                "application/json":{
                  "schema": {
                      "type": "object",
                      "properties": {
                          "firstname": {
                            "type": "string"
                          }
                      }
                  }
              }
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                    "$ref": "./schemas/body/somedata.json#/somedata"
                }
              }
            }
        }
    }
```

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
        url: "common.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
```

### Describe the bug you're encountering
I'm getting following results when content is being used in API description:
![cannot_read](https://user-images.githubusercontent.com/24554795/46794612-81927a80-cd48-11e8-9719-2fa0ed92316b.png)

Open API documentation describing that I can use content inside parameters - section [schema vs content](https://swagger.io/docs/specification/describing-parameters/#schema-vs-content)

### To reproduce...

Run in Swagger UI provided example. 

### Expected behavior
Work as it is described in OpenApi documentation.

### Screenshots
You will get following results.
![could_not_render](https://user-images.githubusercontent.com/24554795/46794977-447ab800-cd49-11e8-84b8-3b6b081bd28c.png)

**Comment by hkosova** [comment] 2018-10-11 16:58
Thanks for the report! This issue is being tracked in #4442.

**Comment by shockey** [comment] 2018-10-11 18:30
Closing as a duplicate of #4442.

**Closed by shockey** 2018-10-11 18:30 UTC
