### ISSUE TITLE
docExpansion is not working

### ISSUE THREAD

**Issue by zak905** [swagger-api/swagger-ui#3047] opened 2017-05-07 14:26 UTC
I am using swagger-ui 3.0.8, and I am trying to get all the operation collapsed on start up using docExapnsion:"none", but it does seem to have any effect. is this option still available? if not, is there any other ways to do it?

**Comment by webron** [comment] 2017-05-08 19:33
It's not supported yet.

**Comment by urukalo** [comment] 2017-05-19 08:53
same issue we have here too:
https://github.com/swagger-api/swagger-ui/issues/3088

**Comment by webron** [comment] 2017-05-30 22:59
Duplicate of #2799.

**Closed by webron** 2017-05-30 22:59 UTC
Labels: 3.x, Feature, P2

**Comment by wraycode** [comment] 2017-09-08 21:11
I just use jquery to collapse them 

`  $.initialize(".is-open", function() {  
    $(".is-open").children('div').hide(); 
  });
`
