### ISSUE TITLE
Wrong model name in the UI

### ISSUE THREAD

**Issue by gsi-delmo** [swagger-api/swagger-ui#3030] opened 2017-05-04 18:31 UTC
As you can see in the image I named the second model as _newUser_, however it is shown as _user_ in the UI.

![image](https://cloud.githubusercontent.com/assets/11967822/25719076/43cc0992-30d6-11e7-87ee-92da3459bda9.png)

**Comment by hkosova** [comment] 2017-05-04 20:18
Duplicate of #2946?

**Comment by webron** [comment] 2017-05-04 20:19
Thanks @hkosova! I was sure there was a ticket on that, but couldn't find it. Sorry for the trouble, @gsi-delmo, but as you can see, it's a known issue.

**Closed by webron** 2017-05-04 20:19 UTC

**Comment by gsi-delmo** [comment] 2017-05-04 20:25
No problem @webron.
