### ISSUE TITLE
Boolean body parameters cause JS error

### ISSUE THREAD

**Issue by phindmarsh** [swagger-api/swagger-ui#966] opened 2015-02-26 07:47 UTC
I've been working on generating swagger schemas and noticed that an operation that uses a boolean parameter in the body will cause a Javascript error `Cannot read property 'toLowerCase' of undefined`.

This seems to happen because the handlebars helper `isArray` (declared in `ParameterView.prototype.initialize`) is calling `toLowerCase()` on the parameter `type` without checking it isn't undefined first. Since body parameters have the `type` defined in `schema`, I figure this is a bug. The validator badge shows that the schema itself is valid, but the UI will fail to render.

If I put a `"type": "boolean"` property onto the parameter (which is not valid) then it will render properly

I've attached two different schemas:
- [Error causing schema](https://gist.githubusercontent.com/phindmarsh/d3b3672936c19eb66dbe/raw/34fcf704742d64d10397fdef0dd923b6cc442c81/valid-but-broken.json), this is the one that should work, but fails.
- [Working schema](https://gist.githubusercontent.com/phindmarsh/d3b3672936c19eb66dbe/raw/85be8a42695472caa7e53fbc10e5ead00f3738c9/invalid-but-works.json), this one renders properly, but is not a valid schema (due to the `type` property being directly on the schema).

Is it appropriate to make the handlebars function check the type is not undefined first? I suspect there's something more going on here since it only seems to affect boolean parameters.

This is in Chrome Version 40.0.2214.115 (64-bit) on OS X 10.10.2

**Comment by webron** [comment] 2015-02-26 17:35
@fehguy - This happens only when the type is `boolean`. For other primitive types it seems to work properly.

@phindmarsh - For what it's worth, both schema are invalid since you can't have more than one body parameter.

**Comment by mohsen1** [comment] 2015-02-26 17:56
According to the validator in Swagger Editor body parameter with `type: boolean` is invalid. Pasting this in Swagger Editor will throw validation errors

```json

{
    "swagger": "2.0",
    "info": {
        "title": "An API description",
        "version": "1.0.0"
    },
    "paths": {
        "/some/path": {
            "post": {
                "parameters": [
                    
                    {
                        "description": "",
                        "in": "body",
                        "name": "test",
                        "type": "boolean"
                    }
                ],
                "responses": {
                    "default": {
                        "description": "The default response",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by webron** [comment] 2015-02-26 17:59
@mohsen1 - @phindmarsh wasn't suggesting it's valid, he just mentioned that when it's written this way, the UI doesn't break.

**Comment by phindmarsh** [comment] 2015-02-26 21:50
@mohsen1 if the schema isn't valid in the editor then which of the (seemingly several) validation services is to be trusted?

I've been validating schemas against the [Swagger JSON Spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) (using various validation libs), and the (what I assume is an official) validation service at [online.swagger.io/validator](http://online.swagger.io/validator/debug?url=https://gist.githubusercontent.com/phindmarsh/d3b3672936c19eb66dbe/raw/34fcf704742d64d10397fdef0dd923b6cc442c81/valid-but-broken.json). Both of these methods return no validation errors, hence my assumption that they way the schema was structured is correct. I was not aware that several `in: body` parameters was not allowed.

If this is indeed the case, relying on pasting a schema into the Editor to validate is a bit of a crutch, since I'd expected that the [2.0 Spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) would be the official source.

As @webron indicated, I posted two schemas, one that was invalid but rendered properly, and one that was valid (from what I could tell) that did not render.

Disclaimer: I've only been using Swagger schemas for a couple of weeks so I am by no means fluent in the intricacies.

**Comment by mohsen1** [comment] 2015-02-26 21:51
JSON Schema can validate your specs to some extend. In Swagger Editor we do more than only JSON Schema validation. It uses Swagger Tools to do that.

**Comment by phindmarsh** [comment] 2015-02-26 21:56
So is Swagger Tools the 'official' way to validate schemas, and the online.swagger.io/validator et all are not guaranteed to validate correctly?

**Comment by fehguy** [comment] 2015-02-27 04:59
Hi @phindmarsh apologies if this is confusing.  Some guidelines.

First and foremost, the _spec_ is the single, authoritative definition of what is possible.  When in doubt, the answers are in the [spec documentation](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md).

Next, tooling can go a great way to help ensure your spec is valid.  They are, though, a convenience and an attempt to represent the intent of the spec.  The spec is *still* the source of truth.  Validators are almost never, ever going to cover all aspects of your definition.

Finally, the online.swagger.io/validator will validate the integrity of the spec though the JSON Schema.  The swagger tools add a layering of "rules" on top of that.  They should be a superset of the online.swagger.io/validator logic.

So while the validators will continue to improve, they are not 100% comprehensive, just like a blood test will have some margin for error.  You cannot have multiple `body` parameters in a single operation, as defined [here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-4)

**Comment by phindmarsh** [comment] 2015-02-27 21:37
Thanks @fehguy for your reply. That clears things up, apologies if I seemed terse previously.

I missed the line about only one body parameter being allowed, sorry about that. That said perhaps it would be useful to call that out a bit more, especially seeing as the JSON validators aren't able to pick up on it (yet). 

In light of all this, is the javascript error (the original reason for the issue) something that should be fixed? I'm not sure if the UI is supposed to be lenient on invalid properties or not. If its not, then no problems for this to be closed.

Thanks for your help :+1:

**Comment by mohsen1** [comment] 2015-03-18 19:42
SwaggerUI is expecting valid specs. I'm closing this issue since the issue was raised with invalid specs.

**Closed by mohsen1** 2015-03-18 19:42 UTC

**Comment by jdamick** [comment] 2015-06-18 19:58
I've run into the same issues, except I only have 1 body parameter that is a Boolean.  It causes the same toLowerCase() being called against a type which is undefined..   As in the original issue, it appears to be  a bug in the ui processing?

```
{
            "in": "body",
            "name": "body",
            "description": "enable feature flag",
            "required": false,
            "schema": {
              "type": "boolean"
            }
          }
```

**Comment by mohsen1** [comment] 2015-06-18 20:19
@jdamick `in: body` should not have `required`

**Comment by wing328** [comment] 2015-06-19 06:58
@mohsen1 may I confirm with you that `in: body` must be a `required` parameter (based on the spec)?

According to the [example] (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object-examples) provided in the spec, it also includes the `required: true`, which seems to imply it can be `false` as well

**Comment by jdamick** [comment] 2015-06-19 13:21
So is that an issue in the swagger-core?  i've tried annotating different ways and it still adds "required" or am using the wrong annotation?

```
 @ApiParam(value = "enable feature flag") Boolean enable
```
thanks

**Comment by webron** [comment] 2015-06-19 15:44
@jdamick, @mohsen1, @wing328 - there seems to be some confusion here. `body` parameters *may* have the `required` property included and set whichever way. If it is not, included, `false` is assumed. This is specified by the spec.

@jdamick - the definition you provide is valid and should work. If you experience an issue with the *latest* swagger-ui version (2.1.0 at the moment), please open a new ticket.

**Comment by wing328** [comment] 2015-06-20 00:55
@webron thanks for the clarification. That's how I understand it.

**Comment by dstaas** [comment] 2015-07-23 16:54
The root cause appears to be that swagger-core is generating JSON output as "schema" : { "type" : "boolean" }, which swagger-ui can't consume.  If I run the following Ruby script to post-process the swagger.json, swagger-ui seems to handle it better:

    filename = "my.json"
    text = File.read(filename)
    puts = text.gsub(/"schema"\s*:\s*{\s*"type"\s*:\s*"boolean"\s*}/m, '"type" : "boolean"')
    File.open("new.json", "w") { |file| file << puts }

**Comment by mstrelex** [comment] 2016-04-13 15:10
Issue still exists, any roadmap on that ?

**Comment by tedvanderveen** [comment] 2016-06-30 09:57
Can fix https://github.com/ebjwc/swagger-ui/commit/4b57f20cb26e3bf0f9f01a379d459e2024419000 be released pleae?

**Comment by iplantemn** [comment] 2016-07-11 20:35
We are experiencing the same issue, and hoping that ebjwc@4b57f20 will fix it for us.
