### ISSUE TITLE
Add custom request headers in Swagger v3.0

### ISSUE THREAD

**Issue by bochkapb** [swagger-api/swagger-ui#3094] opened 2017-05-17 08:28 UTC
I am using Swagger UI 3.0 which comes with SwaggerUIBundle. My code is the same as example one in dist folder. We need put custom header in request. In 2.x version we used jquery way

```
   $.ajaxSetup({
                beforeSend: function (jqXHR, settings) {
                    if (settings.url.indexOf("endpoint/api") !== -1) {
                        jqXHR.setRequestHeader("MyApp-Username", 'login');
                        jqXHR.setRequestHeader("MyApp-Password", 'password');
                        jqXHR.setRequestHeader("MyApp-Custom-Header", 'value');
                    }
                }
            });
```

but in new version it does not work.

**Comment by webron** [comment] 2017-05-17 14:17
Duplicate of #3086.

**Closed by webron** 2017-05-17 14:17 UTC
