### ISSUE TITLE
Attributes without descriptions not formatted correctly

### ISSUE THREAD

**Issue by codewanderer16** [swagger-api/swagger-ui#4134] opened 2018-01-18 18:23 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.9.0, 3.9.1, latest Swagger editor (online)
| How did you install Swagger-UI? | from the download zip
| Which browser & version?        | several
| Which operating system?         | Windows 10

### Demonstration API definition

[example bug_swagger.json file](https://gist.github.com/codewanderer16/e6fbb847d9346acc922c2db49e6d1915)
[example minimal_bug_swagger.json file - just the problem areas](https://gist.github.com/codewanderer16/4e7925c961644da2baef311bd3917c96)

### Current Behavior

I've got one attribute specification (schemas) that is improperly formatted in the Swagger output.

![image](https://user-images.githubusercontent.com/31778191/35114071-c64cdc80-fc40-11e7-865c-f4944d58c60f.png)

I've got the same structure (with a description added) elsewhere in my working file, and it's properly formatted.

When I convert the complex objects (such as extendedMeta) to be arrays with the items keyword, schemas formats correctly.

In Swagger-Editor, I stripped my schema object down to just the schemas attribute and didn't see a change.

Adding a description seems to make the difference.

Additionally, when there's no description for a complex array attribute, the dropdown for the subattributes is at the end of the previous line, not on the next line as for similar attributes with descriptions:

![image](https://user-images.githubusercontent.com/31778191/35114411-da46743e-fc41-11e7-99b1-a9c15dbfb609.png)

### Expected Behavior

Presence or absence of the description property should not impact the formatting of the other properties.

**Comment by heldersepu** [comment] 2018-01-24 02:27
Not sure if this is your only problem but your JSON is not valid:
https://online.swagger.io/validator/debug?url=https://gist.githubusercontent.com/codewanderer16/e6fbb847d9346acc922c2db49e6d1915/raw/499de51c7cef0aedbae0a09b430989a135fc979c/bug_swagger.json

**Comment by codewanderer16** [comment] 2018-01-30 00:09
Thanks, @heldersepu . I've updated the gist with JSON that passes validation, and the issue still exists.

**Comment by heldersepu** [comment] 2018-01-30 00:25
Are you sure it is valid? Here is your latest:
https://online.swagger.io/validator/debug?url=https://gist.githubusercontent.com/codewanderer16/e6fbb847d9346acc922c2db49e6d1915/raw/3591ca5a4ac25b0962a8a4f2c8f3612bd6ca1309/bug_swagger.json

```js
{
    "messages": [
        "attribute definitions.Error Response.externalDocs is unexpected"
    ]
}
```

**Comment by codewanderer16** [comment] 2018-01-30 00:33
@heldersepu Yes. Just checked it again. It passes https://jsonlint.com/
The problem was a remnant comma at the end of line 204. I removed it.

**Comment by heldersepu** [comment] 2018-01-30 00:36
Look at the last link I sent you? 
the validation that should be passing is: https://online.swagger.io/validator

**Comment by heldersepu** [comment] 2018-01-30 00:38
Here what a valid json looks like:
https://online.swagger.io/validator/debug?url=http://offleaseonly.azurewebsites.net/swagger/docs/V1
https://online.swagger.io/validator/debug?url=http://petstore.swagger.io/v2/swagger.json

**Comment by codewanderer16** [comment] 2018-01-30 00:57
That validator doesn't give any hints. How do I determine the problem?
I put my content in editor.swagger.io and it went straight to YML. I saved that YML back to JSON and ran it through the same beautifier as my original content. The files are identical.

**Comment by heldersepu** [comment] 2018-01-30 01:04
Does not give you any hints? 
How about that message, maybe some formatting will help: 

**attribute definitions.Error** `Response.externalDocs is unexpected`

**Comment by codewanderer16** [comment] 2018-01-30 01:20
yeah. i got past that one. now I'm getting:
{"messages":["malformed or unreadable swagger supplied"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (string) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""}}]}
No idea where to start.

**Comment by heldersepu** [comment] 2018-01-30 01:38
You are getting a cascade of errors...

Let's try to tackle this on a different way, How are you generating this swagger?
- If you are using a 3rd party tool to generate it, then contact them see if they can help.
- If by hand, then the road ahead is a long and painful one, my suggestion simplify your swagger.json to a minimal that reproduces this issue or fixes your problem.

**Comment by codewanderer16** [comment] 2018-01-30 04:51
Our Swagger is generated by a custom tool I know nothing about (and have no control over) with some additional modifications to the output of that. What I posted is actually already a minimum content piece, but I'll keep stripping it down to isolate the problem area. (Sigh.)

FWIW, https://www.npmjs.com/package/swagger-spec-validator (when run locally from the command line) gives result: All OpenAPI/Swagger specs are valid.

**Comment by codewanderer16** [comment] 2018-02-08 22:17
@heldersepu finally had time to dig into this. turns out i was passing the wrong thing into the validator. With the updated file, the path is:
https://online.swagger.io/validator?url=https://gist.githubusercontent.com/codewanderer16/e6fbb847d9346acc922c2db49e6d1915/raw/f2f326141afe13b9e2684660d49e4733109c6915/bug_swagger.json

My content is now valid. The formatting anomalies described here and in https://github.com/swagger-api/swagger-ui/issues/4133 still exist. 🤕

**Comment by heldersepu** [comment] 2018-02-09 00:04
That is huge step on the right direction...
If you can, try to reduce that swagger.json to a minimal valid reproducing your issue

**Comment by codewanderer16** [comment] 2018-02-09 00:50
@heldersepu As requested, I'm adding an ultra minimal swagger file. https://gist.github.com/codewanderer16/4e7925c961644da2baef311bd3917c96, also added to the initial description.
thanks for you assistance!

**Comment by heldersepu** [comment] 2018-02-09 01:32
Take a look here:
http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/4134_swagger.json#/

so if I understand correctly the problem you are reporting  is that string on the same line as the `uniqueItems: true`  correct?

**Comment by codewanderer16** [comment] 2018-02-09 21:54
Yes, that's one piece of this issue.
The other is the same idea - the expansion for the subattributes is inline with the previous text when there's not a description string to provide separation.

**Comment by heldersepu** [comment] 2018-02-09 22:47
Perfect! I should have sometime now over the weekend to take a look at the first piece

**Comment by heldersepu** [comment] 2018-02-10 00:41
I think that moving the Type declaration to the top should do...

Before:
![image](https://user-images.githubusercontent.com/545474/36056279-0e25aa36-0dd1-11e8-9089-53daa8558b74.png)

After:
![image](https://user-images.githubusercontent.com/545474/36056291-3124ce68-0dd1-11e8-9297-4765c5ef94ba.png)

What do you think?

**Comment by LivingLovingLearning** [comment] 2018-03-12 14:54
@heldersepu Beautiful. Thanks much!
OK to close this issue now.

**Closed** 2018-03-13 17:28 UTC
Labels: type: support
