### ISSUE TITLE
Circular Reference generate errors

### ISSUE THREAD

**Issue by matthieugeerebaert** [swagger-api/swagger-ui#2889] opened 2017-04-10 09:05 UTC
On master

Circular reference generate errors.

Like "Node" contains a list of nodes for instance

```
Errors

Resolver error
too much recursion
Resolver error
too much recursion
```

Parameters view is also broken

Maybe relative to
Very slow loading times #1919

**Comment by webron** [comment] 2017-04-10 09:08
Can you share a spec that reproduces it? We've tested circular reference support.

**Comment by matthieugeerebaert** [comment] 2017-04-10 09:28
Here it is

[circular.swagger.json.zip](https://github.com/swagger-api/swagger-ui/files/909591/circular.swagger.json.zip)

**Comment by matthieugeerebaert** [comment] 2017-04-10 09:31
3.0.3 OK
3.0.5 and master KO

**Comment by webron** [comment] 2017-04-10 11:22
Interesting. I see a different behavior if the file is embedded vs hosted. No major issues with the embedded version, but once hosted... :boom:.

**Comment by shockey** [comment] 2017-04-25 21:49
Looks like it was introduced into the static build here: https://github.com/swagger-api/swagger-ui/commit/dd8fb58fcd50c0f0639e540d03a273557a66cf9e

**Comment by shockey** [comment] 2017-04-25 23:42
>  I see a different behavior if the file is embedded vs hosted.

@webron, thanks for the hint. You just saved me a couple additional hours of debugging 😄 

The problem has been isolated to swagger-js, writing regression tests and looking for a fix now.

**Comment by shockey** [comment] 2017-04-26 03:38
Problem introduced here: https://github.com/swagger-api/swagger-js/commit/4e2dff33e75744e9

**Comment by shockey** [comment] 2017-04-28 02:20
Hi everyone - we just merged the PR that fixes this in swagger-js, and you can expect the fix to be in our Friday release tomorrow evening 😄

**Closed** 2017-04-29 02:55 UTC
Labels: 3.x, Bug, P1, Pending release
