### ISSUE TITLE
schemaValidationMessages":[{"level":"error","message":"Can't read from file /swagger.json"}]

### ISSUE THREAD

**Issue by xiaonizi-github** [swagger-api/swagger-ui#3623] opened 2017-08-29 11:48 UTC
hello,i generate the swagger.json by this plugin 
                <plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.4</version>
               .........
and i start the swagger-ui by the command:
docker run -p port:port -e "SWAGGER_JSON=xxx" -v xx:xx swagger-ui,but when i open the browser,that occured: schemaValidationMessages:can not read,my project seprated from swagger.json file,what should i fix this problem?thanks.

**Comment by xiaonizi-github** [comment] 2017-08-29 11:49
@ajmanlove

**Comment by xiaonizi-github** [comment] 2017-08-29 11:53
@shockey

**Comment by xiaonizi-github** [comment] 2017-08-30 02:07
i have solved

**Comment by shockey** [comment] 2017-08-30 04:37
@xiaonizi-github, glad to hear it!

Closing.

**Closed by shockey** 2017-08-30 04:37 UTC

**Comment by monica18p** [comment] 2017-10-11 05:19
@xiaonizi-github Could you please post your solution here. I am also facing similar issue. I used the swagger online editor, downloaded the swagger.yaml file, added it to /dist directory and changed the index.html file as following

```
window.onload = function() {
  //url: "http://petstore.swagger.io/v2/swagger.json",
  // Build a system
  const ui = SwaggerUIBundle({
    url: "../swagger.yaml",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
```

Its working locally on http://127.0.0.1:8080/ but when I try to load the index.html file on browser "Failed to load spec" error is shown.

> {
>   "schemaValidationMessages": [
>     {
>       "level": "error",
>       "message": "Can't read from file ../swagger.yaml"
>     }
>   ]
> }

And when I try to load http://192....:8080 (external url) swagger petstore is loaded.

**Comment by shockey** [comment] 2017-10-11 05:21
@monica18p, if your yaml file is in the `dist` directory, you should use `/swagger.yaml` instead of `../swagger.yaml` - if I'm understanding your setup correctly.

**Comment by monica18p** [comment] 2017-10-11 05:26
Already tried that :)

**Comment by monica18p** [comment] 2017-10-11 05:34
@shockey Are there any other specifications that I need to do?

**Comment by maniutek20** [comment] 2018-04-09 18:40
@ajmanlove, @shockey, @monica18p I don't know why it is closed issue. Monica got same problem in October, today it happened to me. Closing issues because we want to got closed issues?

**Comment by webron** [comment] 2018-04-09 19:12
@maniutek20 the issue is closed because the original author said it was solved for him. If you're having an issue, you're welcome to file a new ticket.
