### ISSUE TITLE
When API supports multiple content-type, Support for multiple default value is needed

### ISSUE THREAD

**Issue by vijayansrinivasan** [swagger-api/swagger-ui#515] opened 2014-08-02 13:34 UTC
- Assume an api support multiple content types (json & xml)
- Currently if we set default value for the post body, then automatically option for content-type selection is removed in the current version of the swagger UI
- This issue to support default value for multiple content types also enable content type selection even if it has a default value

**Comment by fehguy** [comment] 2015-05-08 20:32
old issue, but this will be added by 2.1

**Comment by webron** [comment] 2015-07-20 16:42
This one is challenging. Let's clarify that the `default` value is actually intended as the value used by the server when none is provided by the client, the `example` is intended to provide an actual input example.

The problem is that the ability to describe a structure based on mime type is only available for responses and not requests. For requests, you can only assign examples for definitions which affect body parameters, and even there you can't set it per mime type. This is a limitation of the spec which we'd need to resolve. I've opened a ticket for it so we can follow up on it - https://github.com/swagger-api/swagger-spec/issues/418.

We may solve it using vendor extensions for now as workaround.

For now, I'll close the issue as we simply can't deal with it as-is.

**Closed by webron** 2015-07-20 16:42 UTC
Labels: Feature, P3
