### ISSUE TITLE
Parameter $refs are not handled correctly 

### ISSUE THREAD

**Issue by duncanhall** [swagger-api/swagger-ui#906] opened 2015-02-04 14:34 UTC
When specifying a top level `parameter` and then referencing it in a `path`, swagger-ui does not expand the reference at all:

![swagger-ui-ref-bug](https://cloud.githubusercontent.com/assets/1502359/6042225/d7e4f4be-ac7a-11e4-906b-63d8029055ea.png)

This can be tested with this minimal schema:

```
{
    "swagger": "2.0",
    "host": "qa.test.com",
    "basePath": "/api/v2",
    "info": {
        "version": "0.2.0",
        "title": "Parameter $ref test",
        "description": "Example"
    },
    "parameters": {
        "start": {
            "name": "start",
            "in": "query",
            "description": "The starting index to offset results from",
            "type": "integer",
            "default": 0,
            "minimum": 0
        }
    },
    "paths": {
        "/item": {
            "get": {
                "description": "Return some items",
                "parameters": [
                    {
                        "name": "type",
                        "in": "query",
                        "description": "A type of item",
                        "required": true,
                        "type": "string",
                        "format": "string"
                    },
                    {
                        "$ref": "#/parameters/start"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response"
                    }
                }
            }
        }
    }
}
```

The very same schema loaded into the swagger editor works as exepcted:

![swagger-editor](https://cloud.githubusercontent.com/assets/1502359/6042149/679fd462-ac7a-11e4-994f-7a1395aeb11d.png)

**Comment by webron** [comment] 2015-02-04 14:35
Thanks. This is a duplicate of #621 and is currently slated for the M2 release.

**Closed by webron** 2015-02-04 14:35 UTC

**Comment by duncanhall** [comment] 2015-02-04 14:41
Ah, sorry for not looking harder. Thanks for the quick response.

**Comment by webron** [comment] 2015-02-04 14:42
No worries. It's better to have duplicates than having no reports.
