### ISSUE TITLE
Doesn't work unless window.swaggerUi is set

### ISSUE THREAD

**Issue by floydqwz** [swagger-api/swagger-ui#851] opened 2015-01-26 10:30 UTC
I have made a page which uses Swagger UI twice. One for each API I have (since the API changed and I don't want to have ALL my API's in ONE file, but on ONE page.). The only way I can make it work is if window.swaggerUi is assigned to the SwaggerUi() object.

That sounds like a bug to me. I should be able to assign the SwaggerUi object to whatever I want.

**Comment by fehguy** [comment] 2015-01-30 06:03
This is an issue with using globals in the swagger-ui.  It does expect there is only one instance attached to `window`.  This will get fixed but will take a bit more time to address.  Moving to the M2 release.

**Comment by mohsen1** [comment] 2015-03-04 21:26
How exactly this should get fixed? `swaggerUi` is not the only global. There is also `authentications` and maybe more.
Since Swagger UI is designed to render one document per page (think routing and all other design decisions made based on that) it's going to be a major refactor to let Swagger UI work independent from globals. We should update routing mechanism too.

I suggest moving this to future.

**Comment by fehguy** [comment] 2015-03-04 22:03
my suggestion is as follows:

1) Swagger-ui should not assume it's attached to `window`
2) The construction of swagger-ui should determine *what* it's attached to.  It could be an array, etc.
3) Anything inside of swagger-ui should be referencing `this`.  So authorizations should be set directly through the swagger-ui object, not necessarily through window.authorizations.

We should make a mechanism so older deployments of swagger-ui can be compatible with the change, which might be setting window.authorizations = swaggerInstance.authorizations or something like that.

**Comment by mohsen1** [comment] 2015-03-04 22:11
What should we do for routing?

**Comment by fehguy** [comment] 2015-03-04 22:25
which aspect of routing are you talking about?

**Comment by mohsen1** [comment] 2015-03-04 22:31
the fragment routing. what happens when more than two swagger UI's are present in the document?

**Comment by fehguy** [comment] 2015-03-04 22:33
I would guess that maybe the dom-id (which is passed in initialization) would be the right way to do that

**Comment by mohsen1** [comment] 2015-03-04 22:38
ok. sounds good. So the route should always has the DOM id of the current SwaggerUI in the beginning

For example: 

```
http://localhost:8080/#!/swagger-ui-container/pet/addPet
```

**Comment by fehguy** [comment] 2015-03-04 23:53
i think that solves the multiple-dom issue.  it would break existing links.  Perhaps it can be part of the configuration, and without that option, it assumes top-level?

**Comment by mwcz** [comment] 2015-03-05 19:40
#781 was marked as a duplicate of this issue, so I wanted to ask: will the fix for this issue address the quantity of global variables currently in swagger, or is it focused on the `window.swaggerUi` global?

I ask because I'm attempting to embed swagger inside a page that uses RequireJS for dependency management, but swagger overwrites `window.require`, causing all sorts of mayhem.  I did some minor digging and it seems like it's coming from Shred's bundle, which incldues an AMD loader, which overwrites the `require` and `define` globals.  I can break "window.require conflict" off into a separate issue if desired.

**Comment by mohsen1** [comment] 2015-03-18 20:17
I've made a lot of changes to how `SwaggerUi` constructor function works. Now you can have multiple instance of `SwaggerUi` without having to have a global `swaggerUi` object. As of today those changes are in develop_2.0 branch.

**Closed by mohsen1** 2015-03-18 20:17 UTC
