### ISSUE TITLE
Reponse details to not take column width

### ISSUE THREAD

**Issue by Mykolas-Zenitech** [swagger-api/swagger-ui#5498] opened 2019-07-26 08:24 UTC
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142
 - Method of installation: npm
 - Swagger-UI version: 3.22.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

Swagger-UI configuration options:
```js
import React from "react";
import PropTypes from "prop-types";
import SwaggerUI from "swagger-ui-react";
import "swagger-ui-react/swagger-ui.css";

import apis from "../config/apis";

const Api = ({ match }) => {
  const api = apis.find(a => a.id === match.params.apiId);
  return <SwaggerUI url={api && api.oasUrl} />;
};

Api.propTypes = {
  match: PropTypes.shape({
    params: PropTypes.shape({
      apiId: PropTypes.string.isRequired
    }).isRequired
  }).isRequired
};
```
export default Api;
```jsx
import React from "react";
import { Navbar, Nav, NavDropdown } from "react-bootstrap";
import { BrowserRouter, Route } from "react-router-dom";
import Api from "./pages/Api";
import "./App.css";

import apis from "./config/apis";

export default () => (
  <BrowserRouter basename="/api-documentation-app">
    <Navbar bg="pp-dark" expand="lg" variant="dark">
      <Navbar.Brand href="/api-documentation-app">
        API Documentation
      </Navbar.Brand>
      <Navbar.Toggle aria-controls="basic-navbar-nav" />
      <Navbar.Collapse id="basic-navbar-nav">
        <Nav className="mr-auto">
          <NavDropdown title="API" id="basic-nav-dropdown">
            {apis.map(api => (
              <NavDropdown.Item
                key={api.id}
                href={`/api-documentation-app/api/${api.id}`}
              >
                {api.name}
              </NavDropdown.Item>
            ))}
          </NavDropdown>
        </Nav>
      </Navbar.Collapse>
    </Navbar>
    <Route path="/api/:apiId" exact component={Api} />
  </BrowserRouter>
);
```

### Describe the bug you're encountering
When I open API and try a method the response is displayed in very narrow column:
![image](https://user-images.githubusercontent.com/37137051/61937467-d37a5900-af86-11e9-808c-b0d307d5260c.png)

### To reproduce...

1. Go to API
2. Choose any method
3. Click try it out
4. Click execute
5. Error: ![image](https://user-images.githubusercontent.com/37137051/61937467-d37a5900-af86-11e9-808c-b0d307d5260c.png)

### Expected behavior
Response details should take all the column width space

### Screenshots
![image](https://user-images.githubusercontent.com/37137051/61937467-d37a5900-af86-11e9-808c-b0d307d5260c.png)

### Additional context or thoughts
I tweaked the CSS when live in Chrome and it worked.

**Comment by Mykolas-Zenitech** [comment] 2019-08-07 07:24
Any updates regarding this issue?

**Comment by thierrydallacroce** [comment] 2019-08-20 21:28
This seems to be a duplicate of #4574, for which I have an open PR. If approved and merged, this issue can most likely be closed.

**Closed** 2019-08-21 02:51 UTC

**Comment by Mykolas-Zenitech** [comment] 2019-09-02 05:25
I confirm this is being fixed now - thanks a lot!
