### ISSUE TITLE
only few api operations are shows in swagger ui

### ISSUE THREAD

**Issue by amitmawkin** [swagger-api/swagger-ui#2031] opened 2016-03-16 00:33 UTC
while viewing api documentation via swagger ui, only few operations are seen, though controller classes are in the same package for a spring boot application,

Any thoughts why this behaviour

**Comment by fehguy** [comment] 2016-03-16 01:18
Please share the swagger definition. It's impossible to help without it

**Comment by webron** [comment] 2016-03-16 03:17
If you have multiple operations under the same controller that only separated by query parameters, you may encounter this issue, which is not supported by the current version of the spec. As @fehguy mentioned, without swagger definition itself, it'd be impossible to know for sure, but the first step would be to check that it represents what you have in your code.

**Comment by amitmawkin** [comment] 2016-03-16 12:11
<img width="997" alt="screen shot 2016-03-16 at 8 08 04 am" src="https://cloud.githubusercontent.com/assets/6624821/13811841/aaee3b00-eb4e-11e5-8781-02c58cad625f.png">

**Comment by amitmawkin** [comment] 2016-03-16 12:14
Swagger definition




[swaggerdef.txt](https://github.com/swagger-api/swagger-ui/files/175927/swaggerdef.txt)

**Comment by amitmawkin** [comment] 2016-03-16 12:23
I don't see other api controllers that are in the same java package only few of them are picked by swagger ui which is puzzling,

**Comment by webron** [comment] 2016-03-16 15:10
swagger-ui simply takes the swagger spec you get from your app and renders it. If some controllers are missing, it doesn't necessarily mean there's an issue with swagger-ui but can also be that the generated spec doesn't contain them.

Looking at the swagger spec, do you see those missing controllers? If not, then swagger-ui is not the problem. If you do see them, can you point us to such an operation so we can further investigate?

**Comment by amitmawkin** [comment] 2016-03-16 15:14
yes i see a simple Ping-Controller in the output json returned from /v2/api-docs, but do not see it in ui for some reason.

**Comment by amitmawkin** [comment] 2016-03-17 21:25
i narrowed it down to a controller that has this piece of code which causes rest of the controller to not load in swagger
```
@RequestMapping(value = "/commit/github/v3", method = POST,
            consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<String> createGitHubv3(@RequestBody JSONObject request) throws ParseException, HygieiaException {
        String response = commitService.createFromGitHubv3(request);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(response);
    }
```

**Comment by webron** [comment] 2016-03-17 21:30
Regardless of this bug which shouldn't occur, it looks like there's an issue with Springfox (which I assume you're using to generate it).

It converts `JSONObject` to 
```json
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "object"
              }
            }
```
Which I assume is not what you want. Sounds like it should be:
```json
            "schema": {
              "type": "object",
              "additionalProperties": {
              }
            }
```

**Comment by amitmawkin** [comment] 2016-03-17 21:33
that's correct I am using springfox

**Comment by webron** [comment] 2016-03-17 21:35
Then you may want to check with them about this specific generation.

**Comment by brankoiliccc** [comment] 2016-03-20 01:23
Is there a solution for multiple operations under the same controller that are only separated by query parameters problem? I have 4 operations get by pageable/sorted/pageable-and-sorted etc..  Exmple : 

`@RequestMapping(params = { QueryConstants.PAGE, QueryConstants.SIZE }, method = RequestMethod.GET)
    @Secured(Privileges.CAN_USER_READ)
    @ApiOperation("find all - Paginated")
    public List<Resource> findAllPaginated(@RequestParam(value = QueryConstants.PAGE) final int page, @RequestParam(value = QueryConstants.SIZE) final int size, final UriComponentsBuilder uriBuilder, final HttpServletResponse response,Principal principal) {
    }`

Right now swagger2 only generates documentation for one operation (usually randomly chosen).

**Comment by webron** [comment] 2016-03-21 15:20
@brankoiliccc it is not supported by the current version of the spec, so no.

**Comment by ry4n-sc0tt** [comment] 2016-04-27 14:24
@brankoiliccc I have created a workaround for your issue, where I add a hash fragment to the path of endpoints that contain query parameters (or headers) in the `@RequestMapping`. I then modified `swagger-ui.js` to remove this hash fragment. It's not very elegant, but it works.

**Comment by cforce** [comment] 2016-06-08 00:32
@amitmawkin what was the cause an th solution at the end? I have the same issue

**Comment by thirupathi-redpinesignals** [comment] 2016-07-04 11:59
swagger generates UI elements in the alphabetical order. if there is one issue in the controller all other controller after that won't be displayed.  
Ex:  i forgot to all @RequestParam annotation to one method in the controller
<code>
(@RequestParam(defaultValue = "false") Boolean includeAsset,  Boolean includeNested)
</code>
Then rest of the controllers are stopped displaying

**Comment by ittaiyam** [comment] 2017-06-25 04:36
Any solution yet for multiple operations on the same controller that are separated by query parameters?

**Comment by webron** [comment] 2017-06-26 15:28
@ittaiyam it's not supported by the current version version of the spec, and will not be supported in the upcoming one either.

**Comment by tschiman** [comment] 2017-08-28 04:26
I would like the feature added where endpoints separated by query parameters show separately as well.

**Comment by webron** [comment] 2017-09-11 11:06
Closing as it doesn't seem to be an issue anymore in 3.X.

**Closed by webron** 2017-09-11 11:06 UTC

**Comment by Yasgur99** [comment] 2019-05-02 05:24
This is still an issue in 2.9.2

I have multiple GET methods on the same path that take different params but only one method shows in swagger ui, but is there in the api docs

**Comment by shockey** [comment] 2019-05-02 05:55
@Yasgur99 FYI, we're no longer working on or supporting the 2.x series of the UI.

**Comment by Yasgur99** [comment] 2019-05-02 05:57
@shockey, is there a 3.x version i can take advantage of?

**Comment by cmactian** [comment] 2019-05-13 14:55
Is this fixed in 3.x version?
