### ISSUE TITLE
Example Value sections shows nothing with oneOf models

### ISSUE THREAD

**Issue by pauldzy** [swagger-api/swagger-ui#4925] opened 2018-10-07 02:36 UTC
The Example Value section for a response shows a nice emulated construct using example values.
However when the schema contains a oneOf element then the Example Value merely shows "{}".

My feature request would be for the Example Value to render using the the first option of the oneOf element to create a reasonable example value.

Thanks.

 ```yaml
openapi: 3.0.0
info:
  title: foo
  version: 0.0.0
paths:
  /foo_norm:
    get:
      parameters:
        - $ref: '#/components/parameters/foo_parm'
      responses:
        default:
          $ref: '#/components/responses/foo_norm'
  /foo_anyOf:
    get:
      parameters:
        - $ref: '#/components/parameters/foo_parm'
      responses:
        default:
          $ref: '#/components/responses/foo_anyOf'
components:
  schemas:
    foo_norm:
      type: object
      properties:
        Results_norm:
           $ref: '#/components/schemas/foo_schema1'
    foo_anyOf:
      type: object
      properties:
        Results_anyOf:
           $ref: '#/components/schemas/foo_schema_anyOf'
    foo_schema_anyOf:
      oneOf:
        - $ref: '#/components/schemas/foo_schema1'
        - $ref: '#/components/schemas/foo_schema2'
    foo_schema1:
      type: object
      properties:
        Foo1:
          $ref: '#/components/schemas/foo_property1'
      required:
        - Foo
    foo_schema2:
      type: object
      properties:
        Foo2:
          $ref: '#/components/schemas/foo_property2'
      required:
        - Foo
    foo_property1:
      type: string
      example: Foo String
    foo_property2:
      type: number
      example: Foo Numba
  parameters:
    foo_parm:
      name: Foop
      in: query
      schema:
        type: number
  responses:
    foo_norm:
      description: foo norm
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/foo_norm'
    foo_anyOf:
      description: foo anyOf
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/foo_anyOf'
 ```

**Comment by hkosova** [comment] 2018-10-08 07:34
Thanks for the report! This issue is being tracked in #3803.

**Comment by shockey** [comment] 2018-10-09 18:58
Closing as a duplicate of #3803.

**Closed by shockey** 2018-10-09 18:58 UTC
