### ISSUE TITLE
Default view to "Model" rather than "Model Schema"

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-ui#1230] opened 2015-04-30 21:15 UTC
Make it possible to change the default view for an endpoint to  "Model" rather than "Model Schema".

The Model is far more informative and helpful than the schema.

It would be a matter of changing:
https://github.com/swagger-api/swagger-ui/blob/62546445d9a4c6a5680c9ebb8ade76f0893faf3a/src/main/javascript/view/SignatureView.js#L18

**Comment by ponelat** [comment] 2015-05-01 06:27
I guess that is a matter of taste, 
Although if it becomes something people would like to have we can create an option in the SwaggerUI object that would control the default. But again, it comes down to taste :smile:

**Comment by webron** [comment] 2015-05-03 09:39
@cancan101 - that's how it was originally but we changed it quite a few releases ago. As @ponelat mentioned, it's a matter of taste.

**Comment by seanpkps** [comment] 2015-11-19 20:01
I would definitely like to have the option to change the default.

**Comment by ponelat** [comment] 2015-11-20 08:06
+1 would accept a PR here, with the following..
- an option in  SwaggerUI 
- Note in the README
- build then commit all files.

**Comment by seanpkps** [comment] 2015-11-20 14:42
@ponelat - I should be able to make those changes

Do you know what change set altered the default (or can you point me to where the default is set)?
Knowing that would speed my work.

**Comment by ponelat** [comment] 2015-11-20 15:10
@seanpkps cool...
here is the line of code...
https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/SignatureView.js#L18

You might have to trace the model property upwards with some searching... 
This commit might help (has line in README and a simple option)
https://github.com/swagger-api/swagger-ui/commit/29a24c71136aef2e303d6dc3fda90ed1c97c8fe3

**Comment by seanpkps** [comment] 2015-11-20 20:26
@ponelat - I've put in the pull request ... the TravisCI tests seem to always be failing ... ? (I don't think that's caused by anything in my PR)

**Comment by ponelat** [comment] 2015-11-21 13:09
@seanpkps nope... not you :smile:
There is a webdriver issue. Apparently if I build with node.js 0.10 it fails... if I build with node.js 4.2.2 it works. Which means a node.js module that is getting browserified is faulty.. how meta is that?

**Comment by seanpkps** [comment] 2015-11-22 13:57
@ponelat - love it! hahaha

I'll look for feedback on the pull request - hopefully it'll be merged in soon :-)

**Comment by ponelat** [comment] 2015-12-09 05:29
This should have had a link to the PR... fixed in latest

**Closed by ponelat** 2015-12-09 05:29 UTC
Labels: Feature
