### ISSUE TITLE
nickname:"models" crash

### ISSUE THREAD

**Issue by thomassuckow** [swagger-api/swagger-ui#1072] opened 2015-03-25 18:42 UTC
When an operation has the nickname "models" the swagger ui crashes on 

swagger-client.js:1985
```
results.push(model.setReferencedModels(this.models));
```

with setReferencedModels undefined

**Comment by mohsen1** [comment] 2015-03-25 19:18
Duplicate of #802

**Closed by mohsen1** 2015-03-25 19:18 UTC
