### ISSUE TITLE
RequestBody with 'x-www-urlencoded' render error

### ISSUE THREAD

**Issue by wsw0108** [swagger-api/swagger-ui#7210] opened 2021-04-26 06:34 UTC
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version: 89
 - Method of installation: dist assets
 - Swagger-UI version: 3.47.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: "test"
  version: 1.0.0
paths:
  /test:
    post:
      requestBody:
        description: "test"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/Message'
            encoding:
              data:
                contentType: application/json
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Message:
      type: object
      properties:
        text:
          type: string

```

Swagger-UI configuration options:
using https://editor.swagger.io/
```js
SwaggerUI({
  // your config options here
})
```

### To reproduce...

1. Click "Try it out" with content type 'application/x-www-form-urlencoded'
2. See error

### Expected behavior

The edit textarea should fill with default value when select content type 'application/json'.

### Screenshots

![image](https://user-images.githubusercontent.com/4977975/116038582-363cdf00-a69c-11eb-9dc7-4bfb4a6c6ff0.png)

![image](https://user-images.githubusercontent.com/4977975/116038604-3c32c000-a69c-11eb-8a06-fa810a75ab3a.png)

**Comment by hkosova** [comment] 2021-05-20 10:49
Duplicate of #7268.

**Closed by hkosova** 2021-05-20 10:49 UTC

**Comment by tim-lai** [comment] 2021-06-10 17:49
Here's a fixed definition that works for me in https://editor.swagger.io:
```yaml
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
```

Note that the screenshot above is not a render error, because the schema type and properties in the operation takes precedence over the component schema.
