### ISSUE TITLE
Why use globals?

### ISSUE THREAD

**Issue by MattiSG** [swagger-api/swagger-ui#781] opened 2014-12-16 16:33 UTC
This library seems to be relying on a large amount of [globals](https://github.com/swagger-api/swagger-ui/blob/329772af4c6b70f37e7535ed1d675fa6d9972c04/dist/lib/swagger-oauth.js#L10) to function. This is surprising, as leaking state-holding variables in the global namespace is most often considered [bad practice](http://www.w3.org/wiki/JavaScript_best_practices#Avoid_globals), for it leads to potential conflicts with other libraries and decreased maintainability.

However, this practice seems absolutely conscious and voluntary in this project, as these variables are prefixed with `window.` to expose them globally on the browser.

As this practice makes me extremely wary of including the library as it is, I would like to know what is the rationale for exposing so many globals (and requesting clients to do so too).

**Comment by MattiSG** [comment] 2015-01-04 14:37
@fehguy Does adding the “Feature” tag mean removing globals is an expected feature?

**Comment by fehguy** [comment] 2015-01-29 00:55
@MattiSG it means we're going to look into it during that milestone but in general being assigned to a milestone doesn't mean we are for sure going to do it.  But in this case, yes, it will be fixed.

reference https://github.com/swagger-api/swagger-js/issues/178

**Comment by timstott** [comment] 2015-02-25 21:33
Hello fellow swagger-ui folks!
I've just come across a use case where using globals breaks swagger-ui pensive:. That is have multiple instances of `swaggerUi` on the same page. I wish to aggregate multiple swagger apis in one page.

I did a very quick spike at removing globals but it wasn't enough timstott/swagger-ui@9070972. Partial success (or failure :smile:).
I would help but unfortunately I'm not familiar with coffee script at all.

:+1: to allow instantiating multiple SwaggerUi object. (also swagger-ui is awesome, thank you for the great work)

**Comment by MattiSG** [comment] 2015-02-25 21:37
@timstott That's obviously the main conflictual case. I solved this by resolving to `iframe`, FWIW.

**Comment by fehguy** [comment] 2015-02-26 18:51
Yes understood, this fix is slated for the m2 release.

**Comment by mohsen1** [comment] 2015-03-04 21:31
This duplicate of #851

I think for now using `<iframe>` is the best option

**Closed by mohsen1** 2015-03-04 21:31 UTC
Labels: Feature
