### ISSUE TITLE
swagger-ui not resolving $ref path parameter correctly

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#816] opened 2015-01-08 16:54 UTC
swagger-ui is not resolving $ref parameters in a method

Given this swagger.json:
```
{
    "swagger": "2.0",
    "info": {
        "title": "Swagger issue example",
        "version": "1"
    },
    "host": "www.example.com",
    "basePath": "/api",
    "schemes": [ "http"  ],
    "paths": {
        "/models/{modelId}": {
            "get": {
                "summary" : "Get a model resource",
                "produces": [ "application/json" ],
                "responses": {
                    "200": {
                        "description": "return a specific model"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "parameters": [
                    {
                        "$ref": "#/parameters/modelId"
                    }
                ]
            }
        }
    },
    "parameters": {
        "modelId" : {
            "name": "modelId",
            "in": "path",
            "type": "string",
            "required": true,
            "description": "The unique id of a model resource."
        }

    }

}
```

the UI does not pull in the parameter description nor inject the value into the path.
See the screenshot:

![swagger-ref-parameter](https://cloud.githubusercontent.com/assets/545944/5666229/3c761d90-972c-11e4-850b-732e59291f05.png)

I also tried `{"$ref" : "modelId" }` but that also did not work.

If I code the parameter inline, it works:

```
{
    "swagger": "2.0",
    "info": {
        "title": "Swagger issue example",
        "version": "1"
    },
    "host": "www.example.com",
    "basePath": "/api",
    "schemes": [ "http"  ],
    "paths": {
        "/models/{modelId}": {
            "get": {
                "summary" : "Get a model resource",
                "produces": [ "application/json" ],
                "responses": {
                    "200": {
                        "description": "return a specific model"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "parameters": [
                    {
                        "name": "modelId",
                        "in": "path",
                        "type": "string",
                        "required": true,
                        "description": "The unique id of a model resource."
                    }
                ]
            }
        }
    }

}
```

as shown here:

![swagger-inline-parameter](https://cloud.githubusercontent.com/assets/545944/5666233/429b1c5c-972c-11e4-815a-6630ddbd9729.png)

I'm using the latest swagger-ui pulled from this repo today.

See the related closed issues, https://github.com/swagger-api/swagger-editor/issues/182
and https://github.com/apigee-127/swagger-tools/issues/79

**Comment by webron** [comment] 2015-01-08 17:03
This is a duplicate of #621.

**Closed by webron** 2015-01-08 17:03 UTC
