### ISSUE TITLE
Callbacks are not expanding

### ISSUE THREAD

**Issue by mbusatta** [swagger-api/swagger-ui#3921] opened 2017-11-16 21:53 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 3.0
| Which Swagger-UI version?       |  latest
| How did you install Swagger-UI? | using it via editor.swagger.io
| Which browser & version?        | firefox 56.0.2 (64 bit) / but not working in none of other browsers, I've tried chrome and IE
| Which operating system?         |  Windows 7

### Demonstration API definition

```yaml
openapi: 3.0.0
info:
  title: A simple webhook subscription
  version: 1.0.0
paths:
  /subscribe:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
      responses:
        '201':
          description: Created subscription to webhook
      callbacks:
        mainHook:
          '$request.body#/url':
            post:
              responses:
                '200':
                  description: webhook successfully processed
```

### Expected Behavior

Callbacks should be able to expand when I click in some operation.

### Current Behavior

Not able to expand any callback, so I cannot see the details of the operation like requests, reponses, etc.

**Comment by webron** [comment] 2017-11-16 22:21
Thanks for the report. While the issue is in the UI, we have a similar issue opened in the editor, and since that was opened first (and is already assigned to be fixed), I'll close this one as duplicate.

For reference - https://github.com/swagger-api/swagger-editor/issues/1565

**Closed by webron** 2017-11-16 22:21 UTC
