### ISSUE TITLE
Example dissapear

### ISSUE THREAD

**Issue by SurapatNJ** [swagger-api/swagger-ui#6221] opened 2020-07-10 02:26 UTC
#5095 # Q&A (please complete the following information)
 - OS: [Window]
 - Browser: [Chrome]
 - Version: [22]
 - Method of installation: [npm]
 - Swagger-UI version: [3.10.0]
 - Swagger/OpenAPI version: [Swagger 2.0]

### Content & configuration
    "/API/login" : {
      "post" : {
        "tags":["authentication"],
        "consumes" : [ "application/json" ],
        "produces" : [ "text/html" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/Model15"
          },
          "x-examples" : {
            "application/json" : "{\n    \"username\" : \"admin\",\n    \"password\" : \"1234\"\n}"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Definition generated from Swagger Inspector",
            "schema" : {
              "type" : "string"
            }
          }
        }
      }
    },

### Screenshots

![image](https://user-images.githubusercontent.com/33492586/87109612-575c4c80-c28f-11ea-8313-454d37f2eb5c.png)

### How can we help?

I want to know the reason x-examples is not showing up on the site

**Comment by hkosova** [comment] 2020-07-10 14:44
Duplicate of #3233.

**Closed by hkosova** 2020-07-10 14:44 UTC
