### ISSUE TITLE
@ApiModelProperty Map[string,classname] does not include required model for classname

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-ui#1002] opened 2015-03-05 20:00 UTC
Using latest 1.5.2-M1 core and 2.1.8 UI, swagger-ui does not include the required model in the response class section. In this case, the returned model Host, should had it's inner class Disk included in the response and "disks (object, optional): disk" should be "disks (Map[Disk], optional): disk"

Code:
```java
    @ApiModel
    public class Host {
        @ApiModelProperty(value = "disks", dataType =
        "Map[string,com.foo.model.Host$Disk]")
        private DiskMap disks;

        @ApiModel(description = "disk attributes")
        public static class Disk implements Serializable {
            @ApiModelProperty("disk selected")
            private boolean selected;
            @ApiModelProperty("disk size")
            private String size;
        }
    }
```
and output spec:
```js
    Host:  {
       properties: {
           disks: {
               type: "object",
               description: "disks",
               additionalProperties: {
                   $ref: "#/definitions/Disk"
               }
            }
       }
    },
    Disk: {
        properties: {
            selected: {
                type: "boolean",
                description: "disk selected"
            },
            size: {
                type: "string",
                description: "disk size"
            }
        },
        description: "disk attributes"
    }

**Comment by webron** [comment] 2015-03-05 20:18
@todd-richmond - this is a duplicate of your own issue #913  ;) There's just no support for maps yet.

**Comment by todd-richmond** [comment] 2015-03-05 20:42
oops - sorry - I remembered writing the bug about List[string] appearing as an object as well, but completely forgot about this one. I had several inconsistencies in my annotations and noticed this again once everything was standardized

This bug has actual example code, but you can close either

**Comment by webron** [comment] 2015-03-05 20:43
Let's close this one, and if you can, please share the relevant information there.

**Closed by webron** 2015-03-05 20:43 UTC
Labels: swaggger-js
