### ISSUE TITLE
[IE10/IE11] body parameter with required true sets its value to (required)

### ISSUE THREAD

**Issue by aurelian** [swagger-api/swagger-ui#1044] opened 2015-03-18 15:30 UTC
In IE10 / IE 11 ```required``` for ```body``` parameter sets textarea value to ```(required)``` -- value of placeholder. This also prevents ```Click to set as parameter value``` for ```Model Schema``` to be copied.

Somehow I think [it's a known problem in IE10-11](https://connect.microsoft.com/IE/feedback/details/811408/ie10-11-a-textareas-placeholder-text-becomes-its-actual-value-when-using-innertext-innerhtml-or-outerhtml)

Added a screenshot of an IE11 running on Win 10:

![screen shot 2015-03-18 at 16 37 41](https://cloud.githubusercontent.com/assets/350/6712536/5b6ae1c6-cd8d-11e4-88b1-4b615471749a.png)

**Comment by mohsen1** [comment] 2015-03-18 19:23
Are you using develop_2.0 branch?

**Comment by aurelian** [comment] 2015-03-19 11:11
Same happens with the "official" and AFAIK stable swagger-ui as seen on petsore.swagger.io. No idea what branch is that using

![screen shot 2015-03-19 at 11 52 12](https://cloud.githubusercontent.com/assets/350/6728984/9938215c-ce2e-11e4-9f02-3030f74be3bc.png)

I'm using this swagger spec: https://gist.github.com/aurelian/a8718157fb5aa687c495.

For your convenience: 
http://petstore.swagger.io/?url=https://gist.githubusercontent.com/aurelian/a8718157fb5aa687c495/raw/3f05c1aa5bc2bffdc6fdcaf37c4ed6d20a82ec62/petstore-swagger-v2.json

**Comment by mohsen1** [comment] 2015-03-19 17:30
@aurelian I don't have IE to try develop_2.0 in it. Could you clone the repo and try develop 2.0 with IE11?

**Comment by aurelian** [comment] 2015-03-23 16:19
Sorry, I didn't had time to check this yet, I'll let you know. Meanwhile you can get an IE box for free from [modern.ie](http://modern.ie/).

**Comment by mohsen1** [comment] 2015-03-27 00:16
I can't reproduce in develop_2.0 branch at 3de0b36
![screen shot 2015-03-26 at 5 15 10 pm](https://cloud.githubusercontent.com/assets/543633/6859869/b1d6541a-d3db-11e4-9c9e-6f0357f404a2.png)

**Comment by aurelian** [comment] 2015-03-27 10:36
Sure, the body parameter has to be required, from your screenshot it doesn't look like it is.

> I'm using this swagger spec: https://gist.github.com/aurelian/a8718157fb5aa687c495.

![screen shot 2015-03-27 at 11 35 25](https://cloud.githubusercontent.com/assets/350/6866128/7b0a4b54-d475-11e4-9503-a7f3ea8dcbce.png)

@mohsen1 can you reopen this?

**Comment by mohsen1** [comment] 2015-03-27 18:05
You might be using an older version of Swagger UI. body parameter of `POST` `/pet` is required.

http://petstore.swagger.io/v2/swagger.json

Please confirm you're using develop_2.0 branch

**Comment by webron** [comment] 2015-03-27 18:06
@mohsen1 -

```js
"/pet": {

    "post": 

{

    "tags": 

[

    "pet"

],
"summary": "Add a new pet to the store",
"description": "",
"operationId": "addPet",
"consumes":
[

    "application/json",
    "application/xml"

],
"produces":
[

    "application/xml",
    "application/json"

],
"parameters":
[

{

    "in": "body",
    "name": "body",
    "description": "Pet object that needs to be added to the store",
    "required": false,
    "schema": 

        {
            "$ref": "#/definitions/Pet"
        }
    }

],
```
...

**Comment by webron** [comment] 2015-03-27 18:21
Reopening as body parameter of `POST` `/pet

**Comment by fehguy** [comment] 2015-03-28 01:40
@whitlockjc what did we end up with on this?  Last I saw IE was throwing up for default values.

**Comment by whitlockjc** [comment] 2015-03-28 04:58
We talked about it in IRC and agreed there is nothing we can do about it to work around it without changing how we display required fields or making matters worse.  I suggested we punt to 2.1.

**Comment by fehguy** [comment] 2015-03-28 05:12
Is the UI functional but missing the (required) denotation?  Or is the UI busted in IE?

**Comment by whitlockjc** [comment] 2015-03-28 13:19
The UI is fine you just can't click the button to copy the sample to the body textarea without first removing the text in the textarea.

**Comment by fehguy** [comment] 2015-05-08 21:04
This is a limitation in IE.  Closing the issue.

**Closed by fehguy** 2015-05-08 21:04 UTC
Labels: Bug, P3
