### ISSUE TITLE
Delete query array fields

### ISSUE THREAD

**Issue by albertotn** [swagger-api/swagger-ui#4736] opened 2018-07-17 09:54 UTC
### Q&A (please complete the following information)
 - OS: Windows 10, version 1803, 
 - Browser: Firefox 
 - Version: 61.0.1
 - Method of installation: indirectly by https://mvnrepository.com/artifact/org.webjars/swagger-ui/3.17.3
 - Swagger-UI version: 3.17.3
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
If I generate server with java-resteasy and client with typescript-angular, when client call server the working way to delete a resource with list of ids is:

`curl -X DELETE "https://localhost:8080/rest/test/?idCampi=1&idCampi=2" -H  "accept: application/json"`

but from swagger-ui the generated call is 

`curl -X DELETE "https://localhost:8080/rest/test/?idCampi=1,2" -H  "accept: application/json"`

that is not working with java-resteasy as server and typescript-angular as client.

Example Swagger/OpenAPI definition:

```yaml
swagger: "2.0"
info:
  version: "1.0"
  title: "TEST"  
basePath: "/rest"
host: localhost:8080
paths: 
  /test/:
    delete:
      produces:
      - "application/json"  
      parameters:
       - name: "id"
         in: query
         description: "array of id"
         required: true
         type: array
         items: 
           type: "integer"
           format: "int64"
      responses:
        200:
          description: "test response"
          schema:
            type: "string"

```

Swagger-UI configuration options:

no config

### Describe the bug you're encountering
From swagger-ui is not possible to delete a list of resources using array of element, because generated querystring is not generated and parsed correctly from java and angular.

### To reproduce...

1. Go to https://editor.swagger.io
2. import provided yaml
2. generate resteasy server, extract and run mvn install, then mvn tomcat:run
3. run provided curl on localhost, changing server context

### Expected behavior
I expect the same behaviour from swagger-ui and generated client and server

### Screenshots
no screenshoot

### Additional context or thoughts
Update: opened issue here: https://github.com/swagger-api/swagger-codegen/issues/8439

**Comment by hkosova** [comment] 2018-07-17 10:59
The default format for array parameters is [`collectionFormat: csv`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterCollectionFormat) so the request in Swagger UI is correct. The issue is with the code generators, it looks like they are using `collectionFormat: multi` as the default format. Please open a ticket in the Swagger Codegen repository https://github.com/swagger-api/swagger-codegen/issues.

**Comment by albertotn** [comment] 2018-07-17 11:35
Done, thanks @hkosova

**Comment by shockey** [comment] 2018-07-18 22:34
Closing!

**Closed by shockey** 2018-07-18 22:34 UTC
