### ISSUE TITLE
Array item type is displayed incorrectly

### ISSUE THREAD

**Issue by artemananiev** [swagger-api/swagger-ui#5328] opened 2019-04-25 22:41 UTC
Environment:

 - OS: Mac OS X
 - Browser: Firefox
 - Method of installation: dist
 - Swagger-UI version: 3.22.1
 - Swagger/OpenAPI version: 3.0.2

Spec fragment:

```
components:
  schemas:
    registryItem:
      description: >-
        Registration
      type: object
      properties:
        region:
          $ref: "#/components/schemas/region"
        serviceType:
          $ref: "#/components/schemas/serviceType"
        url:
          type: string
          format: uri
          description: >-
            IA v1 API entry point
      required:
        - region
        - serviceType
        - url
    registryItemList:
      description: >-
        A list of IA registrations
      type: array
      items:
        $ref: "#/components/schemas/registryItem"
```

So there are two schemas, registryItem and registryItemList. The latter is an array of the former. However, in UI registryItemList is shown as an array of registryItemList - see the screenshot:

![registryItemList](https://user-images.githubusercontent.com/33361937/56772835-747f2b00-6770-11e9-8eb0-7a3baa7fb605.jpg)

It should display `registryItem` instead of `registryItemList` in the outlined rectangle.

**Comment by hkosova** [comment] 2019-08-07 11:15
Duplicate of #5276.

**Comment by webron** [comment] 2019-08-07 15:25
Closing as duplicate.

**Closed by webron** 2019-08-07 15:25 UTC
