### ISSUE TITLE
'parameters' field defined in 'Path Item Object' doesn't work as expected

### ISSUE THREAD

**Issue by sitnikovme** [swagger-api/swagger-ui#1582] opened 2015-09-07 11:45 UTC
Checked with http://petstore.swagger.io/

this works:

```yaml
paths:
  /api/v1/user/sessions:
    get:
      summary: 'Session list'
      security:
      - auth_header: []
      parameters:
      - $ref: '#/parameters/my_header'
      - $ref: '#/parameters/paramx'
      responses:
        200:
          $ref: '#/responses/ok'
```

but this doesn't (can't see field to enter parameters values):

```yaml
paths:
  /api/v1/user/sessions:
    parameters:
    - $ref: '#/parameters/my_header'
    - $ref: '#/parameters/paramx'
    get:
      summary: 'Session list'
      security:
      - auth_header: []
      responses:
        200:
          $ref: '#/responses/ok'
```

**Comment by webron** [comment] 2015-09-09 07:05
Duplicate of #1118.

**Closed by webron** 2015-09-09 07:05 UTC
