### ISSUE TITLE
allOf nesting is causing issues in the rendering

### ISSUE THREAD

**Issue by phani1kumar** [swagger-api/swagger-ui#1412] opened 2015-06-25 10:38 UTC
I've created a modified version of allOf "petstore-expanded" example. This is not showing the expected behavior in UI. 

The GET and POST methods are supposed to have different schema, but the UI shows the same schema. POST method should not have the "id" attribute and it has. GET method response schema should not have the "Classification", but it has. 
![petstore](https://cloud.githubusercontent.com/assets/9419954/8353501/445e700c-1b5c-11e5-954a-6c700a974306.png)

Updated "petstore-expanded: example can be found at : "https://github.com/phani1kumar/swagger-spec/blob/master/examples/v2.0/json/petstore-expanded.json"

**Comment by tkatkov** [comment] 2015-07-01 21:50
Second that. 
Model which has allOf somehow injects its additional attributes into the model which is included usin allOf.

**Comment by devigned** [comment] 2015-09-01 15:22
Duplicate of #723

**Comment by fehguy** [comment] 2015-09-05 07:36
@phani1kumar I've verified your spec in swagger-ui 2.1.2 and don't see the issue.  See screenshots--i'll close this but please reopen if you're still having issues.

<img width="979" alt="screen shot 2015-09-05 at 12 35 10 am" src="https://cloud.githubusercontent.com/assets/249413/9698331/13f67cba-5366-11e5-8574-8eeeceb0518e.png">
<img width="973" alt="screen shot 2015-09-05 at 12 35 20 am" src="https://cloud.githubusercontent.com/assets/249413/9698332/18264cfc-5366-11e5-9494-89926cdc9494.png">

**Closed by fehguy** 2015-09-05 07:36 UTC
