### ISSUE TITLE
$ref definition does not work in structures nested to more then one level

### ISSUE THREAD

**Issue by tlbdk** [swagger-api/swagger-ui#1003] opened 2015-03-05 20:18 UTC
This is a continuation of #934, nested $ref $ref definition does not work in structures nested to more then one level.

![image](https://cloud.githubusercontent.com/assets/11635/6513700/289a9120-c37d-11e4-9899-066a4c178a45.png)

Sample showing the issue:
```js
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test sample showing swagger error",
        "description": "Show that $ref to the same definition only works to a certain level",
        "contact": {
            "name": "Troels Liebe Bentsen",
            "email": "tlb@nversion.dk"
        }
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Test",
                "description": "Test stuff",
                "operationId": "doTest",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/test"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test stuff response",
                        "schema": {
                          "$ref": "#/definitions/test"
                        }
                    },
                    "405": {
                        "description": "Invalid input"
                    }
                },
                "tags": ["test"]
            }
        }
    },
    "definitions": {
        "test": {
            "required": [
                "test1"
            ],
            "properties": {
                "test1": {
                    "$ref": "#/definitions/badgerfishstring"
                },
                "test2": {
                    "$ref": "#/definitions/badgerfishstring"
                },
                "test3": {
                    "$ref": "#/definitions/testNested"
                }
            }
        },
        "testNested": {
            "required": [
                "test4"
            ],
            "properties": {
                "test4": {
                    "$ref": "#/definitions/badgerfishstring"
                },
                "test5": {
                    "$ref": "#/definitions/badgerfishstring"
                },
                "test3": {
                    "$ref": "#/definitions/testMoreNested"
                }
            }
        },
        "testMoreNested": {
            "required": [
                "test6"
            ],
            "properties": {
                "test6": {
                    "$ref": "#/definitions/badgerfishstring"
                },
                "test7": {
                    "$ref": "#/definitions/badgerfishstring"
                }
            }
        },
        "badgerfishstring": {
            "required": [
                "$"
            ],
            "properties": {
                "$": {
                  "type": "string"
                }
            }
        }
    }
}
```

**Comment by Smolations** [comment] 2015-03-06 17:22
This may also be a duplicate of #975. I'm sure this issue and the other two mentioned are all related...

**Comment by mohsen1** [comment] 2015-03-16 21:12
This is still an issue in develop_2.0

@whitlockjc please take a look at how we resolve refs in swagger-js

Here is a better example to reproduce this issue:

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GrandParent'
definitions:
  GrandParent:
    type: object
    properties:
      Parent:
        $ref: '#/definitions/Parent'
  Parent:
    type: object
    properties:
      Child:
        $ref: '#/definitions/Child'
  Child:
    type: object
    properties:
      name:
        type: string
```

**Comment by mohsen1** [comment] 2015-03-16 21:30
Please follow this issue here:
https://github.com/swagger-api/swagger-js/issues/270

**Closed by mohsen1** 2015-03-16 21:30 UTC
Labels: swaggger-js

**Comment by jchenry** [comment] 2016-02-04 18:50
was this ever fixed/implemented?
