### ISSUE TITLE
Swagger UI endless loading

### ISSUE THREAD

**Issue by noam1610** [swagger-api/swagger-ui#6259] opened 2020-07-23 12:47 UTC
Hi,

I am currently facing an issue with my browser (last chrome version: 84.0.4147.89) rendering swaggers ui.
No matter how I am rendering it (from my localhost or already running live examples in the web), the UI doesn't behave the right way.

The UI is getting stuck on that (endless loading)

<img width="1656" alt="Screen Shot 2020-07-23 at 15 39 48" src="https://user-images.githubusercontent.com/8570784/88287334-d2474d80-ccfa-11ea-9403-954a3e109b8e.png">

What's more, when clicking on a route, the route move on to the upper banner:
For example with this link https://fastapi-realworld-example-app.herokuapp.com/docs
You can see below that all these routes don't belong to *default* but after clicked, it is under the default.
<img width="1576" alt="Screen Shot 2020-07-23 at 15 45 34" src="https://user-images.githubusercontent.com/8570784/88287867-995ba880-ccfb-11ea-9899-ecc80d111beb.png">

Thank you

**Comment by hkosova** [comment] 2020-07-23 12:59
This is a duplicate of #6249 which was fixed in v. 3.30.2.

**Closed by hkosova** 2020-07-23 12:59 UTC

**Comment by dimylkas** [comment] 2020-12-08 21:41
Hi @hkosova,

I have the same issue with { ...version: "3.33.0" }.

Could you please re-check the version where the issue has been fixed?

Regards,
Dmytro
