### ISSUE TITLE
Couldn't find package "@swagger-api/apidom-core@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.

### ISSUE THREAD

**Issue by ReviewSolicitors** [swagger-api/swagger-ui#8418] opened 2023-02-24 11:26 UTC
- OS: macOS
 - Browser: n/a
 - Version: n/a
 - Method of installation: yarn
 - Swagger-UI version: 4.16.0
 - Swagger/OpenAPI version: n/a

### Content & configuration
package.json
```
dependencies: {
    ...
    "swagger-ui-react": "^4.12.0",
    ...
}
```

Since the 4.16.0, when installing swagger-ui-react via yarn it fails with the following output. Installing with 4.15.5 specified works fine.

```
error Couldn't find package "@swagger-api/apidom-core@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@swagger-api/apidom-ns-openapi-3-1@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@swagger-api/apidom-reference@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@swagger-api/apidom-json-pointer@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.19/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### To reproduce...
Run yarn install with ` "swagger-ui-react": "^4.16.0"` as a dependency.

### Additional context or thoughts
Possibly the dependencies are incorrectly pointing to beta releases?

**Comment by sennyeya** [comment] 2023-02-24 20:15
Looks like the `bundleDependencies` used to include the Github package registry packages, `@swagger-api/apidom-core`, `@swagger-api/apidom-reference`, ..., isn't supported by Yarn 2.x. https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies and https://github.com/yarnpkg/yarn/issues/5998#issuecomment-753673170.

**Comment by char0n** [comment] 2023-02-25 16:42
Hi everybody,

Thanks for detailed report. I can confirm the regression. I'll create a reverting commit and subsequent release.

---

### Background

We're in the process of implementing OpenAPI 3.1.0 support in SwaggerUI. The processing of OpenAPI 2.0/3.0.x/3.1.0 comes from swagger-client library. swagger-client is current in latest beta phase - https://github.com/swagger-api/swagger-js/pull/2836. We wanted to make sure that we can use latest swagger-client beta (with OpenAPI 3.1.0 support) in completely backward compatible way with SwaggerUI. We decided to use `bundleDependencies` field of `package.json` to avoid publishing ApiDOM to npm and expedite the support for OpenAPI 3.1.0 as fast as possible. 

Given this issue, we now know that AFAICT `yarn@2` is the only npm package manager that doesn't support `bundleDependencies`. Also given that `yarn@2` is still highly used package manager we must support it fully. This means that ApiDOM must be published to npmjs.com so that `yarn@2` can process swagger-client package (with ApiDOM as transitive deps) in fully backward compatible way.

**Comment by char0n** [comment] 2023-02-25 18:21
Fix released in https://github.com/swagger-api/swagger-ui/releases/tag/v4.16.1

**Closed by char0n** 2023-02-25 18:21 UTC
Labels: type: regression, version: 4.x
