### ISSUE TITLE
Swagger UI - React App - Petstore

### ISSUE THREAD

**Issue by r-ising** [swagger-api/swagger-ui#4363] opened 2018-03-23 16:46 UTC
Hello,

I created a small react app with swagger ui:

https://github.com/r-ising/SwaggerCustomLayout

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.13.0
| How did you install Swagger-UI? | npm install swagger-ui
| Which browser & version?        | Chrome 64
| Which operating system?         | macOS

### Demonstration API definition

http://petstore.swagger.io/v2/swagger.json

### Expected Behavior

GET /pets/{petId} should be work with an integer as petId

### Current Behavior

petId will be deleted without an error

### Possible Solution

Downgrade to Swagger UI v3.10 then it works fine

### Context

I would like to create a custom layout for the react ui.

**Comment by shockey** [comment] 2018-04-07 02:25
Hey @r-ising! Looks like this is being caused by `react@16` being used in SwaggerCustomLayout :smile: you should be able to safely step down to `react@15` in your application to sidestep this.

I'm going to keep this open, so we can address the compatibility issue in the future.

**Comment by shockey** [comment] 2018-04-07 02:25
CC: https://github.com/swagger-api/swagger-ui/issues/3158

**Comment by r-ising** [comment] 2018-04-19 09:06
Hey @shockey,

thanks with react 15 it works better, but now i get an new error with the petstore:

`Warning: Failed prop type: The prop `className` is marked as required in `a`, but its value is `undefined`.
    in a (created by n)
    in n (created by t)
    in div (created by t)
    in div (created by t)
    in t (created by t)
    in section (created by t)
    in t (created by t)
    in div (created by t)
    in t (created by t)
    in div (created by t)
    in div (created by t)
    in t (created by r)
    in r (created by Connect(r))
    in Connect(r) (at CustomLayout.js:17)
    in div (at CustomLayout.js:13)
    in CustomLayout (created by r)
    in r (created by Connect(r))
    in Connect(r) (created by t)
    in t (created by r)
    in r (created by Connect(r))
    in Connect(r) (created by r)
    in Provider (created by r)
    in r`

CustomerLayout.js Line 17: <BaseLayout />

Is this a problem of the custom template too?

**Comment by shockey** [comment] 2018-04-19 21:32
@r-ising, this is probably something internal to Swagger-UI, not your custom layout. I'll look into it for you :smile:

**Comment by shockey** [comment] 2018-04-19 21:40
@r-ising, just noticed and merged your PR which fixes this issue (https://github.com/swagger-api/swagger-ui/issues/4457) - closing!

**Closed by shockey** 2018-04-19 21:40 UTC
Labels: cat: try-it-out, type: bug

**Comment by snehaa** [comment] 2018-06-25 22:22
@shockey I am having the same issue. IF I use swagger-ui latest input param gets deleted and ui shows an error on the required field. If I use have a default value then only the default value is used while triggering the API, inputing any other value in the input box is not reflected in the API.

But when I downgrade Swagger ui to v3.10 it worked properly. But then I miss on the lates enhancements in Swagger UI. 

React version used: 16.3.17 and I cannot downgrade React version as I am using Electrode Js which controls the react version http://www.electrode.io

**Comment by shockey** [comment] 2018-06-26 04:40
@snehaa, unfortunately, we only officially support `react@15` for the time being 😬  See [`epic: usage in react@16`](https://github.com/swagger-api/swagger-ui/labels/epic%3A%20usage%20in%20react%4016) for more context.
