### ISSUE TITLE
The Word "nodeType" is a keywords? 

### ISSUE THREAD

**Issue by SpringStudent** [swagger-api/swagger-ui#2689] opened 2017-02-23 09:35 UTC
When the request's path has "nodeType" the request can't  be correctly call, this is a Bug?
![bug](https://cloud.githubusercontent.com/assets/14833956/23253155/731f7bee-f9ee-11e6-8e62-8221c681fa8c.png)

**Comment by fehguy** [comment] 2017-02-23 15:25
Duplicate of #1691

**Closed by fehguy** 2017-02-23 15:25 UTC
