### ISSUE TITLE
Swagger-ui does not display response description for the 200 response

### ISSUE THREAD

**Issue by rhduwe** [swagger-api/swagger-ui#1533] opened 2015-08-12 13:15 UTC
An example may be seen in the petstore example. Here is a part of the swagger.json:

```
"/user/{username}": {
			"get": {
				"tags": ["user"],
				"summary": "Get user by user name",
				"description": "",
				"operationId": "getUserByName",
				"produces": ["application/xml",
				"application/json"],
				"parameters": [{
					"name": "username",
					"in": "path",
					"description": "The name that needs to be fetched.",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/User"
						}
					},
					"400": {
						"description": "Invalid username supplied"
					},
					"404": {
						"description": "User not found"
					}
				}
			},
```
A description is specified for the response, however it is not displayed anywhere on the [page](http://petstore.swagger.io/#!/user/getUserByName)

**Comment by webron** [comment] 2015-08-12 13:22
Duplicate of #1476.

**Closed by webron** 2015-08-12 13:22 UTC
