### ISSUE TITLE
Use markdown in Model descriptions

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3175] opened 2017-06-02 12:18 UTC
Can we get Markdown ( CommonMark?) support in Model description :)

![image](https://cloud.githubusercontent.com/assets/8438485/26725299/2670fd4c-479e-11e7-8f59-830ab539a54c.png)

```yaml
swagger: '2.0'

info:
  version: 0.0.0
  title: title
  description: description

paths: {}

definitions:
  One:
    type: object
    description: This should be *markdown*
```

Version: `Object {swaggerEditor: "3.0.10/gb2e3da6-dirty", swaggerUi: "3.0.9/ga068f78"}`

**Comment by webron** [comment] 2017-06-05 19:20
Duplicate of #2745.

**Closed by webron** 2017-06-05 19:20 UTC
Labels: 3.x, Bug
