### ISSUE TITLE
"No operations defined in spec!" When loading YAML file

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-ui#2752] opened 2017-03-20 22:53 UTC
Trying to load documents in the swagger UI like this with the `.yaml` extention gives a: "No operations defined in spec!" but we get a "Valid" svg icon.

Example: https://artifactory.plexxi.com/api-docs-local/switch/sapi.yaml

Does the swagger UI no longer support the Yaml format?

**Comment by webron** [comment] 2017-03-20 23:03
It is. We'll look into it.

**Comment by shockey** [comment] 2017-03-21 20:01
Hey @JLLeitschuh, looks like your server is sending back a `Content-Type: application/octet-stream` header with your document. This is causing our fetcher to treat your document as a binary file... which doesn't get you very far.

We're adding an override when we load documents, to always treat them as plaintext, in our next release (see PRs https://github.com/swagger-api/swagger-js/pull/968 + https://github.com/swagger-api/swagger-ui/pull/2755), as a usability enhancement. In the meantime, setting `Content-Type: text/plain` when serving your YAML will fix this.

**Comment by JLLeitschuh** [comment] 2017-03-21 20:34
We can't really control content headers from Artifactory. I bet that others will have this same problem.

**Comment by JLLeitschuh** [comment] 2017-03-21 23:03
We have opened an issue with artifactory:
https://www.jfrog.com/jira/browse/RTFACT-12364

**Comment by shockey** [comment] 2017-03-22 22:52
Closing as a duplicate of #2743 😄

**Closed by shockey** 2017-03-22 22:52 UTC
Labels: P1
