### ISSUE TITLE
allOf: in nested models do not render.

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-ui#2354] opened 2016-08-24 21:34 UTC
swagger-ui version: 2.2.2

When a model contains another model that has allOf with a reference, the outer model is not rendered in swagger-ui. I saw similar issues, but not one exactly like this. I hope this is not a duplicate. 

Top level file:

```
swagger: '2.0'
info:
  version: 2.0.0
  title: Test API
produces:
  - application/json
consumes:
  - application/json
paths:
  /test:
    post:
      parameters:
        - $ref: './test-model.yaml#/parameters/test_request'
      responses:
        '200':
          description: Success
          schema:
            $ref: './test-model.yaml#/definitions/TestResponse'
```

Model file (test-model.yaml):

```
definitions:
  Base:
    properties:
      id:
        type: integer
        format: int64

  TestRequest:
    allOf:
      - $ref: '#/definitions/Base'
      - type: object
        properties:
          attr_a:
            type: string
          attr_b:
            type: string
          sub_model:
            type: array
            items:
              $ref: '#/definitions/LineItem'

  TestResponse:
    allOf:
      - $ref: '#/definitions/Base'
      - type: object
        properties:
          amount:
            type: number
          resp_items:
            type: array
            items:
              $ref: '#/definitions/ResponseItem'
          result_code:
            type: string

  LineItem:
    allOf:
      - $ref: '#/definitions/Base'
      - type: object
        properties:
          code:
            type: string
          amount:
            type: number
          description:
            type: string
          address:
              $ref: '#/definitions/Address'

  Address:
    type: object
    required:
      - line1
      - city
      - region
      - country
      - postal_code
    properties:
      line1:
        type: string
      line2:
        type: string
      city:
        type: string
      region:
        type: string
      country:
        type: string
      postal_code:
        type: string

  ResponseItem:
    type: object
    properties:
      item_id:
        type: string
      amount:
        type: number

parameters:
  test_request:
    name: test_request
    in: body
    description: The test request
    required: true
    schema:
      $ref: '#/definitions/TestRequest'
```

The issue seems to only occur when the definitions are in separate files. For example, the following spec renders just fine. It is the same as above, except everything is in one file.

```
swagger: '2.0'
info:
  version: 2.0.0
  title: Test API
produces:
  - application/json
consumes:
  - application/json
paths:
  /test:
    post:
      parameters:
        - name: test_request
          in: body
          description: The test request
          required: true
          schema:
            $ref: '#/definitions/TestRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/TestResponse'

definitions:
  Base:
    properties:
      id:
        type: integer
        format: int64

  TestRequest:
    allOf:
      - $ref: '#/definitions/Base'
      - type: object
        properties:
          attr_a:
            type: string
          attr_b:
            type: string
          sub_model:
            type: array
            items:
              $ref: '#/definitions/LineItem'

  LineItem:
    allOf:
      - $ref: '#/definitions/Base'
      - type: object
        properties:
          code:
            type: string
          amount:
            type: number
          description:
            type: string
          address:
              $ref: '#/definitions/Address'

  Address:
    type: object
    required:
      - line1
      - city
      - region
      - country
      - postal_code
    properties:
      line1:
        type: string
      line2:
        type: string
      city:
        type: string
      region:
        type: string
      country:
        type: string
      postal_code:
        type: string

  TestResponse:
    allOf:
      - $ref: '#/definitions/Base'
      - type: object
        properties:
          amount:
            type: number
          resp_items:
            type: array
            items:
              $ref: '#/definitions/ResponseItem'
          result_code:
            type: string

  ResponseItem:
    type: object
    properties:
      item_id:
        type: string
      amount:
        type: number


parameters:
  test_request:
    name: test_request
    in: body
    description: The test request
    required: true
    schema:
      $ref: '#/definitions/TestRequest'
```

 Any ideas for a workaround that keeps the specs in different files?

**Comment by jeff9finger** [comment] 2016-08-28 21:24
Does https://github.com/swagger-api/swagger-js/issues/681 fix this as well?

**Comment by tedepstein** [comment] 2016-08-30 16:40
@jeff9finger , just wanted to point out a problem in your input swagger spec that is most likely unrelated to the issue you're reporting here, but could interfere with successful testing.  

Your `Base` schema defines `id` as an integer, while `LineItem` defines `id` as a string.  This means there can never be an legal instance of LineItem, because it's impossible to have an `id` property value that is both an integer and a string.

JSON Schema's `allOf` keyword is often misunderstood.  It's not classical inheritance, with the ability to override or mask inherited properties.  Rather, it's a constraint that says an instance is valid only if it matches each of listed schemas _independently_.  Using `allOf`, it's easy to create schemas that have no possible matching instance. 

As an experiment, try [JSON Lint](http://jsonschemalint.com/draft5/#) with this variant of your schema, just making `LineItem` the top-level schema:

```
allOf:
  -
    $ref: '#/definitions/Base'
  -
    type: object
    properties:
      id: {type: string}
      code: {type: string}
      amount: {type: number}
      description: {type: string}
      address: {$ref: '#/definitions/Address'}

definitions:
  Base:
    properties:
      id: {type: integer, format: int64}
  TestRequest:
    allOf:
      - {$ref: '#/definitions/Base'}
      - {type: object, properties: {attr_a: {type: string}, attr_b: {type: string}, sub_model: {type: array, items: {$ref: '#/definitions/LineItem'}}}}
  Address:
    type: object
    required:
      - line1
      - city
      - region
      - country
      - postal_code
    properties:
      line1: {type: string}
      line2: {type: string}
      city: {type: string}
      region: {type: string}
      country: {type: string}
      postal_code: {type: string}
  TestResponse:
    allOf:
      - {$ref: '#/definitions/Base'}
      - {type: object, properties: {amount: {type: number}, resp_items: {type: array, items: {$ref: '#/definitions/ResponseItem'}}, result_code: {type: string}}}
  ResponseItem:
    type: object
    properties:
      item_id: {type: string}
      amount: {type: number}
parameters:
  test_request:
    name: test_request
    in: body
    description: 'The test request'
    required: true
    schema:
      $ref: '#/definitions/TestRequest'
```

If you try matching `id: "123"`, you'll see the error `.id should be integer`.  If you try matching `id: 123`, you'll see `.id	should be string`.  No way to make that schema happy.

**Comment by jeff9finger** [comment] 2016-08-30 19:53
Thanks. Updated swagger definition - removed id in LineItem. But still exhibits the same problem.

Thanks @tedepstein

**Comment by webron** [comment] 2017-03-02 22:01
duplicate of #1883

**Closed by webron** 2017-03-02 22:01 UTC
