### ISSUE TITLE
"Execute" button inactive

### ISSUE THREAD

**Issue by domfennell** [swagger-api/swagger-ui#3369] opened 2017-07-11 14:09 UTC
Steps to reproduce:

Go to http://petstore.swagger.io

1. Enter swagger url for the api, using HTTPS (e.g. for one of our api calls, use https://imin-platform-api.imin.co/v1/swagger.json)
2. Specify scheme HTTPS
3. Enter required api parameters (e.g. for one of our api calls, use GET /v1/search/sessions)
4. (Attempted to) click "Execute"

Expected:
Petstore executes api call using HTTPS as specified.

Actual:
"Execute" button not clickable. Neither results nor error code generated.

Would someone be able to investigate this issue to determine why the "Execute" button appears not to be working?

Thank you.

**Comment by webron** [comment] 2017-07-11 15:30
Likely a duplicate of #3361.

**Comment by owenconti** [comment] 2017-07-13 00:50
Hi @domfennell, 

Are you able to provide a sample spec that reproduces the issue?

**Comment by owenconti** [comment] 2017-07-22 22:42
Hi @domfennell, I am going to close this issue. If you can still reproduce the issue, let me know.

**Closed by owenconti** 2017-07-22 22:42 UTC
