### ISSUE TITLE
Valid schema fires JS error at module.exports.SwaggerClient.makeUniqueOperationId

### ISSUE THREAD

**Issue by pdonorio** [swagger-api/swagger-ui#2604] opened 2017-01-09 08:31 UTC
Hello,
see  [my attached valid test schema](https://github.com/swagger-api/swagger-ui/files/692955/specs.json.zip) that I previously validated with a Yelp python library and also on the swagger editor online.

Using it on a local swagger ui based on the latest master version, I obtain the error:
```
Uncaught TypeError: Cannot read property 'operations' of undefined
    at module.exports.SwaggerClient.makeUniqueOperationId (client.js:590)
    at client.js:511
    at arrayEach (arrayEach.js:15)
    at Object.forEach (createForEach.js:15)
    at client.js:468
    at arrayEach (arrayEach.js:15)
    at Object.forEach (createForEach.js:15)
    at client.js:422
    at createBaseFor.js:19
    at baseForOwn (baseForOwn.js:14)
```

And the ui hangs on:
```
fetching resource list: http://localhost:8080/api/specs; Please wait.
```

It seems like something in the schema breaks some cycle in the ui. 
If something is not right, it would be nice to receive a warning on where and why.

Can you help me on this? Can I help in some other way?
Thanks

---

swagger-ui version: latest master, commit 2972c3c9b8b2415900025a2a4413965fbfa3f1c7

**Comment by pdonorio** [comment] 2017-01-09 08:32
Also please tell me if this is the case of writing to the swagger-js repo

**Comment by webron** [comment] 2017-01-09 19:36
Looks like the issue is related to the tag `definitions` that you used for one of the operations. If you rename the tag, you could work around the issue for now.

**Comment by pdonorio** [comment] 2017-01-09 22:02
Ah! It's true, thanks a lot @webron for hunting that down, I personally didn't notice at all.

So - at the moment - *tags* can't be swagger keywords?

**Comment by webron** [comment] 2017-01-09 22:14
I think we escaped quite a few of them, but probably missed a few (as you can see).

**Comment by pdonorio** [comment] 2017-01-09 22:23
Let me know if I can help in some way.

I may close the issue since the problem is clear and I may survive without the tag "definitions", it's up to you.

**Comment by webron** [comment] 2017-01-09 22:26
Let's keep it open so we can make sure to tackle it, but happy to hear you're satisfied with the current workaround.

**Comment by albertogg** [comment] 2017-02-02 17:04
Hi folks, I got the very same error, with which I think is the `schemes` tag. I'm not completely sure but I guess so. Is this a reserved word?

Thanks.

**Comment by albertogg** [comment] 2017-02-02 17:08
I guess #2061 may be related.

**Comment by webron** [comment] 2017-02-02 19:25
@albertogg yeah, any term that's used directly in the spec can end up breaking the UI if used out of scope. We try to escape usage where possible, but sometimes things get missed.

**Comment by albertogg** [comment] 2017-02-02 20:40
Thanks for answering!, do you think this will eventually get fixed? I'll be glad to help if some guidance is provided.

Thanks in advance

**Comment by fehguy** [comment] 2017-02-02 20:44
@albertogg this lives in swagger-js, there is a single place to list reserved words.  If you can file a PR + test case there, it will be trivial to merge.

**Comment by albertogg** [comment] 2017-02-03 18:27
thanks, but I don't know where this list is, or what I have to do, can you explain a little better?

Thanks

**Comment by fehguy** [comment] 2017-02-03 18:28
See here
https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L27

**Comment by shockey** [comment] 2017-11-29 07:41
This looks to be 2.x specific, so I'm closing this out.

Thanks everyone!

**Closed by shockey** 2017-11-29 07:41 UTC
