### ISSUE TITLE
Enum values are not displayed correctly as Response Class

### ISSUE THREAD

**Issue by lmprice** [swagger-api/swagger-ui#1907] opened 2016-01-22 02:43 UTC
I don't see a response class represented in Swagger-UI when the type is an enum (Swagger-Core). The GUI doesn't render anything.

I'm on the newest revision (43a78f965807dc2391506d7ca6f3ac5c0da1df52).

**Comment by webron** [comment] 2016-01-22 03:05
It would help if you could share your swagger spec.

**Comment by lmprice** [comment] 2016-01-22 03:25
I can't share my spec directly, but I can create a sample that will result in the same issue.

**Comment by webron** [comment] 2016-01-22 03:28
That would be great, thank you.

**Comment by BonsaiDen** [comment] 2016-01-22 13:40
Encountering the same issue here, having a `enum` type property in the request body causes this, from what I can tell it crashes due to a missing `<div class="parameter-content-type" />` placeholder  in the corresponding enum template.

When renderinge the `SwaggerUi.Views.ParameterView` it runs into the following code anjd crashes:

```
    if (isParam) { // true since it is a body param
      var parameterContentTypeView = new SwaggerUi.Views.ParameterContentTypeView({model: contentTypeModel});

     // ".parameter-content-type" does not exists in the template so the content with the parameterContentType dropdown is never set
      $('.parameter-content-type', $(this.el)).append(parameterContentTypeView.render().el);

      // This eventually tries to grab the ".val()" from the HTML which never got inserted and then runs into a undefined has not method.indexOf()
      this.toggleParameterSnippet(); 
    }
```

**Comment by fehguy** [comment] 2016-01-22 16:46
@bodnia can you look at this?  It may be caused by your recent change.

**Comment by bodnia** [comment] 2016-01-22 16:51
I will look into this

**Comment by bodnia** [comment] 2016-01-25 15:04
@BonsaiDen @lmprice could you please give an example for testing? Thank you in advance!

**Comment by lmprice** [comment] 2016-01-28 20:56
@bodnia I created a sample to test against. Sorry for the delay.

`{"swagger":"2.0","basePath":"/experimental","tags":[{"name":"testApi"}],"schemes":["http","https"],"paths":{"/listItems":{"get":{"tags":["testApi"],"summary":"Retrieve the current raid level","description":"","operationId":"getEvents","parameters":[],"responses":{"404":{"description":"Invalid option"},"200":{"description":"successful operation","schema":{"type":"string","enum":["raid1","raid5","raid6"]}}}}}}}`

**Comment by webron** [comment] 2016-01-28 21:39
The problem is not with the enum, but rather because the response is a primitive. This issue is in fact a duplicate of #1186.

**Comment by lmprice** [comment] 2016-01-28 21:52
@webron Ah, thanks for diagnosis. I look forward to the fix for this.

**Comment by webron** [comment] 2016-01-28 21:55
I'll be closing this issue in favor of the original though, just to help us keep track on things. @bodnia - I believe @ponelat created a PR a long time ago (linked to the original issue) that's supposed to resolve it. The PR is probably stale and needs to be rebased or resubmitted. Can you please look into that? We can continue the discussion on the original issue.

**Closed by webron** 2016-01-28 21:55 UTC
