### ISSUE TITLE
UI Stucks while listing/fetching

### ISSUE THREAD

**Issue by SaadHussain** [swagger-api/swagger-ui#3680] opened 2017-09-19 07:03 UTC
[datajson.zip](https://github.com/swagger-api/swagger-ui/files/1313310/datajson.zip)
Bug
Swashbuckle Version 5.6.0 
Browser IE, Chrome and Firefox
OS Windows 8.1

Json returns fine from my local host
http://localhost:37991/swagger/docs/v1

but browser hangs up while fetching api list

attached here is the json file

**Comment by webron** [comment] 2017-09-19 08:49
Closing as duplicate of #1919.

**Closed by webron** 2017-09-19 08:49 UTC
