### ISSUE TITLE
Description in "Available authorizations" not appearing in OpenApi 3.0.1

### ISSUE THREAD

**Issue by xyptkl** [swagger-api/swagger-ui#5798] opened 2020-01-15 02:18 UTC
As described in the title, I cannot get descriptions to appear in available authorizations although I have already defined the description in securitySchemes.
The description appears when I use Swagger 2.0 but not when I use OpenApi 3.0.1.
I cannot use Swagger 2.0 as I have to rely on OpenApi 3.0 to include multiple hosts.
I am using oauth2 with clientCredentials in flows.

A similar issue is raised here: (Please see this for clarifications)
https://github.com/swagger-api/swagger-ui/issues/5230

Are there any resolutions to this without a workaround as described in the issue?
Any help would be greatly appreciated!

**Comment by hkosova** [comment] 2020-01-15 07:48
Closing as a duplicate of #5230. Please follow that issue for status updates.

**Closed by hkosova** 2020-01-15 07:48 UTC
