### ISSUE TITLE
 No content-type is added in the Request Body 

### ISSUE THREAD

**Issue by pandoly2** [swagger-api/swagger-ui#5577] opened 2019-08-29 08:27 UTC
OS: [macOS]
Browser: [chrome]
Version: [latest]
Method of installation: [npm]
Swagger-UI version: [3.23.4]
Swagger/OpenAPI version: [OpenAPI 3.0]

------------------------------------------------------------------

I tested multipart/form-data.
However, swagger 3.0 is multipart/form-data encoding does not work.

I have completed all the settings and sent a request, but I could not set the content-type: application / json.

The request I sent is:
```
``
[ API 3.0 ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: # Request parts
                id:
                  type: string
                  format: uuid
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                profileImage:
                  type: string
                  format: base64
            encoding: 
              address: 
                contentType: application/json
```
```


[Http - Form Data]
------WebKitFormBoundaryg4ZD9ktAPUfzw09p
Content-Disposition: form-data; name="id"

123
------WebKitFormBoundaryg4ZD9ktAPUfzw09p
Content-Disposition: form-data; name="address"
  **<---------------------------- not added content-type: application/json** 
{
  "street": "111",
  "city": "222"
}
------WebKitFormBoundaryg4ZD9ktAPUfzw09p
Content-Disposition: form-data; name="profileImage"; filename="fina.zip"
Content-Type: application/x-zip-compressed


------WebKitFormBoundaryg4ZD9ktAPUfzw09p--

**Comment by hkosova** [comment] 2019-08-29 11:04
Duplicate of #4826.

**Closed by hkosova** 2019-08-29 11:04 UTC
