### ISSUE TITLE
Request model model is empty when there's more than one schema

### ISSUE THREAD

**Issue by ricardohbin** [swagger-api/swagger-ui#3625] opened 2017-08-29 16:40 UTC
When the request body has multiple schemas, the request body model (and example) appears empty.

Ex:
```
requestBody:
        required: true
        content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Foo'
                  - $ref: '#/components/schemas/Bar'
```

Ok, knowing this what would be the expected value in the UI? How we can handle with various models in the same request?

**Comment by webron** [comment] 2017-09-11 10:17
This is likely a duplicate of #3490. Follow that ticket as we have a pending fix.

**Closed by webron** 2017-09-11 10:17 UTC
