### ISSUE TITLE
The inputs automatically cleared by the Swagger UI (and in the editor.swagger.io too)

### ISSUE THREAD

**Issue by Nur777** [swagger-api/swagger-ui#4279] opened 2018-03-02 09:15 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OAS3 (Screen: http://joxi.ru/gmvWwE4IxYWBv2)
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | Download from GitHub as a zip file yesterday (v3.11.0 ?)
| Which browser & version?        | Chrome 63.0.3239.132 Official 64-bit (Screen: http://joxi.ru/nAyKw54IXo0Qym)
| Which operating system?         | Windows 7 Ultimate 64-bit 6 Gb

### Demonstration API definition
First, sorry for my English please, im not a native speaker...

Demo video: http://recordit.co/jdeSmu9bSP (console opened)
Demo in another file: http://recordit.co/M7VtLuAFwm (very simplified file)

When i try to fill any query parameter input values it is cleared by the swagger automatically... 
I don't see this bug before on previous version of api documentation (Swagger 2).

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Common API (Selena II Core API Documentation)
servers:
  - url: /api/v1/common
    description: Relative server url
paths:
  '/files/{file_hash}/can-download':
    get:
      tags:
        - Attachments
      summary: Authorize the user to download the file by the file hash.
      description: Authorize the user to download the file by the file hash.
      parameters:
        - name: file_hash
          in: path
          required: true
          description: File hash of the file.
          schema:
            type: string
      responses:
        '200':
          description: The result of the checking the permissions.
        '422':
          $ref: '#/components/responses/ValidationFailedResponse'
security:
  - CommonAuthentication: []
components:
  securitySchemes:
    CommonAuthentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Place JWT token of the user here.
  responses:
    ValidationFailedResponse:
      description: Some fields can not be validated. See errors.
    Standard200SuccessResponse:
      description: Success.
```

### Configuration (browser query string, constructor, config.yaml)
I dont use any configurations. I simply open the yml file with the swagger index.html file with the query parameters as described above:

`?url=apis/common.inc.yml`

### Expected Behavior
Parameters should not being cleared automatically by swagger.
### Current Behavior
The inputs with the parameters automatically cleared by the swagger (In the swagger editor on the online version too!).
### Possible Solution
I don't know... But this can help to resolve the problem may be (with console opened):
http://recordit.co/PSKGx5mEwW
(usually i reopen the swagger ui in the new tab and totally reload the page (with Ctrl+Shift+R)).

**Comment by webron** [comment] 2018-03-02 16:24
Closing as a duplicate of #4269 - this has been fixed.

**Closed by webron** 2018-03-02 16:24 UTC
