### ISSUE TITLE
[Swagger 2.0] JSON Body parameter not recognized when is inline

### ISSUE THREAD

**Issue by Maks3w** [swagger-api/swagger-ui#1145] opened 2015-04-10 17:05 UTC
Given a body parameter with schema.

If the schema has the properties defined inline Swagger UI does not show the model.

Instead if properties are referenced via $ref works.

**Comment by webron** [comment] 2015-04-10 17:11
This is a duplicate of #1133.

**Closed by webron** 2015-04-10 17:11 UTC
