### ISSUE TITLE
Fenced code blocks requires additional indentation 

### ISSUE THREAD

**Issue by ZhangYiJiang** [swagger-api/swagger-ui#5236] opened 2019-03-13 02:52 UTC
### Q&A (please complete the following information)
 - OS: Ubuntu Linux
 - Browser: Firefox 
 - Version: Latest beta
 - Method of installation: dist assets
 - Swagger-UI version: Latest on npm and on https://petstore.swagger.io
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Valid Commonmark fenced code blocks do not require indentation for them to be rendered as code blocks, but the parser used in Swagger UI does.

Example Swagger/OpenAPI definition:
```yaml
  description: >
    This is rendered as inline code 


    ```
    Test
    First code block
    ```


    This is rendered as a proper code block, with an additional level of indent 

    
      ```
      Test
      Second code block
      ```

    This is an indented code block 

        Test
        Indented code block
```

Swagger-UI configuration options:

The default, this reproduces on the petstore 

### To reproduce...

1. Go to https://editor.swagger.io/
2. Paste in the config above
3. Notice the incorrectly rendered code blocks

### Expected behavior

Fenced code blocks should not require additional indentation

### Screenshots

![Screenshot from 2019-03-13 10-54-41](https://user-images.githubusercontent.com/445650/54250364-7903d180-457e-11e9-88fa-e36c86fea846.png)

**Comment by shockey** [comment] 2019-03-14 01:01
Hi @ZhangYiJiang, looks like this is working as intended.

Your YAML multiline string is using the [`>` folder block scalar style](https://yaml.org/spec/1.2/spec.html#id2796251), so single newlines are being replaced with spaces in your string. That means that your "Test First code block" is all on one line, i.e. ````This is rendered as inline code \n\n``` Test First code block ```\n\n````. You can use the [js-yaml demo tool](https://nodeca.github.io/js-yaml/) to see how your YAML is being parsed.

Since Commonmark [requires fenced code blocks to put their content on subsequent lines from the backticks that delineate the block](https://spec.commonmark.org/0.28/#fenced-code-blocks), your block does not qualify as a fenced code block and is correctly being treated as a [code span](https://spec.commonmark.org/0.28/#code-spans) instead.

---

You can get the functionality that you want by using the [`|` literal block scalar style](https://yaml.org/spec/1.2/spec.html#id2795688) instead:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/680248/54324160-c7829180-45b9-11e9-93be-cde2683f0155.png">


PS: the YAML spec is kinda dense about this stuff, here's a site that lays out YAML multiline strings in a much simpler fashion... https://yaml-multiline.info

I'm going to close this for now, but if you have any further concerns just let me know and I can reopen it. Thanks!

**Closed by shockey** 2019-03-14 01:01 UTC
