### ISSUE TITLE
allOf inside items doesn't work

### ISSUE THREAD

**Issue by andresz1** [swagger-api/swagger-ui#2271] opened 2016-07-12 19:46 UTC
- Description: Usage of `allOf` inside `items` only shows the first element
- Version: 2.1.4
- Example:

I'm trying to add an **id** field to user's definition. A part of my `swagger.json` file: 

``` json
"docs": {
  "type": "array",
  "items": {
    "allOf": [
      {
        "$ref": "#/definitions/User"
      },
      {
        "properties": {
          "id": {
            "type": "string"
          }
        }
      }
    ]
  }
}
```

The example value showed in the ui is the following:

``` json
{
  "docs": [
    {
      "email": "string",
      "createdAt": "2016-07-12T19:40:42.290Z",
      "updatedAt": "2016-07-12T19:40:42.290Z"
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0
}
```

As you can see, the **id** field is not shown. Any idea ? I would highly appreciate any help.
Thank you.

**Comment by ognus** [comment] 2016-12-11 06:30
duplicate of #1883

**Closed** 2017-03-02 22:00 UTC
