### ISSUE TITLE
Content-type is not being sent with GET and DELETE requests

### ISSUE THREAD

**Issue by manish2aug** [swagger-api/swagger-ui#2408] opened 2016-09-16 13:43 UTC
*\* swagger-ui version*\* 2.2.3
**Swagger file:** 
`"/v1/processes/{guid}" : {
      "get" : {
        "tags" : [ "Process API" ],
        "summary" : "Finds an active process task with supplied process id",
        "description" : "The process id is an user defined unique identifier for New Business process instance",
        "operationId" : "findById",
        "schemes" : [ "https" ],
        "consumes" : [ "application/vnd.bpm-services.v1+json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "guid",
          "in" : "path",
          "description" : "Process id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful: Process found with supplied process id",
            "schema" : {
              "$ref" : "#/definitions/BPMProcessDetail"
            }
          },
          "401" : {
            "description" : "Operation failed: (Un Authenticated) Credentials supplied are not valid",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          },
          "403" : {
            "description" : "Operation failed: (Un Authorized) Principle corresponding to the supplied credentials is not allowed to access the operation",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          },
          "404" : {
            "description" : "Not Found: No active process instance found for supplied id",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          },
          "405" : {
            "description" : "Operation failed: (Method Not Allowed) Only allowed http method for this operation is GET",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          },
          "415" : {
            "description" : "Operation failed: (Unsupported Media Type) The only supported media type for operation is - application/vnd.bpm-services.v1+json",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          },
          "500" : {
            "description" : "Operation failed: (Internal Server Error) An unexpected error was encountered, please check the logs for detailed message",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          }
        }
      }`

**Curl request from swagger-ui**
`curl -X GET --header 'Accept: application/json' 'http://localhost:9080/bpm-services/rest/v1/processes/232'`

as the api methods needs the specific content type, the call failes with 415

**Comment by DavidBiesack** [comment] 2016-09-16 14:55
We see this too; the curl command ignores the media type selected by the Response Content Type drop down.  Stepping into the JavaScript, I also see 

headers : Object
Accept:"application/json"
in Swagger.Http.execute

**Comment by manish2aug** [comment] 2016-09-16 15:08
But somehow it working fine for POST request, if someone has an idea about work around please share

**Comment by manish2aug** [comment] 2016-09-19 09:30
@DavidBiesack well it's not about response content-type, that should only match with accept header. But I am talking about the request content-type which should be matched with @Consume annotation on resource method and this just specifies only one type. So ideally it should by default be sent with request as separate header (Content-Type) but swagger-ui is just ignoring it

**Comment by javierazabache** [comment] 2016-09-20 04:25
According to the HTTP/1.1 specification, neither GET or DELETE request should have a message body, and if they have one, the server should ignore it. I'm guessing that's why swagger-ui doesn't send a Content-Type header with GET or DELETE requests.

Of course, you can implement your server however you want, but then you wouldn't be following the recommendations in the specification.

More here: https://tools.ietf.org/html/rfc2616#section-4.3

**Comment by manish2aug** [comment] 2016-09-20 08:46
Agreed! And our GET and DELETE are not having any message body. But we implemented API versioning with content negotiation and using a custom content type (application/vnd.bpm-services.v1+json) and which is permissible as per spec.

**Comment by DavidBiesack** [comment] 2016-09-20 13:36
@manish2aug thanks, I created a separate issue for our problem, #2413

**Comment by mpalourdio** [comment] 2017-01-11 13:54
I can confirm @manish2aug bug. In swagger-ui, the ``consumes```annotation is not honored as Content-Type header for the CURL request.

**Comment by mpalourdio** [comment] 2017-01-11 15:06
I shall add that Content-Type is sent in my GET request for the same reasons, because of  API versioning with custom Content-Type headers for clients that consume our API.

**Comment by fehguy** [comment] 2017-01-11 18:43
Guys, sorry!  We're not adding body parameters for GET requests.  It is also *not* supported by the Swagger / OAI specification.

If `Content-Type` is sent during your GET operation, that is indeed a bug.

**Comment by mpalourdio** [comment] 2017-01-11 19:14
Hello and thanks for reply,

Sending a Content-Type header in a get request is ok regarding this specification : http://jsonapi.org/format/#content-negotiation-clients

I agree it's not the most natural way to do it, but it looks ok, and is not something that is denied I think. Calling it a 'bug' is maybe not the appropriate word.

Anyway, thanks for reply.

**Comment by mpalourdio** [comment] 2017-01-11 19:21
Looks like the specification is not that clear : https://github.com/json-api/json-api/issues/968

This threads emphasizes the fact that Content-Type should not be sent with GET and DELETE, which makes sense.

Thanks !

**Comment by JLLeitschuh** [comment] 2017-01-28 00:04
Should the OPEN Api specification not have the global `consumes` flag get applied to GET and DELETE's?

It seems to go against the OpenAPI spec to be disregarding the global `consumes` flag.

**Comment by fehguy** [comment] 2017-01-28 00:08
@webron can chime in--I think we were going to add support for `Content-Type` in GET requests, even though it's not only very unusual to do so (and not supported by most tooling) but also a Generally Accepted Bad Idea (tm).

**Comment by webron** [comment] 2017-01-28 00:10
Yeah, pretty much.

**Comment by JLLeitschuh** [comment] 2017-01-28 00:14
Cool, good to hear that this will be fixed.
Its seems like json-api is trying to use a formalization of hateoas which is somewhat orthogonal to what Swagger offers.
How does what json-api have anything to do with this?

**Comment by fehguy** [comment] 2017-01-28 01:01
@JLLeitschuh just to be clear, are you happy that "we are likely adding support for `Content-Type` in GET requests" or are you hoping that they are removed?  FWIW this has been a source of debate...

**Comment by JLLeitschuh** [comment] 2017-01-29 04:04
I am happy. I also agree with your statement:
> also a Generally Accepted Bad Idea (tm)

**Comment by webron** [comment] 2017-03-24 20:37
Since version 3.0.0 of the spec is explicitly not allowing payloads for GET and DELETE operations, it doesn't make sense to fix this.

**Closed by webron** 2017-03-24 20:37 UTC

**Comment by SnowyThinker** [comment] 2021-04-13 09:08
> Since version 3.0.0 of the spec is explicitly not allowing payloads for GET and DELETE operations, it doesn't make sense to fix this.

Postman can works well 
----------------------------------
GET /example1/query_by_id/1111 HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.10
Accept: */*
Cache-Control: no-cache
Postman-Token: caf112b4-5922-4c84-8677-d705eb991b38
Host: localhost:9001
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked
Date: Tue, 13 Apr 2021 09:06:21 GMT
Keep-Alive: timeout=60
Connection: keep-alive
