### ISSUE TITLE
h.filter is not a function

### ISSUE THREAD

**Issue by aalleexxeeii** [swagger-api/swagger-ui#2893] opened 2017-04-10 16:24 UTC
The version installed on petstore.swagger.io at the time of writing stopped working with the attached definition [api-docs.yaml.txt](https://github.com/swagger-api/swagger-ui/files/910734/api-docs.yaml.txt) that worked previously. The following errors are written in the console while trying to enter input data: 

`h.filter is not a function`

`"t.JsonSchema_array</<.value/<@http://petstore.swagger.io/swagger-ui-bundle.js:103:15296ut/r.__iterateUncached/<@http://petstore.swagger.io/swagger-ui-bundle.js:36:18905ze.prototype.__iterate@http://petstore.swagger.io/swagger-ui-bundle.js:37:9644ut/r.__iterateUncached@http://petstore.swagger.io/swagger-ui-bundle.js:36:18868W@http://petstore.swagger.io/swagger-ui-bundle.js:36:6674M.prototype.__iterate@http://petstore.swagger.io/swagger-ui-bundle.js:36:29388.toArray@http://petstore.swagger.io/swagger-ui-bundle.js:37:20625ze@http://petstore.swagger.io/swagger-ui-bundle.js:36:13934St@http://petstore.swagger.io/swagger-ui-bundle.js:36:24901.map@http://petstore.swagger.io/swagger-ui-bundle.js:37:22447t.JsonSchema_array</<.value@http://petstore.swagger.io/swagger-ui-bundle.js:103:15248k/n.prototype.render@http://petstore.swagger.io/swagger-ui-bundle.js:51:8471x._renderValidatedComponentWithoutOwnerOrContext@http://petstore.swagger.io/swagger-ui-bundle.js:67:19065x._renderValidate"`

**Comment by webron** [comment] 2017-04-12 10:27
Please try again. Tested it now and it loads fine.

**Comment by davidmfrey** [comment] 2017-04-12 12:50
I'm getting a similar error now.  When I have an array [string] multi query param type, it barfs when I click add item. 

swagger-ui-bundle.js:51 TypeError: h.filter is not a function
    at swagger-ui-bundle.js:103
    at swagger-ui-bundle.js:36
    at ze.__iterate (swagger-ui-bundle.js:37)
    at r.__iterateUncached (swagger-ui-bundle.js:36)
    at W (swagger-ui-bundle.js:36)
    at r.M.__iterate (swagger-ui-bundle.js:36)
    at r.toArray (swagger-ui-bundle.js:37)
    at new ze (swagger-ui-bundle.js:36)
    at St (swagger-ui-bundle.js:36)
    at ze.map (swagger-ui-bundle.js:37)

**Comment by webron** [comment] 2017-04-12 13:50
I think I misread the original issue. Will retry later.

**Comment by webron** [comment] 2017-04-12 14:10
Duplicate of #2890.

**Closed by webron** 2017-04-12 14:10 UTC
