### ISSUE TITLE
Wrong model titles when composing using allOf

### ISSUE THREAD

**Issue by lekoder** [swagger-api/swagger-ui#2946] opened 2017-04-21 05:28 UTC
When composing models using `allOf`, swagger-ui displays wrong model title for composed model. It uses last model referenced in `allOf` instead of one defined.

## Definition:
```
definitions:
  Simple1:
    type: object
    properties:
      id1:
        type: integer
        format: int64
  Simple2:
    type: object
    properties:
      id2:
        type: integer
        format: int64
  Composed:
    allOf:
      - $ref: '#/definitions/Simple1'
      - $ref: '#/definitions/Simple2'
```
## Expected result:
```
Simple1{...}
Simple2{...}
Composed{...}
```

## Actual result:
```
Simple1{...}
Simple2{...}
Simple2{...}
```

Affected version: **v3.0.0-229-g7790383**

[Ghist with full issue demonstration](https://gist.githubusercontent.com/lekoder/4bd0131c4d1eff7e6ff264a2da3afda6/raw/6e310df096b194ada04b6eac7299a91b83dd953e/swagger-ui-allof-error.yaml)

**Comment by lekoder** [comment] 2017-04-21 05:46
Same issue is affecting latest master: **v3.0.0-235-g6cd66bb**

**Comment by lekoder** [comment] 2017-04-21 07:38
It seems that underlying problem is that schema of model composed with `allOf` has `$$ref` key of last items in `allOf` array.

**Comment by lekoder** [comment] 2017-04-21 08:19
This seems like **swagger-js** issue.

**Comment by buunguyen** [comment] 2017-05-17 18:14
Just added a test on SwaggerJS, it passes: https://github.com/buunguyen/swagger-js/commit/5421ff87f6d26fe593781a04e2677232daefdf1f. Seems to work fine on JS side.

**Comment by wjlow** [comment] 2017-06-02 00:52
Using the fix in @lekoder 's [commit](https://github.com/lekoder/swagger-ui/commit/0d1906ddea0ab74ba53c2bbaaa0f4ebb3ebcf78a), I was able to resolve the issue I was facing. Thanks.

**Comment by Xuanwo** [comment] 2017-06-15 11:23
I have encountered the same problem, how is the progress?

**Comment by webron** [comment] 2017-06-15 15:10
We're not working on a fix right now. Would be happy to review PRs.

**Comment by shockey** [comment] 2017-08-01 06:56
This appears to be fixed:

![image](https://user-images.githubusercontent.com/680248/28812897-bbeee5ce-764b-11e7-8525-12b2752708b3.png)

Closing - please ping if there are any further problems with this!

**Comment by DavidBiesack** [comment] 2017-08-01 20:41
@shockey This problem is still occurring for me in Swagger UI. I just pulled the latest 3.1.2 and it is still showing the base model name and description as I described in #3417 using https://github.com/swagger-api/swagger-ui/files/1160284/duplicate-models.yaml.txt I verified that my browser is not showing cached swagger-ui content.

**Comment by shockey** [comment] 2017-08-02 18:50
@DavidBiesack, your problem is valid but slightly different. This issue centers around inheriting the name based on the key name of the model, and yours has to do with the `title` property.

We'd be happy to look into it - can you open a new issue since this one is fixed?

**Comment by DavidBiesack** [comment] 2017-08-02 19:27
@shockey Please reopen #3417 which covers it all already - it was closed as a dup of this but apparently it is not really a dup. Thanks!

**Comment by shockey** [comment] 2017-08-02 19:34
@DavidBiesack sure, reopening now.

**Comment by marcoreni** [comment] 2017-08-10 09:31
This is still happening to me both in the web version and in the docker image (`swaggerapi/swagger-editor:latest`). Does it still have to be merged somehow?

![image](https://user-images.githubusercontent.com/2797489/29164342-6131146a-7dbf-11e7-8780-4ea32daeb40b.png)

**Comment by webron** [comment] 2017-08-10 13:40
Confirmed.

**Comment by ponelat** [comment] 2017-08-25 13:33
this caused the regression... https://github.com/swagger-api/swagger-ui/issues/3505 . So we need to ensure we don't regress on either this issue, or that issue. When fixing both :D

**Comment by dballance** [comment] 2017-08-28 16:14
Also seeing this is my internal fork (updated to b6cd504 currently). I'm looking to resolve the issue this week hopefully - will try to submit a PR here as well.

**Comment by Schellingerht** [comment] 2017-08-29 14:25
What about? I'm trying editor.swagger.io, but still the same problem.

<img width="1280" alt="schermafbeelding 2017-08-29 om 16 25 33" src="https://user-images.githubusercontent.com/11391078/29826116-b8cec8f4-8cd6-11e7-81d5-6d6e365c29a5.png">

**Comment by tvappagency** [comment] 2017-09-04 13:22
Hi,

Me too... any estimation when is it going to be solved?

**Comment by Schellingerht** [comment] 2017-09-04 13:51
A small fix: change `properties` to `- properties`, so only the model name
is wrong. The content is good.

2017-09-04 15:22 GMT+02:00 tvappagency <notifications@github.com>:

**Comment by shockey** [comment] 2017-09-12 01:40
Fixed by https://github.com/swagger-api/swagger-js/pull/1130, which should be released this week 🎉 

![messages image 3264158295](https://user-images.githubusercontent.com/680248/30304099-9fca05b8-9720-11e7-9c98-bb56e8747cf6.png)

**Closed by shockey** 2017-09-12 01:40 UTC
Labels: 3.x, Bug, P2, swagger-js

**Comment by florent-pasquer-needone** [comment] 2017-10-18 13:19
Tip : add composition value with the model title : 

> \- $ref: '#/definitions/Simple1'
> \- $ref: '#/definitions/Simple2'


=>

     
> \- $ref: '#/definitions/Simple1'
> \- $ref: '#/definitions/Simple2'
> \- title: "Composed"
