### ISSUE TITLE
Swagger UI does not display responses when schema type is of array

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-ui#2703] opened 2017-03-02 21:54 UTC
When reporting a bug, please provide the following details:
- swagger-ui version
Whatever version is running here:
http://petstore.swagger.io/
- a swagger file reproducing the issue
https://artifactory.plexxi.com/api-docs-local/control/gradleBuild_2016111701-SNAPSHOT/swagger.yaml

Simple example:
```yaml
  /ports:
    get:
      description: |
        Gets all of the ports on all switches.
      responses:
        200:
          description: |
            Successfully retrieved information on all switches.
          schema:
            type: array
            items:
              $ref: './definitions/Port.yaml#/Port'
```

This shows up in the UI with an example value as just this:
```json
[
  {}
]
```

**Comment by webron** [comment] 2017-03-02 22:02
duplicate of #1883

**Closed by webron** 2017-03-02 22:02 UTC
