### ISSUE TITLE
[Swagger 2.0] Order in /tags array is ignored when presenting the tags list

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-ui#1640] opened 2015-10-01 15:37 UTC
The specification for Swagger 2.0 says:
> The order of the tags can be used to reflect on their order by the parsing tools.

swagger-ui v2.1.3 does not uses that information and instead sorts tags by string order.

Here is a test case:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "test of Swagger-ui rendering of tags order"
  },
  "tags": [
    { "name": "First" },
    { "name": "Second" },
    { "name": "Third" },
    { "name": "Fourth" }
  ],
  "path": {
    "/last": {
      "get": {
        "tags": [ "Fourth" ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/second": {
      "get": {
        "tags": [ "Second" ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/first": {
      "get": {
        "tags": [ "First" ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/third": {
      "get": {
        "tags": [ "Third" ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment] 2015-10-01 23:54
Duplicate of #1475.

**Closed by webron** 2015-10-01 23:54 UTC
