### ISSUE TITLE
how to show body example value in html like parameters?

### ISSUE THREAD

**Issue by imyellow** [swagger-api/swagger-ui#5996] opened 2020-05-10 17:17 UTC
I want to display the red frame example value on the picture in the page

at 2.0 I can set parameters `in: body`, but how can i show the example value when i use openapi 3.0.0

![image](https://user-images.githubusercontent.com/3270774/81505944-8e60c100-9325-11ea-8786-910082d21213.png)

```
openapi: '3.0.0'
...

parameters:
  - name: phone
    in: query
    description: phone
    required: true
    schema:
      example: 12345678
      type: string
    
requestBody:
  description: ''
  content: 
    application/x-www-form-urlencoded:
      schema:
        type: object
        required:
          - phone
        properties:
          phone:
            type: string
            description: phone
            example: 12345678
```

**Comment by hkosova** [comment] 2020-05-11 15:31
In case of form data, example values are pre-filled in the input fields when you click "Try it out".

**Comment by hkosova** [comment] 2020-05-14 12:19
Duplicate of #5169.

**Closed by hkosova** 2020-05-14 12:19 UTC
