### ISSUE TITLE
Parameters with schema $ref not displaying schema

### ISSUE THREAD

**Issue by froodley** [swagger-api/swagger-ui#3976] opened 2017-12-02 20:33 UTC
If a parameter has its schema set to a $ref, there is no validation error, but Swagger-UI doesn't show the expanded request object definition in the Parameters section

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       |  {"swaggerEditor":"3.1.13/gcd0e941","swaggerUi":{"version":"3.4.3","gitRevision":"gb26654ec","gitDirty":false,"buildTimestamp":"Mon, 27 Nov 2017 14:54:09 GMT","machine":"SB-IE-63BNGTFM.local"}}"
| How did you install Swagger-UI? | Didn't, this is on swaggerhub
| Which browser & version?        | Chrome 62.0.3202.94
| Which operating system?         | Windows 7 professional

### Demonstration API definition

```yaml
openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pburkind8/asdf/1.0.0
info:
  description: |
    Test API
  version: "1.0.0"
  title: Test API
tags:
  - name: test
    description: Test tag
paths:
  /test:
    get:
      tags:
        - test
      summary: Test op
      description: Test op
      operationId: testOp
      parameters:
        - name: testParam
          in: query
          description: Test param
          required: true
          style: form
          explode: true
          schema:
            $ref: '#/components/schemas/test'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Result1
components:
  schemas:
    test:
      type: object
      required:
      - field_a
      - field_b
      properties:
        field_a:
          type: string
          example: Field A
        field_b:
          type: string
          example: Field B
```

### Expected Behavior

Should see the example/model as elsewhere where $ref is used (request body, result)

### Current Behavior

Just see the name given to the parameter

**Comment by hkosova** [comment] 2017-12-05 07:56
@webron this looks like a duplicate of #3558.

**Comment by webron** [comment] 2017-12-07 03:28
Thanks @hkosova, and thanks @froodley for filing the ticket.
This is indeed a duplicate, and I see @shockey slated a fix for this week's release (if nothing goes wrong).

**Closed by webron** 2017-12-07 03:28 UTC
