### ISSUE TITLE
Using allof in an array in response body generates blank examples

### ISSUE THREAD

**Issue by jwmonaco** [swagger-api/swagger-ui#2430] opened 2016-09-28 22:50 UTC
Using master (and 2.2.3/2.2.4) I get the following output.

![screenshot from 2016-09-28 18-45-29](https://cloud.githubusercontent.com/assets/18900595/18935110/d98c1d90-85ab-11e6-9167-fef03a87eb47.png)

For this input.  

[example.txt](https://github.com/swagger-api/swagger-ui/files/499390/example.txt)

Shouldn't the example for the response look exactly like the example for the parameter?  They are defined exactly the same way but the response example is blank.  If you remove the array (as in the /good path in example input) the response example matches the parameter example as I'd expect.

**Comment by bartekchlebek** [comment] 2016-10-08 00:23
dupe of #1883 👀

**Closed** 2017-03-02 22:01 UTC
