### ISSUE TITLE
Long text does not wrap on the new line

### ISSUE THREAD

**Issue by yula-clip** [swagger-api/swagger-ui#6825] opened 2021-01-12 08:49 UTC
### Describe the bug
Long text does not wrap on the new line.

### To reproduce...
 - Browser: all browsers
 - Swagger-UI version: 3.38.0
 
In "Response Body" must be long text. You will see that long text displayed differently than before. 

### Expected behavior
Long text must wrap on the new line.

### Screenshots
How it looks in v. 3.38.0 (looks not so nice)
![image](https://user-images.githubusercontent.com/31652842/104293318-8ebde700-54c6-11eb-8b03-aaa2ec16117e.png)

How it looks in v.3.37.2 (looks nice)
![image](https://user-images.githubusercontent.com/31652842/104293527-c62c9380-54c6-11eb-90e3-988326181590.png)

P.s.: I found the reason of this bug.
![image](https://user-images.githubusercontent.com/31652842/104294554-ffb1ce80-54c7-11eb-88f7-8f726a7c95b3.png)
![image](https://user-images.githubusercontent.com/31652842/104294606-10fadb00-54c8-11eb-8f0a-2c52039ff18e.png)

**Comment by hkosova** [comment] 2021-01-12 09:33
This was fixed in v. 3.39.0.

Duplicate of issue #6749.

**Comment by kevinfrommelt** [comment] 2021-01-13 14:30
@hkosova I'm actually still seeing these issues with v3.39.0. Was going to reopen the issue linked, but this one has better info.

Seems like you might be able to use the `wrapLongLines`prop from [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter#props) to get the right wrapping on the code blocks.
https://github.com/swagger-api/swagger-ui/blob/99fda81ae022e227fe3fcff91a8170d3a49ce7c1/src/core/components/highlight-code.jsx#L49-L55

**Closed** 2021-01-14 18:11 UTC
