### ISSUE TITLE
New version doesn't read basePath from resources

### ISSUE THREAD

**Issue by tasmaniski** [swagger-api/swagger-ui#1210] opened 2015-04-26 16:43 UTC
Hi,
I updated swagger UI to new version (2.1.1),
but it seems that basePath doesn't works during "try it now" call. It perform call without basePath.  
I have set it up in resource. This is part of my resource:
```
{  
   "basePath":"\/api",
   "swaggerVersion":"1.2",
   "apiVersion":"1.0.0",
   "resourcePath":"\/campaignRest",
   "apis":[  
      {  
         "path":"\/campaign",
         "operations":[  
            {  
               "method":"GET",
               "summary":"Fetches a list of all campaigns",
               "nickname":"getList",
               "type":"array",
               "items":{  
                  "$ref":"CampaignList"
               },
               "responseMessages":[  
                  {  
                     "code":200,
                     "message":"OK"
                  }
               ]
            },
```

Until now the call was:   http://URL/api/campaign but now is only http://URL/campaign

**Comment by webron** [comment] 2015-04-26 17:13
Duplicate of #1139.

**Closed by webron** 2015-04-26 17:13 UTC

**Comment by tasmaniski** [comment] 2015-04-26 19:53
sry, thanks!
