### ISSUE TITLE
Dropdown for discriminator

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-ui#3581] opened 2017-08-16 12:29 UTC
Please add dropdown for discriminator like
https://github.com/Rebilly/ReDoc/blob/master/docs/images/discriminator-demo.gif

From https://github.com/Rebilly/ReDoc

**Comment by jjakubik** [comment] 2017-08-25 00:17
This is a duplicate of #2438 and #1526 . But I wonder if the ReDoc solution is close to what is needed for Swagger UI--could it be ported?

**Comment by raderio** [comment] 2018-04-03 20:45
Any news about when it will added?

**Comment by webron** [comment] 2018-07-05 18:32
Closing in favor of #2438.

**Closed by webron** 2018-07-05 18:32 UTC
Labels: P2, type: feature, version: 3.x
