### ISSUE TITLE
Forms based input

### ISSUE THREAD

**Issue by alanrenouf** [swagger-api/swagger-ui#2843] opened 2017-04-03 20:28 UTC
Has anyone ever thought of a form based input as well as the current JSON input? 

Say as an extra tab or something under each resource to make it easier for people to fill out the form with combo boxes for enums etc? 

If someone committed such an enhancement would this be well received or should it be made elsewhere?

**Comment by webron** [comment] 2017-04-03 20:31
We had that feature in 2.X and we're planning on adding it to 3.X as well.

**Comment by alanrenouf** [comment] 2017-04-03 20:37
Great! is there something I can see?

**Comment by webron** [comment] 2017-04-03 20:53
We're not quite there yet. As much as I'd love to do it, it's not at the top of the list.

**Comment by alanrenouf** [comment] 2017-04-03 22:48
Cool, let me know if you have early previews or need help on developing this feature!

**Comment by webron** [comment] 2017-04-19 14:35
Closing as duplicate of #2771.

**Closed by webron** 2017-04-19 14:35 UTC
