### ISSUE TITLE
Field name "entries" in a schema causes swagger-ui javascript error and fails to load

### ISSUE THREAD

**Issue by mke1ms** [swagger-api/swagger-ui#6016] opened 2020-05-17 13:48 UTC
- OS: ubuntu
 - Browser: chrome, firefox
 - Method of installation: python fastapi
 - Swagger-UI version: https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Problem
The openapi definition below has a schema with a field name called "entries". This causes the ui to throw a javascript error "e.entries is not a function" (see the screenshot below).

This behavior only started Friday May 15th 2020 at around 15:00 CET. Before that swagger-ui had no problems loading a schema containing a field called entries, so I am assuming something changed in the bundle I use from the url above.

Example Swagger/OpenAPI definition:
```yaml
{
  "openapi": "3.0.2",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/test/": {
      "get": {
        "summary": "Test",
        "operationId": "test_test__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Testmodel"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Testmodel": {
        "title": "Testmodel",
        "required": [
          "name",
          "entries"
        ],
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "entries": {
            "title": "Entries",
            "type": "integer"
          }
        }
      }
    }
  }
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/7792223/82148148-db2b2700-9852-11ea-93a6-a1370fe343b0.png)

### To reproduce...

Try to load swagger ui using the openapi.json above

**Comment by provegard** [comment] 2020-05-18 08:51
Specifying version 3.25.2 (I'm using unpkg, I assume jsdelivr.net supports that too) fixes the problem.

**Comment by jmmolina796** [comment] 2020-05-18 22:48
Actually I have the same error:

When I type the filed name **entries**, I received a message saying: "Unable to render this definition". 

```yml
paths:
  /pet:
    post:
      summary: "Add a new pet to the store"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Pet:
    type: "object"
    properties:
      id:
        type: "integer"
      entries:
        type: "array"
        items:
          type: "string"
```
<img width="538" alt="Screen Shot 2020-05-18 at 17 14 21" src="https://user-images.githubusercontent.com/6262461/82264712-0e40e980-992b-11ea-9077-065aa2e02bde.png">

I need to write **entries** as a field since my API requires this name.

If I change **entries** to **entry**, it works as expected.

```yml
paths:
  /pet:
    post:
      summary: "Add a new pet to the store"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Pet:
    type: "object"
    properties:
      id:
        type: "integer"
      entry:
        type: "array"
        items:
          type: "string"
```

Can someone help me with this problem, why it fails when I use **entries** as a field name?

**Comment by vivvooren** [comment] 2020-05-19 06:48
I have the same problem with Version 3.23.3

**Comment by stiliyan** [comment] 2020-05-19 17:01
We found the issue is related to this change where the swagger fragment has a string "entries" property.

https://github.com/swagger-api/swagger-ui/blame/96c7b4cbf5e7208e74e18a6cf2d9a0260756914b/src/core/utils.js#L83-L87

**Comment by jlsjonas** [comment] 2020-05-20 11:26
Looks like this is caused by #5999

**Comment by tim-lai** [comment] 2020-05-20 17:30
@mke1ms @jlsjonas @stiliyan @jmmolina796 Thanks for reporting with details and suggestions! A fix is incoming and will be included in the next release.

**Closed** 2020-05-20 18:54 UTC
Labels: type: bug, type: regression

**Comment by RSkorina** [comment] 2020-05-20 20:50
I have a question about this change. The change has been merged but the error still occurs when using petstore. Is there another repository that needs to adopt swagger before using 'entries' as a parameter works when rendering?

**Comment by tim-lai** [comment] 2020-05-20 21:01
@RSkorina A new release of SwaggerUI will make this change visible on petstore.swagger.io

**Comment by katsisaac50** [comment] 2023-03-14 16:33
Your API definition is missing the OpenAPI/Swagger version number, in this case "swagger": "2.0" . Add it at the beginning, like so:

{
    "swagger": "2.0",
    "title" : "Music API Documentation",
    ...

this worked for me, details on https://copyprogramming.com/howto/swagger-unable-to-render-this-definition-the-provided-definition-does-not-specify-a-valid-version-field?utm_content=cmp-true
