### ISSUE TITLE
Swagger-UI - Uncaught TypeError when response includes an attachment

### ISSUE THREAD

**Issue by nurandhawa** [swagger-api/swagger-ui#2439] opened 2016-10-05 18:17 UTC
Hi Guys.

I found an issue where the swagger ui would keep loading when the response of a GET request contains an attachment. The response headers include `Content-Disposition →attachment; filename=example.txt` and `Content-Type →text/plain; charset=UTF-8` along some others. 
The error that I was getting was this: `Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.` 
To fix this, I had to make some changes in the swagger-ui.js. 
`@@ -23447,7 +23447,11 @@ SwaggerUi.Views.OperationView = Backbone.View.extend({`

         var type = contentType || 'text/html';
         var a = document.createElement('a');
         var href = window.URL.createObjectURL(content);
         var binaryData = [];
         binaryData.push(content);
         var href = window.URL.createObjectURL(new Blob(binaryData, {type: type}));
         var fileName = response.url.substr(response.url.lastIndexOf('/') + 1);
         var download = [type, fileName, href].join(':');

I am using swagger-ui-2.2.5. Can anyone confirm this error and if so, make the above mentioned changes and merge it? 

Thanks.

**Comment by tomsaleeba** [comment] 2016-10-13 03:35
I'm getting this error in Springfox 2.6 but AFAIK it uses swagger 2.2.5 completely untouched. I'm doing the same thing with Content-Disposition and it worked with Spring 2.5. I think this commit is what introduced the problem: https://github.com/swagger-api/swagger-ui/commit/80e548df0a46616380d8b6b9d90c50847cee70d5#diff-92930cfe0ffd368f7f1aec615128ca42L701

I assume that commit was made to fix something else so simply reversing the change might not be a solution :(

**Comment by fehguy** [comment] 2016-10-13 05:43
hmm, this was well tested.  Can you point to a sample server so it can be reproduced?

**Comment by tomsaleeba** [comment] 2016-10-13 08:10
Thanks for the quick reply. Luckily I can point to a sample server.

If you go to https://api.aekos.org.au/swagger-ui.html#!/Data_Retrieval_by_Species/speciesDataDotCsvUsingGET and enter `Abutilon aff. leucopetalum` for the species name and hit 'Try it out', it'll work (that is, return a result straight away). If you then change the `download` flag to `true` and try it again, you'll get the error in your JS console. This `download` flag is what triggers the Content-Disposition stuff to be set.

The method that's being called is https://github.com/adelaideecoinformatics/aekos-api/blob/master/src/main/java/au/org/aekos/controller/ApiV1SpeciesRetrievalController.java#L90

As I mentioned, I'm using Springfox 2.6 (which from https://github.com/springfox/springfox/commit/487e9742229901a02ac27ce8d1275f1f8e4b760c I understand uses swagger 2.2.5) so hopefully it's applicable. I'm also kind of n00by in this area so if I'm doing it wrong, I'm happy to be shown the light.

**Comment by fehguy** [comment] 2016-10-13 19:57
Thanks--I'm testing now and will report back.

**Comment by fehguy** [comment] 2016-10-13 22:50
Should be fixed, and tested against your API.  Please confirm!

**Closed** 2016-10-13 22:49 UTC

**Comment by tomsaleeba** [comment] 2016-10-14 02:56
It is indeed fixed. Thank you very much for the quick response and fix.

I've hacked together a fixed JAR and pushed to the server linked above so you can see the fix in action.

**Comment by satyakokku** [comment] 2019-08-09 09:15
MY WEBAPI CODE LOOKS LIKE ..even i am not able to download the excel file from SWAGGER UI.FILE IS CURRUPTED ERROR COMING 
**HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);

            response.Content = new StreamContent(stream);

            response.Content.Headers.ContentType = new MediaTypeHeaderValue("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            response.Content.Headers.ContentDisposition = new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment")
            {
                FileName = fileName
            };

            return response;**
