### ISSUE TITLE
Overriding SWAGGER_JSON and URL does not work for Docker distribution

### ISSUE THREAD

**Issue by sgwood63** [swagger-api/swagger-ui#5213] opened 2019-03-03 23:59 UTC
## Context
 - OS: Alpine (Docker)
 - Browser: any
- Method of installation: Docker
 - Swagger-UI version: 3.20.X and 3.21.X at least
 - Swagger/OpenAPI version: any

## SWAGGER_JSON environment variable ignored by Docker deployment

The Docker build of swaggerapi/swagger-ui does not work when overriding the SWAGGER_JSON with a mounted file as documented in https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md.

run.sh updates the nginx index.html if a mounted file $SWAGGER_JSON exists.
```
if [[ -f $SWAGGER_JSON ]]; then
  cp -s $SWAGGER_JSON $NGINX_ROOT
  REL_PATH="./$(basename $SWAGGER_JSON)"
  sed -i "s|https://petstore.swagger.io/v2/swagger.json|$REL_PATH|g" $INDEX_FILE
  sed -i "s|http://example.com/api|$REL_PATH|g" $INDEX_FILE
fi
```

Problem is that the base image used by swaggerapi/swagger-ui - FROM nginx:1.15-alpine - has a index.html.gz file which takes precedence over the index.html, so the updated index.html is ignored.

### To reproduce:

Have your swagger.json in /bar

docker pull swaggerapi/swagger-ui
docker run -p 80:8080 -e SWAGGER_JSON=/foo/swagger.json -v /bar:/foo swaggerapi/swagger-ui

Access swagger-ui @ http://<machine>/

Will see petstore, not your swagger.json.

### To reproduce:

Have your swagger.json in http://<machine>/swagger.json

docker pull swaggerapi/swagger-ui
docker run -p 80:8080 -e URL="http://<machine>/swagger.json" swaggerapi/swagger-ui

Access swagger-ui @ http://<machine>/

Will see petstore, not http://<machine>/swagger.json.

**Comment by innocencex** [comment] 2019-03-04 08:14
I have met with the same problem...

**Comment by mercuriete** [comment] 2019-03-04 10:41
same problem

**Comment by ChristianUlbrich** [comment] 2019-03-05 02:18
I think the problem is https://github.com/swagger-api/swagger-ui/pull/5199 because it gzip's the nginx-bundled `index.html` into `index.html.gz` on image **build time** which in turn, as @sgwood63 pointed out has precedence over the _generated_ index.html on **runtime**.

Basically the idea of "optimizing" html file on build does not make sense if there are some generated html files on runtime as well.

**Comment by shockey** [comment] 2019-03-05 21:05
Regression! 😱 

We'll ship a fix for this ASAP, probably later today.

**Comment by ChristianUlbrich** [comment] 2019-03-05 21:46
The gzipping should simply happen in the shell init script on runtime. I'd PR' it myself; but I won't be able to do so before the weekend...

**Closed** 2019-03-05 23:49 UTC
Labels: P0, cat: docker, type: regression

**Comment by shockey** [comment] 2019-03-06 00:06
Fixed! We've updated our `swaggerapi/swagger-ui:latest` and `swaggerapi/swagger-ui:v3.21.0` images on Docker Hub to include the patch from #5219.

I'm also going to build out a small integration test suite that pulls down a real Docker image and checks it for env var configuration effectiveness, so that we automatically catch this in our releases going forward.

Apologies for the disruption!

**Comment by anuras** [comment] 2019-03-08 21:05
Is it actually fixed? I seem to observe the same behaviour as described in the first post with setting SWAGGER_JSON, (running on Windows, though).

**Comment by shockey** [comment] 2019-04-09 23:39
@anuras, should be - can you make sure you're pulling a fresh image from Docker Hub? We overwrote existing tags to fix this, so you might have an old cached version locally.

**Comment by imcaizheng** [comment] 2019-04-12 07:58
@shockey 
Does it relevant to #3348?

**Comment by xshrim** [comment] 2019-07-10 01:45
you should use API_URL, not SWAGGER_JSON.
example:
`docker run -it -e API_URL=http://192.168.43.103:9090/swagger.json -p 8081:8080 swaggerapi/swagger-ui`
192.168.43.103 is host ip.

**Comment by sitetester** [comment] 2019-09-24 10:51
I have a swagger.json on my desktop, so running this command worked:

> docker run -p 9000:8080 -e SWAGGER_JSON=/mnt/swagger.json -v ~/Desktop:/mnt swaggerapi/swagger-ui

`localhost:9000` is loading correct file.
