### ISSUE TITLE
Broken layout in swagger-ui of fastapi

### ISSUE THREAD

**Issue by paymand** [swagger-api/swagger-ui#7292] opened 2021-05-20 14:50 UTC
Please see the original issue here: https://github.com/tiangolo/fastapi/issues/3255

### To reproduce...

1. Go to http://idril.softedgeuganda.info:5000/docs

### Expected behavior
Layout not broken.

### Screenshots
Layout is broken.

![image](https://user-images.githubusercontent.com/951563/119003317-e943e400-b98d-11eb-895f-8f3279e9eac3.png)

**Comment by paymand** [comment] 2021-05-20 14:51
Seems to be related to the latest release. i.e. 3.49.0.

**Comment by hkosova** [comment] 2021-05-20 15:50
Duplicate of #7290.

**Closed by hkosova** 2021-05-20 15:50 UTC
