### ISSUE TITLE
$ref of sibling yaml file not found

### ISSUE THREAD

**Issue by markdemich** [swagger-api/swagger-ui#4258] opened 2018-02-26 13:36 UTC
Swagger-ui Version 3.11.0 or 3.10.0

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 3.0
| Which Swagger-UI version?       | 3.11.0
| How did you install Swagger-UI? |  cdn.jsdelivr.net/npm/swagger-ui-dist
| Which browser & version?        | Chrome Version 63.0.3239.132 (Official Build) (64-bit), FF 58.0.2 (64-bit)
| Which operating system?         | Windows 10

### Demonstration API definition

Here is a simple example.  It's odd.  I've gotten this to not give an error sometimes.  I thought if I load api2.yaml prior to loading api1.yaml it worked.  But then when I tried later it did not.  Basically, I'm having issue referring to a sibling yaml file.

```yaml
```

### Configuration (browser query string, constructor, config.yaml)

api1.yaml
```
openapi: 3.0.0
info:
  description: |
    This is a test to show how model refererence from another file are failing.
    This file references api2.yaml.  If you load this file first in the browser it fails.
    However, if you load api2.yaml first, then load this one it will work.
  version: 1.0.0
  title: API1 Test
paths:
  '/test-api-1':        
    get:
      summary: Api 1
      responses:
        '200':
          description: 'api 2 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
components:
  schemas:
    Api1Prop:
      type: string
      example: 'api1prop-value'
      
    TestResponse:
      type: object
      properties:
        api1prop:
          $ref: '#/components/schemas/Api1Prop'
        api2prop:
          $ref: 'api2.yaml#/components/schemas/Api2Prop'
```
api2.yaml
```
openapi: 3.0.0
info:
  description: |
    This is a test to show how model refererence from another file are failing.
    This file is referenced api1.yaml.  If you load api1.yaml first in the browser it fails.
    However, if you load this file first, then load api1.yaml it will work.
  version: 1.0.0
  title: API2 Test
paths:
  '/test-api-2':        
    get:
      summary: Api 2
      responses:
        '200':
          description: api 2 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse2'
components:
  schemas:
    Api2Prop:
      type: string
      description: this is a api2prop
      example: 'api1prop-value'

    TestResponse2:
      type: object
      description: This is a test prop
      properties:
        api2prop:
          $ref: '#/components/schemas/Api2Prop'
```
### Expected Behavior

api1.yaml should reference api2.yaml without a problem if the files are siblings.

### Current Behavior

I receive an error when trying to reference api2.yaml.  I tried putting in a full url and I get 406 error because the accept header is application/json and my server will not allow it.

**Comment by markdemich** [comment] 2018-02-26 13:45
I think I figured out one of the mysteries.  When using version 3.10.0.  If I load api2.yaml first, then api1.yaml works.  If I use 3.11.0, then it never works regardless of the order.  So it kind of worked in 3.10.0, but doesn't work at all in 3.11.0

**Comment by heldersepu** [comment] 2018-02-26 13:52
@markdemich if you have time take a look at issue https://github.com/swagger-api/swagger-ui/issues/4214
This sounds like the same issue as that one

**Comment by heldersepu** [comment] 2018-02-26 15:03
Here is a link that shows the error:
http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/4258_p1_swagger.yaml&defaultModelsExpandDepth=5

We get: 
>Resolver error at components.schemas.TestResponse.properties.api2prop.$ref
Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: './api2.yaml' basePath: 'undefined'

Look like this might be a duplicate of #4214

**Closed** 2018-03-01 18:12 UTC
Labels: Regression

**Comment by shockey** [comment] 2018-03-01 19:42
Fixed! Thanks for the report @markdemich, sorry for the trouble.

You can review a build that contains the fix here: http://spooky-jellyfish.surge.sh/?url=https://gist.githubusercontent.com/shockey/bbfafa9a57a37d80348a558b2124e314/raw/2d03c5feb0b039d332519582b5e2e0b97365cf61/api1.yaml
