### ISSUE TITLE
Parameters at paths object's level are ignored

### ISSUE THREAD

**Issue by pleasedontbelong** [swagger-api/swagger-ui#1496] opened 2015-07-27 14:45 UTC
The [Specs for 2.0](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#user-content-pathItemParameters) for `parameters` in "Path Objects" says:
> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there.

In this example I define the parameters on the "path object" (`/pets/{id}`) and not inside the "operation object" ("get" and "delete") because it's a parameter that I apply to all operations

``` json
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Swagger Petstore (Simple)",
        "description": "A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification",
        "termsOfService": "http://helloreverb.com/terms/",
        "contact": {
            "name": "Swagger API team",
            "email": "foo@example.com",
            "url": "http://swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "http://opensource.org/licenses/MIT"
        }
    },
    "host": "petstore.swagger.wordnik.com",
    "basePath": "/api",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/pets/{id}": {
        	"parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "ID of pet",
                    "required": true,
                    "type": "integer",
                    "format": "int64"
                }
            ],
            "get": {
                "description": "Returns a user based on a single ID, if the user does not have access to the pet",
                "operationId": "findPetById",
                "produces": [
                    "application/json",
                    "application/xml",
                    "text/xml",
                    "text/html"
                ],
                "responses": {
                    "200": {
                        "description": "pet response",
                        "schema": {
                            "$ref": "#/definitions/pet"
                        }
                    },
                    "default": {
                        "description": "unexpected error",
                        "schema": {
                            "$ref": "#/definitions/errorModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "deletes a single pet based on the ID supplied",
                "operationId": "deletePet",
                "responses": {
                    "204": {
                        "description": "pet deleted"
                    },
                    "default": {
                        "description": "unexpected error",
                        "schema": {
                            "$ref": "#/definitions/errorModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pet": {
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "name": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "errorModel": {
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int32"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}
```

But SwaggerUi does not get that and doesn't display the parametter:

![selection_085](https://cloud.githubusercontent.com/assets/1785603/8908736/02640942-347e-11e5-81d3-0f5e44ec2688.png)

However If i define the same parameters on each operation I get the expected behaviour:

![selection_086](https://cloud.githubusercontent.com/assets/1785603/8908802/64627688-347e-11e5-93d6-768baac96bc7.png)

**Comment by webron** [comment] 2015-07-27 15:10
@pleasedontbelong - I really hate doing this because you've put a lot of effort into the bug submission (it's really awesome), but I'm afraid this is a duplicate of #1118.

**Closed by webron** 2015-07-27 15:10 UTC

**Comment by pleasedontbelong** [comment] 2015-07-27 15:21
@webron my fault for not searching correctly if there was a duplicate :P thxs!
