### ISSUE TITLE
Api display error

### ISSUE THREAD

**Issue by Alan-Lun** [swagger-api/swagger-ui#6924] opened 2021-02-09 09:32 UTC
### Q&A (please complete the following information)
 - OS: windows
 - Browser: edge
 - Version: 88.0.705.63
 - Method of installation: Nuget
 - Swagger-UI version: 

<PackageReference Include="NJsonSchema" Version="10.3.4" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.10.2" />
    <PackageReference Include="NSwag.Core" Version="13.10.2" />
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### Content & configuration

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

API expected display 68267599263309460 and 68267599263309459

But Swagger View display 68267599263309460 and 68267599263309460

### To reproduce...

``` CSharp
    <PackageReference Include="NJsonSchema" Version="10.3.4" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.10.2" />
    <PackageReference Include="NSwag.Core" Version="13.10.2" />
```

``` CSharp
[HttpGet]
        public ActionResult<TestLong> Get()
        {
            var data = new TestLong();
            data.Data = new List<long>();
            data.Data.Add(68267599263309460);
            data.Data.Add(68267599263309459);
            return this.Ok(data);
        }
```
``` CSharp
public class TestLong
    {
        public List<long> Data { get; set; }

    }
```

### Expected behavior

API expected display 68267599263309460 and 68267599263309459

But Swagger View display 68267599263309460 and 68267599263309460

### Screenshots

https://imgur.com/OFsB4Jw

**Comment by hkosova** [comment] 2021-02-09 11:47
Duplicate of #2030.

**Closed by hkosova** 2021-02-09 11:47 UTC
