### ISSUE TITLE
Self is not defined

### ISSUE THREAD

**Issue by jd-carroll** [swagger-api/swagger-ui#3291] opened 2017-06-24 20:36 UTC
- node version
```
$ node --version
v6.9.5
```
- swagger-ui version
```
"swagger-ui-dist": "^3.0.17",
```
- a swagger file reproducing the issue
```
npm install --save swagger-ui-dist
```
Sample file:
```
const express = require('express');
const app = express();
app.listen();
const swaggerDist = require('swagger-ui-dist');
const swaggerUiAssetPath = swaggerDist.getAbsoluteFSPath(); // <-- errors out
app.use('/swagger', express.static(swaggerUiAssetPath));
```

Full stack trace:
```
ReferenceError: self is not defined
    at Object.<anonymous> (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:73:22556)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:402)
    at Object.e.exports.e.__esModule.default (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:10755)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:110)
    at Object.<anonymous> (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:9958)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:110)
    at Object.e.exports.e.__esModule.default (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:11205)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:110)
    at Object.<anonymous> (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:73:1750)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:110)
    at c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:493
    at Object.<anonymous> (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:72:503)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:402)
    at Object.e.exports.n.(anonymous function).i (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:71:31725)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:402)
    at Object.t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:39:4816)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:402)
    at Object.t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:39:3431)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:402)
    at Object.<anonymous> (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:15146)
    at t (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:402)
    at Object.<anonymous> (c:\dev\cpt\ads\ads-web-services\node_modules\swagger-ui-dist\swagger-ui-bundle.js:1:802)
```

**Comment by shockey** [comment] 2017-06-26 19:24
I'm able to reproduce this - thanks for reporting!

**Comment by shockey** [comment] 2017-06-26 22:05
The problem here is that we're [importing the bundle and Standalone preset](https://github.com/swagger-api/swagger-ui/blob/master/swagger-ui-dist-package/index.js#L1) in the main file for the module. 

This is great for people using `swagger-ui-dist` in a webapp (see https://github.com/swagger-api/swagger-ui/pull/3126), but isn't getting along well with Node.

We can't remove the references, because that would be a breaking change - we'd have to bump the major version for `swagger-ui-dist`, which is not acceptable because we want to track `swagger-ui`'s version. It would also completely drop a community-contributed feature, which isn't great.

It may be possible to detect at runtime what context we're running in. I'm going to try out some solutions and try to get this fixed by Friday.

To all - comments and PRs around this are welcome.

**Comment by goinggood** [comment] 2017-06-29 09:26
\swagger-api-doc\swagger-ui-bundle.js:73
j.default)("JSONRefError",function(e,t,n){this.originalError=n,(0,T.default)(this,t||{})}),L={},z=new C.default,q={key:"$ref",plugin:function(e,t,n,r){var u=n.slice(0,-1),c=r.getContext(n).baseDoc;if("string"!=typeof e)return new B("$ref: must be a string (JSON-Ref)",{$ref:e,baseDoc:c,fullPath:n});var l=a(e),p=l[0],h=l[1]||"",d=void 0;try{d=c||p?i(p,c):null}catch(t){return o(t,{pointer:h,$ref:e,basePath:d,fullPath:n})}var m=void 0,v=void 0;if(!y(h,d,u,r)){if(null==d?(v=f(h),void 0===(m=r.get(v))&&(m=new B("Could not resolve reference: "+e,{pointer:h,$ref:e,baseDoc:c,fullPath:n}))):(m=s(d,h),m=null!=m.__value?m.__value:m.catch(function(t){throw o(t,{pointer:h,$ref:e,baseDoc:c,fullPath:n})})),m instanceof Error)return[N.default.remove(n),m];var _=N.default.replace(u,m,{$$ref:e});return d&&d!==c?[_,N.default.context(u,{baseDoc:d})]:g(r.state,_)?void 0:_}}},U=(0,T.default)(q,{docCache:L,absoluteify:i,clearCache:u,JSONRefError:B,wrapError:o,getDoc:c,spl

ReferenceError: self is not defined

We are facing this issue with swagger api. 
Appreciate the early solution to this issue.

**Comment by homerjam** [comment] 2017-07-04 10:31
+1

**Comment by shockey** [comment] 2017-07-04 17:09
This should be fixed next time the projects are released - I wrapped the require calls for the SwaggerUIBundle and SwaggerUIStandalonePreset in a try/catch in #3336, which should keep the whole module from exploding when that happens in a Node context.

I'll close this issue once the projects are released with a fix - once that's done, I invite everyone that has commented to update if the issue is resolved from your end.

**Comment by shockey** [comment] 2017-07-08 01:35
Releasing now, so this fix should be live shortly.

**Closed by shockey** 2017-07-08 01:35 UTC
Labels: Bug, P1, Pending release

**Comment by chaitralisk** [comment] 2017-07-10 12:51
Hi
I am working on swagger-ui. But I am getting this issue::
swagger-ui-standalone-preset.js:2 Uncaught SyntaxError: Unexpected token <
(index):76 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload ((index):76)

**Comment by shockey** [comment] 2017-07-10 16:25
@chaitralisk, are you sure you're loading `swagger-ui-bundle.js` into your page? I get a similar error if I comment out [this line](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L70),

**Comment by chaitralisk** [comment] 2017-07-11 06:54
Yes, I am loading`swagger-ui-bundle.js` into page.I have created nodejs server which will load index.html file.
But I am getting:
swagger-ui-standalone-preset.js:2 Uncaught SyntaxError: Unexpected token <
(index):76 Uncaught ReferenceError: SwaggerUIBundle is not defined
at window.onload ((index):76)

**Comment by shockey** [comment] 2017-07-12 18:40
@chaitralisk, can you please open a new ticket so we can help you with this? I want to minizine the noise for the five people getting emails about this thread.
