### ISSUE TITLE
Swagger UI doesn't indicate by red asterix required field

### ISSUE THREAD

**Issue by piotrzarzycki21** [swagger-api/swagger-ui#4899] opened 2018-09-26 11:57 UTC
### Q&A (please complete the following information)
 - OS: Windows 10 64bit
 - Browser: Chrome 
 - Version: 69.0.3497.100 (Official Build) (64-bit)
 - Method of installation: dist
 - Swagger-UI version: 3.19.0
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```
 "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                    "$ref": "./schemas/body/myFile.json#/someFile"
                }
              }
            }
},
```

and someFile is:

```
{
  "someFile": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "required": "true"
      }
    }
  }
}
```

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
        url: "myfile.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
```

### Describe the bug you're encountering
I have request body which is being described by external file. One of the property is required, unfortunately it's not indicated in Swagger UI.

### To reproduce...

1. Create request body where schema is in separate file
2. Make sure that one of the property of that object is required
3. Launch Swagger UI

### Expected behavior
Required property should  be marked by red asterix 

### Screenshots
![swagger_ui](https://user-images.githubusercontent.com/24554795/45607923-f6c3a600-ba4f-11e8-923a-e54415c8f332.png)

### Additional context or thoughts
None

**Comment by hkosova** [comment] 2019-07-05 09:21
@shockey this is not a bug, it's an invalid definition.

`required` is not a property attribute, it's an object-level attribute containing a list of required properties.

```yaml
            schema:
              type: object
              required: [a]   # <-- Correct
              properties:
                a:
                  type: string
                  # required: true # <-- Wrong
```

**Comment by shockey** [comment] 2019-07-09 00:41
Good catch @hkosova -- closing!

**Closed by shockey** 2019-07-09 00:41 UTC
Labels: cat: rendering, cat: try-it-out, type: bug
