### ISSUE TITLE
invalid json

### ISSUE THREAD

**Issue by hortPT** [swagger-api/swagger-ui#1513] opened 2015-08-05 14:18 UTC
Hello,

I'm trying the swagger 2.0 and I have the following error:
Partial swagger.json (might be missing some portions)

--------------------------- CODE ----------------

``` javascript
{"swagger":"2.0",
    "info":{"description":"Test API","version":"1.0.0","title":"Test API","termsOfService":"http://www.test.com/en/api/terms/","contact":{"email":"web@test.com"}, "license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"}
    },
    "host":"192.168.1.120",
    "basePath":"/test/en/api",
    "tags":[
        {"name":"user","description":"Operations about user","externalDocs":{"description":"Find out more about our store","url":"http://swagger.io"}},
        {"name":"booking","description":"Creating a booking","externalDocs":{"description":"Find out more about our store","url":"http://swagger.io"}}
    ],
    "schemes":["http"],
    "paths":{
        "/booking":{
            "post":{
                "tags":["booking"],
                "summary":"Create a new booking",
                "description":"",
                "operationId":"createBooking",
                "consumes":["application/json","application/xml"],
                "produces":["application/xml","application/json"],
                "parameters":[                      {"name":"sign","in":"formData","description":"Hash key","required":true,"type":"string"},                   {"name":"booking","in":"formData","description":"bookings","required":true,"type":"array", "items": {"$ref":"#/definitions/Booking"}},
    "definitions":{
        "Booking":{
                "type":"object",
                "required": ["client", "type", "payment", "services"],
                "properties":{
                        "client": {"description":"Client's name","type":"array", "items": {"$ref":"#/definitions/Client"}}
],              
    "responses":{"400":{"description":"Invalid Parameter (read info)"}},
            }
        },
                },
                "xml":{"name":"Booking"}
        },
        "Client":{
                "type":"object",
                "required": ["name", "email", "country", "phone"],
                "properties":{
                        "name":{"type":"string"},
                        "email":{"type":"string"},
                        "country":{
                                "required":true,
                                "type":"integer",
                                "format":"int32",
                                "description":"From countries list"
                        },
                        "phone":{"type":"string"},

                },
                "xml":{"name":"Client"}
        }
}
}
```

CURL
curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" -d "sign=b538833389c66a2aaddb2dd11cf6460c&booking=%5B%2C%20%20%7B%2C%20%20%20%20%22client%22%3A%20%5B%2C%20%20%20%20%20%20%7B%2C%20%20%20%20%20%20%20%20%22name%22%3A%20%22string%22%2C%2C%20%20%20%20%20%20%20%20%22email%22%3A%20%22string%22%2C%2C%20%20%20%20%20%20%20%20%22country%22%3A%200%2C%2C%20%20%20%20%20%20%20%20%22phone%22%3A%20%22string%22%2C%20%20%20%20%20%20%7D%2C%20%20%20%20%5D%2C%20%20%7D%2C%5D" "http://192.168.1.120/test/en/api/booking"

BODY RESPONSE (PHP booking variable post output)
[,  {,    "client": [,      {,        "name": "string",,        "email": "string",,        "country": 0,,        "phone": "string",      },    ],  },]
--------------------------- / CODE ----------------
What is wrong?? Thank you for your help.

**Comment by webron** [comment] 2015-08-05 15:04
That's not a valid JSON. It looks like it was cut off after the `parameters` definition. You open an array and don't close it, but based on the structure it seems more is missing beyond it.

**Comment by hortPT** [comment] 2015-08-05 16:17
Here is the full json
```javascript
{"swagger":"2.0",
	"info":{"description":"TEST API","version":"1.0.0","title":"TEST API", "termsOfService":"http://www.test.com/en/api/terms/","contact":{"email":"web@test.com"}, "license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"}
	},
	"host":"192.168.1.120",
	"basePath":"/test/en/api",
	"tags":[
		{"name":"user","description":"Operations about user","externalDocs":{"description":"Find out more about our store","url":"http://swagger.io"}},
		{"name":"booking","description":"Creating a booking","externalDocs":{"description":"Find out more about our store","url":"http://swagger.io"}}
	],
	"schemes":["http"],
	"paths":{
		"/booking":{
			"post":{
				"tags":["booking"],
				"summary":"Create a new booking",
				"description":"",
				"operationId":"createBooking",
				"consumes":["application/json","application/xml"],
				"produces":["application/xml","application/json"],
				"parameters":[
				{"name":"sign","in":"formData","description":"Hash key","required":true,"type":"string"},					{"name":"booking","in":"formData","description":"bookings","required":true,"type":"array", "items": {"$ref":"#/definitions/Booking"}}
],				
				"responses":{"400":{"description":"Invalid Parameter (read info)"}},
			}
		},
	},
	"definitions":{
		"Booking":{
				"type":"object",
				"required": ["client"],
				"properties":{
						"client": {"description":"Client's name","type":"array", "items": {"$ref":"#/definitions/Client"}}
				},
				"xml":{"name":"Booking"}
		},
		"Client":{
				"type":"object",
				"required": ["name", "email", "country", "phone"],
				"properties":{
						"name":{"type":"string"},
						"email":{"type":"string"},
						"country":{
								"required":true,
								"type":"integer",
								"format":"int32",
								"description":"From countries list"
						},
						"phone":{"type":"string"},
						
				},
				"xml":{"name":"Client"}
		}
		},	
	"externalDocs":{"description":"Find out more about TEST","url":"http://www.test.com"}
}

```
Plus image from swagger

![swagger](https://cloud.githubusercontent.com/assets/13660932/9090958/5556dc92-3b95-11e5-859b-a6ce92fbe6d0.png)

Hope this helps.to find the issue.

**Comment by webron** [comment] 2015-08-05 16:24
That's still not a valid JSON.

**Comment by hortPT** [comment] 2015-08-05 16:59
You are right sorry (to many end commas!)

Here is the corrected json

```javascript
{"swagger":"2.0",
    "info":{"description":"TEST API","version":"1.0.0","title":"TEST API", "termsOfService":"http://www.test.com/en/api/terms/","contact":{"email":"web@test.com"}, "license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0.html"}
    },
    "host":"192.168.1.120",
    "basePath":"/test/en/api",
    "tags":[
        {"name":"user","description":"Operations about user","externalDocs":{"description":"Find out more about our store","url":"http://swagger.io"}},
        {"name":"booking","description":"Creating a booking","externalDocs":{"description":"Find out more about our store","url":"http://swagger.io"}}
    ],
    "schemes":["http"],
    "paths":{
        "/booking":{
            "post":{
                "tags":["booking"],
                "summary":"Create a new booking",
                "description":"",
                "operationId":"createBooking",
                "consumes":["application/json","application/xml"],
                "produces":["application/xml","application/json"],
                "parameters":[
                {"name":"sign","in":"formData","description":"Hash key","required":true,"type":"string"},                   {"name":"booking","in":"formData","description":"bookings","required":true,"type":"array", "items": {"$ref":"#/definitions/Booking"}}
],              
                "responses":{"400":{"description":"Invalid Parameter (read info)"}}
            }
        }
    },
    "definitions":{
        "Booking":{
                "type":"object",
                "required": ["client"],
                "properties":{
                        "client": {"description":"Clients name","type":"array", "items": {"$ref":"#/definitions/Client"}}
                },
                "xml":{"name":"Booking"}
        },
        "Client":{
                "type":"object",
                "required": ["name", "email", "country", "phone"],
                "properties":{
                        "name":{"type":"string"},
                        "email":{"type":"string"},
                        "country":{
                                "required":true,
                                "type":"integer",
                                "format":"int32",
                                "description":"From countries list"
                        },
                        "phone":{"type":"string"}
                },
                "xml":{"name":"Client"}
        }
    },  
    "externalDocs":{"description":"Find out more about TEST","url":"http://www.test.com"}
}
```

Also made a php variable from the json string and print_r(json_encode($x)) works fine 

1) Is it a bug for swagger to accept invalid json?
2) The error reported continues...

Thank you.

**Comment by webron** [comment] 2015-08-05 18:50
Okay, I'm not sure what the problem is. What *is* the error you're getting? Where do you see it? What steps to do take to produce the error?

**Comment by hortPT** [comment] 2015-08-06 09:41
OK.

I am using github.com/chriskacerguis/codeigniter-restserver and in my method "booking" I am just outputing the post receive by swagger (response body, image on the previous post)

```javascript
[, {, "client": [, {, "name": "string",, "email": "string",, "country": 0,, "phone": "string", }, ], },]
```
which is an invalid JSON format.

When I click on the "model schema" and it passes the JSON to the textarea value all pretty with newline and spaces (or tabs) all indented.
With the try it out the response is an invalid JSON.
However I have tried to remove all the newlines and spaces in the textarea value,  it works!

Example 1)
textarea value
```javascript
[{"client":[{"name":"string","email": "string","country": 0,"phone": "string"}]}]
```
response body (valid JSON)
```javascript
[{"client":[{"name":"string","email": "string","country": 0,"phone": "string"}]}] 
```
Example 2)
textarea value
```javascript
[
{"client":[{"name":"string","email": "string","country": 0,"phone": "string"}]}
]
```
response body (invalid JSON)
```javascript
[,{"client":[{"name":"string","email": "string","country": 0,"phone": "string"}]},] 
```

Hope this helps to understand the issue.

Thank you.

**Comment by hortPT** [comment] 2015-08-06 14:47
@webron I have found the place where this happens and replace two lines, how it works just fine... 

```javascript
  getTextAreaValue: function(textArea) {
    var param, parsed, result, i;
    if (textArea.value === null || jQuery.trim(textArea.value).length === 0) {
      return null;
    }
    param = this.getParamByName(textArea.name);
    if (param && param.type && param.type.toLowerCase() === 'array') {
      parsed = textArea.value.split('\n');
     result = ''; //[]; changed to string
      for (i = 0; i < parsed.length; i++) {
        if (parsed[i] !== null && jQuery.trim(parsed[i]).length > 0) {
          //result.push(parsed[i]);
          result += parsed[i]; //concatenate instead of push
        }
      }
      return result.length > 0 ? result : null;
    } else {
      return textArea.value;
    }
  },

**Comment by webron** [comment] 2017-03-20 22:27
This should no longer be an issue with 3.0. Please reopen if needed.

**Closed by webron** 2017-03-20 22:27 UTC
Labels: Support
