### ISSUE TITLE
Move init code from `dist/index.html` into a separate file?

### ISSUE THREAD

**Issue by bebraw** [swagger-api/swagger-ui#952] opened 2015-02-23 18:01 UTC
Currently consuming the project as a NPM dependency is a little bit problematic. You'll have to set up a build to copy `/dist` somewhere and then overwrite `index.html` with a custom one. The problem with this is that `index.html` might have received changes beyond just JavaScript (ie. deps change or something).

To make it easier to consume `swagger-ui` this way it would be beneficial to push the init bit (ie. `$(function () { ...`) into a separate file (say `init.js`) and point at that from `index.html`. In this case you would effectively avoid the problem I described above as long as the file name remains the same.

Related to https://github.com/apigee-127/swagger-tools/issues/163 .

**Comment by webron** [comment] 2015-02-23 18:04
I believe this is a duplicate of #804.

**Closed by webron** 2015-02-23 18:04 UTC

**Comment by bebraw** [comment] 2015-02-23 18:05
Yeah. Excellent point!
