### ISSUE TITLE
Sub and Superclasses have the same name

### ISSUE THREAD

**Issue by Jonsen94** [swagger-api/swagger-ui#3147] opened 2017-05-30 10:54 UTC
Swagger-ui version 3.x

When using the given json file (created with swagger annotations) the subclasses in the model view have the same names as the superclasses.
So there are 3 different classes shown with different fields but their name is the same.

```
{
  "swagger" : "2.0",
  "info" : {
    "description" : "*****",
    "version" : "0.0.1",
    "title" : "****",
    "contact" : {
      "name" : "****"
    }
  },
  "basePath" : "/api",
  "tags" : [ {
    "name" : "configurator"
  } ],
  "schemes" : [ "http", "https" ],
  "paths" : {
    "/configurator/compositionmodels" : {
      "post" : {
        "tags" : [ "configurator" ],
        "summary" : "Starts a configuration process.",
        "description" : "",
        "operationId" : "postConfigCompositionModel",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/RequirementsSpec"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "UUID to refer to this request.",
            "schema" : {
              "type" : "string",
              "format" : "uuid"
            }
          },
          "400" : {
            "description" : "Error message in the body. Depends on the problem.",
            "schema" : {
              "type" : "string"
            }
          }
        }
      }
    },
    "/configurator/compositionmodels/{uuid}/dataflow/{count}" : {
      "get" : {
        "tags" : [ "configurator" ],
        "summary" : "Returns the dataflow visualization of the first {count} compositions.",
        "description" : "",
        "operationId" : "getCompositionAsDataflow",
        "produces" : [ "text/plain" ],
        "parameters" : [ {
          "name" : "uuid",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        }, {
          "name" : "count",
          "in" : "path",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "Composition's dataflow.",
            "schema" : {
              "type" : "string"
            }
          },
          "400" : {
            "description" : "Error message in the body. Depends on the problem.",
            "schema" : {
              "type" : "string"
            }
          }
        }
      }
    },
    "/configurator/compositionmodels/{uuid}/results" : {
      "get" : {
        "tags" : [ "configurator" ],
        "summary" : "Prints an textual representation of a composition.",
        "description" : "",
        "operationId" : "getCompositionModel",
        "produces" : [ "text/plain" ],
        "parameters" : [ {
          "name" : "uuid",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        } ],
        "responses" : {
          "200" : {
            "description" : "Composition as a text. Beginning with current status.",
            "schema" : {
              "type" : "string"
            }
          },
          "400" : {
            "description" : "Error message in the body. Depends on the problem.",
            "schema" : {
              "type" : "string"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "Number" : {
      "type" : "object"
    },
    "OTFSimpleMatchingResultRequirement" : {
      "allOf" : [ {
        "$ref" : "#/definitions/OTFMatchingResultRequirement"
      }, {
        "type" : "object",
        "properties" : {
          "minValue" : {
            "type" : "number",
            "format" : "double"
          }
        }
      } ]
    },
    "OTFMatchingResultRequirement" : {
      "type" : "object",
      "discriminator" : "matchingType"
    },
    "OTFReputationCondition" : {
      "type" : "object",
      "required" : [ "context", "requestedFiveStarRange" ],
      "properties" : {
        "context" : {
          "type" : "string",
          "enum" : [ "OVERALL", "USABILITY", "PERFORMANCE", "SECURITY", "OTHER" ]
        },
        "requestedFiveStarRange" : {
          "type" : "string",
          "enum" : [ "ONE", "TWO", "THREE", "FOUR", "FIVE" ]
        },
        "operator" : {
          "type" : "string",
          "enum" : [ "GREATER", "GREATER_OR_EQUAL", "APPROX_GREATER_OR_EQUAL" ]
        }
      }
    },
    "OTFReputationRequest" : {
      "type" : "object",
      "required" : [ "matchingResultReq", "reputationConditions" ],
      "properties" : {
        "reputationConditions" : {
          "type" : "array",
          "readOnly" : true,
          "items" : {
            "$ref" : "#/definitions/OTFReputationCondition"
          }
        },
        "matchingResultReq" : {
          "$ref" : "#/definitions/OTFMatchingResultRequirement"
        }
      }
    },
    "OTFFuzzyMatchingResultRequirement" : {
      "allOf" : [ {
        "$ref" : "#/definitions/OTFMatchingResultRequirement"
      }, {
        "type" : "object",
        "properties" : {
          "minLowerBound" : {
            "type" : "number",
            "format" : "double"
          },
          "minUpperBound" : {
            "type" : "number",
            "format" : "double"
          }
        }
      } ]
    },
    "RequirementsSpecLiteral" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "params" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        }
      }
    },
    "RequirementsSpecParameter" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "datatype" : {
          "type" : "string"
        }
      }
    },
    "OTFMatchingSpecification" : {
      "type" : "object",
      "properties" : {
        "qualityInputParams" : {
          "type" : "number",
          "format" : "double"
        },
        "qualityOutputParams" : {
          "type" : "number",
          "format" : "double"
        },
        "qualityPreconditions" : {
          "type" : "number",
          "format" : "double"
        },
        "qualityEffects" : {
          "type" : "number",
          "format" : "double"
        }
      }
    },
    "RequirementsSpec" : {
      "type" : "object",
      "required" : [ "effect", "inputParams", "matchingSpecification", "nonFunctionalRequirements", "operationName", "outputParams", "preCondition", "strategy", "timeout" ],
      "properties" : {
        "operationName" : {
          "type" : "string"
        },
        "inputParams" : {
          "type" : "array",
          "readOnly" : true,
          "items" : {
            "$ref" : "#/definitions/RequirementsSpecParameter"
          }
        },
        "outputParams" : {
          "type" : "array",
          "readOnly" : true,
          "items" : {
            "$ref" : "#/definitions/RequirementsSpecParameter"
          }
        },
        "preCondition" : {
          "type" : "array",
          "readOnly" : true,
          "items" : {
            "$ref" : "#/definitions/RequirementsSpecLiteral"
          }
        },
        "effect" : {
          "type" : "array",
          "readOnly" : true,
          "items" : {
            "$ref" : "#/definitions/RequirementsSpecLiteral"
          }
        },
        "nonFunctionalRequirements" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Number"
          }
        },
        "requester" : {
          "type" : "string"
        },
        "timeout" : {
          "type" : "integer",
          "format" : "int64"
        },
        "matchingSpecification" : {
          "$ref" : "#/definitions/OTFMatchingSpecification"
        },
        "strategy" : {
          "type" : "string",
          "enum" : [ "E_BFS", "E_DFS", "E_FAST", "E_NF" ]
        },
        "reputationRequest" : {
          "type" : "array",
          "readOnly" : true,
          "items" : {
            "$ref" : "#/definitions/OTFReputationRequest"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment] 2017-05-30 23:15
Duplicate of #2946.

**Closed by webron** 2017-05-30 23:15 UTC
