### ISSUE TITLE
Bug - mediaType level examples are not rendered in Chrome

### ISSUE THREAD

**Issue by Ostro** [swagger-api/swagger-ui#4733] opened 2018-07-16 10:20 UTC
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 67
 - Method of installation: none, using editor live version https://editor.swagger.io 
 - Swagger/OpenAPI version: openapi 3

### Content & configuration
Here is my schema

```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Examples
paths:
  /user:
    get:
      summary: Adds a new user
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:    # Child of media type
                id: 11
                name: Ron Stewart    
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
```

### Describe the bug you're encountering
I'm switch my swagger v2 doc to openApi v3. I'm experiencing trouble using examples
i'm following doc example: https://swagger.io/docs/specification/adding-examples/
I want to add example to the response of my route. 

### To reproduce...

1. Go to https://editor.swagger.io/ and use the schema above.
2. Click on get /user
3. Scroll down to response 200 example text box
4. Example is not rendered

### Expected behavior
I should see
```javascript
{
  id: 20,
  name: "Ron Stewart"
}
```
displayed in example box

### Additional context or thoughts
I don't know if this is a poor schema design from me or if there is some trouble in swagger-ui.
I'm more likely to think it's me but, i can't figure it out. 
Editor says there is an error line 10, and i don't understand the error, this might be the cause.

**Comment by bestmike007** [comment] 2018-07-16 10:47
Could you please upload your api doc?

**Comment by hkosova** [comment] 2018-07-16 13:03
This looks like a duplicate of https://github.com/swagger-api/swagger-ui/issues/3437.

Support for `example` was [implemented](https://github.com/swagger-api/swagger-ui/releases/tag/v3.17.4) in the latest release of Swagger UI, 3.17.4. Swagger Editor was not updated yet, but I guess these changes will be included in the next Editor release as well.

@Ostro If you need `example` support in the Editor now, you can [build a local copy of the Editor](https://github.com/swagger-api/swagger-editor#building-and-running-an-image-locally) with the latest version of Swagger UI.

**Comment by Ostro** [comment] 2018-07-17 04:11
@hkosova I installed swagger-ui from docker 
`Pulling swagger (swaggerapi/swagger-ui:3.17.4)...`

I am using your tests from your previous PR you mentioned 

Here is my swagger.yml

```yaml
openapi: 3.0.0
servers:
- url: http://example.com/v1
  description: Production server version 1
- url: http://staging-api.example.com
  description: Staging server
info:
  description: 'This is an API documentation of example.

'
  version: 0.1.0
  title: Example
  termsOfService: http://www.example.com/terms/
  contact:
    email: developer@example.com
  license:
    name: Proprietary license
    url: http://www.example.com/license/
tags:
- name: agent
  description: Access to example
paths:
  "/agents/{agentId}":
    put:
      tags:
      - agent
      summary: Edit agent
      operationId: editAgent
      parameters:
      - in: path
        name: agentId
        schema:
          type: integer
        example: 12345
        required: true
        description: Numeric ID of the paper agent to edit
      requestBody:
        required: true
        content:
          application/json_media-type-level:
            schema:
              type: object
              properties:
                code:
                  type: string
                name:
                  type: string
            example:
              code: AE1
              name: Andrew
          application/json_schema-level:
            schema:
              type: object
              properties:
                code:
                  type: string
                name:
                  type: string
              example:
                code: AE1
                name: Andrew
          application/json_property-level:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: AE1
                name:
                  type: string
                  example: Andrew
      responses:
        '200':
          description: media type-level example
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                          readOnly: true
                        code:
                          type: string
                        name:
                          type: string
              example:
                code: 200
                payload:
                - id: 1
                  code: AE2
                  name: Yono
        '201':
          description: schema-level example
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                          readOnly: true
                        code:
                          type: string
                        name:
                          type: string
                example:
                  code: 201
                  payload:
                  - id: 1
                    code: AE2
                    name: Yono
        '202':
          description: property-level example
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                    example: 202
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                          readOnly: true
                          example: 1
                        code:
                          type: string
                          example: AE2
                        name:
                          type: string
                          example: Yono
```

either for response or body request, media-type example are not rendered
schema and property level are working great.

here is a screenshot in Chrome
<img width="1588" alt="capture d ecran 2018-07-17 a 12 09 44" src="https://user-images.githubusercontent.com/4363418/42796109-756a9070-89ba-11e8-9d11-8a08f026512a.png">

Safari is OK thought

**Comment by hkosova** [comment] 2018-07-17 11:17
@Ostro if you open your Swagger UI in Chrome, then open the browser console and evaluate `versions` - which version does it show?

**Comment by shockey** [comment] 2018-08-16 00:47
This is working for me on Chrome:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/680248/44180794-34c95500-a0b3-11e8-99a0-63accf4c5dfe.png">

I'm going to close this out, since it appears to be fixed. Please bump this issue if there are any outstanding concerns.

**Closed by shockey** 2018-08-16 00:47 UTC
