### ISSUE TITLE
Referenced Example shows in Swagger UI

### ISSUE THREAD

**Issue by SOTFNicole** [swagger-api/swagger-ui#5756] opened 2019-12-18 14:25 UTC
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: Chrome version 79.0.3945.79 (Official Build) (64-bit)
 - Swagger-UI version: 3.24.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```openapi: 3.0.0
tags:
  - name: myTag
    description: Operations on myTags
paths:
  '/myTag/{id}':
    get:
      tags:
        - myTag
      operationId: get
      parameters:
        - in: path
          name: id
          description: The id.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detail'
              examples:
                GlutenFree:
                  $ref: '#/components/examples/GlutenFree'
examples:
    EnglishLanguage:
      value:
        id: 1
        code: "EN"
        name: "English"
    GlutenFree:
      value:
        id: 10
        name: "Gluten-Free"
        type: "Boolean"
        display: 
          - id: 1
            language:
              $ref: '#/components/examples/EnglishLanguage/value'
            displayText: "Gluten-Free"
        internalDescription: "Sets values if the product is free of gluten."
```

### Describe the bug you're encountering
I am attempting to setup examples in my Swagger UI. But when an example's property references another example the reference is included.

In the screenshot below you can see that my example "GlutenFree" has a reference to the English language example. The properties are displaying as expected, but the "ref" field is unexpected.
![image](https://user-images.githubusercontent.com/48130448/71093674-a9187a80-2177-11ea-8360-30f7864d6a55.png)

### Expected behavior
I would not expect to see
"$$ref": "#/components/examples/EnglishLanguage/value"

**Comment by hkosova** [comment] 2019-12-18 15:29
The `value` keyword does not support `$ref`. The whole example value must be specified inline.

```yaml
components:
  examples:
    GlutenFree:
      value:
        id: 10
        name: "Gluten-Free"
        type: "Boolean"
        display: 
          - id: 1
            language:  # <-------
              id: 1
              code: "EN"
              name: "English"
            displayText: "Gluten-Free"
        internalDescription: "Sets values if the product is free of gluten."
```
The actual issue here is that Swagger UI tries tries to resolve that `$ref`. This is most likely a duplicate of #5625.

**Comment by SOTFNicole** [comment] 2019-12-18 16:04
I concur

**Comment by webron** [comment] 2019-12-18 21:06
Yup, it's the same issue. Closing as duplicate.

**Closed by webron** 2019-12-18 21:06 UTC
