### ISSUE TITLE
UI shows wrong title/description for composed model schema

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#3417] opened 2017-07-19 19:54 UTC
When viewing the OpenAPI definition in the attached OpenAPI definition, the Models section of the Swagger UI (3.0.19) does not render the model titles and descriptions correctly. This definition uses schema composition with `allOf` to combine schema. 

[duplicate-models.yaml.txt](https://github.com/swagger-api/swagger-ui/files/1160284/duplicate-models.yaml.txt)

There is a base schema named `createModel`
```YAML
  createModel:
    title: "Create Model"
    description: "The representation used to create a new model."
    properties:
      name:
        type: "string"
```
then two derived schema `updateModel` and `model` which define an inheritance hierarchy `createModel` -> `updateMode` -> `model` via `allOf` / `$ref`,
 but each with their own title and description.
```
  updateModel:
    title: "Update Model"
    description: "The representation used to update a model."
    allOf:
    - $ref: "#/definitions/createModel"
    - type: "object"
      properties:
  model:
    title: "Model"
    description: "The representation of a model."
    allOf:
    - $ref: "#/definitions/updateModel"
    - type: "object"
      properties:
```
Similarly, there is another schema `baseCollection2` and another model schema `modelCollection` which is defined via `allOf` with `$ref: "#/definitions/baseCollection2"`

As shown by the attached screen shots, the `updateModel` and `model` schema have the wrong title ("Create Model") and description, although the members are correct. All three have the same description, from `createModel`

![wrong-model-titles-descriptions-1](https://user-images.githubusercontent.com/545944/28386716-6de047f2-6c9a-11e7-8af6-fc78da4ea2cc.png)

Similarly, both `baseCollection2` and `modelCollection` use the title and description from `baseCollection2` instead of the title/description for `modelCollection`:  "Model Summary Collection" and "A collection of model representations." respectively.

![wrong-model-titles-descriptions-2](https://user-images.githubusercontent.com/545944/28386739-7e52dd66-6c9a-11e7-9b61-d767f79464ce.png)

**Comment by hkosova** [comment] 2017-07-20 07:26
@webron looks like a duplicate of #2946.

**Comment by webron** [comment] 2017-07-20 22:37
Thanks @hkosova, that's true. Closing as duplicate. @DavidBiesack - Thanks for the detailed report though, it's very helpful.

**Comment by shockey** [comment] 2017-08-02 19:37
Reopening - this is not a duplicate of #2946. As I noted there:

> [#2946] centers around inheriting the name based on the key name of the model, and [this issue] has to do with the title property.
>
> https://github.com/swagger-api/swagger-ui/issues/2946#issuecomment-319763679

Sorry about the mixup, @DavidBiesack!

@owenconti, feel free to assign yourself if this sounds like something you can tackle - I recall you tackled some allOf merging issues recently.

**Comment by mxmader** [comment] 2017-08-23 21:47
@DavidBiesack I encountered a similar scenario, but dealt with it by moving `title` underneath the second list item of `allOf` (beneath the array item with the `$ref` key). I believe a restated version of your original schema will express this point:

```yaml
  updateModel:
    description: "The representation used to update a model."
    allOf:
    - $ref: "#/definitions/createModel"
    - title: "Update Model"
      type: "object"
      properties:
  model:
    description: "The representation of a model."
    allOf:
    - $ref: "#/definitions/updateModel"
    - title: "Model"
      type: "object"
      properties:
```

Try this and share the result. Note that I discovered this via trial and error.

**Comment by ponelat** [comment] 2017-08-25 10:04
Thanks @mxmader for your trial/error efforts!
The problem does appear to be one of ordering.
`allOf` ( as implemented in swagger-js) will overwrite fields in order.
That's why your example works. 

One suggest approach is the make the root contents of the model higher in priority.
So currently, `ModelA` and `ModelB` will be different. 

@webron @shockey should we make them the same? ie: root level fields cannot be overwritten by `allOf`? ( that makes sense to me, and may have been an oversight in implementation, but I'm not sure ).

example:
```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Hello Model Names!
  description: |
    This one: https://github.com/swagger-api/swagger-ui/issues/3417
paths: {}

definitions:
  ModelA:
    title: My Title
    type: object
    properties:
      one: 
        type: number
    allOf:
    - title: AllOf Title
      type: object
      properties:
        one: 
          type: string 
  ModelB:
    allOf:
    - title: AllOf Title
      type: object
      properties:
        one: 
          type: string 
    - title: My Title
      type: object
      properties:
        one: 
          type: number```

**Comment by owenconti** [comment] 2017-09-17 16:04
Hi @DavidBiesack,

I believe this issue should be fixed now. Could you please test on this URL and confirm the issue has been fixed? http://petstore.swagger.io/?url=https://gist.githubusercontent.com/owenconti/f370a18780ab948398e92057a8c06bed/raw/6b9f84e1e0f2f61fb96c18651e095a221f6b0be8/%25233417r

**Comment by DavidBiesack** [comment] 2017-09-17 21:56
@owenconti that URL does not work

I also tried http://petstore.swagger.io/?url=https://github.com/swagger-api/swagger-ui/files/1160284/duplicate-models.yaml.txt but that fails to load (does petstore.swagger.io handle CORS?)

**Comment by owenconti** [comment] 2017-09-18 02:51
I updated the URL, there was an extra `r` character at the end.

**Comment by DavidBiesack** [comment] 2017-09-18 11:32
Yes, that looks great - thanks!

**Comment by webron** [comment] 2017-09-18 12:06
@DavidBiesack great, thanks for the verification. Closing!

**Closed by webron** 2017-09-18 12:06 UTC
Labels: 3.x, Bug, P2
