### ISSUE TITLE
Enabling jsonEditor does not change POST body editor

### ISSUE THREAD

**Issue by iamtheddrman** [swagger-api/swagger-ui#4483] opened 2018-04-26 19:33 UTC
Using Swagger UI v3.13.6 and v3.0.19, setting the jsonEditor parameter to true does not seem to enable any sort of graphical JSON editor as the documentation describes. I have tried with my local copy of Swagger UI with a Swagger 2.0 spec and the live demo on http://petstore.swagger.io/ using Chrome 66 on Windows 10.

In my local UI, I added `jsonEditor: true` to the `SwaggerUIBundle` constructor in the index.html file. I verified through the Chrome debugger that the changes were properly picked up, so I don't believe this is a caching issue.

In the live demo and my local UI, I tried adding a `?jsonEditor=true` query string, which likewise had no resulting change to the Swagger UI. I would expect the editor to no longer have the large JSON string text field and instead have a more user-friendly HTML form.

Is this feature currently broken on the v3 Swagger UI? If it is working for others, how do I properly enable it using the dist from the swagger-ui repo? I can modify the index.html or provide a query string; I don't really care which so long as I can get this working. Our API is large and some POSTs are rather complex, so the better editor would be of massive benefit to us.

**Comment by webron** [comment] 2018-04-26 20:16
It's not broken, it doesn't exist. We never added it to v3.

**Comment by hkosova** [comment] 2018-04-26 21:10
Possible duplicate of #3373.

**Comment by iamtheddrman** [comment] 2018-04-27 03:37
Is there a plan to add it to v3? It's in the documentation for v3, so I assumed the feature existed. It would be nice to either update the documentation to reflect the v3 features, or get it added in so that the documentation matches.

**Comment by webron** [comment] 2018-04-27 06:25
Where do you see it in the documentation for v3?

The JSON Editor was previously added by a community contribution, and it's not high on the priority list.

**Comment by iamtheddrman** [comment] 2018-04-28 03:41
At the bottom of the table here, as well as in the list of scripts that you need to add to a custom HTML file:
https://swagger.io/docs/swagger-tools/#customization-36

**Comment by webron** [comment] 2018-04-30 23:06
Thanks. That's the documentation for v2. Unfortunately, we haven't kept this up to date.

We're in the process of updating the website completely, and it will work differently, showing the information directly from the github repositories, thus avoiding such situations in the future. Apologies for the confusion.

**Comment by iamtheddrman** [comment] 2018-05-02 21:10
Thanks for the response! I love the project and look forward to the updated website whenever it's ready.

**Comment by webron** [comment] 2018-07-17 18:13
Closing in favor of #2771.

**Closed by webron** 2018-07-17 18:13 UTC
