### ISSUE TITLE
required param is repeated ui screen

### ISSUE THREAD

**Issue by swarupe04** [swagger-api/swagger-ui#1175] opened 2015-04-16 19:06 UTC
Latest master from today's code:

![screen shot 2015-04-16 at 3 01 56 pm](https://cloud.githubusercontent.com/assets/1471201/7189025/ec3d15e8-e449-11e4-8f96-53217eff7c73.png)

Here's corresponding swagger.json snippet:

{
name: "date_range",
in: "query",
description: "type of date ranges. for CUSTOM date_start, date_end params are required",
required: true,
type: "string",
default: "MONTH_TO_DATE",
enum: [
"TODAY",
"YESTERDAY",
"LAST_WEEK",
"LAST_MONTH",
"CUSTOM_DATE_TIME",
"PREVIOUS_SEVEN_DAYS",
"WEEK_TO_DATE",
"MONTH_TO_DATE",
"QUARTER_TO_DATE",
"YEAR_TO_DATE",
"LINE_ITEM_TO_DATE",
"CAMPAIGN_TO_DATE",
"CONTRACT_TO_DATE",
"TO_DATE",
"CUSTOM"
]
},

**Comment by webron** [comment] 2015-04-16 19:07
Thank you for the report but this is a duplicate of #1113.

**Closed by webron** 2015-04-16 19:07 UTC
