### ISSUE TITLE
dereferencing a local `$ref` for a property definition doesn't work

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-ui#1792] opened 2015-12-01 20:25 UTC
![screen shot 2015-12-01 at 3 26 01 pm](https://cloud.githubusercontent.com/assets/8569655/11513206/ea7726fe-983f-11e5-92e1-acfa4e7192cd.png)

possibly this is an issue with swagger-js ... definitely, the resulting api from it includes a URL reference instead of a local reference

Here is the `ThingSummary` definition:

``` json
    "ThingSummary": {
      "required": [
        "ThingNumber",
        "address"
      ],
      "properties": {
        "ThingNumber": {
          "type": "string",
          "description": "The unique identifier of this Thing."
        },
        "address": {
          "$ref": "#/definitions/Address"
        }
      }
    }
```

[gist of the full test case](https://gist.github.com/seanpkps/89b2b21be03e60235486)

**Comment by dsem** [comment] 2016-01-05 22:09
Extending `Thing` with `ThingSummary` via `allOf` is vital to reproducing this issue:

```json
    "Thing": {
      "allOf": [
        {
          "$ref": "#/definitions/ThingSummary"
        },
        {
          "type": "object",
          "properties": {
            "stuff": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "source": {
                  "type": "string"
                }
              },
              "description": "The stuff about the thing.\n"
            }
          }
        }
      ]
    }
```

If you remove this `allOf` block, you should see `ThingSummary` resolve properly.

Still a bug, though.

**Comment by dsem** [comment] 2016-01-06 13:45
Looks like this duplicates #1723.

**Comment by seanpkps** [comment] 2016-01-06 14:05
@dsem - so, if the `ThingSummary` is not included in an `allOf` elsewhere it works?

This is one of the major issue affecting the display of my API using swagger-ui. When I've investigated, it looks like it may be caused by [swagger-parser](https://github.com/swagger-api/swagger-parser) ... ? At the very least, I haven't identified an obvious and straight-forward way of resolving the issue from within the swagger-ui code.

**Comment by fehguy** [comment] 2016-01-06 14:09
Can you please share a complete spec for this?  It seems like you are defining the `Thing` inline in the response of a Get method, but it'd be helpful to see a complete view of this.

**Comment by seanpkps** [comment] 2016-01-06 14:36
@fehguy the **full test** case was linked to from the summary:
<https://gist.github.com/seanpkps/89b2b21be03e60235486>

**Comment by dsem** [comment] 2016-01-06 14:47
@seanpkps I think so.  I've encountered this exact issue in my spec and was able to get it to display properly only when I removed all references to my definition in `allOf` blocks of other defs.  See the duplicate, it describes the same problem.

**Comment by fehguy** [comment] 2016-01-06 15:20
It's definitely not an issue in swagger-parser, which is a java tool (I've added a test case there just for coverage).

**Comment by fehguy** [comment] 2016-01-06 15:28
Well, good news, it appears that master is rendering as we would expect.

For `/things`:  We show an array of `Inline Model` with type `ThingSummary`.  There is an embedded `Address` model, which is expected.

For `/things/{id}`, the `Inline Model 1` appears because the `stuff` property in `Thing` is defined inline, which is also expected

Please comment if you are expecting other than what is showing up here.

![image](https://cloud.githubusercontent.com/assets/249413/12146100/b669a4f4-b446-11e5-962d-c1ef37a34a4c.png)

**Comment by seanpkps** [comment] 2016-01-06 15:50
that is looking good!

I'm also going to try master with my actual API definition, but this is very promising.

**Comment by seanpkps** [comment] 2016-01-06 17:25
With the current `master` my real API spec displays well too.

FWIW, I notice that a new version of swagger-client is used now.

**Closed** 2017-03-22 18:06 UTC
