### ISSUE TITLE
Response schema not shown

### ISSUE THREAD

**Issue by Ohems** [swagger-api/swagger-ui#3489] opened 2017-07-31 08:19 UTC
Swagger UI version: 3.1.1

Response schema rendering is broken. YAML file:
```
info:
  title: Example
  version: 1.0.0
swagger: '2.0'
paths:
  '/endpoint1':
    get:
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
  '/endpoint2':
    get:
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
```

Result:
<img width="598" alt="screen shot 2017-07-31 at 11 18 07" src="https://user-images.githubusercontent.com/8604342/28768864-f5d04644-75e1-11e7-9aa6-964de6ab96f7.png">

**Comment by weirdan** [comment] 2017-07-31 08:41
referenced schema doesn't show up either

**Comment by kliyes** [comment] 2017-07-31 08:50
Same here

**Comment by hkosova** [comment] 2017-07-31 10:15
Probably a duplicate of #3446.

**Comment by reznik789** [comment] 2017-07-31 14:10
Same for me. But shema showed in previous version of editor
 http://joxi.ru/82QMGO7c1yWbQ2
Editor 2
![image](https://user-images.githubusercontent.com/20238250/28781538-166f61a6-7613-11e7-86b2-640abaeceea6.png)

Editor 1
![image](https://user-images.githubusercontent.com/20238250/28781515-01395882-7613-11e7-8031-63b53a445f33.png)

**Closed** 2017-07-31 22:49 UTC
Labels: 3.x, Bug, P1

**Comment by weirdan** [comment] 2017-08-01 00:24
could dist files be rebuilt for those of us who just use them, and not building ourselves?

**Comment by shockey** [comment] 2017-08-01 00:25
@weirdan sure - will update them now!

**Comment by ricardofiorani** [comment] 2017-08-01 07:50
Lessons learned. Don't do releases on Fridays. 😂

**Comment by weirdan** [comment] 2017-08-01 09:17
And now that the dist files are in master, could a new release be published, please? Because release tarball for v3.1.2 contains dist files from v3.1.1 — so if one can't rebuild it's as broken as v3.1.1 was.

**Comment by shockey** [comment] 2017-08-01 21:46
@ricardofiorani, we usually do releases on Friday - our mistake was doing it on Saturday instead 😉 

@weirdan, I'll author a Github release with the release notes later today, but in the meantime you can download the [.zip of commit `6b1d78c`](https://github.com/swagger-api/swagger-ui/archive/6b1d78c6a6430fd860c2cf1cefd52ba42d40dda3.zip), which will be equivalent to the release tarball.

**Comment by weirdan** [comment] 2017-08-01 22:31
@shockey I built 3.1.2 myself where I needed it, but some package managers (like composer) supply packaged files based on the github releases/tags.

**Comment by shockey** [comment] 2017-08-16 19:13
@weirdan gotcha, apologies for not packing the dist updates into the release correctly. Shouldn't happen again 😄
