### ISSUE TITLE
Swagger UI does not show the "title" of array type.

### ISSUE THREAD

**Issue by titoc** [swagger-api/swagger-ui#2795] opened 2017-03-27 13:23 UTC
Using the master branch, Swagger UI does not show the` "title": "Responses"`, in the `Models `section.
```
"Response": {
                "type": "object",
                "title": "Response",
                "description": "Response to query.",
                "properties": {
                    "Query": {
                        "$ref": "#/definitions/Query"
                    },
                    "Result": {
                        "$ref": "#/definitions/Result"
                    }
                }
            },
   "Responses": {
                "type": "array",
                "title": "Responses",
                "description": "Array of responses.",
                "items": {
                    "$ref": "#/definitions/Response"
                }
            }
```

![response-array](https://cloud.githubusercontent.com/assets/12772268/24358327/ce6061be-12ce-11e7-8569-9b7f5d25438a.png)

**Comment by webron** [comment] 2017-03-27 20:53
The issue is not related to `title` but rather any definitions that are not of type `object`.

**Comment by bodnia** [comment] 2017-03-31 15:36
fixed with https://github.com/bodnia/swagger-ui/commit/d2e20a72f0a06361f5d72f7c5e80cf314e10d055

**Closed** 2017-03-31 15:36 UTC
Labels: 3.x
