### ISSUE TITLE
window is not defined when running  swagger-ui-react  

### ISSUE THREAD

**Issue by johnwhitton** [swagger-api/swagger-ui#6153] opened 2020-06-17 01:23 UTC
## Environment
 - OS: Linux
 - Browser: Chrome
 - Version: `  "name": "swagger-ui-react", "version": "3.26.2",`
 - Method of installation: yarn install 
 - Swagger-UI version: `  "name": "swagger-ui-react", "version": "3.26.2",`
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration
I'm running 
* [docusarus](https://v2.docusaurus.io/docs/installation)
* [swagger-ui-react](https://www.npmjs.com/package/swagger-ui-react)
* [redoc npm package](https://www.npmjs.com/package/redoc)

Swagger-UI configuration options:
```
import React from 'react';
import classnames from 'classnames';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './styles.module.css';
import SwaggerUI from "swagger-ui-react"
import "swagger-ui-react/swagger-ui.css"

function Home() {
  const context = useDocusaurusContext();
  const {siteConfig = {}} = context;
  return (
    <Layout
      title='Harmony Swagger'
      description="Harmony Swagger">
      <main>
	  <SwaggerUI url="harmony.yml" />
      </main>
    </Layout>
  );
}

```

### Describe the bug you're encountering
When running `yarn run start` the server is started and the swagger page shows and works.

When running 'yarn run build` I get the following error

```
ReferenceError: Buffer is not definedReferenceError: window is not defined
(undefined) ReferenceError: Buffer is not defined
```

Gist containing more detailed error is [here](https://gist.github.com/johnwhitton/0280dfb25360d04bd309a8a05865c5f6)

### Expected behavior
`yarn run build` works

### Additional context or thoughts
This seems similar to [this issue](https://github.com/agoncal/swagger-ui-angular6/issues/2) for swagger-ui and [this issue](https://github.com/LedgerHQ/ledgerjs/issues/392)

**Comment by hkosova** [comment] 2020-06-17 10:17
Duplicate of #6136.

**Closed by hkosova** 2020-06-17 10:17 UTC
