### ISSUE TITLE
UI incorrect display of type: integer format: int64 as rounded int values in response body

### ISSUE THREAD

**Issue by rgunn** [swagger-api/swagger-ui#2030] opened 2016-03-15 22:56 UTC
swagger.json correctly shows the data types and format but the values displayed in the response body are rounded int values.

**Comment by webron** [comment] 2016-03-16 03:26
Rounded int values?

**Comment by rgunn** [comment] 2016-03-16 05:50
swagger.json properties are correctly typed

"someKey":{"type":"integer","format":"int64"},
"anotherKey":{"type":"integer","format":"int64"},

The raw JSON returned from my REST service is correct but the values displayed in the swagger response body:

   "someKey": 1253261109769874400,
   "anotherKey": 212081872531357440,

Should be:

   "someKey": 1253261109769874438,
   "anotherKey": 212081872531357452,

Which is exactly the same result as running JavaScript's
parseInt("1253261109769874438")
/*
1253261109769874400
*/

I am new to swagger and have produced swagger 2 spec for approx 70 REST API endpoints and this is the only issue I have.  Javascript only supports 53 bit integers  and the UI does not process these values properly although I assumed it would according to the "format" type ?

**Comment by scott-orleman** [comment] 2016-09-09 17:51
What news of this issue? Having the same problem.

**Comment by webron** [comment] 2016-09-14 20:54
I believe this is a javascript limitation. Not sure there's much we can do about it, but ideas are welcome.

**Comment by code-ape** [comment] 2017-03-02 13:39
I personally would like to see this resolved if possible. A project I've worked on has had to be rearchitectured because of this limitation of the values presented in the UI being rounded. We had been using 64 bit hashes.

**Comment by bobvanluijt** [comment] 2017-06-12 15:33
Not sure if this is still an issue, but for other projects I've used this package to deal with large integers: https://www.npmjs.com/package/big-integer

**Comment by webron** [comment] 2017-06-12 15:48
@bobvanluijt thanks for that, it's still an issue, yes. Would you consider submitting a PR that would add support for it?

**Comment by heldersepu** [comment] 2017-12-09 20:55
This is caused by `JSON.parse`  you can see it in [response-body.jsx#L25](https://github.com/swagger-api/swagger-ui/blob/52693254e920e5376d4386d2968e936d66c8af9c/src/core/components/response-body.jsx#L25)

Try this on the browser console:
```js
JSON.parse("{\"MyInt64\":1253261109769874438,\"MyData\":\"1253261109769874438\"}")
```
```json
{MyInt64: 1253261109769874400, MyData: "1253261109769874438"}
```

**Comment by heldersepu** [comment] 2017-12-09 21:06
Perhaps we should have a config option to bypass the prettification, and always render response as PlainText

**Comment by shockey** [comment] 2017-12-11 19:10
I think a Pretty/Raw switcher is the right answer here, as it offers a more generalized approach

**Comment by heldersepu** [comment] 2017-12-11 19:13
@shockey 100% agree, you can merge this issue with #4018

**Comment by webron** [comment] 2018-06-05 22:34
Closing this as a JavaScript limitation, with the suggested alternative of #4018. Not sure there's more we can do about this one beyond it.

**Comment by shockey** [comment] 2019-09-28 06:33
I'm reopening this — the [ECMAScript `BigInt` proposal](https://tc39.es/proposal-bigint/#sec-bigint-objects) is in stage 3 with [support in latest Chrome, Firefox, and Opera](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Browser_compatibility), so JavaScript itself may not be a limitation here going forward.

**Comment by breun** [comment] 2019-11-12 14:44
It seems not all browsers support BigInt yet, like for instance Safari: https://caniuse.com/#feat=bigint

**Comment by RSully** [comment] 2020-05-29 20:03
There is some discussion about Safari's BigInt support here: https://github.com/mdn/browser-compat-data/issues/4848

There is a [Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=179001) being tracked for this feature, and the latest [dependency](https://bugs.webkit.org/show_bug.cgi?id=190800) there has updates recently, so it sounds like they're working on it. Fingers crossed!

**Comment by zapek** [comment] 2020-08-10 10:47
This problem is really nasty. It's not obvious for someone using Swagger UI for checking the output of the REST API that Javascript uses float for everything and the number showing up there might be wrong.

**Comment by tim-lai** [comment] 2021-03-24 16:44
Closing this issue again. On the subject of BigInt, [JSON specification, section 6](https://tools.ietf.org/html/rfc7159#section-6) (Numbers) is quite clear about supported number ranges. Going beyond them creates issues of correctly interpreting numbers.

In addition, exposing integers via API in JSON format that may be really big is not a good idea. One can accidentally generate a number that is outside of the range, and different platforms consuming the JSON will interpret the number differently. Even [JSON:API](https://jsonapi.org/examples/) has a convention of sending numbers as strings to avoid that problem.

Some time ago JavaScript landed a new type BigInt that can support ranges outside of 253 - 1. Unfortunately this type is not JSON serializable and the only recommended way of transferring it via JSON is: [transfer it as a string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Use_within_JSON). That way, every platform can deal with it as it likes.

**Closed by tim-lai** 2021-03-24 16:44 UTC
Labels: P2, type: bug, version: 3.x

**Comment by sz763** [comment] 2025-07-23 05:48
I've implemented kind of workaround for this issue. [Guideline for SpringBoot](https://gist.github.com/sz763/a4d262a5a9a400c878b62759fc3f4787)
