### ISSUE TITLE
expression on path param on UI 2.0 not working

### ISSUE THREAD

**Issue by swarupe04** [swagger-api/swagger-ui#1054] opened 2015-03-19 17:58 UTC
expression such as `/v1/report/{report_type:[aA-zZ]+}` for a path param is not getting translated and uses it as is in UI 2.0 instead of replacing with the value of 'report_type'

This was working fine in UI 1.x

**Comment by fehguy** [comment] 2015-03-19 18:00
@whitlockjc this may be a swagger-js issue

**Comment by whitlockjc** [comment] 2015-03-19 18:26
Can you explain what is happening and what you'd expect to happen?  I'm not sure this is a valid path because you'd typically have `/v1/report/{report_type}` and have the `report_type` parameter definition set the `pattern` property appropriately.  If some library is creating the spec from this, it needs to be updated to pull that information out and add the proper `pattern` property to the parameter schema.

I agree we should not fail when an invalid path is encountered but since I'm not sure what is going on, I can't do anything just yet.  I'll look into this more when you give me more details.

**Comment by swarupe04** [comment] 2015-03-19 18:42
It's a standard jax-rs feature:
https://docs.oracle.com/cd/E19798-01/821-1841/ginpw/

And this was supported in UI 1.x

So basically when we execute that API call in swagger ui, it sends it as it
is such as: localhost:8080/reporting/v1/report/{report_type:[a-z]+} instead
of replacing with the value such as
localhost:8080/reporting/v1/report/summary  -- where report_type = summary

**Comment by fehguy** [comment] 2015-03-19 19:36
Yes @whitlockjc I think if it simply replaced the path pattern with the value from the input box, it would at least follow previous behavior.

**Comment by whitlockjc** [comment] 2015-03-19 19:45
A JAX-RS standard does not mean it's a valid Swagger path expression, sorry.  Many server frameworks and routing libraries out there support this type of syntax but it is not valid Swagger.  That is the truth.

@fehguy I'm not sure we want to get into parsing paths like this.  If we support JAX-RS paths then we open ourselves up to supporting the plethora of other well known approaches out there.  I know we do our best to support invalid Swagger documents and such but I don't see a good way to do it for this.  For example, take Express _(and all the Node.js routers that support Express-style path patterns)_, how would we work around this: http://expressjs.com/4x/api.html#router.METHOD

**Comment by fehguy** [comment] 2015-03-19 20:58
Seems to me that using the property name *as-is* and doing replacements based on that would suffice for this, and not break back compatibility.  Is that doable?  We did it previously

**Comment by whitlockjc** [comment] 2015-03-19 21:22
I've not touched any of this stuff so I'm not sure how it worked previously but I'm still not sure we should go down the path of adding explicit support to swagger-js to allow people to knowingly provide invalid Swagger paths and have us work around it.  As of right now, swagger-js/swagger-ui do everything possible to avoid blowing up at runtime do to invalid Swagger documents but this isn't a runtime blow up, things in swagger-js/swagger-ui are working as designed but the input information.  The fix you're suggesting basically requires swagger-js/swagger-ui to support non-Swagger path patterns.  In some cases, like the Express example I showed you, it's not even possible to infer the path parameter name.

First we'll start with JAX-RS, when we'll need to support Express...when does this stop?

**Comment by fehguy** [comment] 2015-03-19 21:28
@whitlockjc is right.  This is actually an unimplemented feature in swagger-core.  I've opened this:

https://github.com/swagger-api/swagger-core/issues/922

The right thing to do will be to generate a name alias and define the regex pattern.

**Comment by fehguy** [comment] 2015-03-20 03:33
fixed in https://github.com/swagger-api/swagger-core/commit/994b475e3bc02e5f57a3fc90275979d942804f1c

**Closed by fehguy** 2015-03-20 03:33 UTC
Labels: Bug

**Comment by swarupe04** [comment] 2015-03-20 15:43
If I understand correctly, the fix was in swagger-core, and no change on swagger ui side? Should I be pulling the latest snapshot from 1.5.3-M1-SNAPSHOT?

**Comment by fehguy** [comment] 2015-03-20 15:45
Correct. The server is doing the right thing now and this doesn't affect the ui
