### ISSUE TITLE
Unable to import YAML files in the swagger editor.

### ISSUE THREAD

**Issue by rrajan2** [swagger-api/swagger-ui#4371] opened 2018-03-26 18:47 UTC
Unable to import yaml files in the latest version of the online swagger editor. When the File ->Import File menu is clicked, the pop up to browse to the location of the file to be imported is not available.

**Comment by shockey** [comment] 2018-03-27 03:37
Closing as a duplicate of https://github.com/swagger-api/swagger-editor/issues/1714.

FYI: this is fixed on Swagger.io now :smile:

**Closed by shockey** 2018-03-27 03:37 UTC
