### ISSUE TITLE
v3.25.3 breaking on definition containing property "entries" 

### ISSUE THREAD

**Issue by jgdiva** [swagger-api/swagger-ui#6021] opened 2020-05-20 14:17 UTC
Hallo,

with version v3.25.3 our API-definition is breaking. I did some line-by-line copy-and-pasting, and found out, that it always breaks whenever a definition contains a property named "entries". The error message is not that helpful:

_Unable to render this definition
The provided definition does not specify a valid version field._

_Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0)._

We are using "swagger: '2.0'"

Example of a breaking definition:

_definitions:
... 
  ExampleWsDTO:
    type: object
    properties:
      exampleproperty:
        type: number
        format: double
      entries:
        type: array
        items:
          $ref: '#/definitions/AnotherWsDTO'
      anotherproperty:
        $ref: '#/definitions/AnotherWsDTO'
..._

When I remove the "entries" property, everything works fine. But I cannot actually remove or rename them in our definition.

With v.3.25.2, everything still works fine.

Can you have a look at this, please?

Thank you!

**Comment by hkosova** [comment] 2020-05-20 15:30
Duplicate of #6016.

**Closed by hkosova** 2020-05-20 15:30 UTC
