### ISSUE TITLE
default operationsSorter prioritising DELETE method

### ISSUE THREAD

**Issue by zanona** [swagger-api/swagger-ui#2017] opened 2016-03-08 13:33 UTC
I just have noticed that for by default, even though `operationsSorter` is not defined, the operations with DELETE methods containing path parameters, will display before other methods even though the definition is declared other way.

The use case can be seen at  http://petstore.swagger.io where for the operation `/pet/{petId}` and others containing path parameters as well.

<img width="242" alt="screen shot 2016-03-08 at 13 28 59" src="https://cloud.githubusercontent.com/assets/32017/13603004/19ba7f12-e532-11e5-99b1-ddcd6abb8c44.png">

**Comment by webron** [comment] 2016-03-08 14:47
There's no order of declaration on operations - the path items are maps, and maps are not ordered. Even without looking at the code, I would assume the verbs are ordered alphabetically which is why you'd see DELETE first.

**Comment by zanona** [comment] 2016-03-08 15:35
Hmm, I am not sure.
If you check [/dist/swagger-ui.js](https://raw.githubusercontent.com/swagger-api/swagger-ui/master/dist/swagger-ui.js)

You will find the line:
```js
   var supportedOperationMethods = ['delete', 'get', 'head', 'options', 'patch', 'post', 'put'];
```

By simply changing the order of the methods as I wanted fixed the issue.
```js
   var supportedOperationMethods = ['get', 'head', 'options', 'patch', 'post', 'put', 'delete'];
```

However I have couldn't find any reference to this method on the source code but found https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/SwaggerUi.js#L33-L41

Now declaring methods in different order but also with different name, so I am not sure if it's the same thing. Perhaps the dist directory is outdated?

**Comment by webron** [comment] 2016-03-08 16:43
If the `supportedOperationMethods` affect the ordering, that sounds like a bug to me. You'll notice that that list is indeed alphabetized though.

In any case, the current ordering makes sense to me because it's at least predictable. Not really sure what else you'd expect.

**Comment by zanona** [comment] 2016-03-08 17:23
The order defined here is pretty intuitive for me:

https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/SwaggerUi.js#L33-L41

Think about the APIs documentations from companies out there such as twitter or github, etc. It usually starts with GET and the last one is DELETE.

**Comment by webron** [comment] 2016-03-08 18:00
That's really a matter of user preference. 'Intuitive' is relative. What's intuitive to you may not be intuitive to someone else. We can't satisfy everyone.

**Comment by zanona** [comment] 2016-03-08 18:32
I see it more like as a question of defining standards, specially when so many people think alike.  This is why standards are created after all.

Listing things alphabetically without allowing users to control it doesn't feel right at all. 
Logically it makes a lot of sense order it by the least destructive action coming first, hence GET.

Nevertheless, without getting into too much philosophy here, the README states:

> operationsSorter:	Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically), 'method' (sort by HTTP method) or a function (see Array.prototype.sort() to know how sort function works). **Default is the order returned by the server unchanged.**

So, the default here is not returned unchanged as stated?

**Comment by webron** [comment] 2016-03-08 18:42
That line is probably from the 1.2 days when the operations were an array and not a map. In 2.0 that cannot be guaranteed.

**Comment by zanona** [comment] 2016-03-08 20:52
Got it. Thanks for your help @webron. All the best.

**Comment by OlafvdSpek** [comment] 2017-01-31 13:16
So the docs should be updated?

If the 'default' is basically unordered, wouldn't it make sense to default to alpha instead?

**Comment by lgelfan** [comment] 2017-04-17 20:07
This seems to have been fixed (or at least now works as expected) in v3. I can confirm @zanona that changing `supportedOperationMethods` in the source does address this specific issue (I'm using v2.2). I didn't see a way to override that variable when declaring `swaggerUi`. Perhaps some advanced multi-sort function on `operationsSorter` would also work, but adjusting `supportedOperationMethods` will work for us until we update to v3.

I don't see how you can dismiss this as simply "user preference" though when every major API documentation starts with GET method and generally progresses through POST, PUT/PATCH, DELETE.

**Comment by webron** [comment] 2017-06-09 22:02
Closing as-is for now. If anyone wants to submit a PR that will sort the operations in the suggested manner, we'd be happy to review.

**Closed by webron** 2017-06-09 22:02 UTC
