### ISSUE TITLE
Allow "try-it-out" all the time

### ISSUE THREAD

**Issue by moecre** [swagger-api/swagger-ui#5707] opened 2019-11-09 13:26 UTC
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 78
 - Method of installation: npm swagger-ui-dist
 - Swagger-UI version: 3.23.11
 - Swagger/OpenAPI version: OpenAPI 3.0

### How can we help?
Is there a way to allow using every API endpoint without clicking the Try-It-Out button first? I already tried using the disable try-it-out button plugin but this disables the functionality completely, that's not what I want.
I'm looking for the same behaviour like in the older versions: every input field is accessible and there is an "execute" button in every request panel.

**Comment by hkosova** [comment] 2019-12-12 13:30
Duplicate of #4792.

**Closed by hkosova** 2019-12-12 13:30 UTC

**Comment by ldipotetjob** [comment] 2020-06-08 17:05
Any solution finally ? we have the same complain. In #4792 nothin there

**Comment by ElkanRoelen** [comment] 2020-12-18 13:42
We managed to get a plain JS solution working in swagger-ui-express:
https://github.com/swagger-api/swagger-ui/issues/4792#issuecomment-748089530
