### ISSUE TITLE
Issue with: exclusiveMaximum/exclusiveMinimum

### ISSUE THREAD

**Issue by zbuh** [swagger-api/swagger-ui#9013] opened 2023-07-13 08:57 UTC
- OS: macOS
 - Browser: FireFox
 - Method of installation: fastapi 0.100
 - Swagger/OpenAPI version: OpenAPI 3.1]

example schema:

```
{
    "components": {
        "schemas": {
            "HTTPValidationError": {
                "properties": {
                    "detail": {
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        },
                        "title": "Detail",
                        "type": "array"
                    }
                },
                "title": "HTTPValidationError",
                "type": "object"
            },
            "Location": {
                "properties": {
                    "lat": {
                        "exclusiveMaximum": 90.0,
                        "exclusiveMinimum": -90.0,
                        "title": "Lat",
                        "type": "number"
                    },
                    "lng": {
                        "maximum": 180.0,
                        "minimum": -180.0,
                        "title": "Lng",
                        "type": "number"
                    }
                },
                "required": [
                    "lat",
                    "lng"
                ],
                "title": "Location",
                "type": "object"
            },
            "ValidationError": {
                "properties": {
                    "loc": {
                        "items": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        },
                        "title": "Location",
                        "type": "array"
                    },
                    "msg": {
                        "title": "Message",
                        "type": "string"
                    },
                    "type": {
                        "title": "Error Type",
                        "type": "string"
                    }
                },
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "title": "ValidationError",
                "type": "object"
            }
        }
    },
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "openapi": "3.1.0",
    "paths": {
        "/location": {
            "post": {
                "operationId": "create_location_location_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Location"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        },
                        "description": "Successful Response"
                    },
                    "422": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        },
                        "description": "Validation Error"
                    }
                },
                "summary": "Create Location"
            }
        }
    }
}
```

Generated:

![image](https://github.com/swagger-api/swagger-ui/assets/190734/1fdfdd84-4aa7-4431-9713-6ea599755678)

Originally reported in: https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6435773

**Comment by char0n** [comment] 2023-07-17 11:36
Hi @zbuh,

Looks legit, investigating...

**Comment by Kludex** [comment] 2023-07-17 11:59
The issue is on `exclusiveMaximum` and `exclusiveMinimum`, not on `minimum` and `maximum` (as the title mentions).

It should show `(-90, 90)` for `exclusive*`, and `[-180, 180]` for the non-exclusive ones (the latter is fine).

**Comment by char0n** [comment] 2023-07-17 12:05
Ahh OK, because the image in issue description and the https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6435773 deals with `lng`.

**Comment by char0n** [comment] 2023-07-17 12:23
Nope, thanks! I identified the bug and working on the bugfix

**Comment by Kludex** [comment] 2023-07-17 12:26
> Nope, thanks! I identified the bug and working on the bugfix

Thanks! 🙏

**Comment by char0n** [comment] 2023-07-17 12:41
Addressed in https://github.com/swagger-api/swagger-ui/pull/9030. Will be part of next SwaggerUI release.

**Closed by char0n** 2023-07-17 12:41 UTC
Labels: type: bug, version: 5.x

**Comment by Kludex** [comment] 2023-07-17 12:43
@char0n It will render the above as `(-90, 90)`, and not `[-90, 90]`, right?

**Comment by zbuh** [comment] 2023-07-17 12:44
shouldnt it be rendered as ]-90, 90[ ?

**Comment by zbuh** [comment] 2023-07-17 12:50
got it. thanks!

**Comment by Kludex** [comment] 2023-07-17 12:50
Cute! Thanks! 🙏

**Comment by char0n** [comment] 2023-07-17 13:01
Another thing I've notice is that I forgot to handle `integer` type:

```yaml
openapi: 3.1.0
info:
  version: 1.2.3
  title: title
components: 
  schemas:
    Location:
      properties:
        lat:
          type: integer
```

results in 

![image](https://github.com/swagger-api/swagger-ui/assets/193286/d2cb3e7e-168c-4442-97cf-0f320a3bb435)
