### ISSUE TITLE
Inconsistent Markdown Newlines

### ISSUE THREAD

**Issue by dotasek** [swagger-api/swagger-ui#2981] opened 2017-04-26 22:43 UTC
In the info description, newlines work as expected, producing a blank line between ```Something in a line``` and ```And something in a **new** line``` but in operation descriptions, the blank line doesn't appear. The schema below illustrates.

```
{
  "swagger" : "2.0",
  "info" : {
    "description" : "Something in a line  \n  \nAnd something in a **new** line.",
    "version" : "V2.0.0",
    "title" : "Newline behavior"
  },
  "host" : "localhost:1234",
  "tags" : [ {
    "name" : "Tag1"
  } ],
  "schemes" : [ "http" ],
  "consumes" : [ "application/json", "application/xml" ],
  "produces" : [ "application/json", "application/xml" ],
  "paths" : {
    "/" : {
      "get" : {
        "tags" : [ "Tag1" ],
        "summary" : "operation",
        "description" : "Something in a line  \n  \nAnd something in a **new** line.",
        "operationId" : "getVersions",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "object",
              "additionalProperties" : {
                "type" : "array",
                "items" : {
                  "type" : "string"
                }
              }
            },
            "headers" : { }
          }
        }
      }
    },

  },
  "definitions" : {
  }
}
```

**Comment by webron** [comment] 2017-04-26 22:44
Which version of swagger-ui do you use?

**Comment by dotasek** [comment] 2017-04-27 16:20
Occurs in 3.0.7

**Comment by owenconti** [comment] 2017-07-08 17:08
Hi @dotasek, _should_ be fixed in: https://github.com/swagger-api/swagger-ui/pull/3353

**Comment by owenconti** [comment] 2017-07-22 23:01
Closing as I believe the issue is fixed. Please re-open if you can reproduce the issue

**Closed by owenconti** 2017-07-22 23:01 UTC
Labels: 3.x, Bug, P2

**Comment by dotasek** [comment] 2017-07-24 16:03
I downloaded Swagger UI 3.0.20, and this seems to still be present.

The swagger info description text supports blank lines, but the operation description does not. Issue appears in multiple browsers.
