### ISSUE TITLE
Swagger 2.0 - string array response described incorrectly

### ISSUE THREAD

**Issue by domaindrivendev** [swagger-api/swagger-ui#857] opened 2015-01-26 18:28 UTC
Hey there

When an operation's 200 response is a string array, the resulting description in the UI makes no sense!
 
Given this operation description ...

    "/Values": {
        "get": {
            "tags": ["Values"],
            "operationId": "Values_GetAll",
            "consumes": [],
            "produces": ["application/json","text/json","application/xml","text/xml"],
            "responses": {
                "200": {
                    "description": "OK",
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "deprecated":false
        }
    }

I'm seeing the following in swagger-ui ...

![screen-shot](https://cloud.githubusercontent.com/assets/1434343/5905610/1710b484-a546-11e4-94b8-7b3c2fc111c5.png)

**Comment by webron** [comment] 2015-01-27 19:59
Thanks, but this is a duplicate of #800.

**Closed by webron** 2015-01-27 19:59 UTC
