### ISSUE TITLE
Markdown links not working in description object within path item object

### ISSUE THREAD

**Issue by xquery-guy** [swagger-api/swagger-ui#3792] opened 2017-10-20 06:05 UTC
I've got a bug here related to having links in the markdown in the description object in a path item object. The link part shows as blue, but clicking does not take you to the link and highlighting it does not show the link at the bottom left of the browser page. Also when highlighting, only the normal cursor shows, not the little hand with the finger pointing.

Here is an example:
"paths": {
        "/api/some-name/v1.0/search": {
            "post": {
                "consumes": [
                    "application/xml",
                    "application/json"
                ],
                "description":
                    "An API that returns the ids relative to a member and the member's family along with corresponding membership data. \n**Documentation:**\n Go to github here: [Github](https://github.com)",
...

I am using swagger ui version 3.2.2, swagger spec 2.0, just using the code in the dist folder. Using Chrome 61.0.3163.100 and Mac Sierra OS. It was working in a previous version a couple months ago. I am wanting to provide links to API documentation.

**Comment by shockey** [comment] 2017-10-20 07:05
Yep, this was a regression! It was previously reported in #3767, and patched in #3768. The fix will be released Friday evening as part of our weekly release. Sorry for the inconvenience!

Closing this as a duplicate of #3767; feel free to reply if you have any thoughts or questions. Thanks for the report!

**Closed by shockey** 2017-10-20 07:05 UTC

**Comment by xquery-guy** [comment] 2017-10-20 07:36
Thank you for the quick response, good to hear!


Sent with BlackBerry Work
(www.blackberry.com)
