### ISSUE TITLE
basePath is not used

### ISSUE THREAD

**Issue by lasselehtinen** [swagger-api/swagger-ui#1139] opened 2015-04-10 10:16 UTC
Hi,

I upgraded my swagger-ui and for some reason the basePaths stopped working. My swagger documentation and UI are placed in:

http://host.dev/swagger-doc
http://host.dev/api/docs

Here is a snippet from my spesification:
```javascript
"basePath": "/api/v1/",
"swaggerVersion": "1.2",
"apiVersion": "1.0.0",
"resourcePath": "login",
```

So when I send the request, swagger-ui tries to send it to http://host.dev/login instead of http://host.dev/api/v1/login. This used to work before just fine.

**Comment by webron** [comment] 2015-04-10 11:40
Technically, even if it worked in previous versions, a relative basePath in Swagger 1.2 is invalid and not supported. If you want it to work, I'd suggest you either change it to a full URL or upgrade to Swagger 2.0 which allows relative basePaths.

**Comment by fehguy** [comment] 2015-04-11 15:05
This should be fixed by https://github.com/swagger-api/swagger-js/commit/c02cffc3da266a1d1d3e57d3c85271f91a3091a1  Please pull develop_2.0 and retest.

**Comment by pip25** [comment] 2015-04-13 10:38
I tested with the current develop_2.0 HEAD, checked that the fix in the above commit is present in node_modules, but the issue still persists.

**Comment by fehguy** [comment] 2015-04-14 17:01
hi, you have to pull develop_2.0 and run `npm install` to pick up the latest from the swagger-client

**Comment by pip25** [comment] 2015-04-14 22:42
That is exactly what I did. I tested with the latest develop_2.0 branch, and also checked that the swagger-client dependency includes the above fix (I even deleted the node_modules directory and re-ran <code>npm install</code> to make sure everything is downloaded again).

**Comment by pip25** [comment] 2015-04-14 23:09
I debugged the JS code in the browser. Apparently, the 
```
if (obj.basePath) {
  this.setDocumentationLocation(obj.basePath);
}
```
part introduced in the above commit does not work, because the base path setting is not present in the main service list (such as "..../api-docs"), but in the individual service descriptions ("..../api-docs/somethingService"), at least on my end. I am using Swagger Core 2.10-1.3.12 and the swagger version number of the generated documentation is 1.2.

**Comment by fehguy** [comment] 2015-04-14 23:31
OK got it, I'll get that tested.  Are you using "multiple" base paths?  Meaning, different values on each one?  If so, that's not supported in 2.1.x of swagger-js:

https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0-M2

**Comment by pip25** [comment] 2015-04-14 23:35
No, I'm using only one base bath. The same base path is used/reported for all services.

**Comment by GuiSim** [comment] 2015-04-28 21:42
Do we know which commit broke this?

I'd like to use the last swagger-ui version that supported basePath correctly.

**Comment by lasselehtinen** [comment] 2015-04-29 07:24
This does not provide anything more, but I have version 2.0.22 and it works fine there as well.

**Comment by fehguy** [comment] 2015-05-08 21:26
this should have been addressed in the latest swagger-js.

**Closed by fehguy** 2015-05-08 21:26 UTC
Labels: P2, Regression, swagger-js

**Comment by pip25** [comment] 2015-05-11 11:11
I can confirm that the basePath is now used correctly. Thank you. :)
