### ISSUE TITLE
Examples referenced with $ref are not rendered correctly

### ISSUE THREAD

**Issue by Alexgmin** [swagger-api/swagger-ui#4924] opened 2018-10-05 11:08 UTC
Not sure if a regression of https://github.com/swagger-api/swagger-ui/issues/4021

This renders the example but also adds the $$ref key
```
openapi: '3.0.0'
info:
  title: 'test'
  version: '1.0.0'
paths:
  /hello:
    get:
      description: 'Get welcome message.'
      responses:
        '200':
          description: 'welcome message'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
              example:
                $ref: '#/components/examples/WelcomeExample'
components:
  schemas:
    Welcome:
      type: object
      properties:
        message:
          type: string
  examples:
    WelcomeExample:
      value:
        api_identifier: act_12345
```

And this one shows the $ref key instead of parsing it (Although the editor shows an error if the $ref doesn't exist):
```
openapi: '3.0.0'
info:
  title: 'test'
  version: '1.0.0'
paths:
  /hello:
    get:
      description: 'Get welcome message.'
      responses:
        '200':
          description: 'welcome message'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
              example:
                $ref: '#/components/examples/WelcomeExample'
components:
  schemas:
    Welcome:
      type: object
      properties:
        message:
          type: string
  examples:
    WelcomeExample:
      value:
        api_identifier: act_12345
```

All of this tested in the swagger editor.

**Comment by lrtherond** [comment] 2018-10-05 23:31
Yep, I see that too in 3.19.2 and quite a few releases before that

**Comment by sasha-borodin** [comment] 2018-10-07 23:12
In #4021, @webron states that using a $ref inside an “example” is not supported, because the “example” section is interpreted (and rendered) literally. 

My more general question is, is example composition supported in the OpenAPI 3 spec, or not? For example, if I define a response schema that composes several objects of other schema types (where $ref IS allowed), can I use the same $ref approach when defining an example for that schema, or must the example be completely literal (without any $refs)?

**Comment by lrtherond** [comment] 2018-10-08 15:19
I think $ref should work in that case too. Clearly, passing a 10-KB piece of JSON example as a string is very problematic.

**Comment by webron** [comment] 2018-10-10 01:34
@sasha-borodin the spec isn't explicit about it, but I would expect what you shared to be rendered simply as:
```yaml
              user:
                $ref: '#/components/examples/User'
              product:
                $ref: '#/components/examples/Product'
              quantity: 1
```
(that is, $ref's are not being dereferenced)

**Comment by sasha-borodin** [comment] 2018-10-10 01:57
@webron, thanks for the response!  I think there are two issues:

1. The implementation both a) resolves the `$ref`, and b) leaves an internal artifact of `$$ref`.  I think that consistency needs to be achieved.  Either `$ref`s are *not* supported (and displayed literally), or they *are* supported (in which case, rendering `$$ref` is a bug that needs to be fixed).
1. Since the spec isn't explicit about the matter of resolving `$ref`s inside examples, I would like to make a case for resolution instead of literal rendering.  What's the most appropriate channel through which to make such a case or feature request?

**Comment by Alexgmin** [comment] 2018-10-10 09:39
I would like add another argument to the case for resolution. 
Is the current behavior for schemas. 
As a developer trying to define an API, I don't see why I can have nested schema references but not nested example references.

From my point of view, what is wrong in this example is the `value` key being rendered. Why can I reuse schemas but not examples?

```yaml
openapi: '3.0.0'
info:
  title: 'test'
  version: '1.0.0'
paths:
  /hello:
    get:
      description: 'Get welcome message.'
      responses:
        '200':
          description: 'welcome message'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
components:
  schemas:
    Welcome:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        title:
          type: string
        info:
          type: string
      example:
        $ref: '#/components/examples/WelcomeExample'
  examples:
    WelcomeExample:
      $ref: '#/components/examples/MessageExample'
    MessageExample:
      value:
        foo: 2
        bar: 3
```

**Comment by dkrantsberg** [comment] 2019-01-03 20:19
Encountering the same issue. Is anyone working on it?

**Comment by timbedard** [comment] 2019-02-21 23:04
Been running into this lately as well. Any news?

**Comment by shockey** [comment] 2019-04-05 20:11
I'm picking this up - as mentioned in https://github.com/swagger-api/swagger-ui/issues/4931#issuecomment-428358133, we shouldn't be resolving `example` values at all.

**Closed** 2019-08-09 00:07 UTC
Labels: P1, type: bug

**Comment by OnkelTem** [comment] 2020-03-24 03:29
Just trying to clarify things.

So basically we cannot use examples not only in a good way, but _in fact_. Because no one in their clear mind would insert a huge block of example data right in the middle of definitions - and that is exactly what we're forced to do, because:

1) Arrays is what desperately needs loads of data,
2) but arrays can only consume `example` and not `examples`,
3) which is actually the only option to decouple definitions and data.
4) And this nonsense behavior we totally owe to some API spec, sent from above.

Did I get it right?

**Comment by webron** [comment] 2020-03-24 17:36
Couldn't really follow what you're saying, but regardless, this is how the spec is defined, not something within the control of this tool.

**Comment by carlos-soto** [comment] 2020-06-09 00:07
I agree with @alexgmin. Could we request the ability to nest examples so we can, uhm... reuse definitions? After all, that's the whole idea of Domains, isn't it?

**Comment by hkosova** [comment] 2020-06-10 07:24
@carlos-soto you can propose changes to the OpenAPI Specification here:
https://github.com/OAI/OpenAPI-Specification/issues

**Comment by dmak** [comment] 2020-06-12 11:24
Would be nice in addition to support arrays in `example`:
```
responses:
  "200":
    content:
      application/json:
        example:
          - $ref: "#/components/examples/sample1"
          - $ref: "#/components/examples/sample2"
          - $ref: "#/components/examples/sample3"
```

**Comment by hkosova** [comment] 2020-06-12 14:22
@dmak you can propose changes to the OpenAPI Specification syntax constructs here:
https://github.com/OAI/OpenAPI-Specification/issues

As of OAS 3.0.3, multiple examples require the use of the `examples` keyword:
```yaml
responses:
  "200":
    content:
      application/json:
        examples:
          sample1:
            $ref: "#/components/examples/sample1"
          sample2:
            $ref: "#/components/examples/sample2"
          sample3:
            $ref: "#/components/examples/sample3"
```

**Comment by BenceSzalai** [comment] 2020-11-02 00:11
Do you think the issue where `$ref` used in `examples` (plural, which is valid, and part of the OpenAPI specification as opposed to inside `example` (singular)) is dereferenced properly, but also causes an artifact of `$$ref` being added to the dereferenced object?

So for example this:
```yaml
...
examples:
  Users:
    value:
      - $ref: '#/components/examples/User1/value'
      - $ref: '#/components/examples/User2/value'
...
```

Renders as this (in JSON):
```json
[
  {
    "id": 1,
    "email": "johnd@example.com",
    "name": "John Doe",
    "$$ref": "#/components/examples/User1/value"
  },
  {
    "id": 2,
    "email": "janed@example.com",
    "name": "Jane Doe",
    "$$ref": "#/components/examples/User2/value"
  }
]
```

Notice the `"$$ref": "#/components/examples/User*/value"` as the last property. This seems to be an issue regardless what's going on with `example` (singular) also mentioned in https://github.com/swagger-api/swagger-ui/issues/4924#issuecomment-428411720

Should that be opened as a separate issue than?

**Comment by hkosova** [comment] 2020-11-17 18:03
@BenceSzalai 
> What do you think about the issue where `$ref` used in `examples` (plural, which is valid, and part of the OpenAPI specification as opposed to inside `example` (singular)) is dereferenced properly, but also causes an artifact of $$ref being added to the dereferenced object?
> 
> ```
> ...
> examples:
>   Users:
>     value:
>       - $ref: '#/components/examples/User1/value'
>       - $ref: '#/components/examples/User2/value'
> ...
> ```

This is not valid usage. `$ref` is supported only under `examples.<name>`, that is:
```yaml
examples:
  Users:
    $ref: '#/components/examples/User1'
```
The `value` keyword is an analog of `example` (singular) and requires an inline example value.

> Should that be opened as a separate issue than?

#5625

**Comment by BenceSzalai** [comment] 2020-11-17 18:16
Oh, makes sense! Thanks for providing clarity!

**Comment by random-developer-7** [comment] 2022-03-10 14:12
I tried combining multiple $ref elements using allOf. Even though I'm getting a Structural error in Swagger editor, the output in examples seems to be correct. For e.g.,

**Comment by random-developer-7** [comment] 2022-03-10 14:31
I tried combining multiple $ref elements using allOf, just for the sake of it. Even though I'm getting a Structural error in Swagger editor, the output for examples seems to be correct. For e.g.,
```
examples:
 myTestExample:
  $ref: '#/components/examples/testExample'
  
components:
 examples:
  testExample:
   allOf:
    - $ref: '#/components/examples/data1'
    - $ref: '#/components/examples/data2'
  data1:
   value:
    'key1': 'value1'
  data2:
   value:
    'key2': 'value2'
```
This produces the output value for myTestExample as follows:
```
{
 'key1': 'value1',
 'key2': 'value2'
}
```
Is this an expected behaviour?

**Comment by bodo79** [comment] 2022-03-29 12:01
Hi @alexgmin, 
I'v tried many solutions, the only one that seems to work is using 'examples' key and not 'example' and put sigle example with a $ref.
just like this:
`
paths:
  /hello:
    get:
      description: 'Get welcome message.'
      responses:
        '200':
          description: 'welcome message'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
              examples:
                WelcomeExample1: # you can give as an example name any name you want
                  $ref: '#/components/examples/WelcomeExample'
`
