### ISSUE TITLE
Multiple Examples for Response Header not working

### ISSUE THREAD

**Issue by iamjoshuabcxvii** [swagger-api/swagger-ui#5873] opened 2020-02-26 06:12 UTC
I am trying to define two different examples for the Location header of 302 redirect Response.

The ff. code doesn't work even though this is what is placed on the Open API documentation.

> responses:
>         '200':
>           description: 'Sample 200 Response'
>         '302':
>           description: Some token has expired... Clients should follow the `Location` header to refresh the token.
>           headers:
>             Location:
>               schema:
>                 type: string
>               examples: 
>                 'test1':
>                   value: 'value1'
>                 'test2':
>                   value: 'value2'
>               description: 'Description of Location Header'

I am already using SwaggerHub which uses Swagger UI version  3.25.0 , all the while the new feature for multiple examples was placed on Swagger UI version 3.23.0

**Comment by hkosova** [comment] 2020-02-26 07:47
Duplicate of #5432.

**Closed by hkosova** 2020-02-26 07:47 UTC
