### ISSUE TITLE
[Swagger 2.0] Parameters defined at path level are not recognized

### ISSUE THREAD

**Issue by Maks3w** [swagger-api/swagger-ui#1146] opened 2015-04-10 17:06 UTC
Swagger 2.0 allows to define common parameters at path level instead of define for each http method.

Swagger UI does not inherit the parameters and don't display the form.

**Comment by webron** [comment] 2015-04-10 17:08
This is a duplicate of #911 and #929.

**Closed by webron** 2015-04-10 17:08 UTC

**Comment by gaillard** [comment] 2015-06-05 17:36
I tried to use a path level parameter, which was a reference to one at the info level but it does not work. Having a operation level parameter that is a reference to one at the info level does though.

**Comment by webron** [comment] 2015-06-05 17:37
@gaillard - if you can open a new issue with a (full) small sample definition to test, that would be great.
