### ISSUE TITLE
Authorization not being sent through headers

### ISSUE THREAD

**Issue by ajonp** [swagger-api/swagger-ui#3499] opened 2017-08-01 02:36 UTC
When reporting an issue, please provide the following details:
- swagger-ui version
```"swagger-ui-dist": "^3.0.21"```
- a swagger file reproducing the issue
```
{"swagger":"2.0","host":"nahollap780.na.haworthinc.com/bec","produces":["application/json"],"basePath":"/sap/opu/odata/sap/ZGW0001V1_TECHNICAL_SRV","info":{"title":"OData Service","version":"0.0.1","x-odata-version":"1.0"},"paths":{"/backendSystemSet":{"get":{"operationId":"getbackendSystemSet","parameters":[{"name":"$filter","type":"string","required":false,"in":"query"},{"name":"$top","type":"integer","required":false,"in":"query"},{"name":"$skip","type":"integer","required":false,"in":"query"},{"name":"$orderby","type":"string","required":false,"in":"query"},{"name":"$expand","type":"string","required":false,"in":"query"},{"name":"$inlinecount","type":"string","required":false,"in":"query"}],"responses":{"200":{"description":"List of backendSystem","schema":{"type":"object","properties":{"value":{"type":"array","items":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}}}}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"post":{"operationId":"createbackendSystem","parameters":[{"name":"backendSystem","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}}],"responses":{"201":{"description":"Created entity","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}},"/backendSystemSet('{id}')":{"get":{"operationId":"getbackendSystemById","parameters":[{"name":"id","required":true,"in":"path","type":"string"}],"responses":{"200":{"description":"A backendSystem.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"delete":{"operationId":"deletebackendSystem","parameters":[{"name":"id","required":true,"in":"path","type":"string"}],"responses":{"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"patch":{"operationId":"updatebackendSystem","parameters":[{"name":"id","required":true,"in":"path","type":"string"},{"name":"backendSystem","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}}],"responses":{"200":{"description":"A backendSystem.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}},"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}},"/userNameSet":{"get":{"operationId":"getuserNameSet","parameters":[{"name":"$filter","type":"string","required":false,"in":"query"},{"name":"$top","type":"integer","required":false,"in":"query"},{"name":"$skip","type":"integer","required":false,"in":"query"},{"name":"$orderby","type":"string","required":false,"in":"query"},{"name":"$expand","type":"string","required":false,"in":"query"},{"name":"$inlinecount","type":"string","required":false,"in":"query"}],"responses":{"200":{"description":"List of userName","schema":{"type":"object","properties":{"value":{"type":"array","items":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}}}}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"post":{"operationId":"createuserName","parameters":[{"name":"userName","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}}],"responses":{"201":{"description":"Created entity","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}},"/userNameSet('{Bname}')":{"get":{"operationId":"getuserNameById","parameters":[{"name":"Bname","required":true,"in":"path","type":"string"}],"responses":{"200":{"description":"A userName.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"delete":{"operationId":"deleteuserName","parameters":[{"name":"Bname","required":true,"in":"path","type":"string"}],"responses":{"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"patch":{"operationId":"updateuserName","parameters":[{"name":"Bname","required":true,"in":"path","type":"string"},{"name":"userName","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}}],"responses":{"200":{"description":"A userName.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}},"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}}},"definitions":{"Error":{"type":"object","properties":{"error":{"type":"object","properties":{"code":{"type":"string"},"message":{"type":"string"}}}}},"ZGW0001V1_TECHNICAL_SRV.backendSystem":{"type":"object","properties":{"id":{"type":"string"},"client":{"type":"string"},"operatingSystem":{"type":"string"},"database":{"type":"string"},"systemDateTime":{"type":"string","format":"date-time"},"user":{"type":"string"},"currentUserTimeZone":{"type":"string"},"currentUserDate":{"type":"string"},"currentUserTime":{"type":"string"}},"required":["id","client","operatingSystem","database","systemDateTime","user","currentUserTimeZone","currentUserDate","currentUserTime"]},"ZGW0001V1_TECHNICAL_SRV.userName":{"type":"object","properties":{"Bname":{"type":"string"},"Mandt":{"type":"string"},"NameFirst":{"type":"string"},"NameLast":{"type":"string"},"NameText":{"type":"string"}},"required":["Bname","Mandt","NameFirst","NameLast","NameText"]}},"securityDefinitions":{"Bearer":{"type":"apiKey","name":"Authorization","in":"header"}}}
```

Before
![image](https://user-images.githubusercontent.com/3102249/28806871-54847526-7640-11e7-9cac-8ef1326b6797.png)

After
<img width="665" alt="screen shot 2017-07-31 at 10 32 10 pm" src="https://user-images.githubusercontent.com/3102249/28806846-3a09b8c8-7640-11e7-9398-cdf7d8840b24.png">

Request doesn't show headers...
![image](https://user-images.githubusercontent.com/3102249/28806899-80fc9886-7640-11e7-8bb6-cdbf55d8653a.png)

Network debug also does not show headers...
![image](https://user-images.githubusercontent.com/3102249/28806921-a0742cc4-7640-11e7-8a50-24f4abe4556f.png)

**Comment by webron** [comment] 2017-08-01 02:53
@ajonp the issue is with the API definition. The `securityDefinitions` is just a declaration of what security schemes are available. You need to use the `security` property to apply the security globally or to specific operations.

**Comment by ajonp** [comment] 2017-08-03 00:22
Ah I totally missed that. Here is updated spec...
```
{"swagger":"2.0","host":"nahollap780.na.haworthinc.com/bec","produces":["application/json"],"basePath":"/sap/opu/odata/sap/ZGW0001V1_TECHNICAL_SRV","info":{"title":"OData Service","version":"0.0.1","x-odata-version":"1.0"},"paths":{"/backendSystemSet":{"get":{"operationId":"getbackendSystemSet","parameters":[{"name":"$filter","type":"string","required":false,"in":"query"},{"name":"$top","type":"integer","required":false,"in":"query"},{"name":"$skip","type":"integer","required":false,"in":"query"},{"name":"$orderby","type":"string","required":false,"in":"query"},{"name":"$expand","type":"string","required":false,"in":"query"},{"name":"$inlinecount","type":"string","required":false,"in":"query"}],"responses":{"200":{"description":"List of backendSystem","schema":{"type":"object","properties":{"value":{"type":"array","items":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}}}}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"post":{"operationId":"createbackendSystem","parameters":[{"name":"backendSystem","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}}],"responses":{"201":{"description":"Created entity","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}},"/backendSystemSet('{id}')":{"get":{"operationId":"getbackendSystemById","parameters":[{"name":"id","required":true,"in":"path","type":"string"}],"responses":{"200":{"description":"A backendSystem.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"delete":{"operationId":"deletebackendSystem","parameters":[{"name":"id","required":true,"in":"path","type":"string"}],"responses":{"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"patch":{"operationId":"updatebackendSystem","parameters":[{"name":"id","required":true,"in":"path","type":"string"},{"name":"backendSystem","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}}],"responses":{"200":{"description":"A backendSystem.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.backendSystem"}},"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}},"/userNameSet":{"get":{"operationId":"getuserNameSet","parameters":[{"name":"$filter","type":"string","required":false,"in":"query"},{"name":"$top","type":"integer","required":false,"in":"query"},{"name":"$skip","type":"integer","required":false,"in":"query"},{"name":"$orderby","type":"string","required":false,"in":"query"},{"name":"$expand","type":"string","required":false,"in":"query"},{"name":"$inlinecount","type":"string","required":false,"in":"query"}],"responses":{"200":{"description":"List of userName","schema":{"type":"object","properties":{"value":{"type":"array","items":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}}}}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"post":{"operationId":"createuserName","parameters":[{"name":"userName","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}}],"responses":{"201":{"description":"Created entity","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}},"/userNameSet('{Bname}')":{"get":{"operationId":"getuserNameById","parameters":[{"name":"Bname","required":true,"in":"path","type":"string"}],"responses":{"200":{"description":"A userName.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"delete":{"operationId":"deleteuserName","parameters":[{"name":"Bname","required":true,"in":"path","type":"string"}],"responses":{"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}},"patch":{"operationId":"updateuserName","parameters":[{"name":"Bname","required":true,"in":"path","type":"string"},{"name":"userName","in":"body","required":true,"schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}}],"responses":{"200":{"description":"A userName.","schema":{"$ref":"#/definitions/ZGW0001V1_TECHNICAL_SRV.userName"}},"204":{"description":"Empty response."},"default":{"description":"Unexpected error","schema":{"$ref":"#/definitions/Error"}}}}}},"definitions":{"Error":{"type":"object","properties":{"error":{"type":"object","properties":{"code":{"type":"string"},"message":{"type":"string"}}}}},"ZGW0001V1_TECHNICAL_SRV.backendSystem":{"type":"object","properties":{"id":{"type":"string"},"client":{"type":"string"},"operatingSystem":{"type":"string"},"database":{"type":"string"},"systemDateTime":{"type":"string","format":"date-time"},"user":{"type":"string"},"currentUserTimeZone":{"type":"string"},"currentUserDate":{"type":"string"},"currentUserTime":{"type":"string"}},"required":["id","client","operatingSystem","database","systemDateTime","user","currentUserTimeZone","currentUserDate","currentUserTime"]},"ZGW0001V1_TECHNICAL_SRV.userName":{"type":"object","properties":{"Bname":{"type":"string"},"Mandt":{"type":"string"},"NameFirst":{"type":"string"},"NameLast":{"type":"string"},"NameText":{"type":"string"}},"required":["Bname","Mandt","NameFirst","NameLast","NameText"]}},"securityDefinitions":{"Bearer":{"type":"apiKey","name":"Authorization","in":"header"}},"security":{"Bearer":[]}}
```
Now I get an error
![image](https://user-images.githubusercontent.com/3102249/28900580-3d7f294e-77c0-11e7-9e9b-dfa2f5666206.png)

Which gets stuck on Loading spinner
![image](https://user-images.githubusercontent.com/3102249/28900590-50bf77b6-77c0-11e7-895f-f7814d381606.png)

**Comment by webron** [comment] 2017-08-03 00:48
The correct structure for the `security` part would be:

```json
  "security": [
    {
      "Bearer": []
    }
  ]
```

For more information, take a look at https://swagger.io/docs/specification/authentication/.

Also, the `host` can't include path segments. You need to specify it as follows:

```json
"host": "nahollap780.na.haworthinc.com",
"basePath": "/bec",
```

**Comment by ajonp** [comment] 2017-08-03 11:55
@webron thanks for all your help! You can close this ticket for sure, but can you point me in the direction of two other issues. 
1. How can I preset the security since the site we are logged in with already pulled the access_token. Or should I just use some jQuery magic to handle the modal event and fill the field?
2. Is css for result off on this page or is it my site? I would think that we want a new table row for the response body??
![image](https://user-images.githubusercontent.com/3102249/28920715-fa8f80be-7820-11e7-8531-73212a24e4a3.png)

**Comment by shockey** [comment] 2017-08-21 23:42
@ajonp: 

1. dynamically setting security values has been on our radar for a while, see #2793. There's no official support, but if you need it working, there's some rumblings of a workaround in #3318.
2. Yeah, your CSS is off, I think. Try viewing your spec with editor.swagger.io to be sure.

I'm closing this since it's been quiet here - please reply or open a new issue for any other concerns. 

Cheers!

**Closed by shockey** 2017-08-21 23:42 UTC
Labels: Support
