### ISSUE TITLE
Upgrade to swagger-ui-2.1.1 and swagger-spec 2, swagger-ui does not load and uses gigabytes of memory

### ISSUE THREAD

**Issue by rdiehl** [swagger-api/swagger-ui#1583] opened 2015-09-08 13:07 UTC
We are successfully using swagger-core_2.10-1.3.10.jar to generate an old version of the swagger spec, and using an old version of swagger-ui (I believe it's 2.0.23 but not positive), and that all works.  We have a large API with over 50 endpoints.  The old version of swagger-ui is very slow to load, but it does eventually load (after like 10 minutes, so that's unusable).  We are attempting to upgrade to the newest swagger-core and swagger-ui in order to see if the speed improves.

I've got our app server generating a swagger 2.0 spec now, using swagger-core-1.5.3.  We currently don't have any externally accessible sites, so I can't include a link to the swagger.json page - what's the best way to include the generated spec?  It's quite large.

To start, I downloaded a zip of swagger-ui-2.1.1 and just deployed it.  The default pet store app loads.  When I put in the URL to our api in the explorer and hit go, it gives the "fetching resource list" message, but never gets past that.  So far I've tried in Chrome and Safari.  I opened Activity Monitor, and it shows that the Safari/Chrome process takes up an entire CPU core, and uses literally gigabytes of memory.  I let Safari get up to 7GB of memory usage before I killed it.

I saw that there was a new validatorUrl option, I set that to null to turn off the validation.  That does not seem to make a difference, Safari still got up to 3GB of memory before I killed it.  

I got a little curious about whether the swagger.json was valid, so I downloaded a local copy of the validator-badge project, but it seems like it still can't read from a localhost URL.  The debug message I get is: [{"level":"error","message":"Can't read from file http://172.16.189.1:9080/docfinity/webservices/rest/swagger.json"}]

So my questions at this point are:
1. Why are gigs of memory being consumed when trying to load the new swagger.json format?
2. How can I go about debugging this?  
3. What are my options going forward?  The old swagger-ui is unusably slow, and the new one won't load.
4. What's the best way to attach the output from swagger.json so that it's available in this ticket?
5. Is there a way to validate a swagger.json that's running on localhost?

**Comment by webron** [comment] 2015-09-09 07:00
@rdiehl - thanks for opening the ticket, and hopefully together we can debug the probelm.
There are two parts here that can cause an issue, and combined, they can create even bigger issues.

So part one is the swagger-core exposing the json, and part two is swagger-ui loading the json.

For part one - can you try opening the swagger.json directly in your browser (not via swagger-ui) and see how long it takes to load? You can use the network tab in the developer console to get the timing.

For part two - we'd need the json itself. One way to share it is using http://gist.github.com, but if you don't want to sure it publicly, you can email it to me directly (email in profile).

**Comment by rdiehl** [comment] 2015-09-09 13:41
I used Chrome dev tools to get the timing to load the swagger.json, here are the details in HAR format:
```
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2015-09-09T13:19:54.034Z",
        "id": "page_2",
        "title": "http://172.16.189.1:9080/docfinity/webservices/rest/swagger.json",
        "pageTimings": {
          "onContentLoad": 3493.362000000161,
          "onLoad": 3404.190000000199
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2015-09-09T13:19:54.034Z",
        "time": 3299.047999999857,
        "request": {
          "method": "GET",
          "url": "http://172.16.189.1:9080/docfinity/webservices/rest/swagger.json",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Host",
              "value": "172.16.189.1:9080"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
            },
            {
              "name": "Cookie",
              "value": "JSESSIONID=ADB3B50D3CB5525F8FC04576FA2E2282; DOCFINITY_DEVICE_ID_COOKIE=n_43151f3dfdde20670i4mt8w1b0000000"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "JSESSIONID",
              "value": "ADB3B50D3CB5525F8FC04576FA2E2282",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "DOCFINITY_DEVICE_ID_COOKIE",
              "value": "n_43151f3dfdde20670i4mt8w1b0000000",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": 541,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Date",
              "value": "Wed, 09 Sep 2015 13:19:57 GMT"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache, no-store, must-revalidate"
            },
            {
              "name": "Server",
              "value": "DocFinity Server"
            },
            {
              "name": "Content-Type",
              "value": "application/json;charset=UTF-8"
            },
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Expires",
              "value": "Thu, 01 Jan 1970 00:00:00 GMT"
            }
          ],
          "cookies": [],
          "content": {
            "size": 658520,
            "mimeType": "application/json",
            "compression": -652
          },
          "redirectURL": "",
          "headersSize": 266,
          "bodySize": 659172,
          "_transferSize": 659438
        },
        "cache": {},
        "timings": {
          "blocked": 0.427999999828899,
          "dns": -1,
          "connect": -1,
          "send": 0.05899999996472599,
          "wait": 3195.5240000002063,
          "receive": 103.03699999985702,
          "ssl": -1
        },
        "connection": "23007",
        "pageref": "page_2"
      }
    ]
  }
}
```

Here is a link to the gist of the swagger.json, I ran it through a formatter so it's hopefully slightly more readable: https://gist.github.com/rdiehl/55630bd808c743237417

**Comment by adeelshahid** [comment] 2015-09-10 13:38
go into dist/swagger-ui.js

find the lines which say,

```var expectedCalls = 0, toResolve = [];
  // if the root is same as obj[i].root we can resolve locally
  var all = resolutionTable;

  for(i = 0; i < all.length; i++) {
```

update the code to

```var expectedCalls = 0, toResolve = [];
  // if the root is same as obj[i].root we can resolve locally
  var all = resolutionTable;

  all = [];

  for(i = 0; i < all.length; i++) {
```

Because the resolution table fills up and starts calling json specification file for as many times as there are the number of request inside your specification **multiplied** by the method types.

**Comment by rdiehl** [comment] 2015-09-10 15:49
I made that change and cleared my cache to make sure it was applied, but the same behavior continues to occur.  I tried sticking a breakpoint in/around the area of the change in swagger-ui.js, but the breakpoint is never triggered.

**Comment by adeelshahid** [comment] 2015-09-10 15:57
Must be something else, but i assume the problem is similar.

The new Swagger UI probably in my opinion accumulates http GET calls for JSON specification file.

Another way to look at the problem is to see the .exec() function related to the httpManager you can 

```console.log object and options```

and see what get's printed in console.

**Comment by rdiehl** [comment] 2015-09-10 19:18
I went and downloaded some milestone versions from Github.  I found that 2.1.6M1, 2.1.7M1, and 2.1.8M1 do actually load successfully.  2.1.0, 2.1.1, 2.1.2, and all other milestones prior to 2.1.6M1 fail with the symptoms described above.  

So is it possible that this issue has already been fixed in an upcoming release?  If so, is there an ETA for that release?

**Comment by webron** [comment] 2015-09-10 19:22
The milestone releases are actually significantly older so this is a regression. I think @fehguy has put a fix in swagger-js that should help here, but there's no ETA for the update.

**Comment by rdiehl** [comment] 2015-09-14 18:52
OK, for now, we are going to remain on Swagger spec 1.2 using our old version of swagger UI.  We found the Swagger2Markup project recently, and to mitigate the slow loading time, we're going to generate a PDF copy of the docs.

This is a work project, so I've been able to get a few hours a week that I can spend on this.  I can try to make a local build to test the potential fix in swagger-js, but I've never built the swagger stuff before.  I've found the pages detailing how to build swagger-js and swagger-ui, but I'm unclear on how the 2 projects tie together in the build process.  My thought is that I would clone master of swagger-js, make sure the given fix is applied, build swagger-js, and then pull that build into swagger-ui.  Can you give some direction for that?

**Comment by adeelshahid** [comment] 2015-09-14 21:12
the simple bits from my end would be.

clone the repo, take the dist folder,

`https://github.com/swagger-api/swagger-ui/tree/master/dist`

as that contains everything you need to see the swagger-ui

then apply the fix for to the swagger distribution js file, you'll need to do this in the un-minified (https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.js) file.

**Comment by webron** [comment] 2015-09-21 15:56
Can you give the latest version a try?

**Comment by rdiehl** [comment] 2015-09-21 19:23
I downloaded version 2.1.3 and we're still encountering the problem.  Safari's memory usage will climb gradually up to about 700 MB, then it jumps to 3 GB, then Safari crashes.

**Comment by webron** [comment] 2015-09-21 19:25
That's definitely not good. Do you experience the same issue in other browsers too?

**Comment by rdiehl** [comment] 2015-09-21 19:47
It seems to be consistent across all browsers.  CPU usage is always pegged.  

Firefox gives me a couple Unresponsive Script warnings:

Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:26104
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:2672
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:2672
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:26282
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:26104
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:26104
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:2672
Script: http://172.16.189.1:9080/swagger-ui-2.1.3/swagger-ui.js:2614

It gets up to 4.2 GB of memory used, then drops to 350 MB but never actually crashes, or loads the API.

IE consumes 1.7 GB of memory (all available on that VM), never crashed, but never loaded either.

Chrome on IE gives me the unresponsive page dialog a couple times, stays around 800 MB of memory, never crashes, never loads.

**Comment by webron** [comment] 2015-09-21 19:48
And is this the definition you shared above? You're using swagger 1.2?

**Comment by rdiehl** [comment] 2015-09-21 20:01
This is using swagger 2.0, and yes, the gist of my swagger.json is here: https://gist.github.com/rdiehl/55630bd808c743237417

I went back to using swagger 1.2, and that does load successfully, in about 60 seconds the first time, and about 30 the second time.  Memory usage does not spike with swagger 1.2 version.

**Comment by webron** [comment] 2015-09-21 20:06
Aha, so yeah, a 1.1MB JSON *could* end up causing some issues. It shouldn't, but it's definitely not small. What library is generating that? There's something a bit odd in it.

**Comment by rdiehl** [comment] 2015-09-21 20:19
We're using the swagger-core JAX-RS stuff along with the Java annotations to dynamically generate it.  We did identify some problems last week with how are using @ApiModel annotations between version 1.2 and 2.0.  We're using value instead of description there, it seems like 1.2 ignored value.  https://github.com/swagger-api/swagger-core/issues/1441

If you're thinking that could be causing issues here, I'll work on that in my spare time to see if we get better results.

**Comment by webron** [comment] 2015-09-21 20:23
Yeah, I saw the comments there but actually, the behavior hasn't changed. It's been the same, at least in 1.3.X - http://docs.swagger.io/swagger-core/apidocs/com/wordnik/swagger/annotations/ApiModel.html.

I don't *think* that should be the cause of the problem you're seeing, but it's definitely worth a fix.

**Comment by rdiehl** [comment] 2015-09-22 13:40
I took a little time this morning to change @ApiModel value to description, and I uploaded a gist of the results here: https://gist.github.com/rdiehl/a04e4014db6b0ea21b23

I get the same behavior in all the browsers when trying to load it in swagger UI, gobs of memory consumed and the API never loads.

**Comment by webron** [comment] 2015-09-22 13:49
Thanks for the update. I didn't think it would solve the issue, but it's best to eliminate it as an option. I imagine the real issue is the size of the definition and we'll have to investigate it further.

**Comment by fehguy** [comment] 2015-12-10 04:45
Ok so that's a very large spec.  Some good news--loading the swagger javascript client takes well under 500ms so the issue is solely in rendering in the UI.

I will dig in further as this should work fine, there is clearly something needing optimization in the rendering layer.

**Comment by webron** [comment] 2017-03-20 22:41
@buunguyen if you check https://github.com/swagger-api/swagger-ui/issues/1583#issuecomment-142292288 - you'll see that there are performance issues with 3.0 with this spec.

**Comment by shockey** [comment] 2017-04-05 03:14
Loading this spec with latest Swagger-UI (3.0.4) yields the following error:

```
Resolver error: Maximum call stack size exceeded
```

**Comment by shockey** [comment] 2017-09-07 23:34
Closing this in favor of our newer performance tickets.

**Closed by shockey** 2017-09-07 23:34 UTC
Labels: 3.x, Bug, In progress, P2, Performance
