### ISSUE TITLE
Feature Request : Make swagger responses collapsible (if possible via plugin)

### ISSUE THREAD

**Issue by jahirsaiyed** [swagger-api/swagger-ui#7448] opened 2021-08-03 06:21 UTC
### Content & configuration
Make swagger responses collapsible (if possible via plugin)
Swagger/OpenAPI definition:
 ```yaml
 # your YAML here
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

**Comment by hkosova** [comment] 2021-08-03 06:32
Duplicate of #6630.

**Closed by hkosova** 2021-08-03 06:32 UTC
