### ISSUE TITLE
Parameters of type "array" not described correctly

### ISSUE THREAD

**Issue by domaindrivendev** [swagger-api/swagger-ui#713] opened 2014-11-10 16:40 UTC
When pointing to a Swagger 2.0 description, I've noticed that parameters of type "array" are displayed as the "items" type rather than an array of the "items" type. This can be seen in the existing, live petstore port:

http://petstore.swagger.wordnik.com/ui

The /pet/findByStatus operation parameter is described as follows:

    parameters: [
    {
        in: "query",
        name: "status",
        description: "Status values that need to be considered for filter",
        required: false,
        type: "array",
        items: {
            type: "string"
        },
        collectionFormat: "multi"
    }]

But displayed like this:

![image](https://cloud.githubusercontent.com/assets/1434343/4979556/230ad56a-68f8-11e4-8864-cda749c09e9c.png)

As far as I can see, this occurs for all parameter locations (path, query, body etc.)

Cheers

**Comment by fehguy** [comment] 2015-01-31 22:02
this has been fixed in the develop_2.0 branch

**Closed by fehguy** 2015-01-31 22:02 UTC
Labels: Feature

**Comment by Mikhus** [comment] 2016-01-10 22:24
Is there any chance having 

    "required": false,
    "schema": {
        "$ref": "InstructionSequence"
    }

The problem is that seems I can not define a non-mandatory parameter of type "array of primitives", always got validation errors. Does anyone can point me how to do that?

**Comment by webron** [comment] 2016-01-11 21:38
@Mikhus - your question is unclear. That's not an array definition, definitely not an array of primitives. So... what are you trying to do here?

**Comment by Mikhus** [comment] 2016-01-12 21:33
Well, sorry, I meant something like this:

    "required": false,
    "schema": {
        "type": "array",
        "items": {
            "type": "string"
        }
    }

I actually opened a new issue for this here: https://github.com/swagger-api/swagger-node/issues/341

**Comment by GreensterRox** [comment] 2016-08-04 14:41
I seem to be having a similar issue to @Mikhus in that I have defined a parameter as an array of strings with `required: false` but if I do not pass the param in the GET request I get `Expected string - got null.`

How do I make it so that NOT passing sectors in my GTE request will be a valid request?
```
- name: sectors
          description: Array of sectors
          in: query
          type: array
          collectionFormat: multi
          required: false
          items:
            type: string
```

**Comment by vafrcor** [comment] 2017-11-07 03:23
I had similar issue.
I hope there is a solution for this problem

my parameter config:
```
{
  "name": "scope",
  "in": "query",
  "description": "DB Model Scope. For details, please contact system-developer.",
  "required": false,
  "type": "array",
  "items": {
    "type": "string"
  }
}
```

![screen shot 2017-11-07 at 10 17 19](https://user-images.githubusercontent.com/2148366/32475613-53539ba2-c3a5-11e7-8077-76ab27d7e76c.png)

Current solution:
- Add new item to array
- Delete last inserted item
- re-run simulation
