### ISSUE TITLE
model object's "required" field being ignored (spec v1.2)

### ISSUE THREAD

**Issue by dwalden** [swagger-api/swagger-ui#1307] opened 2015-05-25 09:55 UTC
Hi, 
I'm using swagger-ui at tag 198dd641b460e16f85b9bc5f69c46639878b8781 on master.
My JSON input file specifies "swaggerVersion" : "1.2".
It appears that the "required" field of the following model object is ignored:

``` json
  "models" : {
    "Animal": {
      "id": "Animal",
      "required": [
        "id",
        "type"
      ],
      "properties": {
        "id": {
          "type": "long"
        },
        "type": {
          "type": "string"
        }
      }
    }
  }
```
The resultant documentation:
![capture](https://cloud.githubusercontent.com/assets/12455949/7795368/99af7826-02d4-11e5-8e95-999181c5d89f.PNG)

**Comment by ponelat** [comment] 2015-05-25 14:10
This is a duplicate of https://github.com/swagger-api/swagger-ui/issues/1152. Which is a regression bug.

**Comment by webron** [comment] 2015-05-26 14:30
Closing as duplicate.

**Closed by webron** 2015-05-26 14:30 UTC
