### ISSUE TITLE
A tag cannot be named "debug"

### ISSUE THREAD

**Issue by giacomodrago** [swagger-api/swagger-ui#896] opened 2015-02-02 16:45 UTC
If an operation is tagged with a tag named "debug" (case sensitive) the API specification fails to load, and this error is printed on the console:

    Uncaught TypeError: Cannot set property 'help' of undefined

Changing it to "Debug" or anything else fixes the problem.

My user agent is:

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36

**Comment by fehguy** [comment] 2015-02-02 17:25
see this ticket https://github.com/swagger-api/swagger-js/issues/209

**Comment by mohsen1** [comment] 2015-03-11 22:28
#802 is duplicate of this

**Closed by mohsen1** 2015-03-11 22:28 UTC
Labels: swaggger-js
