### ISSUE TITLE
Odd scenario with parameter being highlighted required after value is entered

### ISSUE THREAD

**Issue by ascertrobw** [swagger-api/swagger-ui#5622] opened 2019-09-25 18:23 UTC
### Q&A (please complete the following information)
 - OS: [Windows 8.1]
 - Browser: [F/fox, Chrome, Edge]
 - Version: [All latest]
 - Method of installation: [Manual]
 - Swagger-UI version: [github head]
 - Swagger/OpenAPI version: [Swagger 2.0]

Swagger-UI configuration options:
(all being handled via osgi-jaxrs-connector, and seems to be working normally)

### Screenshots

![Capture](https://user-images.githubusercontent.com/4760572/65628453-5ccefb80-dfc9-11e9-8946-e99481fa14d5.JPG)

### How can we help?

Very odd scenario where the 1st of two path params is flagged as required on Try It Now, even after a value has been entered. Our path params are inherited across ResourceClasses, which I thought might be the issue. 

I did my best to recreate a simpler version of our approach - [P1.zip](https://github.com/swagger-api/swagger-ui/files/3654191/P1.zip) - but the cut down example behaves fine. Our real code is essentially similar to P1.java, just a bigger version with a lot more methods and a handful of other resource classes. Everything with a single path param works fine. Everything with more than one doesn't. But this alone is clearly not an issue, since P1.java doesn't fall down on that. If I inspect the page (as much as I am able to understand), I see the element getting a value="whatever entered" so the value is getting set at least onto the DOM element.

Highly likely this is a rookie error, but I'm battling to see where it could be

**Comment by ascertrobw** [comment] 2019-09-26 08:12
So without realising how or why, I seem to have worked around it. If I move the resource class method to the top level class, rather than the inner static class it behaves e.g.

    @Path("envs/{env_name}")
    public Class<EnvResource> getEnv()
    {
        return EnvResource.class;
    }
    
    @Path("envs/{env_name}/drivers/{driver_name}")
    public Class<DriverResource> getDriver()
    {
        return DriverResource.class;
    }

So rather than having the getDriver as a method on EnvResource, I expose it at the top level class. 

My guess is this simplifies the Swagger output in some way that the UI is happier with. The actual REST API works fine both ways. 

What's odd is that P1.Java seems mean with nested resource class methods on the inner classes. But  that is a much more simplistic example.

Anyhow, we can live with this I think - although it'd be nice to understand what was causing the issue

**Comment by webron** [comment] 2019-09-26 09:30
@ascertrobw thanks for the update. The thing is, as far as Swagger UI is concerned, your actual code is irrelevant. What matters is API description that's loaded into it. If you can share the definition that you loaded into it that caused the issue, it would help us figure out what went wrong.

**Comment by ascertrobw** [comment] 2019-09-26 09:39
> 
> 
> @ascertrobw thanks for the update. The thing is, as far as Swagger UI is concerned, your actual code is irrelevant. What matters is API description that's loaded into it. If you can share the definition that you loaded into it that caused the issue, it would help us figure out what went wrong.

Yeah - realise that it is probably more to do with how the Swagger Core scanning was happening and what that produced than the UI aspect itself. Unfortunately, I can't share the direct definition (company policy) that's why I tried to mimic it with a smaller class, but then failed to trigger the same issue!

Oh well - declaring all the paths upfront in the top level class seems to allow the Swagger core scanners to produce a definition that Swagger UI is happy with.

FWIW - I think there is some weird bug here, because the UI code thinks that a required param is missing even after data has been entered into the HTML field. But I agree, it's probably some odd combination inside the definition behind which is causing that.

**Comment by webron** [comment] 2019-09-26 09:49
Okay, if you don't mind, I'll close the issue for now, but if you update we can reopen. If the problem is sharing it _publicly_, you can also email me the definition directly, but completely understand if you cannot.

**Comment by ascertrobw** [comment] 2019-09-26 09:52
Cool, thanks - that sounds fine. Let me share it privately before you close it off. I have a hunch there may be some obscure bug underlying this. Albeit, that bug may be in how swagger core is scanning our annotations more than it is in the actual UI code.

**Comment by webron** [comment] 2019-09-26 09:54
It sounds like there's a bug here and in swagger-core, and I hope we can fix both, but one step at a time.

**Comment by shockey** [comment] 2019-09-27 01:40
@ascertrobw it would be optimal if you'd provide both versions of the definition (before and after the resource class change) 🙂

**Comment by ascertrobw** [comment] 2019-09-27 06:29
> 
> 
> @ascertrobw it would be optimal if you'd provide both versions of the definition (before and after the resource class change) slightly_smiling_face

Ron's dug into it thx and confirmed his suspicion that it's a bug in swagger core producing an invalid definition. Our core version is very old (1.5.7) due to us using OSGi JAX-RS Connector, which hasn't been updated much. I need to find or make time to fork the repo and update it ourselves since it seems largely unmaintained now. Anyhow, issue now found and if it's a bug that we still see in core once up to date I'll re-raise in there. 

I'll leave open for today in case Ron wants to comment further and then close this down. Assistance has been great thx.

**Comment by webron** [comment] 2019-09-27 08:18
@shockey the short version is that the same parameter was included multiple times and that drove UI a bit nuts, but I don't think we should add a guard for it.

**Closed by webron** 2019-09-27 08:18 UTC

**Comment by oleksiivasylenko** [comment] 2019-11-01 12:44
I have similar issue. 
Any solutions available for the moment to resolve it?
