### ISSUE TITLE
How can I mark a parameter as null in the request body?

### ISSUE THREAD

**Issue by cia1** [swagger-api/swagger-ui#5163] opened 2019-02-07 13:57 UTC
### Content & configuration
Openapi v3, "multipart/form-data" in requestBody.

### Is your feature request related to a problem?
In Swagger UI I can set empty value to a property in RequestBody ("multipart/form-data"), but I cannot ignore the property and not send this to server.

### Describe the solution you'd like
I want have an opertunity to mark (checkbox) a property in RequestBody to send or ignore (if this property is not required).

**Comment by hkosova** [comment] 2019-08-12 13:02
Closing as a duplicate of #5303.
(This issue is older, but #5303 has more details.)

**Closed by hkosova** 2019-08-12 13:02 UTC
