### ISSUE TITLE
swagger-ui doesn't display tags in the order they're specified in 'tags'

### ISSUE THREAD

**Issue by yzats** [swagger-api/swagger-ui#1246] opened 2015-05-06 23:14 UTC
In the documentation for top-level tags list, The 2.0 spec says that "The order of the tags can be used to reflect on their order by the parsing tools.". I don't see that it affects the order of tags displayed in Swagger-UI. 

My tags section looks as follows. 
```
"tags": [
        {         
            "name": "foo"
        },
        {
            "name": "bar"
        }
    ]
```
but the order of tags shown in Swagger-UI doesn't match.

https://groups.google.com/forum/#!topic/swagger-swaggersocket/ZGWmEtgriyw

**Comment by webron** [comment] 2015-07-21 07:38
Closing this one as a duplicate of #1475 even though this one came first. The other is slightly more descriptive.

**Closed by webron** 2015-07-21 07:38 UTC
Labels: Bug, P2

**Comment by faizaantrialx** [comment] 2016-04-29 10:44
can i add sub tags in swagger UI
eg: 
1. Abc
        a. xyz
           i. api call
           ii. api call2
        b. pqr
             i. api call
            ii. api call2
