### ISSUE TITLE
Special operation nicknames put swagger out of order

### ISSUE THREAD

**Issue by cmeresse** [swagger-api/swagger-ui#840] opened 2015-01-21 09:13 UTC
If you use some "reserved words" for operation nicknames, swagger is completely lost.
Try for instance to set "nickname":"name"

This is due to the SwaggerOperation function in swagger.js.
At line 805, SwaggerOperation stores a function in this.resource[this.nickname]:

```javascript
this.resource[this.nickname] = function(args, callback, error) {
    return _this["do"](args, callback, error);
};
```
The problem is that this.resource has some particular properties yet (id, name, description, basePath, etc...) so they are overwritten and this can lead to very odd behaviors of swagger.

**Comment by fehguy** [comment] 2015-01-22 06:26
I've opened an issue on swagger-js and referenced this.

**Comment by fehguy** [comment] 2015-01-28 21:49
will confirm in m1 and close when verified.

**Comment by fehguy** [comment] 2015-02-01 09:15
this is related to https://github.com/swagger-api/swagger-js/issues/209 and will be looked at in m2

**Comment by mohsen1** [comment] 2015-03-16 21:38
This is duplicate of https://github.com/swagger-api/swagger-ui/issues/802

Please follow this issue here https://github.com/swagger-api/swagger-js/issues/194

**Closed by mohsen1** 2015-03-16 21:38 UTC
Labels: swaggger-js

**Comment by whitlockjc** [comment] 2015-03-18 16:14
This should be fixed in the latest `develop_2.0` build of `swagger-js`.
