### ISSUE TITLE
200 response doesnt show up data type in Response Class (Status 200) section

### ISSUE THREAD

**Issue by huded** [swagger-api/swagger-ui#1584] opened 2015-09-08 13:53 UTC
Hi All,
I am using swagger-ui 2.1.1 and on my REST API side i am using springfox-swagger2 2.2.2, REST API's are created using Spring MVC.

The issue i am getting is ,in UI in the Response Class (Status 200) section i will see the response type if its a POJO(Model class),but if the response is a simple datatype like String.class or Integer.class its not showing up in UI,but the generated json have the response schema properly.

In case of success i am returning the accountID back from my controller,if there is error i will return RestErrorMessage class.Please help me on this

1)Server code:

@ApiOperation(value="Update Account", 
            notes="This method will validate the information passed before attempting to update an Account. It will check if the " +
                "accountId, account Name, creation date, user and holding information is correct. Thereafter, the account update process starts ",
            produces=   "application/json,application/xml",
            response=String.class,
            consumes="application/json, application/xml"
            )
    @ApiResponses(value = { 
    	    @ApiResponse(code = 200, message = "Successful response",response=String.class),
    	    @ApiResponse(code = 420, message = "Acccount cannot be updated",response=RestErrorMessage.class),
    	    @ApiResponse(code = 500, message = "Unkown error",response=RestErrorMessage.class) })
    @RequestMapping(value = "/accounts", method = RequestMethod.POST)
    public ResponseEntity<?> updateAccount(@RequestBody Account acct)

2)Generated JSON:

![issue1](https://cloud.githubusercontent.com/assets/14162711/9736389/8a7428e2-565e-11e5-986b-f586fa57ae3d.png)

3)UI:
![issue2](https://cloud.githubusercontent.com/assets/14162711/9736426/c23a3bae-565e-11e5-9aa2-7701b242e3f4.png)

**Comment by webron** [comment] 2015-09-11 09:08
This is a known issue, duplicate of #1186.

**Closed by webron** 2015-09-11 09:08 UTC
