### ISSUE TITLE
Failing when trying to run 'npm run build'

### ISSUE THREAD

**Issue by JimSterling** [swagger-api/swagger-ui#3027] opened 2017-05-04 16:56 UTC
I am using v3.0.8 and I am running into issues when I am trying to build swagger-ui with my changes. I have included the npm-debug log, as well as some of the dependencies that npm had said were deprecated when installing npm.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle swagger-ui@3.0.8~prebuild: swagger-ui@3.0.8
6 silly lifecycle swagger-ui@3.0.8~prebuild: no script for prebuild, continuing
7 info lifecycle swagger-ui@3.0.8~build: swagger-ui@3.0.8
8 verbose lifecycle swagger-ui@3.0.8~build: unsafe-perm in lifecycle true
9 verbose lifecycle swagger-ui@3.0.8~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/swagger-ui/releases/3.0.8/node_modules/.bin:/usr/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin/
10 verbose lifecycle swagger-ui@3.0.8~build: CWD: /var/www/swagger-ui/releases/3.0.8
11 silly lifecycle swagger-ui@3.0.8~build: Args: [ '-c',
11 silly lifecycle   'npm run build-core && npm run build-bundle && npm run build-standalone' ]
12 silly lifecycle swagger-ui@3.0.8~build: Returned: code: 1  signal: null
13 info lifecycle swagger-ui@3.0.8~build: Failed to exec build script
14 verbose stack Error: swagger-ui@3.0.8 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid swagger-ui@3.0.8
16 verbose cwd /var/www/swagger-ui/releases/3.0.8
17 error Linux 3.10.0-514.10.2.el7.x86_64
18 error argv "/usr/bin/node" "/bin/npm" "run" "build"
19 error node v6.10.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error swagger-ui@3.0.8 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
22 error Exit status 1
23 error Failed at the swagger-ui@3.0.8 build script 'npm run build-core && npm run build-bundle && npm run build-standalone'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the swagger-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build-core && npm run build-bundle && npm run build-standalone
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs swagger-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls swagger-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Modules that NPM says are deprecated:

```
babel-plugin-module-alias@1.6.0
to-iso-string@0.0.2
jade@0.26.3
minimatch@0.3.0
```

There was also output saying npm-gyp should be installed globally (not sure if that is something I should do since I am not running npm on windows
and some warning NPM gave me after the install:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN react-addons-shallow-compare@0.14.8 requires a peer of react@^0.14.8 but none was installed.
> npm WARN react-addons-perf@0.14.8 requires a peer of react@^0.14.8 but none was installed.
> npm WARN react-object-inspector@0.2.1 requires a peer of react@^0.14.0 but none was installed.
> npm WARN sass-loader@6.0.3 requires a peer of webpack@^2.0.0 but none was installed.
> npm WARN eslint-config-standard-jsx@3.2.0 requires a peer of eslint@>=3.0.0 but none was installed.
> npm WARN eslint-config-standard@6.2.1 requires a peer of eslint@>=3.8.1 but none was installed.
> npm WARN eslint-plugin-standard@2.0.1 requires a peer of eslint@>=3.0.0 but none was installed.

I am putting this in the google group as well as here, and either one can be removed if it feels redundant. Thank you for any help you can provide!

**Comment by Azotherian** [comment] 2017-05-04 20:28
Just my suggestion: I have had the exact same issue, and I grabbed  v3.0.7 and ran the build on it, and it worked. Not sure if that really helps too much, but it may help narrow down where the problem lies

**Comment by shockey** [comment] 2017-05-04 20:33
@JimSterling1, it's not clear from your post what OS you're on, can you clarify?

@Azotherian, can you share your OS, Node version, and NPM version?

Thanks to both of you!

**Comment by JimSterling1** [comment] 2017-05-04 20:35
@shockey I am using cent os 7

**Comment by Azotherian** [comment] 2017-05-04 20:42
@shockey I am also using cent os, and my npm version is v3.10.10 and my node version is v6.10.1

**Comment by tylerjames** [comment] 2017-05-09 15:16
Facing a similar issue on macOS Sierra using Node v7.5.0 and npm v4.1.2 and swagger-ui v3.0.9

I get a similar set of npm warnings when I run `npm install`:

```
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint@>=3.8.1 but none was installed.
npm WARN eslint-config-standard-jsx@3.2.0 requires a peer of eslint@>=3.0.0 but none was installed.
npm WARN eslint-plugin-standard@2.0.1 requires a peer of eslint@>=3.0.0 but none was installed.
npm WARN react-addons-perf@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-shallow-compare@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-object-inspector@0.2.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN sass-loader@6.0.3 requires a peer of webpack@^2.0.0 but none was installed.
```

**Comment by shockey** [comment] 2017-05-10 19:24
@tylerjames, do you only get the warnings, or does your build fail? FYI, we don't explicitly support Node 7 yet.

CentOS people: I'm going to spin up a VM today and try to reproduce the issues you're seeing.

**Comment by tylerjames** [comment] 2017-05-10 20:26
@shockey 
I was able to get it to work. At first I had downloaded a zip of the repo. In that case I experienced the problems I described.
When I instead cloned the repo the `npm install` worked fine. It seemed to not like that it didn't reside in an existing git repo.

**Comment by Azotherian** [comment] 2017-05-10 20:39
I pulled the zip right from my vm and unzipped and copied the contents over to my project. Maybe that had something to do with it?

**Comment by shockey** [comment] 2017-05-10 20:46
@Azotherian, I can't think of why that would be off the top of my head, but I'll test the zip and cloning when I get around to this today.

If you can try cloning on your end as well, that would be helpful. Thanks for chiming in!

**Comment by shockey** [comment] 2017-05-11 04:52
All: Did you see this error message?

```
Error: Git returned with status 128: fatal: Not a git repository (or any of the parent directories): .git
    at handleProcessResult (/root/swagger-ui-3.0.8/node_modules/git-describe/lib/git-describe.js:69:19)
    at wrapper (/root/swagger-ui-3.0.8/node_modules/lodash/lodash.js:5259:19)
    at gitDescribe (/root/swagger-ui-3.0.8/node_modules/git-describe/lib/git-describe.js:46:16)
    at wrapper (/root/swagger-ui-3.0.8/node_modules/lodash/lodash.js:5259:19)
    at Object.<anonymous> (/root/swagger-ui-3.0.8/make-webpack-config.js:12:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by tylerjames** [comment] 2017-05-11 05:49
Yeah, that looks familiar

**Comment by shockey** [comment] 2017-05-11 06:12
I just merged something that appears to fix a problem I'm encountering when trying to `npm run build` in a folder not part of a Git repository (i.e. a zip download of swagger-ui)

Can y'all try to do an `npm run build` with `https://github.com/swagger-api/swagger-ui/archive/master.zip`, and tell me if it works for you?

**Comment by tylerjames** [comment] 2017-05-11 20:03
@shockey That seems to have fixed it

**Comment by shockey** [comment] 2017-05-24 16:07
Ok, haven't heard anything new about this here or in any other tickets - also can't reproduce anything on my end. I'm going to assume my PR fixed all the problems here.

Please comment here or open a new ticket if any issues persist. Thanks!

**Closed by shockey** 2017-05-24 16:07 UTC
Labels: Bug
