### ISSUE TITLE
Objects used as query parameters lose information

### ISSUE THREAD

**Issue by daniel-frak** [swagger-api/swagger-ui#5790] opened 2020-01-13 09:57 UTC
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version: 79.0.3945.79
 - Method of installation: via Springdoc OpenAPI dependency
 - Swagger-UI version: 3.24.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

The following OpenAPI definition shows two ways to achieve this issue - via directly defining an object as a query parameter and via referencing one using $ref. Both will lose information when displayed with Swagger UI.

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
paths:
  /filtered:
    get:
      parameters:
        - name: filter
          in: query
          schema:
            type: object
            properties:
              property1:
                type: string
                description: Property1 description
                example: "abc"
              property2:
                type: integer
                description: Property2 description
                maximum: 2000
                minimum: 1
                format: int32
        - name: filter2
          in: query
          schema:
            $ref: '#/components/schemas/ArticleFilter'
      responses:
        '200':
          description: default response
          content:
            'application/json': {}
components:
  schemas:
    ArticleFilter:
      type: object
      properties:
        property3:
          type: string
          description: Property3 description
          example: "abc"
        property4:
          type: integer
          description: Property4 description
          maximum: 2000
          minimum: 1
          format: int32
```

Swagger-UI configuration options:
Default

### Describe the bug you're encountering

When an object is defined as a query parameter there is no way to view the schema/descriptions. On the other hand, the example value works correctly and the "Try it out" functionality correctly unwraps the object to query parameters, suggesting that this is a valid OpenAPI spec.

### To reproduce...

1. Define a GET endpoint
2. Define a schema of type=object in that endpoint OR reference a component schema of type object via $ref
3. Add properties to that object
4. Observe the lack of Schema tab on the endpoint in Swagger-UI

### Expected behavior
Swagger-UI should show a "Schema" tab for the endpoint parameters of type=object, just like it happens in the case of POST endpoints (or every endpoint in the "Responses" section).

Alternatively, the object should be unwrapped into individual query parameters in the "Parameters" section, just like it happens in the generated CURL when using "Try it out".

Either way, valuable documentation information should not be skipped as it is right now just because the parameters were passed as an object.

### Screenshots
![image](https://user-images.githubusercontent.com/46451063/72245769-9451ca00-35f1-11ea-8252-eae08c7993c3.png)

**Comment by hkosova** [comment] 2020-01-13 10:51
Duplicate of #4581.

**Closed by hkosova** 2020-01-13 10:51 UTC
