### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wangkang007** [swagger-api/swagger-ui#3035] opened 2017-05-05 10:53 UTC
When reporting an issue, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

when is use this model

public class Tree{
   private int pid;
   private List<Tree> child;
}
immutable.js:2407 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at eval (immutable.js:2407)
    at List.Map.withMutations (immutable.js:1355)
    at updateList (immutable.js:2407)
    at List.set (immutable.js:2098)
    at updateOrderedMap (immutable.js:2782)
    at OrderedMap.set (immutable.js:2688)
    at eval (immutable.js:2653)
    at eval (immutable.js:3018)
    at ObjectSeq.__iterate (immutable.js:420)
    at KeyedIterable.mappedSequence.__iterateUncached (immutable.js:3017)

**Comment by webron** [comment] 2017-05-05 21:27
Duplicate of #2923.

**Closed by webron** 2017-05-05 21:27 UTC
