### ISSUE TITLE
Swagger UI doesn't display 0 example on Int32

### ISSUE THREAD

**Issue by SledgeHammer01** [swagger-api/swagger-ui#5950] opened 2020-04-06 01:57 UTC
I'm using Springdoc 1.3.0 (Open API), but I have seen this issue with pretty much every implementation in every language.

`OpenApi doc snippet looks like: "operationId":"getPagedFlights_1","parameters":[{"name":"page","in":"query","description":"The page number to retrieve.","required":true,"schema":{"type":"integer","format":"int32"},"example":0}
`

In this case, the UI renders with no example. If I put anything else in there except for 0, it works, just not 0.

**Comment by hkosova** [comment] 2020-04-06 07:35
Duplicate of #5573.

**Closed by hkosova** 2020-04-06 07:35 UTC
