### ISSUE TITLE
Download link in response body does not work

### ISSUE THREAD

**Issue by egemenvardar** [swagger-api/swagger-ui#2132] opened 2016-05-02 10:50 UTC
I am having a problem similar to the ones described in #374 and #1196. I have a service which returns a pdf file as attachment with `Content-Disposition` header. This works when I call the endpoint from the browser - file is downloaded. On Swagger UI I get a download link after calling the service with response content type application/pdf, however that link downloads an empty pdf file:

![swagger_pdf_download_doesnt_work](https://cloud.githubusercontent.com/assets/17125072/14950868/620dad36-1055-11e6-9eef-aaac37ecaeb9.png)

My `swagger.json` is generated by Enunciate (version 2.3.0) and the relevant part looks like this:

```
"responses": {
  "200": {
    "schema": {
    "description": "",
    "$ref": "#/definitions/json_File"
  }, ...
```

I tried adding `"type": "file"` to the schema, but it didn't fix the problem. What could be going wrong here?

**Comment by ebetschart** [comment] 2016-07-12 05:49
After further investigations I could narrow the problem. The downloaded pdf is not empty but some characters have changed and therefore it cannot be shown properly. All the special characters are replaced by '�'. Looks like an encoding problem:

Original pdf:
> %PDF-1.4
> %<E2><E3><CF><D3>
> 5 0 obj
> <<
> /Type/XObject
> /Subtype/Form
> /FormType 1
> /BBox [0 0 0 0]
> /Matrix [1 0 0 1 0 0]
> /Resources <<
> /ProcSet 1 0 R
> ...

In blob:
> %PDF-1.4
> %����
> 5 0 obj
> <<
> /Type/XObject
> /Subtype/Form
> /FormType 1
> /BBox [0 0 0 0]
> /Matrix [1 0 0 1 0 0]
> /Resources <<
> /ProcSet 1 0 R
> ...


- The pdf is correctly downloaded and put into a local blob object in the browser
- When reading the pdf from the blob (the link provided in the response body) some of the characters are replaced

**Comment by dgreenbean** [comment] 2016-07-14 13:00
This is because the xhr.responseType is not blob.  This causes the contents of the response are encoded into a UTF-8 string, which cannot be converted back to the original bytes of the response.  I don't have a fix, but would be very interested in finding one.

**Comment by IsmaGitHub** [comment] 2016-07-21 11:33
I have the same problem, if I click to download the file is corrupted , but if you download the file by url from chrome or the file is perfect postman .

We may be missing some annotation of swagger ?

**Comment by dgreenbean** [comment] 2016-07-21 12:39
The issue is the xhr.responseType is not blob, so the contents are encoded
as a string.  Encoding to UTF-8 and back to bytes does not necessarily
yield the original bytes.

2016-07-21 7:34 GMT-04:00 IsmaGitHub <notifications@github.com>:

**Comment by IsmaGitHub** [comment] 2016-07-21 13:14
There is no solution for now?

**Comment by dgreenbean** [comment] 2016-07-21 13:22
No.  Take a look at https://github.com/swagger-api/swagger-ui/pull/2282 and
https://github.com/swagger-api/swagger-js/pull/812.  These won't solve your
issue in themselves, but they should outline what is involved.

2016-07-21 9:14 GMT-04:00 IsmaGitHub <notifications@github.com>:

**Comment by fehguy** [comment] 2016-07-29 14:57
@bodnia could you please look at this and see if we can have a generalized solution for the `xhr.responseType`?

**Comment by fehguy** [comment] 2016-09-15 08:11
@dgreenbean please take a look at https://github.com/swagger-api/swagger-ui/pull/2404/commits/4bdaeba797224bde922f3cefe55a6807428437a8.  I believe this addresses this in a general fashion.

**Comment by dgreenbean** [comment] 2016-09-15 15:22
It won't hurt, but binary -> string is a lossy operation.  This means that
string -> binary will not always result in the same binary as the original
response.  It might work in some cases, but there are cases where it will
fail.  The only way I have found to get this to work generally is to set
the responseType on the XHR to blob.  Then, when reading out the response,
the raw blob needs to be preserved without converting it to a string.

2016-09-15 4:11 GMT-04:00 Tony Tam <notifications@github.com>:

**Comment by fehguy** [comment] 2016-09-15 15:26
Got it, let me look at that.

**Comment by fehguy** [comment] 2016-09-15 18:30
ok @dgreenbean fixed in the PR

**Comment by dgreenbean** [comment] 2016-09-16 01:09
I believe that will work as long as the content contains the raw binary
content.

2016-09-15 14:30 GMT-04:00 Tony Tam <notifications@github.com>:

**Closed** 2016-09-16 17:02 UTC

**Comment by ckkiran** [comment] 2016-10-20 15:24
Hi, Taking dist folder is enough for this fix? I see few changes in the src folder as well.

**Comment by fehguy** [comment] 2016-10-20 15:25
There was a release, [2.2.6](https://github.com/swagger-api/swagger-ui/releases/tag/v2.2.6) that incorporates this fix.

**Comment by ckkiran** [comment] 2016-10-20 15:34
Thanks, Tony Tam. I took the 2.2.6 but problem is not gone. I have taken
only dist folder. So I am wondering if I missed out anything. Should I be
taking the contents of src folder as well? Because there is a file change
in src folder.

Thanks and Regards,
Kiran
Mobile: +91 9972599033

**Comment by fehguy** [comment] 2016-10-20 15:40
No, the dist folder is *everything*.  You only need `src` if you're going to rebuild it.

If the problem is still there, please open a new ticket and share a specification and other details.  then we can provide a general fix.

**Comment by milind-pawar** [comment] 2017-01-16 12:15
@ckkiran did you find any solution for this. I am returning file from java code in response, but on download the file get corrupts. While when downloading from browser the URL works fine.

**Comment by fehguy** [comment] 2017-01-17 03:48
@milind-pawar usually this happens when the `produces` attribute does not specify a binary file type, or the server lies in the response, and says it's something other than what it actually is.  Can you please share more about your situation?

**Comment by ckkiran** [comment] 2017-01-17 04:22
Yes. The problem was with encoding. In swagger-ui.js, there is a function binaryRequest. You need to add your data type there, else by default it will be encoded as unicode/text. Currently, only image and pdf data types are handled.

**Comment by milind-pawar** [comment] 2017-01-17 08:49
@fehguy ok I will show my backend java code also the swagger UI responses i get
**JAVA (server side)**: I am returning file and this would be a image, mp3, vedio, pdf, text etc
```
@GET
@Produces({MediaType.MULTIPART_FORM_DATA, MediaType.APPLICATION_OCTET_STREAM})
@ApiOperation(value = "Get Case Resource by resource Id")
@ApiResponses(value = {@ApiResponse(code = 200, message = "Success" })
@Path("attachment/{resourceId}")
public Response getCaseResource(@PathParam("resourceId") Long resourceId) {
 //........
return Response.status(Response.Status.OK).entity(file).header("Content-Disposition", "attachment ; filename=" + fileName).build();
}
```
![swaggerui](https://cloud.githubusercontent.com/assets/15321923/22013544/8e0b47fe-dcbf-11e6-922f-10baf44d9544.png)


On download this file, the file name is this as shown in the below image(_which is not the actual file name_) also the file gets corrupt. 
![on_download](https://cloud.githubusercontent.com/assets/15321923/22013492/4b0c7810-dcbf-11e6-9f21-d95d146fa6f8.png)

Also when i hit my server URL directly on the browser I get the exact file .
please text if need any thing else?

**Comment by ckkiran** [comment] 2017-01-17 08:58
@milind-pawar. Try what I have suggested. It will resolve your problem - I was facing the same issue.

**Comment by milind-pawar** [comment] 2017-01-17 09:02
@ckkiran I found those line of code in swagger-ui.js file, but since I am newbie I don't understand what line of code i need to attach there. :(

**Comment by ckkiran** [comment] 2017-01-17 10:13
return (/^image/i).test(accept) || (/^application\/pdf/).test(accept) || (/^application\/octet-stream/).test(accept);

**Comment by milind-pawar** [comment] 2017-01-17 12:26
@ckkiran as I have updated version of swagger-ui.js i.e. 2.2.8, and this code is already in the new js, unfortunately this doesn't work for me :(

**Comment by fehguy** [comment] 2017-01-17 16:36
Look at your request headers. `Accept: multipart/form-data` doesn't make sense.

**Comment by milind-pawar** [comment] 2017-01-18 05:34
Any perfect solution?

Thanks
Milind Pawar
Software Engineer.
LMS Solutions pvt. ltd

(sent from phone)

**Comment by ckkiran** [comment] 2017-01-18 08:11
I think it should have worked if you have taken 2.2.8. Try downloading a text file and see if its corrupted. If its not corrupted then its to do with encoding and the problem will be to do with content type.

**Comment by milind-pawar** [comment] 2017-01-18 10:18
Thanks @ckkiran 
I tried as you said. I tried downloading a text file
Having response content type as **application/octet-stream** I got a download link in the response body, but got a corrupt file :(

**Comment by ckkiran** [comment] 2017-01-18 10:25
Okay. Then its not encoding problem. There could be lot going wrong. Try different browsers if possible. Check file size after downloading. Vary the file size and check if the file size matches. Open the downloaded text file and see if its completely random or there is some text from your original file. Give a try with application/text when downloading a text file. This is pretty much I could think of so. Hope it helps.

**Comment by carvilsi** [comment] 2017-02-27 14:36
I have the same problem, clicking at the download link will download corrupted file.
Tried on :
Google Chrome: Version 56.0.2924.87 (64-bit)
Safari version 10.0.3 (In this case it did not download anything: `Failed to load resource: Frame load interrupted`)
On a Mac OS X 10.10.5

**Comment by cogito-clarus** [comment] 2017-03-07 21:40
I have the same issue. I'm using a controller to grab firmware from the cloud - testing with swagger = EPIC FAIL, Postman = perfect
This is a serious PITA...

**Comment by nojarp** [comment] 2017-09-12 20:22
Any updates on this issue? I am facing the same

**Comment by shockey** [comment] 2017-09-12 21:07
This issue won't be reopened, as Swagger-UI 2.x is no longer under development.

I'm locking this thread to prevent further bumping. If you're experiencing this with the newer 3.x series, please open a new issue 😄
