### ISSUE TITLE
Render models in UI code, not JS

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#1248] opened 2015-05-07 23:48 UTC
This may be a duplicate, but we need to move the rendering of models out of swagger-js and into swagger-ui.

**Comment by fehguy** [comment] 2015-05-07 23:50
- [ ] add rendering of read-only attributes

**Comment by webron** [comment] 2015-05-09 17:51
Shouldn't there be an equivalent issue in swagger-js for removing it?

**Comment by makimat** [comment] 2015-05-20 09:45
Sorry but being new here, could someone tell how can I find out which release version has or will have this issue fixed?

**Comment by webron** [comment] 2015-05-20 12:40
@makimat - we haven't set a plan for it yet.

**Comment by gaillard** [comment] 2015-06-03 21:04
:+1: It appears the issue I mentioned over at https://github.com/swagger-api/swagger-spec/issues/303 is caused by this

**Comment by gaillard** [comment] 2015-06-04 00:58
Also a big :+1 to getting readOnly to have meaning in the UI.

**Comment by sschwell** [comment] 2015-08-13 20:01
+1 for showing model descriptions in the UI

**Comment by bixibu** [comment] 2015-09-15 09:08
+1

**Comment by alexkrishnan** [comment] 2015-09-21 21:29
We would also really love to have support for the readOnly property!

**Comment by treidco** [comment] 2015-10-02 14:06
+1 for this feature!

**Comment by matoushavlena** [comment] 2015-10-20 20:11
+1

**Comment by JeroenDeDauw** [comment] 2015-11-29 16:17
:+1:

**Comment by luigibianchi** [comment] 2015-12-22 08:57
+1

**Comment by cabbonizio** [comment] 2015-12-27 15:35
Hi, is there an update to when we will be able to document Maps for JSON responses?  I'm trying to push Swagger in our organization and this is one of the things I have trouble explaining to the masses that we cannot show JSON schemas with maps.

**Comment by fehguy** [comment] 2015-12-27 16:20
Simple maps are easy but complex maps (values which are complex models) are tricky. The most helpful input would be how you'd expect them to appear in both the sample and schema views

**Comment by cabbonizio** [comment] 2015-12-28 12:43
@fehguy fair enough!  I'll be in the office soon and will push some examples over to you.   Stay tuned and thanks for your response.

**Comment by cabbonizio** [comment] 2015-12-28 16:32
Here's what I propose @fehguy:

Here is the sample JSON.   This a simple response of a map of product objects with the key being the product number.
```
{
	"products": {
		"01234": {
			"shortDescription": "Sample Product Description",
			"price": 100.00
		},
		"56789": {
			"shortDescription": "Another Sample Product Description",
			"price": 50.00
		}
	}
}
```

Here is how I propose (roughly!) it should look in the model schema view:

![swagger](https://cloud.githubusercontent.com/assets/6088654/12021601/008d75f8-ad56-11e5-8168-d2c53749387e.png)


Here is how I propose (in YAML using Swagger editor) we define a map:
```
    Response:
      description: "Sample description"
      type: object
      properties:
        products:
          type: map
          key:
            description: "Product identifier"
            type: string
          value:
            $ref: "#/definitions/Product"
    Product:
      description: Product Object
      type: object
      properties:
        shortDescription:
          description: Sample description.
          type: string
        price:
          description: Price of product.
          type: number          
```

**Comment by cabbonizio** [comment] 2015-12-28 16:37
I hope this helps @fehguy.   I had a few developers at my desk to put this proposal together for maps as many of us in the organization are taking advantage of maps within our response models and we're all big fans of Swagger.   As I said before this is one of the main missing pieces to complete our documentation.  There are others questioning the use of Swagger due to this limitation and I'm trying to evangelize it.   I hope the example above helps provide a general guideline what we're looking for and I know other users of the Swagger community have been asking for this.   Thanks very much for your attention to this and hope there's something cool that comes out of this!

**Comment by fehguy** [comment] 2015-12-31 20:57
thanks @cabbonizio this is a pretty easy fix in the short term.  There are some limitations, though, that make it harder to support, such as in-line map definitions, etc.

**Comment by cabbonizio** [comment] 2016-01-04 18:57
@fehguy, thanks for the response I'm excited to hear this would be an easy fix.   Just curious, is this a "fix" or actually an "enhancement" since maps are currently not supported?   Either way, I'm hoping maps will be available soon.   

I agree, complex map definitions and in-line definitions would be challenging, but like anything else those can be incremental and if you show people Swagger can support maps, even if functionality is limited at the start, this is a step in the right direction.  

Curious, how soon would I be able to test something out for map support?

**Comment by fehguy** [comment] 2016-01-04 19:13
@cabbonizio we are moving the code into swagger-ui right now.  Then the rendering will be much easier to do.

**Comment by webron** [comment] 2016-01-16 07:04
@cabbonizio - Swagger (or rather JSON Schema) supports map definitions in a different way, which potentially adds to the complexity of the implementation. There's no `type: map`.

Maps are controlled via the `additionalProperties` property. JSON doesn't support non-string properties, so the key will *always* be a string. The value is defined by whatever is defined under that property. Following the example you provided, it would be:

```yaml
    Response:
      description: "Sample description"
      type: object
      properties:
        products:
          type: object
          additionalProperties:
            $ref: "#/definitions/Product"
```

Hope this clarifies it.

**Comment by cabbonizio** [comment] 2016-01-16 15:03
I thought I tried this before but will give it another whirl.  If it at least renders the definition then i can kust describe it's a map and our api clients will hopefully get it

**Comment by webron** [comment] 2016-01-16 17:00
Well, it won't. The display of maps is not yet supported in the UI as @fehguy mentioned. That's why he asked for suggestions on the display.

**Comment by cabbonizio** [comment] 2016-01-16 17:54
Do you recommend an issue be opened (map support) on the OpenAPI GitHub for tracking?   You mentioned any asks for changes to the spec be opened there.   On here i suppose we should just keep this open for the UI and rendering possibilities.   Sound like a plan?

**Comment by webron** [comment] 2016-01-16 17:56
There is map support in the spec (`additionalProperties`), so there's no need for a ticket about it. This is a tooling issue, not a spec.

**Comment by cabbonizio** [comment] 2016-01-16 18:28
Ah, so additionalProperties IS used for map support which covers spec perspective, all about the tooling...got it.

**Comment by webron** [comment] 2016-01-16 18:31
Yup, sorry of my previous explanation was confusing.

**Comment by cabbonizio** [comment] 2016-01-16 18:53
@webron you are very helpful no worries.  Who can complain you are responding over the weekend?   Very much appreciated!

**Comment by webron** [comment] 2016-01-16 21:24
Thanks for the feedback, have a great weekend ;)

**Comment by cabbonizio** [comment] 2016-02-02 19:23
@fehguy @webron curious any further discussions/ideas on when Swagger UI can render the additionalProperties (for maps)?   I was curious if my suggestions on display earlier in this issue on added any value.   Thanks!

**Comment by gullerya** [comment] 2016-04-21 07:03
Hi all,
I do see some work is going on about to show the XML schema in body preview, so just to be sure: is it already available feature, soon to be available, ETA?
I'm struggling with my configuration to get XML shown, but it's always JSON that is previewed.

**Comment by webron** [comment] 2016-04-21 08:05
@gullerya XML is currently rendered in the UI

**Comment by gullerya** [comment] 2016-04-21 08:17
well, i must be doing something wrong then:
AFAIU, all i need to do is to set "consumes": ["application/xml"] on the POST/PUT operation, am i missing something?
Should this be asked in another thread/forum or is it okay here?

**Comment by webron** [comment] 2016-04-21 08:19
@gullerya may be better to open a new ticket so we can cover it there easily. If you can, please provide the spec itself or something close that reproduces the issue.

**Comment by koekemos** [comment] 2016-05-06 14:15
Hi all,

Has the issue been resolved to display XML in the model and model schema on the swagger UI  ? 
Links #583, #744

**Comment by fehguy** [comment] 2016-05-06 15:51
Try master

**Comment by kjschnei001** [comment] 2016-05-11 13:46
@fehguy @webron Is there any update on the work to display maps in the swagger ui?

**Comment by fehguy** [comment] 2016-05-11 14:25
Yes, we are doing substantial work in the rendering code now.

**Comment by kjschnei001** [comment] 2016-05-11 20:38
@fehguy That's great news!  Our team is looking to utilize this functionality as soon as it is available.

**Comment by cabbonizio** [comment] 2016-05-12 02:04
Looking very forward to seeing map support in the UI!

**Comment by Espolette** [comment] 2016-05-26 12:20
Hi all,
@fehguy @webron Have you a date for the support of maps in Swagger UI ? We are also very interested in this development.

**Comment by webron** [comment] 2016-06-03 17:56
No ETA I'm afraid. We're working on something that will greatly impact this feature request, but I can't say when it'll be available.

**Comment by Espolette** [comment] 2016-06-06 07:15
Ok thanks.

**Comment by burnaz** [comment] 2016-06-12 19:33
Tracking map support. Thanks

**Comment by baramsinsa** [comment] 2016-10-26 03:04
Hi all,
Sorry but, is any update support Map in swagger UI?

**Comment by angela-mylo** [comment] 2016-12-12 15:31
It's been six months since the last comment.  Any update on the schema support for maps?

**Comment by KaranKamath** [comment] 2017-01-12 10:41
Any ETA / priority assigned to this? Our organization loves swagger, but this is a deal breaker.

**Comment by webron** [comment] 2017-01-12 16:06
@KaranKamath we should have an experimental version within a few weeks.

**Comment by BourbonGit** [comment] 2017-01-31 15:02
Is there any update on map support?

**Comment by mrapavy** [comment] 2017-01-31 21:22
+1

**Comment by fehguy** [comment] 2017-01-31 21:24
This has been 100% implemented in our soon-to-be released update to the UI.

**Comment by cabbonizio** [comment] 2017-01-31 23:46
Woo hoo!  Excited to see what's in store.

**Comment by webron** [comment] 2017-02-01 00:44
So are we ;)

**Comment by matthiasBender** [comment] 2017-02-02 16:03
@KaranKamath, @fehguy: Is there a branch where we may see this experimental feature? We would really like to try it out. Or is there a plan on when we may expect this feature to be released?

**Comment by webron** [comment] 2017-02-02 19:29
It will be available for testing in a few weeks.

**Comment by xiaochengxuyuan** [comment] 2017-02-07 07:38
so cool

**Comment by webron** [comment] 2017-03-20 21:38
Done in 3.0.

**Closed by webron** 2017-03-20 21:38 UTC
Labels: Feature

**Comment by anderejd** [comment] 2017-11-27 16:12
How do I use maps in swagger 2.0? (since 3.0 is not ready yet)
