### ISSUE TITLE
Response body not show in the page when "try it out" and API response http code 404 and response body 

### ISSUE THREAD

**Issue by hebihong** [swagger-api/swagger-ui#3212] opened 2017-06-09 05:20 UTC
When reporting an issue, please provide the following details:
- swagger-ui version: swagger-ui-3.0.12

Response code is 404, response body is a json string.

In swagger-ui-2.2.8 it works fine, show in the web page when "try it out":
Response Body:
{
  "error": "404005",
  "message": "failed"
}
Response Code: 404

But in 3.0.12 it shows:
 Error: Not Found
Response headers

**Comment by webron** [comment] 2017-06-09 06:00
Duplicate of #3041.

**Closed by webron** 2017-06-09 06:00 UTC
