### ISSUE TITLE
Help? Is there a way to use swagger-ui-react in Gatsby?

### ISSUE THREAD

**Issue by reselbob** [swagger-api/swagger-ui#7443] opened 2021-08-01 16:38 UTC
I've tried to do simple integration like so:

```
import * as React from "react"
import SwaggerUI from "swagger-ui-react"
import "swagger-ui-react/swagger-ui.css"



// markup
const IndexPage = () => {
  return (
    <SwaggerUI url="https://petstore.swagger.io/v2/swagger.json" />
  )
}

export default IndexPage

```

But, when I run `gatsby develop` I get the following error:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

The argument 'path' must be a string or Uint8Array without null bytes. Received
'/Users/reselbob/Projects/swagger-ui-gatsby/gatsby-swagger-ui-demo/node_modules/es5-ext/array/\x00#/e-index-of.js'

```
Can anybody help me out?

**Comment by reselbob** [comment] 2021-08-01 23:34
I can get the `swagger-ui-react` to run under standard React. The problem seems to be running under Gatsby. Here is how to replicate:

**Step 1:** Install the Gatsby CLI

`npm install -g gatsby-cli`

**Step 2:** Use the CLI to create a vanilla Gatsby app.

`gatsby new`

You can follow the instructions [here](https://www.gatsbyjs.com/docs/tutorial/part-1/).

**Step 3:** Substitute the contents of the file, `src/pages/index.js` with the following code:

```
import * as React from "react"
import SwaggerUI from "swagger-ui-react"
import "swagger-ui-react/swagger-ui.css"

// markup
const IndexPage = () => {
  return (
    <div>
      hi
    </div>   
  )
}

export default IndexPage
```

**Step 4:** Compile the Gatsby app

`gatsby develop`

You'll get output similar to the following: 

```
success open and validate gatsby-configs, load plugins - 2.121s
success onPreInit - 0.035s
success initialize cache - 0.006s
success copy gatsby files - 0.240s
success Compiling Gatsby Functions - 0.789s
success onPreBootstrap - 0.821s
success createSchemaCustomization - 0.012s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.150s
success building schema - 0.471s
success createPages - 0.001s
success createPagesStatefully - 0.091s
info Total nodes: 32, SitePage nodes: 4 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success update schema - 0.179s
success write out redirect data - 0.039s
success onPostBootstrap - 0.003s
info bootstrap finished - 9.634s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.381s
success write out requires - 0.090s
success run page queries - 0.022s - 1/1 46.21/s
success Caching HTML renderer compilation - 0.001s

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

The argument 'path' must be a string or Uint8Array without null bytes. Received
'/Users/reselbob/Projects/swagger-ui-gatsby/my-gatsby-site/node_modules/es5-ext/array/\x00#/e-index-of.js'

failed Building development bundle - 11.480s
ERROR in The argument 'path' must be a string or Uint8Array without null bytes. Received 
'/Users/reselbob/Projects/swagger-ui-gatsby/my-gatsby-site/node_modules/es5-ext/array/\x00#/e-index-of.js'

webpack compiled with 1 error
success Writing page-data.json files to public directory - 0.247s - 1/2 8.08/s
```

----
Notice I am not calling the `swagger-ui-react`. I am must using the `import` statement.

I hope you can help me. It's a critical path item. Thanks in advance.

**Comment by char0n** [comment] 2021-08-02 08:17
Hi @reselbob,

You're right, I could reproduce the same thing you're seeing. There are two possible related problems with using SwaggerUI with gatsby:

1. SwaggerUI support for Server Side Rendering is just theoretical. We don't tests for it, thus we re'not sure if it currently works. The main usecase for SwaggerUI is to be rendered as interactive React components in browser

1. Gatsby + SwaggerUI looks like a specific integration issue when mixing these two technologies. If you'd be able to identify the cause of this issue I'd be able to probably help you further.

**Comment by reselbob** [comment] 2021-08-02 14:31
So, it looks as if I need to get with the Gatsby experts to go down that rabbit hole. Correct @char0n ?

**Comment by char0n** [comment] 2021-08-02 16:06
> So, it looks as if I need to get with the Gatsby experts to go down that rabbit hole. Correct @char0n ?

I'm afraid so. 


But you can still use SwaggerUI in an HTML fragment to server side this HTML as it is, but only when it renders the SwaggerUI browser rendering will trigger.

**Comment by reselbob** [comment] 2021-08-02 17:37
Sorry, @char0n, I am not fully understanding this:

_But you can still use SwaggerUI in an HTML fragment to server side this HTML as it is, but only when it renders the SwaggerUI browser rendering will trigger._

What do you mean by an HTML fragment? Are you saying to generate the UI as fully functional HTML on the server side that then include the result in Gatsby as an HTML fragment that gets transformed within the usual Gatsby compilation process?

If so, any tips on how to do this?

PS: I really appreciate the help and attention you are providing. Thanks!

**Comment by reselbob** [comment] 2021-08-02 17:38
Along this lines: @char0n https://www.gatsbyjs.com/docs/reference/config-files/gatsby-ssr/ ?

**Comment by char0n** [comment] 2021-08-02 19:25
Well, I never used Gatsby , so I'm not sure how the internals work, but basically you have avoid Server Side Rendering of SwaggerUI. Here is a resource that could help you achieve it: https://github.com/gatsbyjs/gatsby/issues/11081#issuecomment-466634634

**Comment by char0n** [comment] 2021-08-11 08:32
Closing this as there is recommend way how to integrate SwaggerUI with Gatsby without SSR.

**Closed by char0n** 2021-08-11 08:32 UTC
Labels: type: support

**Comment by reselbob** [comment] 2021-08-11 15:35
> Closing this as there is recommend way how to integrate SwaggerUI with Gatsby without SSR.

I have a solution @char0n : https://github.com/reselbob/swagger-ui-gatsby-integration
