### ISSUE TITLE
"No operations defined in spec!" is shown with path with $ref in 3.13.0 version

### ISSUE THREAD

**Issue by jiguillen** [swagger-api/swagger-ui#4350] opened 2018-03-20 16:20 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 3.0
| Which Swagger-UI version?       | 3.13.0
| How did you install Swagger-UI? | Using swaggerapi/swagger-ui docker 
| Which browser & version?        | Chrome Versión 64.0.3282.186
| Which operating system?         | Linux Mint 18 Sarah

### Demonstration API definition

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref : './doc/paths/pets.yaml#/pets'
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

### Configuration (browser query string, constructor, config.yaml)

Configuration by default in swaggerapi/swagger-ui docker 

### Expected Behavior

Can see /pets path

### Current Behavior

"No operations defined in spec!" is shown

### Possible Solution

It is was working in version 3.10.0

### Context

I've updated from 3.10.0 to 3.13.0 version and it has stopped working.
File ./doc/paths/pets.yaml exists and it is well formed.

**Comment by shockey** [comment] 2018-03-20 18:37
Thanks for the report, @jiguillen - I bumped into this while helping out on a support ticket, and have already started on a fix!

**Comment by shockey** [comment] 2018-03-20 20:14
The `depth` option mentioned in https://github.com/swagger-api/swagger-ui/issues/4280 would be helpful in limiting the performance hit we'll get from resolving path items at load time.

**Comment by glipman** [comment] 2018-03-20 20:27
I am not entirely sure if delayed resolving for paths is possible: a remote path item may define a `tag`.
Swagger UI uses `tags` to group the displayed operations. The resolved path item is needed even to display the collapsed items.

**Comment by shockey** [comment] 2018-03-24 01:14
@glipman yeah, my solution is likely going to be check for $ref at the path level, and if it's there, go ahead and resolve.

Using https://gist.github.com/shockey/8c60fc810aa513fb27c9d4f025d0ac16 to test.

**Comment by shockey** [comment] 2018-03-28 00:04
fixed! thanks for the report, @jiguillen 👍

**Closed** 2018-03-28 00:04 UTC
Labels: P1, cat: rendering, type: regression

**Comment by heldersepu** [comment] 2018-03-28 00:33
I noticed that this `No operations defined in spec!` also shows when we use the filter
http://petstore.swagger.io/?filter=NoOp
Every time we search for something that does not exist that is what we get...

**Comment by shockey** [comment] 2018-03-28 00:37
@heldersepu, yeah that's been around since 3.0.0 I believe. it's a different root cause: the filter is modifying the output of a selector (`taggedOperations` iirc), so that when no operations match, the data flowing into the component is indistinguishable from a definition that has no operations.

There's ways to fix that, but they aren't closely related to this issue :smile:
