### ISSUE TITLE
Access is denied IE9 :: unable to complete CORS from swagger-client.js

### ISSUE THREAD

**Issue by humblefools** [swagger-api/swagger-ui#1129] opened 2015-04-07 20:53 UTC
Hi everyone,

While trying to access a cross-domain resource, more specifically making a REST API call which is hosted on some other domain, I am not able to make the call using swagger-client.js only on IE9 and lesser versions. However, everything works fine in IE 10+ and other browsers like chrome and firefox.

I think the issue is that IE 10+ and other modern browsers use XMLHttpRequest to make CORS call for which there is an implementation in swagger-client.js but since IE 9 and lesser versions use XDomainRequest to do the same , the code is failing since I didn't find an implementation for the same in swagger-cleint.js file.

I could see in the code it is specifically mentioned that you could make CORS call only if supported through XMLHttpRequest . 
The following comment is there in the swagger-cleint.js file.
	// Cross domain only allowed if supported through XMLHttpRequest.

Is there a way for making this work in IE 9 and lesser versions.

Thanks & regards,
humblefools

**Comment by mohsen1** [comment] 2015-04-07 21:06
Seems to be a problem with shred library which we removed from SwaggerUI recently. Which version of SwaggerUi are you using? If you're not using the latest, please try using the latest version and let us know if the problems still persists.

**Comment by humblefools** [comment] 2015-04-07 21:09
Hi Mohsen,

I amm using version v2.1.2 of swagger

**Comment by mohsen1** [comment] 2015-04-07 21:52
Please try [2.1.0-M2](https://github.com/swagger-api/swagger-ui/blob/master/package.json#L9) and let me know what happened

**Comment by humblefools** [comment] 2015-04-07 21:54
Thanks Mohsen...let me give it a try .

**Comment by humblefools** [comment] 2015-04-07 22:43
It doesn't work with that either . :(

**Comment by humblefools** [comment] 2015-04-08 21:30
Any suggestions ? anyone..

**Comment by fehguy** [comment] 2015-04-08 23:36
This could be an issue in the swagger-us client.  @whitlockjc  any ideas?

**Comment by whitlockjc** [comment] 2015-04-14 21:44
I'm closing this since the issue is with swagger-js and not swagger-ui.

**Closed by whitlockjc** 2015-04-14 21:44 UTC
Labels: Regression, swaggger-js
