### ISSUE TITLE
No autorization header with try it out request 

### ISSUE THREAD

**Issue by sandeeprao** [swagger-api/swagger-ui#1812] opened 2015-12-11 17:15 UTC
Hi,

Authorization header is not sending the user name and password with the try it out option in the swagger UI. Where as curl command is setting the basic authorization and returning the response.  I am very new to swagger and can you please let me know what i might be doing wrong ? 

My authorization in index.html 
  swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", "Basic XXX(I changed this for security reasons)", "header"));

security info in json file

"securityDefinitions" : {
    "basicAuth" : {
      "type" : "basic"
    }
  }
MY Header params: 

OPTIONS /atdb/v1.0/_core/collections/marketplace/feeds/Ice_CelearedOil?limit=5 HTTP/1.1
Host: casl-atdbws01.xxxx.com:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://localhost:8080
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization
Connection: keep-alive

**Comment by sandeeprao** [comment] 2015-12-11 17:55
Thanks for replying, I have tried changing it to the basicAuth but still there is no response when i use try it out and the UI displays 
{
  "error": "no response from server"
}

**Comment by webron** [comment] 2015-12-11 17:56
Can you check your browser's network console to see the request and response?

**Comment by sandeeprao** [comment] 2015-12-11 17:57
I did and their is no response or error from the request.

**Comment by webron** [comment] 2015-12-11 17:59
I'm confused. What status code do you get? There has to be some information there.

**Comment by sandeeprao** [comment] 2015-12-11 18:05
Sorry I think i might have some network issues on my side and the server is not returning any response but i will update you once i fix it.

**Comment by sandeeprao** [comment] 2015-12-12 21:32
I am getting 200 but it's still displaying error.

**Comment by sandeeprao** [comment] 2015-12-13 03:01
My Response headers 

Allow: OPTIONS,POST,GET,DELETE,HEAD
Connection: keep-alive
Content-Length: 553
Content-Type: application/vnd.sun.wadl+xml
Date: Sun, 13 Dec 2015 02:59:35 GMT
Server: Apache-Coyote/1.1
Connection: keep-alive

**Comment by webron** [comment] 2015-12-15 02:01
Yes, but when you get 200, what's the content of the response from the server?

**Comment by synth** [comment] 2015-12-18 23:51
I'm experiencing this issue as well. I'm using v2.1.4. I downgraded to v2.1.3 and it works as expected. Looks like a regression.

**Comment by fehguy** [comment] 2015-12-19 00:03
can you please try master?  just pushed a fix to that

**Comment by synth** [comment] 2015-12-19 00:05
Hmm. I took swagger-ui.js from dist on master and something seems wrong..I get error in console: JSONEditor is not defined

**Comment by fehguy** [comment] 2015-12-19 00:09
let me see...

**Comment by fehguy** [comment] 2015-12-19 00:12
Ah, you need to grab the files under `dist/lib` as well if you're not using the whole package.

**Comment by synth** [comment] 2015-12-19 00:12
I tried that too.

**Comment by synth** [comment] 2015-12-19 00:14
gah! sorry, that was it. Needed to update the js includes...

**Comment by fehguy** [comment] 2015-12-19 00:14
ok great

**Comment by synth** [comment] 2015-12-19 00:14
Dang, still having the Authorization header issue though...

**Comment by fehguy** [comment] 2015-12-19 00:15
can you share your spec file?

**Comment by synth** [comment] 2015-12-19 00:18
https://7a01fdb4.ngrok.com/api/docs/

**Comment by webron** [comment] 2016-06-09 22:32
@synth - were you able to resolve your issue?

**Comment by synth** [comment] 2016-06-09 23:03
Our swagger api seems to be working without issue now...that said its been a while and I don't remember if I worked around it or fixed it properly. So all good I guess :)

**Closed** 2016-06-10 01:01 UTC
