### ISSUE TITLE
Cannot find module: 'isomorphic-form-data' in swagger-ui-react

### ISSUE THREAD

**Issue by AlexKutkanych** [swagger-api/swagger-ui#7436] opened 2021-07-27 17:20 UTC
### Q&A (please complete the following information)
 - OS: Win 10
 - Browser: Chrome
 - Version: 91.0.4472.164
 - Method of installation: npm
 - Swagger-UI version: 3.51.1

### Describe the bug you're encountering
When running `npm run build` we ran into a problem with `swagger-ui-react` package. The error occured in `swagger-ui.js` - Cannot find module: 'isomorphic-form-data'. Make sure this package is installed.

`isomorphic-form-data` package is not in node_modules.

### Expected behavior
`npm run build` runs without errors.

### Screenshots
![image](https://user-images.githubusercontent.com/22956226/127199062-6872e82c-f25c-46d6-849e-5c6f497e7e8e.png)

### Additional context or thoughts
When I install `isomorphic-form-data` package into my project, build works fine.

**Comment by emanb29** [comment] 2021-07-27 18:02
If I understand correctly, this seems to have been introduced by the dependency change in https://github.com/swagger-api/swagger-js/pull/2154

**Comment by kaisawind** [comment] 2021-07-28 04:16
any way to fixed it right now?

**Comment by char0n** [comment] 2021-07-28 08:05
You're absolutely right and thanks for reporting this. The problem is in swagger-ui-react build fragments. It contains build fragments that reference the isomorphic-form-data in lazy way. As every build on CI of swagger-ui-react will download latest version of swagger-client, which now doesn't require isomorphic-form-data and thus don't install it. We need to fix how we expose build fragments for swagger-ui-react so that this doesn't happen in future. On Thursday 29.7.2021 there will a new release of swagger-ui-react that will fix this issue automatically by updating to it.

The workaround mentioned in this issue, must be implemented (**adding isomorphic-form-data** in package.json) before the new release of swagger-ui-react is available.

**Comment by char0n** [comment] 2021-07-30 10:15
Fixed in https://github.com/swagger-api/swagger-ui/releases/tag/v3.51.2

**Closed by char0n** 2021-07-30 10:15 UTC
Labels: swagger-js, type: regression, version: 3.x
