### ISSUE TITLE
Allow to skip Try it out and have the form enabled by default

### ISSUE THREAD

**Issue by valentijnscholten** [swagger-api/swagger-ui#6528] opened 2020-10-17 07:46 UTC
This is coming from me using [django rest swagger](https://github.com/marcgibbons/django-rest-swagger/blob/master/client/index.js), which includes/uses swagger ui.

My main usage of the swagger docs is to try things with the API. It would be nice if we could disable the "Try it out" button and just have the form enabled by default so you save some pointing and clicking before you can try out a request. Or multiple requests.

 ### Content & configuration

I think django-rest-swagger is using a default SwaggerUI() instance

### Is your feature request related to a problem?
no

### Describe the solution you'd like
Allow a config option to have the form for requests enabled by default and remove the need to click try it out .

### Describe alternatives you've considered
I have seen #4590 which is closed as duplicate of #2806, but to me that looks like a different feature request.

**Comment by hkosova** [comment] 2020-10-19 10:27
This is probably a duplicate of #2805 (not 2806).

**Comment by valentijnscholten** [comment] 2020-10-19 10:38
Agreed didn't see this one (and I did use the search 😄)

**Comment by valentijnscholten** [comment] 2020-10-19 10:38
But maybe still good to have it as a separate action here as 2805 send to trigger a more lengthy discussion around "everything usability".

**Comment by MrBuddyCasino** [comment] 2020-10-20 11:52
Oh yes please, clicking "Try it out" for no good reason is so annoying.

**Comment by hkosova** [comment] 2021-02-25 11:49
Implemented in Swagger UI v. 3.41.0 (PR https://github.com/swagger-api/swagger-ui/pull/6865).

You'll need to configure UI with the [`tryItOutEnabled: true`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-tryitoutenabled) option.

Demo: https://petstore.swagger.io/?tryItOutEnabled=true

**Closed by hkosova** 2021-02-25 11:49 UTC
Labels: cat: try-it-out, cat: user experience, needs: UX/design input, type: feature

**Comment by Vaccano** [comment] 2021-10-19 22:52
@hkosova - How does this "tryItOutEnabled" relate to the existing "tryItOutEnabled" setting from a long time ago (Here is a thread from 2017: https://github.com/swagger-api/swagger-ui/issues/3678)

I ask, because I set the "tryItOutEnabled" setting to false (and also true) and it has no effect.  

I am using Swagger UI 3.52.0 (via the Swashbuckle.AspNetCore project).

**Comment by 0xced** [comment] 2022-03-10 15:41
For Swashbuckle.AspNetCore, you have to configure it like this:
```csharp
app.UseSwaggerUI(options => options.EnableTryItOutByDefault());
```

It's available since version 6.1.5, see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/ee334d6b1ac2c057b1595cd27403b9d57129f436

**Comment by JerryNixon** [comment] 2022-07-29 15:51
Could this be the default instead?

**Comment by MrBuddyCasino** [comment] 2022-08-05 12:32
Yes please reverse the default. The "try it out" button is really unnecessary.

**Comment by pietrodantuono** [comment] 2024-05-06 17:01
Any update on this?
