### ISSUE TITLE
Add support for Maps / additionalProperties

### ISSUE THREAD

**Issue by newtechfellas** [swagger-api/swagger-ui#558] opened 2014-09-03 19:48 UTC
How to specify the swagger documentation annotation for generating model schema for Map attribute in a Java bean?
<pre>
//groovy code
class Foo {
  int id
  String description
  Map&lt;String, Bar&gt; targets
  //few other attributes
}
</pre>
For `targets` attribute, swaggerui shows 1 line but does not give the model schema for Bar class.
<pre>
targets (Map[string,Bar])
</pre>

How do I get `Bar` class Model schema as well in UI? Am using latest swagger library `('com.wordnik:swagger-jersey-jaxrs_2.10:1.3.8')`

**Comment by DavidTPate** [comment] 2015-02-20 15:18
:+1:

**Comment by tsz662** [comment] 2015-03-12 10:40
:pray:

**Comment by webron** [comment] 2015-05-04 10:51
https://github.com/swagger-api/swagger-js/pull/262 should provide the basics for support here.

**Comment by fehguy** [comment] 2015-05-08 20:38
@whitlockjc this should be supported as of https://github.com/swagger-api/swagger-js/issues/230 but the petstore's `/store/inventory` doesn't show what I'd expect.  The response definition looks like this:

```json
{
  "200": {
    "description": "successful operation",
    "schema": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "format": "int32"
      }
    }
  }
}
```

but the model definition looks like this in the UI:

![image](https://cloud.githubusercontent.com/assets/249413/7545064/83c75830-f587-11e4-96ba-79b5447f7f49.png)

**Comment by whitlockjc** [comment] 2015-05-08 21:03
There is an existing issue for supporting `additionalProperties` that is/was awaiting feedback.  I'm not sure why it's closed but here it is: https://github.com/swagger-api/swagger-js/issues/298

Supporting additional properties would not take a lot of effort but when I asked how it should be rendered, so we could do the work, no one answered and now the issue is closed.

**Comment by maver1ck** [comment] 2015-05-19 11:00
I have the same problem.
Maybe we can find some representation ?

**Comment by ponelat** [comment] 2015-05-19 11:07
@maver1ck I believe the method of displaying it is still pending. Although, perhaps @whitlockjc has a experimental branch with it? We're also trying to move the html representation of models into swagger-ui (where it belongs). Once the refactor is complete (ETA +/- week to get into develop_2.0, thereafter into master -> normal release cycle time) we can add the additionalProperties extra.
Hope this helps give you a timeframe :smiley:

**Comment by maver1ck** [comment] 2015-05-19 12:21
Great.
Thank you for the answer.

**Comment by webron** [comment] 2015-05-28 19:09
According to https://github.com/swagger-api/swagger-js/issues/298#issuecomment-100048445 this should be ready for implementation.

**Comment by nikdunn** [comment] 2015-06-17 05:11
@whitlockjc I'm going in circles trying to track the state of these issues. You mentioned lack of feedback on this (https://github.com/swagger-api/swagger-js/issues/298) issue for the HTML rendering for additional properties. I personally think your suggestion was fine and there would at least be some thing there. I'd like to see that feature working. Does an issue need to be reopened or is it waiting on a future release? I can't tell from the way the issues link all around.

**Comment by whitlockjc** [comment] 2015-06-17 05:16
I'm not the holdup and it's currently in the queue.  /cc @ponelat

**Comment by ponelat** [comment] 2015-06-17 05:22
We can definitely re-stress this one. Right now we've just extracted some of the markup logic, and once that meets approval, we can add this on top of that. https://github.com/swagger-api/swagger-js/pull/486

**Comment by nikdunn** [comment] 2015-06-17 05:27
Thanks for the feedback. So the additionalProperty issue was swept up into the separation of markup from swagger-js? That makes sense. I'll keep an eye on https://github.com/swagger-api/swagger-js/pull/486 and check it out once it hits the streets. Thanks guys!

**Comment by webron** [comment] 2015-06-17 07:42
@nikdunn - it's one of the features that unfortunately didn't make the cut. I'm going to re-prioritize the issues on the projects soon, and this one is likely to get a bump.

**Comment by nikdunn** [comment] 2015-06-17 15:05
Thanks, @webron. Do you have an idea when this might be available? If it's going to be a while, I could jump in and fix it with a pointer or two. Is there a release candidate branch?

@whitlockjc did you have an initial cut prior to the decision to defer to the separation of the markup from swagger-js? If you do, I might like to patch the current version if it's going to be a while before support hits a release.

**Comment by webron** [comment] 2015-06-17 15:08
@nikdunn - the develop_2.0 branch is our development branch. Unfortunately, I can't give you a date for a point release. Once we accumulate 'enough' bug fixes and features, we'll release it.

**Comment by nikdunn** [comment] 2015-06-17 15:39
@webron Can you point me to where in the code I would add support for additionalProperties on the development branch? Thanks.

**Comment by webron** [comment] 2015-06-17 15:50
I wish I could :) That'd be more @ponelat / @whitlockjc / @mohsen1 / @fehguy's domain.

**Comment by dkirrane** [comment] 2015-07-07 12:49
+1

**Comment by thjaeckle** [comment] 2015-07-29 05:38
Is this in release 2.1.1 or not? I'm confused about the "Milestone v2.1.1" this issue is tagged with.

**Comment by webron** [comment] 2015-08-03 14:30
@thjaeckle - it is not. Our release process is not fully automated yet so there's a delay between releases and milestone updates. In general, the milestone is a target aspiration, it doesn't necessarily mean it's going to get in it.

**Comment by timmy82** [comment] 2015-09-23 16:00
Hi,
 when will you support documentation of maps in swagger ui. Any plans?
Tim

**Comment by fehguy** [comment] 2015-11-19 05:56
Try to update to 1.5.4.  Yes, maps are supported, but the key type is typically a string.

**Comment by timmy82** [comment] 2015-11-24 21:24
Hi,
 we have a Java class Foo that contains a bars Map<BarId,Bar>. The swagger.json is 
bars: {
type: "object",
description: "...",
additionalProperties: {
$ref: "#/definitions/Bar"
}
},

The type Bar does not appear in the documentation. Any hints?

Thx

**Comment by JeroenDeDauw** [comment] 2015-11-30 13:13
A part of my API returns a map in which the keys are arbitrary user defined strings.

```
"simple_statement_map": {
    "type": "object",
    "additionalProperties": {
        "$ref": "#/definitions/simple_statement"
    }
}
```

This is not showing in the UI at all, much like @fehguy's example from May 8th. I'm using Swagger UI 2.1.4, which makes the combined fact that this is assigned to 2.1.3 and that it's been open for over a year a bit disconcerting.

**Comment by cabbonizio** [comment] 2015-12-03 17:44
I feel like this is one of the primary things that is missing from our perspective.   We love Swagger, but this issue with the Maps prevents us from properly documenting our API's.

**Comment by fehguy** [comment] 2015-12-07 20:32
Please track meta issue #1248.  It will be handled there.

**Closed** 2015-12-07 20:32 UTC
Labels: Feature

**Comment by luigibianchi** [comment] 2015-12-22 08:54
+1 for this. Without support for maps, we cannot proceed with Swagger
