### ISSUE TITLE
BearerToken instead Bearer

### ISSUE THREAD

**Issue by vjosyula4254** [swagger-api/swagger-ui#5591] opened 2019-09-04 15:20 UTC
### Q&A (please complete the following information)
 - OS: [windows 10]
 - Browser: [chrome]
 - Version: [76.0.3809.132]
 - Method of installation: [npm]
 - Swagger-UI version: [3.23.8]
 - Swagger/OpenAPI version: [Swagger 2.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# Its confidential.
```

### Describe the bug you're encountering

The above curl command is being generated 
curl -X GET "https://testapi2.ferguson.com/v1/locations/warehouses/134" -H "accept: application/xml" -H "authorization: BearerToken AT43HPJzqpFWukFjhZgDlvlid2fh"
I need a the curl command to have Bearer intead of BearerToken
curl -X GET "https://testapi2.ferguson.com/v1/locations/warehouses/134" -H "accept: application/xml" -H "authorization: Bearer AT43HPJzqpFWukFjhZgDlvlid2fh"

### To reproduce...

1. Go to 'Authorize'
2. Enter your ' client_ID, client_secret'
3. Try to make a request to backend by clicking on "TRY IT OUT"
![Capture](https://user-images.githubusercontent.com/39568310/64268378-f42eba80-cf05-11e9-9a66-eaf442c9f02f.PNG)

3. See error 'Type Failed to fetch'

### Expected behavior

i should be getting the following curl command
curl -X GET "https://testapi2.ferguson.com/v1/locations/warehouses/134" -H "accept: application/xml" -H "authorization: Bearer AT43HPJzqpFWukFjhZgDlvlid2fh"

**Comment by shockey** [comment] 2019-09-04 22:53
`Bearer` is the default. We override that default based on the `token_type` that your OAuth provider sends back in the Access Token Response:

https://github.com/swagger-api/swagger-js/blob/f8fccb45107c76c0dd45d9d0e4583087b97ef6b3/src/execute/oas3/build-request.js#L163-L169

You'll need to fix your OAuth provider in order for Swagger UI to format your tokens correctly.

---

Closing as this is working as intended!

**Closed by shockey** 2019-09-04 22:53 UTC

**Comment by shockey** [comment] 2019-09-04 22:56
PS: This behavior is called for in the OAuth spec, see [RFC 6479 § 7.1: "Access Token Types"](https://tools.ietf.org/html/rfc6749#section-7.1).

Hope this helps!
