### ISSUE TITLE
swagger ui 3.14 errors are thrown instead of rendered 

### ISSUE THREAD

**Issue by gaborbernat** [swagger-api/swagger-ui#3242] opened 2017-06-14 14:04 UTC
whenever the response is not ok (e.g. 404), the response is not rendered, but thrown (so I can see it on the console log, but not on the UI) 

e.g. for 404 resource not found is quite standard for trying to access and invalid resource

is that the expected behavior? can I alter it?

**Comment by webron** [comment] 2017-06-14 18:53
Can you try the master version?

**Comment by gaborbernat** [comment] 2017-06-15 09:14
So it works with master, but for non success the headers are not printed, which they should I feel like. Just because there was an error the headers still exist and may contain important information. Thanks!

**Comment by webron** [comment] 2017-06-15 15:09
Closing as duplicate of #3041.

**Closed by webron** 2017-06-15 15:09 UTC

**Comment by roma11111122** [comment] 2017-06-16 15:27
іва
