### ISSUE TITLE
Model attributes in random order within an endpoint

### ISSUE THREAD

**Issue by codewanderer16** [swagger-api/swagger-ui#3643] opened 2017-09-08 21:32 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.1.7, 3.0.14
| How did you install Swagger-UI? | from the download zip
| Which browser & version?        | several
| Which operating system?         | Windows 10

### Demonstration API definition

[example swagger.json file](https://gist.github.com/codewanderer16/1ba4327eb54dcb97ec63f5ba40580f8d)

### Current Behavior

In the Responses section of the GET endpoint, the 1st-level attributes of the Axxass model are listed in a non-obvious order.

In the example value for this same object and in the Models section, the attributes are in alphabetical order, which aligns with the order of the definitions in the swagger.json file.

### Expected Behavior

Attribute order should be consistent across model presentations. Preference is to be able to select alphabetical order or the order given in the JSON file.

**Comment by hkosova** [comment] 2017-09-11 14:44
@webron this looks like a duplicate of #3032.

**Comment by webron** [comment] 2017-09-11 15:08
It is! Closing as duplicate of #3032.

**Closed by webron** 2017-09-11 15:08 UTC
Labels: 3.x, Bug, P3
