### ISSUE TITLE
Setting default value on an enum causes the default to always be used

### ISSUE THREAD

**Issue by BasKooij** [swagger-api/swagger-ui#3726] opened 2017-10-03 14:38 UTC
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2
| Which Swagger-UI version?       | 3.2.2
| How did you install Swagger-UI? |  Composer
| Which browser & version?        | Chrome 61  
| Which operating system?         | Windows 10

Whenever a default is set on an enum parameter it becomes impossible to send another version than the default. 

### Demonstration API definition

```yaml
swagger: '2.0'
host: localhost
info:
  title: Demo
  description: Demo
  version: 1.0.0
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/demo':
    get:
      summary: Enum demo
      parameters:
        - name: enum_demo
          in: query
          required: true
          type: string
          default: first_value
          enum:
            - first_value
            - second_value
      responses:
        '200':
          description: Result
          schema:
            type: array
            items:
              type: object

```
### Expected Behavior
The value selected in the dropdown box to be sent in the query string

### Current Behavior
The default value is always sent in the query string

### Possible Solution
Whenever you omit the default tag the request is fine

**Comment by hkosova** [comment] 2017-10-03 18:32
This spec is probably not valid.

1) If `enum` is used, the `default` value should be part of that `enum`.

2) More importantly, `default` is not used with `required` parameters. It's an attribute of optional parameters and is handled on the server side. That is, if the client does not supply the parameter, the server will use the `default` value.

@webron?

**Comment by BasKooij** [comment] 2017-10-04 07:33
As for 1, you are right and in my actual implementation the default is actually part of the enum. I edited my example, but it doesn't matter for the results.

The Swagger editor does not indicate there is an error in the specification, but even so: if the default is to be handled on the server the interface should not put the default value in the query string if I select a different one.

**Comment by webron** [comment] 2017-10-04 23:07
@BasKooij - having `default` and `required` for the same property/parameter is indeed pointless, however, it doesn't contradict the spec which is why the editor doesn't throw an error. We should provide a warning though, and I'll file a separate ticket for that.

@owenconti - this is a fairly critical bug. If you can't work on it for this week's release, please let @shockey know so he can take over.

**Comment by owenconti** [comment] 2017-10-04 23:33
Looking now.

**Comment by owenconti** [comment] 2017-10-04 23:45
Not sure if I am missing something, but I cannot reproduce the issue with the provided spec in the OP. See screenshot:

<img width="1917" alt="screen shot 2017-10-04 at 5 39 54 pm" src="https://user-images.githubusercontent.com/791222/31204887-4af1ff1a-a92b-11e7-8945-dc270ab42689.png">

Please advise @webron and @BasKooij

**Comment by owenconti** [comment] 2017-10-04 23:50
Nevermind. I cannot reproduce on petstore.swagger.io, but I can on editor.swagger.io

**Comment by owenconti** [comment] 2017-10-05 00:21
Okay, further confusion here:

- I cloned `swagger-ui`
- I cloned `swagger-editor`
- I linked `swagger-ui` to `swagger-editor` so I was using both of the cloned repos
- I could not reproduce the issue on my local `swagger-editor` instance either

I did notice though, that the `versions` information is different across the various environments:

<img width="1920" alt="screen shot 2017-10-04 at 6 19 39 pm" src="https://user-images.githubusercontent.com/791222/31205767-b45857ce-a930-11e7-9d98-03a040b9f304.png">

<img width="1920" alt="screen shot 2017-10-04 at 6 19 12 pm" src="https://user-images.githubusercontent.com/791222/31205769-b92ee29a-a930-11e7-935d-aa0382f8bc21.png">

<img width="1909" alt="screen shot 2017-10-04 at 6 19 05 pm" src="https://user-images.githubusercontent.com/791222/31205771-be229eae-a930-11e7-9117-5e3d521e9360.png">

@shockey Do you have any ideas on how I should be trying to fix this?

**Comment by shockey** [comment] 2017-10-05 00:23
@owenconti, I’ll take a look, and try to reproduce this on my end.

**Comment by webron** [comment] 2017-10-05 01:36
@owenconti keep in mind the online editor uses one version back of swagger-ui as there was no release last Friday - and swagger-ui had a bunch of fixes in it. Maybe the issue was there and is no longer?

**Comment by owenconti** [comment] 2017-10-05 01:38
That would explain all the symptoms I was seeing then!

**Comment by shockey** [comment] 2017-10-05 01:41
Yep, looks like `swagger-ui@3.2.2` has this issue, but `swagger-ui@3.3.1` does not.

I'm looking for a specific commit that fixes it now.

**Comment by webron** [comment] 2017-10-05 02:11
I wouldn't dig too much into it. If the fix is there, it'll roll into the editor in this week's release because there's definitely going to be one.

**Comment by owenconti** [comment] 2017-10-08 15:07
Hi @BasKooij, now that `swagger-editor` has been updated, could you please confirm this has been fixed on http://editor.swagger.io?

**Comment by BasKooij** [comment] 2017-10-09 08:12
Yes, this look fine to me. The dropdown selects the default at first, and the right value appears in the query when I submit the request. I tried both with and without the required keyword and with default values that are not in the enum.

**Closed** 2017-10-09 15:00 UTC
Labels: 3.x, Bug, P1

**Comment by rthille** [comment] 2018-07-17 21:52
The issue seems back on 3.17.3 (editor.swagger.io as of 2018-07-17)
```
swagger: '2.0'
host: localhost
info:
  title: Demo
  description: Demo
  version: 1.0.0
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/demo':
    get:
      summary: Enum demo
      parameters:
        - name: enum_demo
          in: query
          required: true
          type: string
          enum:
            - first_value
            - second_value
      responses:
        '200':
          description: Result
          schema:
            type: array
            items:
              type: object
```
Shows the issue.

**Comment by rthille** [comment] 2018-07-17 21:58
Ah, it's this issue: https://github.com/swagger-api/swagger-ui/issues/4693 already fixed.
