### ISSUE TITLE
Allow Manual URL Spec Even When Multiple URLs Already Declared

### ISSUE THREAD

**Issue by Scuilion** [swagger-api/swagger-ui#4769] opened 2018-07-27 18:45 UTC
### Content & configuration
 Swagger-UI configuration options:
 ```js
 swaggerUI({
      urls: [
        {url:'https://petstore.swagger.io/v2/swagger.json', name: 'petstore'},
      ]
    });
 ```

### Is your feature request related to a problem?
Feature Request
I'm specifying multiple url in my configuration. I want to be able to manually browse other swagger.json files that I don't know about ahead of time.

The code will do either url drop down or explore input:
https://github.com/swagger-api/swagger-ui/blob/bf5acc1f40af3fb1ed37e0f7725666d3fcce77e7/src/plugins/topbar/topbar.jsx#L119-L137

### Describe the solution you'd like
Add a configuration that would allow both to exist at the same time.
![image](https://user-images.githubusercontent.com/241151/43340775-077a9786-91a3-11e8-8171-7329b8b9aa67.png)

### Describe alternatives you've considered
I could defined two SwaggerUIs but this seems heavy handed.
There might be another solution that I'm unaware of.

**Comment by hkosova** [comment] 2019-08-08 10:54
Closing as a duplicate of #4292.

**Closed by hkosova** 2019-08-08 10:54 UTC
Labels: cat: try-it-out, type: enhancement
