### ISSUE TITLE
CURL section in try-it ignores the content type

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-ui#1447] opened 2015-07-06 03:01 UTC
For example, in GET /pet/{pet-id} in PetStore example, if content type is selected to be `application/xml` the CURL command is still using `application/json`

<img width="1031" alt="screen shot 2015-07-05 at 7 58 08 pm" src="https://cloud.githubusercontent.com/assets/543633/8515088/abbf77e0-2350-11e5-9ddf-d11fb074142a.png">

**Comment by webron** [comment] 2015-07-06 06:21
Duplicate of #1397.

**Closed by webron** 2015-07-06 06:21 UTC
Labels: Bug
