### ISSUE TITLE
Multiple headers don't work

### ISSUE THREAD

**Issue by HoltR** [swagger-api/swagger-ui#1374] opened 2015-06-16 07:52 UTC
Adding multiple headers using the following will not work.

swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", "XXXX", "header"));

I tracked the issue to the swagger-ui.js line 987

status = status || !!auth.apply(obj); // logical ORs regarding status

which i believe should be (single !)

status = status || !auth.apply(obj); // logical ORs regarding status

fixed my issues but its a complex beast and I don't have time to submit changes myself sorry

**Comment by ponelat** [comment] 2015-06-16 08:16
Yes this is a bug...
fixed here https://github.com/swagger-api/swagger-js/pull/488
The double `!!` is correct, it forces the value to be boolean without inverting it.
If you'd like to fix this yourself quickly...
```javascript
status = !!auth.apply(obj) || status;
```

**Comment by HoltR** [comment] 2015-06-16 09:08
ah, i couldn't find a bug or issue and i am not really a js developer! thanks for taking a look and educating me in the vagaries of !!

**Comment by ponelat** [comment] 2015-06-16 10:09
Next time, there might not be an open issue or resolved PR, so thanks spotting this ;D

**Comment by webron** [comment] 2015-06-16 11:31
Closing as duplicate of https://github.com/swagger-api/swagger-js/issues/487.

**Closed by webron** 2015-06-16 11:31 UTC
