### ISSUE TITLE
Where is the lang dir?

### ISSUE THREAD

**Issue by NoGrief** [swagger-api/swagger-ui#2765] opened 2017-03-22 08:52 UTC
for localization, the lang in 'dist' directory is missing. 3.0.2

**Comment by webron** [comment] 2017-03-22 16:03
There's no localization support in 3.X yet.

**Comment by arthurdm** [comment] 2017-04-29 00:24
+1

**Comment by leochr** [comment] 2017-05-01 15:39
+1

**Comment by leochr** [comment] 2017-07-12 15:33
@webron any idea when the localization support will be added for 3.X?

**Comment by webron** [comment] 2017-07-12 15:58
It's not currently on our roadmap, due to time constraints. We consider the feature important though, and would be happy to review PRs that help add this feature back.

**Comment by shockey** [comment] 2018-03-02 00:07
Closing as a duplicate of https://github.com/swagger-api/swagger-ui/issues/2488

**Closed by shockey** 2018-03-02 00:07 UTC
Labels: P2, type: feature, version: 3.x

**Comment by obender** [comment] 2019-02-27 09:17
Hi, 
We wold like to implement that feature and contribute it, any guide how to do so?

**Comment by shockey** [comment] 2019-04-05 20:27
@obender please join the discussion in #2488 or email me (kyle.shockey@smartbear.com) if you'd like to discuss how best to architect an internationalization feature 😄
