### ISSUE TITLE
Post requests w/ multipart form data fail to render curl command

### ISSUE THREAD

**Issue by plemarquand** [swagger-api/swagger-ui#2922] opened 2017-04-17 17:36 UTC
Rendering the curl command no longer works for POST requests that have formData. The request body isn't getting set as a string before being passed to `curlify`. As a result, line `21` in `src/core/curlify.js` throws the following error when you Execute the request: 

`TypeError: request.get(...).split is not a function`

And you see this in the UI: `😱 Could not render Curl, see the console.`

The line in question:

`let formDataBody = request.get("body").split("&")`

Found in swagger-ui version: `3.0.6`

Here is my paired down `swagger.json` that reproduces the issue:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "NA",
    "description": "..."
  },
  "basePath": "/api",
  "tags": [
    {
      "name": "products",
      "description": "Product APIs"
    },
    {
      "name": "scans",
      "description": "Scanning Files"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/scans": {
      "post": {
        "description": "Upload a file to be scanned without a product association. Use\nthis for 'quick scans' which are one-off scans whose results are\nuncorrelated with previous ones.\n",
        "tags": [
          "scans"
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "file",
            "in": "formData",
            "type": "file",
            "description": "The file to scan.",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "The file was successfully uploaded and the scan has started.\nReturns a scan object containing the status of the scan. Use\nthe returned ID to poll /scans/{scanId} to monitor the progress\nof the scan.\n",
            "schema": {
              "$ref": "#/definitions/Scan"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Scan": {
      "type": "object",
      "required": [
        "id",
        "recipe",
        "progress",
        "uploaded_on"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Scan ID"
        },
        "recipe": {
          "type": "string",
          "description": "The type of scan. This varies depending on the type of file uploaded."
        },
        "progress": {
          "type": "array",
          "description": "A list of all the steps in the scan.",
          "items": {
            "$ref": "#/definitions/ScanProgress"
          }
        },
        "created_on": {
          "type": "integer",
          "format": "int64",
          "description": "The time the file upload began."
        },
        "uploaded_on": {
          "type": "number",
          "format": "int64",
          "description": "The time the file upload finished."
        },
        "started_on": {
          "type": "number",
          "format": "int64",
          "description": "The time the scan was started. Omitted if the scan has not yet started."
        },
        "completed_on": {
          "type": "number",
          "format": "int64",
          "description": "The time the scan was completed. Omitted if the scan is not complete."
        },
        "file": {
          "$ref": "#/definitions/File"
        }
      }
    },
    "ScanProgress": {
      "type": "object",
      "required": [
        "name",
        "status",
        "started_on"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the scan step."
        },
        "status": {
          "type": "string",
          "description": "The status of the scan step.",
          "enum": [
            "pending",
            "in progress",
            "complete",
            "failed"
          ]
        },
        "started_on": {
          "type": "string",
          "format": "date-time",
          "description": "The time the scan step was started."
        },
        "completed_on": {
          "type": "string",
          "format": "date-time",
          "description": "The time the scan step was completed. This is omitted if the scan step is not complete."
        },
        "message": {
          "type": "string",
          "description": "An optional message explaining the status. For instance if there was an error this would explain the cause."
        }
      }
    },
    "File": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Filename id as a UUID."
        },
        "name": {
          "type": "string",
          "description": "The scan filename."
        },
        "size": {
          "type": "number",
          "format": "int64",
          "description": "The size of the file."
        },
        "scantype": {
          "type": "string",
          "description": "The type of file as described by the system."
        }
      }
    }
  }
}
```

**Comment by webron** [comment] 2017-04-17 18:29
Would you be able to submit a PR for the fix?

**Comment by plemarquand** [comment] 2017-04-17 19:09
@webron I got as far as identifying the issue but I'm not familiar enough with the expected results coming out of curlify to prepare a fix.

**Comment by shockey** [comment] 2017-05-14 07:20
Reopening - reverted the fix commit before release, as it introduced a problem.

It looks like the `value` may just ned a `fromJSOrdered` call around it if the value isn't a file - not putting that into the release, though.

**Comment by shockey** [comment] 2017-06-13 22:49
Bumping.

**Comment by dwickern** [comment] 2017-06-13 22:58
@shockey there's a PR open at #3211

**Comment by shockey** [comment] 2017-06-13 23:00
Thanks @dwickern 😅

**Comment by hkosova** [comment] 2017-08-07 11:11
@shockey could you please reopen this? This issue is back in 3.1.4 and is affects the Petstore spec (`/pet/{petId}/uploadImage`). There are no console errors though.

![multipart-curl](https://user-images.githubusercontent.com/8576823/29024317-2fc8793c-7b7a-11e7-828e-2672c0e071a3.png)

**Comment by shockey** [comment] 2017-08-07 18:26
Confirmed - I'm getting this error:

> TypeError: Invalid attempt to destructure non-iterable instance

**Comment by shockey** [comment] 2017-08-11 19:14
This appears to have been fixed by https://github.com/swagger-api/swagger-ui/pull/3556.

**Closed by shockey** 2017-08-11 19:14 UTC
Labels: 3.x, Bug, P1
