### ISSUE TITLE
New version of swagger ui makes requests without the web context in the url

### ISSUE THREAD

**Issue by pprabhu3430** [swagger-api/swagger-ui#1105] opened 2015-03-31 17:30 UTC
Previously if my api doc was at http://localhost/application/api-docs, the 'try it out' button would call 
an api at the endpoint /rest/invoice/get at http://localhost/application/rest/invoice/get.

Now it calls it at a http://localhost/rest/invoice/get. This is going to result in a 404. Is there a way to get around this?

**Comment by pprabhu3430** [comment] 2015-03-31 17:40
Also it doesnt appear to pass the api_key along with the request.

**Comment by fehguy** [comment] 2015-03-31 18:22
Please share your swagger specification.

**Comment by pprabhu3430** [comment] 2015-03-31 18:48
I am using the spring mvc swagger plugin to generate the metadata for my rest services. Here is an image of the json structure returned for one of my api's. 

![image](https://cloud.githubusercontent.com/assets/5148405/6926527/d3f5f0dc-d7b4-11e4-89ad-361ba4dff415.png)

It sounds like it is totally ignoring basePath

**Comment by webron** [comment] 2015-03-31 20:27
In Swagger 1.2 the basePath has to be a full URL which is probably the cause of this issue.

**Comment by mohsen1** [comment] 2015-04-15 21:59
If I'm not wrong this is a duplicate of #1139.

**Closed by mohsen1** 2015-04-15 21:59 UTC
Labels: Regression

**Comment by webron** [comment] 2015-04-16 12:56
@mohsen1 - wouldn't #1139 be a duplicate of this then? ;) This one was opened first ;)

**Comment by mohsen1** [comment] 2015-04-16 17:15
@webron #1139 has more discussion in it. Either way these two issues are about the same thing.

**Comment by webron** [comment] 2015-04-16 17:18
I was kidding. I agree that the issue with more discussion should stay alive.

**Comment by mohsen1** [comment] 2015-04-16 17:21
👍
