### ISSUE TITLE
allOf  keywords as property name error

### ISSUE THREAD

**Issue by tomsue** [swagger-api/swagger-ui#4290] opened 2018-03-05 08:59 UTC
I trying to use 'allOf' keywords as a property name in the alarmSetting model, and then i get a error message : 
**Resolver error at paths./AlarmSetting.get.responses.200.schema.properties.data.properties.list.items.properties.allOf
allOf must be an array**

swagger-editor error:

![image](https://user-images.githubusercontent.com/5195809/36966036-6599932c-2096-11e8-92da-420176164a0a.png)

swagger-ui error:

![image](https://user-images.githubusercontent.com/5195809/36966001-4d6f0098-2096-11e8-97dd-dbdb50ea2312.png)

**Comment by scottohara** [comment] 2018-03-07 02:44
What version of swagger-ui are you seeing this error in?

I've tested in the latest v3.12.0, but I couldn't reproduce.

It was previously a bug that was fixed in swagger-client@3.4.11 (see https://github.com/swagger-api/swagger-js/pull/1195), which means that (in theory) it ceased to be issue since swagger-ui@3.10.0.

**Closed** 2018-03-07 23:06 UTC
