### ISSUE TITLE
If return value is array it does not render the models

### ISSUE THREAD

**Issue by tlbdk** [swagger-api/swagger-ui#1026] opened 2015-03-12 17:21 UTC
![image](https://cloud.githubusercontent.com/assets/11635/6623629/63e273c6-c8e4-11e4-9e6d-1b3bdbe6ef9d.png)

![image](https://cloud.githubusercontent.com/assets/11635/6623654/9211c332-c8e4-11e4-9a7f-1884b9bae19d.png)

{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test sample showing swagger error",
        "description": "Show that if the return value is an array the ref does not get rendered",
        "contact": {
            "name": "Troels Liebe Bentsen",
            "email": "tlb@nversion.dk"
        }
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Test",
                "description": "Test stuff",
                "operationId": "doTest",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test stuff response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }
                    },
                    "405": {
                        "description": "Invalid input"
                    }
                },
                "tags": ["test"]
            }
        }
    },
    "definitions": {
        "test": {
            "required": [
                "test1"
            ],
            "properties": {
                "test1": {
                    "type": "string"
                }
            }
        }
    }
}

**Comment by webron** [comment] 2015-03-12 17:35
Thanks for the report, it is a duplicate of #975.

**Closed by webron** 2015-03-12 17:35 UTC
