### ISSUE TITLE
Swagger UI requests don't work unless API spec includes host property

### ISSUE THREAD

**Issue by ddelay** [swagger-api/swagger-ui#2801] opened 2017-03-27 18:56 UTC
I have Swagger UI 3.0.2 deployed on an internal HTTP server (inside a firewall).  I'm having issues loading the API spec from this location:

`https://rawgit.com/OpenNTF/das-api-specs/master/calendar.yaml`

The specification seems to load OK and Swagger UI displays the list of operations.  However there is no Authorize button and I can't figure out how to send an authenticated request.  Each operation includes a "Try it out" button, but all requests fail because they are not properly authenticated.

As a *temporary* work around, I can use the API spec from this location:

`https://gist.githubusercontent.com/ddelay/5574f43214db1c0d7babdfd1615b515b/raw/f792e369cdec192e9414d7bee426641984e75bf6/calendar.yaml`

Now Swagger UI displays the Authorize button as expected.  The only difference between the two specs is the second one has these properties:

```
host: "algonquin.swg.usma.ibm.com"

schemes:
  - "http"
```

... where `algonquin.swg.usma.ibm.com` is the name of the internal HTTP host.

I have intentionally skipped the `host` property in the first version of the spec because my API is hosted on multiple hosts.  This was not a problem for Swagger UI 2.2.x.  It would just send requests to the same host Swagger UI itself was loaded from.

**Comment by webron** [comment] 2017-03-27 22:16
The Authorize button now will appear in the latest `master` branch. The `host` issue is a duplicate of #2760.

**Closed by webron** 2017-03-27 22:16 UTC

**Comment by ddelay** [comment] 2017-03-28 15:33
I grabbed the latest from `master` today and confirmed this is fixed.  Thanks!
