### ISSUE TITLE
QoL issue on the interface "try it out" => "execute"  

### ISSUE THREAD

**Issue by soyuka** [swagger-api/swagger-ui#3241] opened 2017-06-14 10:26 UTC
Hi there,

We recently updated swagger-ui (v3) on api-platform and I noticed that were you could execute in one click before, now requires two steps:

1. click on `try it out`
2. then only we can fill the fields and click `execute`

Wouldn't this be easier if the fields were directly available when expanding the route, so that one click on `execute` would suffice to test it? 

I'm willing to patch this if you think it can be changed.

Thanks!

ref https://github.com/api-platform/core/issues/1177#issuecomment-308379125

**Comment by webron** [comment] 2017-06-14 18:49
Closing this as a duplicate of #2805. In short - the current behavior is intentional, it just targets a different audience. We're willing to accept a change to make it *configurable*, but by default it should be the current behavior.

**Closed by webron** 2017-06-14 18:49 UTC
