### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by meeech** [swagger-api/swagger-ui#2892] opened 2017-04-10 15:50 UTC
Hi, seeing range error when loading my spec using 3.0.5 - was fine with 3.0.4 

Log from chrome attached, and copy of swagger json attached - let me know what other info I can provide. 
browser - chrome

[1491837596142.log.txt](https://github.com/swagger-api/swagger-ui/files/910537/1491837596142.log.txt)

[gsm-api-swagger.zip](https://github.com/swagger-api/swagger-ui/files/910632/gsm-api-swagger.zip)

**Comment by webron** [comment] 2017-04-12 01:55
Thanks for the detailed report.
What's interesting is that the issue only occurs when the file is hosted, but works as expected when the file is embedded.

**Comment by shockey** [comment] 2017-04-12 01:57
Gist for spec: https://gist.github.com/shockey/ce7026317d11e948a0334f1b8eeafd65

**Comment by meeech** [comment] 2017-04-12 13:09
just as an fyi, get the exact same error in swagger-editor when I import url (which makes sense, since i know editor is based on UI)

**Comment by shockey** [comment] 2017-04-26 19:41
On closer inspection, this looks like a duplicate of https://github.com/swagger-api/swagger-ui/issues/2889.

**Comment by shockey** [comment] 2017-04-28 02:22
This is not a duplicate - I'll dig into this shortly.

**Comment by shockey** [comment] 2017-05-06 03:00
Build that was just made for the new release does not have issues with this spec. Closing! 

Please reply here or open a new issue if any issues persist.

**Closed by shockey** 2017-05-06 03:00 UTC
Labels: 3.x, Bug, P1, Pending release
