### ISSUE TITLE
Required formData parameters are not checked on form validation (OAS 3.0)

### ISSUE THREAD

**Issue by champidead** [swagger-api/swagger-ui#5539] opened 2019-08-20 08:22 UTC
### Q&A
 - OS: Linux (Ubuntu 18.04)
 - Browser: Chromium
 - Version: 76.0.3809.100
 - Method of installation: `pip install connexion[swagger-ui]`
 - Swagger-UI version: 3.22.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering

Normally, on the swagger UI, required parameters are checked on the form validation, like this (red background):

![image](https://user-images.githubusercontent.com/4362224/63329196-c0fb0180-c331-11e9-854e-273a6777adf3.png)

But when it comes to required `formData` parameters, they are not checked on the form validation (no red background):

![image](https://user-images.githubusercontent.com/4362224/63329341-061f3380-c332-11e9-8054-4458dfcc23e4.png)

### To reproduce...

Try the below snippet on https://editor.swagger.io/

```yaml
openapi: 3.0.1

info:
  title: Test
  version: 1.0.0
  
paths:

  /survey/{surveyId}:
    get:
      parameters:
      - name: surveyId
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: successful operation

  /survey:
    post:
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                fav_number:
                  type: integer
              required:
                - name
      responses:
        200:
          description: survey created
```

I took this example from the Swagger documentation: [Describing Request Body → Form Data](https://swagger.io/docs/specification/describing-request-body/).

### Expected behavior

Just like the required `path` parameter, I expected the `formData` parameter to be checked on the form validation (red background if the parameter is empty).

### Additional context or thoughts

The issue #3747 may be related but I think it applies only for `path` parameters and not for `formData`ones.

Thanks!

**Comment by hkosova** [comment] 2019-08-20 10:40
Duplicate of #5181.

**Closed by hkosova** 2019-08-20 10:40 UTC

**Comment by lucasbusellato** [comment] 2019-10-23 02:15
I'm experiencing the same problem, I think is not duplicate. I tried the example from [4899](https://github.com/swagger-api/swagger-ui/issues/4899#issuecomment-508693822).

On [edito.swagger.io](https://editor.swagger.io/):

1. this **required** works:
    ```yaml
   parameters:
      - name: petId
        in: path
        description: ID of pet that needs to be updated
        required: true
        schema:
          type: integer
          format: int64
    ```

2. this doesn't:
    ```yaml
    requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Updated name of the pet
              required:
                - name
     ```

**Comment by hkosova** [comment] 2019-10-23 07:41
Hi @catapimba, this problem is tracked in #5181.
