### ISSUE TITLE
Default edit-value contains optional fields

### ISSUE THREAD

**Issue by tiagolobocastro** [swagger-api/swagger-ui#7348] opened 2021-06-16 15:53 UTC
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Firefox
 - Version: 84
 - Swagger-UI version: whatever is on https://editor.swagger.io/
 - Swagger/OpenAPI version: [Swagger 2.0]

### How can we help?
Hi, for request bodies, the "Example Value" is auto filled in with optional fields. Is there an option to not add the optional fields to the example value?

Thank you

**Comment by hkosova** [comment] 2021-06-16 16:16
Duplicate of #4752.

@tiagolobocastro the recommended way to customize schema examples is to provide a custom `example` in the schema. See [Adding Examples](https://swagger.io/docs/specification/2-0/adding-examples/).

**Closed by hkosova** 2021-06-16 16:16 UTC
