### ISSUE TITLE
Body with non-object type blows up?

### ISSUE THREAD

**Issue by pluma** [swagger-api/swagger-ui#2095] opened 2016-04-15 10:00 UTC
Swagger-UI v2.1.4 blows up when trying to render this file:

https://gist.github.com/pluma/ee759adf7703365214beaebbddb5798d

I don't see any errors in editor.swagger.io but for some reason it chokes when it tries to render the `/foxxes/devel` route while parsing the body parameter:

```json
"parameters": [{
  "required": false,
  "description": "The mount point of the service. Has to be url-encoded.",
  "type": "string",
  "name": "mount",
  "in": "query"
}, {
  "required": false,
  "schema": {
    "type": "boolean"
  },
  "name": "body",
  "in": "body"
}]
```

It tries to call `toLowerCase` on the non-existent `type` attribute of the second parameter (which is forbidden for body parameters according to editor.swagger.io and the spec).

This may be a blocking issue for [ArangoDB 3.0](https://github.com/arangodb/arangodb).

**Comment by webron** [comment] 2016-04-15 14:40
Duplicate of #2004.

**Closed by webron** 2016-04-15 14:40 UTC
