### ISSUE TITLE
Cannot define path file extension in latest Swagger UI 

### ISSUE THREAD

**Issue by corleonis** [swagger-api/swagger-ui#3080] opened 2017-05-15 08:52 UTC
I have following two paths in Swagger specification:
```/search/companies.{format}``` and ```/company/{countryCode}/{companyId}.{format}```

so that used to work fine with the old Swagger Editor here: http://editor2.swagger.io/
but now it's broken in the new version here: http://editor.swagger.io/

this is the actual error:
```
Semantic error at paths./search/companies.{format}
Partial path templating is not allowed.
```

The full specification is available here: https://duedil.io/v4/swagger.json

So my question is, is this a bug with the parsing of the spec in the new UI or is that some core issue with the definition of the paths in my spec?

**Comment by webron** [comment] 2017-05-15 16:37
Duplicate of https://github.com/swagger-api/swagger-editor/issues/1303.

**Closed by webron** 2017-05-15 16:37 UTC
