### ISSUE TITLE
Path in $ref is partually percent-encoded

### ISSUE THREAD

**Issue by bokic** [swagger-api/swagger-ui#5626] opened 2019-09-05 07:43 UTC
### Q&A
 - OS: windows
 - Browser: chrome
 - Version: 76.0.3809.132
 - Method of installation: no installation, issue is presented at editor.swagger.io
 - Swagger-Editor version: current editor.swagger.io
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Swagger/OpenAPI definition:
```
swagger:` '2.0'
info:
  description: 'Swagger docs'
  title: API example
  version: '1.0'
host: server
basePath: /docs
paths:
  '/ws/person':
    get:
      parameters:
        - name: id
          type: number
          in: path
          description: 'person id'
          required: true
      description: Get person
      operationId: 'get_person'
      tags:
        - Person
      responses:
        '200':
          description: Ok
          schema:
            type: object
            properties:
              result:
                $ref: '#/definitions/custom%3A%3Anamespace%3A%3APerson'
definitions:
  'custom::namespace::Person':
    properties:
      id:
        type: number
      FirstName:
        type: string
      LastName:
        type: string
      Address:
        type: array
        items:
          $ref: '#/definitions/custom%3A%3Anamespace%3A%3AAddress'
  'custom::namespace::Address':
    properties:
      id:
        type: number
      street:
        type: string
      city:
        type: string
```

### How can we help?

In order to generate JSON without warnings some part $ref needs to be percent encoded, and not. Is this correct behavior, or maybe bug.

Way to reproduce this issue:
* Current JSON that contains part without and part with percent encoding will not have warnings.
* If we convert $ref without percent encoding warning will popup `$ref: '#/definitions/custom::namespace::Person'`
* If we convert $ref with all characters percent encoding warning will popup `$ref: '%23%2Fdefinitions%2Fcustom%3A%3Anamespace%3A%3APerson'`

**Comment by shockey** [comment] 2019-09-28 06:00
Indeed, we should be decoding these JSON Reference partials before displaying them in the UI.

**Comment by souenzzo** [comment] 2023-02-21 12:36
still occurs, both with JSON Pointer and URL Encoding.


Note that Swagger-UI "engine" decodes and dereference it correctly.

The issue is UI-Only.

Easy steps to reproduce: 

- Go to https://petstore.swagger.io/
- Paste this data-url in  the url field

```
data:application/json;base64,eyJjb21wb25lbnRzIjp7InNjaGVtYXMiOnsiYVwvYitjIjp7InR5cGUiOiJudW1iZXIifX19LCJvcGVuYXBpIjoiMy4wLjMiLCJwYXRocyI6eyJcLyI6eyJnZXQiOnsicmVzcG9uc2VzIjp7ImRlZmF1bHQiOnsiY29udGVudCI6eyJhcHBsaWNhdGlvblwvanNvbiI6eyJzY2hlbWEiOnsiJHJlZiI6IiNcL2NvbXBvbmVudHNcL3NjaGVtYXNcL2F+MWIlMkJjIn19fX19fX19fQ==
```

<img width="1026" alt="Screenshot 2023-02-21 at 09 32 51" src="https://user-images.githubusercontent.com/3241703/220346017-8ab6a439-e70d-4789-afb4-54a07e4a8154.png">

**Comment by char0n** [comment] 2023-03-13 11:00
Addressed in https://github.com/swagger-api/swagger-ui/pull/8400.

**Closed** 2023-03-13 10:59 UTC
Labels: type: bug, cat: rendering
