### ISSUE TITLE
Example String Missing Quotes

### ISSUE THREAD

**Issue by wrightleft** [swagger-api/swagger-ui#6283] opened 2020-08-04 15:35 UTC
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Edge
 - Version: 84.0.522.52 (Official build) (64-bit)
 - Method of installation: dist assets
 - Swagger-UI version: 3.31.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

I created an path with a POST request and a JSON request body with a schema that specifies a string as the only content. Expand the POST section, and note that the example generated does not include quotes, and is therefore not a valid JSON string and also does not pass JSON schema validation.

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.2
info:
  title: Test
  description: Testing Schemas
  version: 1.0.0
paths:
  /test:
    post:
      summary: Test string schema.
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: OK
```

Swagger-UI configuration options:
```js
SwaggerUIBundle({
  urls: [{"url":"openapi.yaml","name":"Test"}],
  validatorUrl: null,
  dom_id: '#swagger-ui',
  deepLinking: true,
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
  ],
  plugins: [
    SwaggerUIBundle.plugins.DownloadUrl,
    HideInfoUrlPartsPlugin
  ],
  layout: "StandaloneLayout"
})
```

### Describe the bug you're encountering
JSON strings must be quoted in the example values.

### To reproduce...

1. Go to 'Swagger UI'
2. Click on 'POST'
3. Scroll down to 'Example Value'
![image](https://user-images.githubusercontent.com/6497524/89313072-e4938680-d62c-11ea-800e-697a252e9a75.png)

### Expected behavior

The string should be quoted in order to pass JSON schema validation:
![image](https://user-images.githubusercontent.com/6497524/89313228-1573bb80-d62d-11ea-9477-a697f640fc9c.png)

### Additional context or thoughts

If the string is nested in an array, it is properly quoted:
![image](https://user-images.githubusercontent.com/6497524/89313373-45bb5a00-d62d-11ea-9019-9b2efbb15e13.png)

**Comment by hkosova** [comment] 2020-08-04 17:05
Duplicate of #6120.

**Closed by hkosova** 2020-08-04 17:05 UTC

**Comment by wrightleft** [comment] 2020-08-04 18:03
Man. I swear I searched before I created a new issue...
