### ISSUE TITLE
Path parameters not displayed in UI

### ISSUE THREAD

**Issue by xelwarto** [swagger-api/swagger-ui#1137] opened 2015-04-09 16:26 UTC
For parameters which are defined at the path level and not the operation level, the UI does not render the parameters. Only when the parameters are added directly to an operation does the UI display them.

**Comment by mohsen1** [comment] 2015-04-09 17:08
I believe this is an issue in SwaggerJS. SwaggerJS is not populating path parameters to operations.

**Comment by fehguy** [comment] 2015-04-09 17:43
please track https://github.com/swagger-api/swagger-ui/issues/1137#issuecomment-91294012

**Comment by webron** [comment] 2015-04-09 17:48
I believe @fehguy meant https://github.com/swagger-api/swagger-js/issues/360.

However, this is a duplicate of #911 and #929 so I'm going to close this one.

**Closed by webron** 2015-04-09 17:48 UTC
Labels: swaggger-js
