### ISSUE TITLE
cannot fire onchange

### ISSUE THREAD

**Issue by willin** [swagger-api/swagger-ui#3275] opened 2017-06-22 05:55 UTC
When reporting an issue, please provide the following details:
- swagger-ui version 3.0.16
- a swagger file reproducing the issue

```js
// fire react onchange event and change input values
  var setValue = function (element, value) {
    if (!element) {
      return;
    }
    element.value = value;
    if ('createEvent' in document) {
      var event = new Event('input', { bubbles: true });
      element.dispatchEvent(event);
    }
    else {
      element.fireEvent('onchange');
    }
  };
```

it works in 3.0.10...

**Comment by shockey** [comment] 2017-06-22 15:59
@willin, what's the context of this code? I don't have an idea of what you're trying to accomplish, or where I can put this snippet in order to reproduce your problem.

**Comment by willin** [comment] 2017-06-23 00:35
![wx20170623-083414](https://user-images.githubusercontent.com/1890238/27461790-ccd7210a-5781-11e7-8209-8d68ddf74dcf.png)

like this,  

we inject a form to dom, which user can fill in  app key/secret info.

some params need to sign and auto fill in

**Comment by shockey** [comment] 2017-07-06 03:52
@willin, I can't find anything in the diff between `3.0.10` and `3.0.16` that concerns the `data-name` of parameter inputs. 

Regardless - while I admire the ingenuity of your solution, please be aware that element data attributes, and element signatures in general, are not part of our public API, so they can change at any time without triggering a breaking change.

If you'd like to open a PR for a change that makes it easier to target parameter inputs via query selector, we'd be happy to consider it.

**Comment by willin** [comment] 2017-07-09 00:31
is the react version updated?

**Comment by shockey** [comment] 2017-07-10 17:50
@willin, we've been using React 15 since Swagger-UI 3.0 was originally released. 

See the manifest for [3.0.0](https://github.com/swagger-api/swagger-ui/blob/v3.0.0/package.json#L47) and [3.0.18](https://github.com/swagger-api/swagger-ui/blob/v3.0.18/package.json#L52) - they both call for `react@^15.4.0`.

**Comment by willin** [comment] 2017-07-11 01:58
i'll try 3.0.18 later

**Comment by shockey** [comment] 2017-07-17 22:53
@willin, any updates?

**Comment by willin** [comment] 2017-07-18 00:33
3.0.18 & 3.0.19 cannot work properly

```js
module.exports = (document, pathPrefix, moreConfig = '') => `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${document.info.title}</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3.0.10/swagger-ui.css" >
  <link rel="icon" type="image/png" href="${pathPrefix}favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="${pathPrefix}favicon-16x16.png" sizes="16x16" />
  <style>
    html
    {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
    }
    *,
    *:before,
    *:after
    {
        box-sizing: inherit;
    }

    body {
      margin:0;
      background: #fafafa;
    }
  </style>
</head>

<body>

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;width:0;height:0">
  <defs>
    <symbol viewBox="0 0 20 20" id="unlocked">
          <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V6h2v-.801C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8z"></path>
    </symbol>

    <symbol viewBox="0 0 20 20" id="locked">
      <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8zM12 8H8V5.199C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="close">
      <path d="M14.348 14.849c-.469.469-1.229.469-1.697 0L10 11.819l-2.651 3.029c-.469.469-1.229.469-1.697 0-.469-.469-.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-.469-.469-.469-1.228 0-1.697.469-.469 1.228-.469 1.697 0L10 8.183l2.651-3.031c.469-.469 1.228-.469 1.697 0 .469.469.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c.469.469.469 1.229 0 1.698z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="large-arrow">
      <path d="M13.25 10L6.109 2.58c-.268-.27-.268-.707 0-.979.268-.27.701-.27.969 0l7.83 7.908c.268.271.268.709 0 .979l-7.83 7.908c-.268.271-.701.27-.969 0-.268-.269-.268-.707 0-.979L13.25 10z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="large-arrow-down">
      <path d="M17.418 6.109c.272-.268.709-.268.979 0s.271.701 0 .969l-7.908 7.83c-.27.268-.707.268-.979 0l-7.908-7.83c-.27-.268-.27-.701 0-.969.271-.268.709-.268.979 0L10 13.25l7.418-7.141z"/>
    </symbol>


    <symbol viewBox="0 0 24 24" id="jump-to">
      <path d="M19 7v4H5.83l3.58-3.59L8 6l-6 6 6 6 1.41-1.41L5.83 13H21V7z"/>
    </symbol>

    <symbol viewBox="0 0 24 24" id="expand">
      <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z"/>
    </symbol>

  </defs>
</svg>

<div id="swagger-ui"></div>
<script src="//unpkg.com/jssha"> </script>
<script src="//unpkg.com/@airx/authcode/dist/authcode.js"> </script>
<script src="//unpkg.com/@airx/swagger-hook"> </script>
<script src="//unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"> </script>
<script src="//unpkg.com/swagger-ui-dist/swagger-ui-standalone-preset.js"> </script>
<script>
function HideTopbarPlugin() {
  // this plugin overrides the Topbar component to return nothing
  return {
    components: {
      Topbar: function() { return null }
    }
  }
}
window.onload = function() {
  // Build a system
  const ui = SwaggerUIBundle({
    url: location.protocol + '//' + location.host + '${pathPrefix}/api-docs',
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl,
      HideTopbarPlugin
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
</script>
</body>
</html>
`;
```

**Comment by shockey** [comment] 2017-09-14 02:54
Hi @willin, I'm going to close this - again, targeting elements with custom `querySelector` code is _not_ supported. It's dangerous to interact directly with the DOM elements outside of the application's internal lifecycle!

If you'd like to see an officially supported autofill feature built into Swagger-UI, please open a feature request ticket, and consider contributing a PR for it if you have the time!

**Closed by shockey** 2017-09-14 02:54 UTC
Labels: Support
