### ISSUE TITLE
Inherited model name and description ignored in the documentation

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#3342] opened 2017-07-05 16:15 UTC
_From @prakashguru on July 5, 2017 13:32_

I have a yaml definition where a model "OrderEx" inherited using allOf from "Order". And the OrderEx is used as model for an api. The problem is the documentation shows name and description of the Order model (base) instead of OrderEx. 

![image](https://user-images.githubusercontent.com/11089125/27866511-4736750e-61b4-11e7-821e-a1be90ef25a1.png)

Am I doing something wrong? The yaml definition attached.

[buggy.txt](https://github.com/swagger-api/swagger-editor/files/1124767/buggy.txt)

_Copied from original issue: swagger-api/swagger-editor#1392_

**Comment by webron** [comment] 2017-07-05 16:15
@owenconti can you take a look at this? You've touched the area before.

**Comment by prakashguru** [comment] 2017-07-06 13:35
Also the "Example Value" shows the base model's example instead of derived.

**Comment by jgslima** [comment] 2017-07-10 14:48
1+

The "Example value" issue is the most critical one. For the model name and description, one can have a workaround by writing some generic description that can actually be used throughout the inherited models 
(we can live with that), but the lack of specific examples for the inherited models is actually preventing me to use the inheritance at all.

**Comment by raderio** [comment] 2017-08-14 12:09
Is inheritance works in Swagger UI? Is there an example?

**Comment by owenconti** [comment] 2017-09-10 17:36
This seems to be the same problem as https://github.com/swagger-api/swagger-ui/issues/3417.

IMO the fix is changing the spec, not the code. In your spec you have:

```
OrderEx:
    description: "Order Ex"
    allOf: 
      - $ref: '#/definitions/Order'
      - properties:
          customOrderId:
            type: string
```

Both `description` and `properties` are direct descendants of `OrderEx`, yet they are in different places in your definition. By treating all of the `OrderEx` properties as part of the `allOf` merge, the issue is fixed. 

Note: the following was tested with the latest from these two pull requests:

https://github.com/swagger-api/swagger-ui/pull/3650
https://github.com/swagger-api/swagger-js/pull/1130

So you may need to wait until those are merged and release before this is working 100%.

```
OrderEx:
    allOf: 
      - $ref: '#/definitions/Order'
      - description: "Order Ex"
        properties:
          customOrderId:
            type: string
```

<img width="763" alt="screen shot 2017-09-10 at 11 35 20 am" src="https://user-images.githubusercontent.com/791222/30251409-2eb2993a-961c-11e7-9735-229142a82da4.png">


If there is somewhere defined in a spec/standard that says that root properties of a definition should be treated differently, I'd be happy to look into this further.

**Comment by shockey** [comment] 2017-09-12 01:44
Fixed by https://github.com/swagger-api/swagger-js/pull/1130, which should be released this week 🎉 

![messages image 3481647048](https://user-images.githubusercontent.com/680248/30304199-259dff82-9721-11e7-83de-97bcbfc9434e.png)

**Closed by shockey** 2017-09-12 01:44 UTC
Labels: 3.x, Bug, P2
