### ISSUE TITLE
c# boolean parameter with [FromBody] attribute prevents ui from rendering

### ISSUE THREAD

**Issue by AndyGJ** [swagger-api/swagger-ui#1502] opened 2015-07-30 08:49 UTC
I have an issue with a webapi project using Swashbuckle.Core 5.2.1 installed via nuget, A method with the signature (int idRequest, [FromBody]bool authorisation) causes the docs generation to fail. A part of the usual docs page is visible, but the message "Finished Loading Resource Information. Rendering Swagger UI..." continues to be displayed.

I've been redirected here after originally raising this on the swashbuckle side, where it was pointed that the browser console displays an error in this state. The message is "Cannot read property toLowerCase"

If the method signature is switched to an integer (or any other primitive type) the docs page loads fine. If [FromBody] is removed, the page also generates fine. The JSON generated for this method is as follows:

```
"\/api\/MyDetails\/PendingRequests\/{idRequest}": {
  "post": {
    "tags": [
      "Member"
    ],
    "operationId": "Member_ApproveRequest",
    "consumes": [
      "application\/json",
      "text\/json",
      "application\/xml",
      "text\/xml",
      "application\/x-www-form-urlencoded"
    ],
    "produces": [
      "application\/json",
      "text\/json",
      "application\/xml",
      "text\/xml"
    ],
    "parameters": [
      {
        "name": "idRequest",
        "in": "path",
        "required": true,
        "type": "integer",
        "format": "int32"
      },
      {
        "name": "authorisation",
        "in": "body",
        "required": true,
        "schema": {
          "type": "boolean"
        }
      }
    ],
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "$ref": "#\/definitions\/Object"
        }
      }
    },
    "deprecated": false
  }
},
```

**Comment by ravengerUA** [comment] 2015-08-04 07:13
This error throws because this line
````JavaScript
var isArray = param.type.toLowerCase() === 'array' || param.allowMultiple;
````
and your schema has undefined 'type' for this parameter

Anyway, why Swashbuckle can't generate?
````JSON
"type": "boolean"
````
instead of 
````JSON
"schema": {
    "type": "boolean"
}
````

**Comment by webron** [comment] 2015-08-04 14:56
@ravengerUA - for `body` parameters, the `type` has to be inside a `schema` property.

**Comment by dgarry01** [comment] 2015-08-06 10:10
We have encountered this error also if an empty parameters section is included for a swagger operation.
"parameters": [
{}
],

Here’s a swagger that includes the empty parameters that doesn’t load: http://54.171.250.144/api-docs/customerManagementSwagger.json 

Here’s a version with parameters section removed that does: http://54.171.250.144/api-docs/customerManagementSwaggerV2.json

**Comment by webron** [comment] 2015-08-06 14:46
@dgarry01 - it doesn't load because it's not a valid definition. You can keep the empty array, but you can't have an empty object inside the array.

**Comment by dgarry01** [comment] 2015-08-06 15:24
Thanks, we'll correct the swagger description. Just a note as well that this seems to be allowed in swagger editor at the moment.

 

__________________________
David Garry
NOMOS-logo-email
CTO, Nomos Software <http://www.nomos-software.com/> 
Direct Line: +353-21-4928945
Mobile: +353-86-1980236
Skype: david.garry3
 <https://twitter.com/nomossoftware> cid:image002.gif@01CD6A46.64269EC0  <http://www.linkedin.com/company/2508693> cid:image003.gif@01CD6A46.64269EC0

**Comment by webron** [comment] 2015-08-06 15:29
@dgarry01 - thanks for pointing it out with regards to the editor. Would you mind opening an issue on it? It's definitely not valid and I'm not sure why it validates there.

**Comment by dgarry01** [comment] 2015-08-07 10:26
Done. Thanks for the clarification.

**Comment by polykar** [comment] 2015-11-25 10:04
Note that this is related to #966, which supposedly was fixed in https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.1, but i can still reproduce the problem on v2.1.3. Monkey-patching helps - 

    var isArray = (param.type && param.type.toLowerCase() === 'array') || param.allowMultiple;

- but it seems to be the wrong place to fix it. Most likely the '.type' should be set.

**Comment by tedvanderveen** [comment] 2015-11-25 10:47
@polykar Maybe the two characters "c#" in the title of this issues, has caused the severity rating to be downgraded to P2 by a not-so-much-MS-fan. So the fact that json output generated by Java also causes the error, may get this bug fixed finally soon...

**Comment by polykar** [comment] 2015-11-25 10:50
@tedvanderveen now if I told you that deep in my heart I am a C# fan, and that I was only doing Java because I get moneys for it, would that downgrade the priority? :smile:

**Comment by webron** [comment] 2017-03-20 22:25
This should no longer be an issue with 3.0. Please reopen if needed.

**Closed by webron** 2017-03-20 22:25 UTC
Labels: Bug, P2
