### ISSUE TITLE
Nested definitions not showing on *Response Messages* area

### ISSUE THREAD

**Issue by yoanisgil** [swagger-api/swagger-ui#1567] opened 2015-08-26 19:25 UTC
I have an API specification where response definitions are nested:

https://gist.githubusercontent.com/yoanisgil/4f682a2fff099f4088a2/raw/55ca4513dba6fb20c5d31f071c32aaedf6bc71ba/api.json

however the response models are not shown in the *Response Messages* area
![screenshot from 2015-08-26 15-13-34](https://cloud.githubusercontent.com/assets/918271/9503527/798c53e6-4c05-11e5-8b82-b7e8e379d9d3.png)

Is this a bug or is it just the way that is supposed to work?

**Comment by webron** [comment] 2015-08-27 07:50
You mean inline definitions?

**Comment by yoanisgil** [comment] 2015-08-27 19:14
I am new to swagger but I am talking about the column Response Model under the section Response Messages. If I define an array of items like this:

```json
"responses": {
     "400": {
            "description": "Validation error",
            "schema": {
                 "properties": {
                     "errors": {
                     "type": "array",
                     "items": {
                         "$ref": "#/definitions/DomainCreationError"
                    }
         }
     }
}
```

that won't display under the Response Messages section. If I switch to "200" then it will properly display on Response Class (Status 200). And if I use a flat schema, i.e no nested properties, no array, etc it will display fine under Response Messages. 

I think one easy way to test is just to modify my sample api.json and swap 400 and 200 responses. That should explain the issue.

**Comment by webron** [comment] 2015-08-28 12:56
Yup, that's an inline definition and a duplicate of #1297 - please follow that issue.

**Closed by webron** 2015-08-28 12:56 UTC

**Comment by yoanisgil** [comment] 2015-08-28 13:00
Cool. Thanks for the follow up!
