### ISSUE TITLE
Parameters in the "parameters" section in a path are not shown

### ISSUE THREAD

**Issue by shawm11** [swagger-api/swagger-ui#1443] opened 2015-07-03 08:43 UTC
When parameters are defined in the `parameters` section in a path, they are not shown in the UI. Here is an example of defining a parameter in the `parameters` section in a path:
```
"/users/{username}": {
    "parameters": [
        {
            "name": "username",
            "description": "Username of the user",
            "name": "username",
            "in": "path",
            "required": true,
            "type": "string"
        }
],
```
In this case, the other parameters defined within the operations (e.g. `get`, `post`) are shown correctly, but the "username" path parameter is not shown at all.

**Comment by webron** [comment] 2015-07-05 11:00
Which version of swagger-ui do you use?

**Comment by shawm11** [comment] 2015-07-06 05:30
I am using version 2.1.0

**Comment by webron** [comment] 2015-07-06 06:19
Thanks, this is a duplicate of #1118.

**Closed by webron** 2015-07-06 06:19 UTC
