### ISSUE TITLE
Cannot use "models" as a tag

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#858] opened 2015-01-27 17:18 UTC
If you add a tag named "models" to an API and tag a method with it, swagger-ui throws an exception.
```
swagger-client.js:466 Uncaught TypeError: Cannot read property 'push' of undefined
```
```
 operationGroup.apis.push(operationObject);
```

here, operationGroup.apis is undefined

I tracked this down to swagger-client.js line 458 which does:
````
operationGroup = this[tag];
````
but this.tag is not an operations group, it is the list of models (schemas) in the API.
(in this example A : Model, B : Model )

Unfortunately, this conflicts with SwaggerClient.models 

This also means that any other field of the SwaggerClient object may not be used as a tag.

This should probably be stored elswwhere, such as this.operationGroups[tag] 
````
operationGroup = this.operationGroups.[tag];
````
to avoid conflicting with the other members of SwaggerClient (such as basePath, title, etc.)

Here is a sample swagger.json file that causes this:

````
{
    "swagger" : "2.0",
    "info" : {
	"title" : "issue with a tag named 'models'",
	"contact" : {
	    "name" : "David Biesack",
	    "email" : "David.Biesack@sas.com"
	},
	"version" : "1"
    },
    "tags" : [{ "name" : "tag1",
		"description" : ""
	      },
              { "name" : "models",
                "description" : "TODO: add description of models"
              }
	     ],
    "host" : "www.example.com",
    "basePath" : "/",
    "schemes" : ["http"],
    "paths" : {
	"/" : {
	    "get" : {
		"tags" : ["tag1"],
		"summary" : "Return a list of links to the top level collections in this REST API, as well as links to create new instances in the top level collections.",
		"produces" : ["application/xml",
			      "application/json"],
		"responses" : {
		    "200" : {
			"description" : "REST API resource collection links."
		    }
		}
	    }
	},
	"/models/{modelId}" : {
	    "head" : {
		"tags" : ["models"],
		"summary" : "get headers for a model",
		"parameters" : [{
		    "name" : "modelId",
		    "in" : "path",
		    "type" : "string",
		    "required" : true,
		    "description" : "String containing the id of the model."
		}
			       ],
		"responses" : {
		    "200" : {
			"description" : "Return a specific model resource status code."
		    },
		    "403" : {
			"description" : "The project is not locked by the current user."
		    },
		    "404" : {
			"description" : "Not found."
		    },
		    "423" : {
			"description" : "The project is locked by a different user."
		    }
		}
	    }
	}
    },

    "definitions" : {
	"A" : {
	    "id" : "A",
	    "title" : "Resource A",
	    "properties" : {
		"id" : {
		    "type" : "string",
		    "description" : "The id."
		}
	    },
	    "B" : {
                "id" : "B",
		"title" : "Resource B",
		"properties" : {
		    "context" : {
			"type" : "string",
			"description" : "The context"
		    }
		}
	    }
        }
    }
}
````

**Comment by mohsen1** [comment] 2015-03-04 20:14
This is a duplicate  of #802. The issue is in underlying swagger-js library. https://github.com/swagger-api/swagger-js/issues/194 is for addressing this issue. 

Closing as duplicate

**Closed by mohsen1** 2015-03-04 20:14 UTC
Labels: Documentation, Feature

**Comment by whitlockjc** [comment] 2015-03-18 16:14
This should be fixed in the latest `develop_2.0` build of `swagger-js`.

**Comment by zdila** [comment] 2015-05-25 15:29
See #1061: It is caused for tag `info`. Client version is 2.1.8-M1.
