### ISSUE TITLE
Double slash in swagger UI

### ISSUE THREAD

**Issue by MateuszKubuszok** [swagger-api/swagger-ui#2840] opened 2017-04-03 15:47 UTC
I think there is a regression of a https://github.com/swagger-api/swagger-ui/issues/819: when I use Swagger UI from the master, when I fetch JSON generated by annotations, I end up with paths having double slashes.

![screenshot from 2017-04-03 17 43 43](https://cloud.githubusercontent.com/assets/1900121/24617744/261e1e7a-1895-11e7-8d06-e8e19478966e.png)

https://gist.github.com/MateuszKubuszok/e1d2eac07ecc2fab4b6b138992050e09

I assume that `baseUrl` should be `"/"` rather than `""`, as even if I set it to empty string it will be corrected to string ending with `/`. Same with endpoints - even if I remove leading slash it will be restored, so I assume it should be there.

(PS. Is there a reason why `dist` do not contain favicons nor `oauth2-response.html`?)

**Comment by heejs** [comment] 2017-04-03 23:20
same issue here. Any workaround?

**Comment by pjfanning** [comment] 2017-04-04 18:23
This is a duplicate of https://github.com/swagger-api/swagger-ui/issues/2815

**Comment by webron** [comment] 2017-04-04 18:26
Yup, thanks.

**Closed by webron** 2017-04-04 18:26 UTC
